---
title: TechDraw Annotation
---

|                                                                                           |
| ----------------------------------------------------------------------------------------- |
| TechDraw Annotation                                                                       |
| Menu location                                                                             |
| TechDraw → Annotations → Insert Annotation                                                |
| Workbenches                                                                               |
| [TechDraw](/TechDraw_Workbench "TechDraw Workbench")                                      |
| Default shortcut                                                                          |
| _None_                                                                                    |
| Introduced in version                                                                     |
| -                                                                                         |
| See also                                                                                  |
| [TechDraw RichTextAnnotation](/TechDraw_RichTextAnnotation "TechDraw RichTextAnnotation") |
|                                                                                           |

## Description

The **TechDraw Annotation** tool adds a text block to a drawing page.

![](/images/AnnotationSample.png)

Annotation in the drawing page

## Usage

1. If there are multiple drawing pages in the document: optionally activate the desired page by selecting it in the [Tree view](/Tree_view "Tree view").
2. There are several ways to invoke the tool:
   - Press the ![](/images/TechDraw_Annotation.svg) [Insert Annotation](/TechDraw_Annotation "TechDraw Annotation") button.
   - Select the **TechDraw → Annotations → ![](/images/TechDraw_Annotation.svg) Insert Annotation** option from the menu.
3. If there are multiple drawing pages in the document and you have not yet activated a page, the **Page Chooser** dialog box opens:
   1. Select the desired page.
   2. Press the OK button.
4. A text block containing _Default Text_ appears on the page.
5. Use the [Property editor](/Property_editor "Property editor") to change the text.
6. Optionally drag the Annotation to the different position.

![](/images/UpdateAnnotation.png)

Modifying the annotation through the Property editor

## Notes

- Some characters interfere with the internal representation of the Annotation text. Specifically, these are the double quote `"`, less than `<`, and greater than `>` symbols; these must be replaced by HTML escape characters, `&quot;`, `&lt;`, and `&gt;` respectively. See [Character encodings in HTML](https://en.wikipedia.org/wiki/Character_encodings_in_HTML#HTML_character_references) for details.

## Properties

The Annotation inherits all applicable basic View properties except Data**Scale**. Use the Data**TextSize** property instead.

- Data**Text**: The text to be displayed.
- Data**Font**: The name of the font to use. Annotation will use the best match of installed fonts.
- Data**TextColor**: The color of the text.
- Data**TextSize**: The size of the text in mm.
- Data**MaxWidth**: The maximum width of the Annotation block. -1 indicates no maximum width.
- Data**LineSpace**: Line spacing adjustment (%).
- Data**TextStyle**: "Normal", "Bold", "Italic", "Bold-Italic"

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

The New Annotation tool can be used in [macros](/Macros "Macros") and from the [Python](/Python "Python") console by using the following functions:

```
anno = FreeCAD.ActiveDocument.addObject('TechDraw::DrawViewAnnotation','TestAnno')
anno.Text = ['Different Text']
anno.TextStyle = 'Bold'
rc = page.addView(anno)

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_Annotation/en&oldid=1486100>"
