---
title: TechDraw GeometricHatch
---

|                                                                                                                 |
| --------------------------------------------------------------------------------------------------------------- |
| TechDraw GeometricHatch                                                                                         |
| Menu location                                                                                                   |
| TechDraw → Hatching → Apply Geometric Hatch to Face                                                             |
| Workbenches                                                                                                     |
| [TechDraw](/TechDraw_Workbench "TechDraw Workbench")                                                            |
| Default shortcut                                                                                                |
| _None_                                                                                                          |
| Introduced in version                                                                                           |
| -                                                                                                               |
| See also                                                                                                        |
| [TechDraw Hatch](/TechDraw_Hatch "TechDraw Hatch"), [TechDraw Hatching](/TechDraw_Hatching "TechDraw Hatching") |
|                                                                                                                 |

## Description

The **TechDraw GeometricHatch** tool fills a closed region in a View with a pattern based on an AutoDesk PAT hatching specification. Alternatively the ![](/src/assets/images/TechDraw_Hatch.svg) [TechDraw Hatch](/TechDraw_Hatch "TechDraw Hatch") tool uses SVG based hatch patterns. See [Hatching](/TechDraw_Hatching "TechDraw Hatching") for details.

![](/src/assets/images/TechDraw_GeomHatch_example.png)

Geometric hatch pattern on a face

## Usage

1. Select a closed region in a View.
2. There are several ways to invoke the tool:
   - Press the ![](/src/assets/images/TechDraw_GeometricHatch.svg) [TechDraw GeometricHatch](/TechDraw_GeometricHatch "TechDraw GeometricHatch") button.
   - Select the **TechDraw → Hatching → ![](/src/assets/images/TechDraw_GeometricHatch.svg) Apply Geometric Hatch to Face** option from the menu.
3. The **Apply Geometric Hatch to Face** task panel opens.
4. Optionally change the **Pattern File**, the **Pattern Name**, the **Pattern Scale**, the **Line Weight** and the **Line Color**.
5. Press the OK button.

## Notes

- For a solid color fill use [TechDraw Hatch](/TechDraw_Hatch "TechDraw Hatch") instead and select solid.svg as the **Pattern File**.
- Hatching objects are vulnerable to the "[topological naming problem](/Topological_naming_problem "Topological naming problem")". See [TechDraw LengthDimension](/TechDraw_LengthDimension "TechDraw LengthDimension") for more information. It is recommended that hatching be one of the last steps in your drawing process.
- A small set of sample patterns are available in:

: ```
$INSTALL_DIR/data/Mod/TechDraw/PAT/FCPAT.pat

    ```

: Where `$INSTALL_DIR` is the directory where FreeCAD was installed, for example:
: ```
/usr/share/freecad/data/Mod/TechDraw/PAT/FCPAT.pat

    ```

## Properties

- Data**Source**: The View and Face to receive the hatch pattern.
- Data**File Pattern**: The location of the PAT file to use.
- Data**Name Pattern**: The name of the PAT specification within File Pattern.
- Data**Scale Pattern**: The scale to be applied to the pattern (must be > 0.0).
- View**Weight Pattern**: The thickness of the pattern lines.
- View**Color Pattern**: The color for the pattern lines.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A GeometricHatch can be created with [macros](/Macros "Macros") and from the [Python](/Python "Python") console by using the following functions:

```
hatch = FreeCAD.ActiveDocument.addObject("TechDraw::DrawGeomHatch", "GeomHatch")
hatch.Source = (view1, ["Face0"])
hatch.FilePattern = "path/to/myPATfile.pat"
hatch.NamePattern = "Diamond"
page.addView(hatch)

```

It is also possible to use TechDraw's geometric hatch engine to produce a compound object in the 3D space. One must take care that the base face lies on the XY plane, as the algorithm is not tailored yet for other cases:

```
import TechDraw
face = Part.makePlane(10, 10)
patfile = "path/to/myPATfile.pat"
pattern = "Diamond"
scale = 10
hatch = TechDraw.makeGeomHatch(face, scale, pattern, patfile)
Part.show(hatch)

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_GeometricHatch/en&oldid=1486092>"
