---
title: TechDraw Midpoints
---

|                                                                                                                                               |
| --------------------------------------------------------------------------------------------------------------------------------------------- |
| TechDraw Midpoints                                                                                                                            |
| Menu location                                                                                                                                 |
| TechDraw → Add Vertices → Add Midpoint Vertices                                                                                               |
| Workbenches                                                                                                                                   |
| [TechDraw](/TechDraw_Workbench "TechDraw Workbench")                                                                                          |
| Default shortcut                                                                                                                              |
| _None_                                                                                                                                        |
| Introduced in version                                                                                                                         |
| 0.19                                                                                                                                          |
| See also                                                                                                                                      |
| [TechDraw CosmeticVertex](/TechDraw_CosmeticVertex "TechDraw CosmeticVertex"), [TechDraw Quadrants](/TechDraw_Quadrants "TechDraw Quadrants") |
|                                                                                                                                               |

## Description

The **TechDraw Midpoints** tool adds [cosmetic vertices](/TechDraw_CosmeticVertex "TechDraw CosmeticVertex") at the midpoint of one or more selected edges.

![](/images/TechDraw_CosmeticMidpoint_Sample.png)

Cosmetic vertices at the midpoint of edges

## Usage

1. Select one or more edges in a view.
2. There are several ways to invoke the tool:
   - Press the ![](/images/TechDraw_Midpoints.svg) [Add Midpoint Vertices](/TechDraw_Midpoints "TechDraw Midpoints") button.
   - Select the **TechDraw → Add Vertices → ![](/images/TechDraw_Midpoints.svg) Add Midpoint Vertices** option from the menu.

## Notes

- The created cosmetic vertices are not parametrically linked to the selected edges.
- To delete a cosmetic vertex select it and press Delete. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0")

## Properties

Cosmetic vertices have no properties of their own, as they are not document objects. They share color and size settings with regular geometry vertices.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

Cosmetic vertices are not accessible from [macros](/Macros "Macros") or the [Python](/Python "Python") console at this time. This snippet will remove all cosmetic vertices from the view.

```
v = App.ActiveDocument.View
v.clearCV()
App.ActiveDocument.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_Midpoints/en&oldid=1402770>"
