---
title: TechDraw ComplexSection
---

|                                                                                                                   |
| ----------------------------------------------------------------------------------------------------------------- |
| TechDraw ComplexSection                                                                                           |
| Menu location                                                                                                     |
| TechDraw → TechDraw Views → Insert Complex Section                                                                |
| Workbenches                                                                                                       |
| [TechDraw](/TechDraw_Workbench "TechDraw Workbench")                                                              |
| Default shortcut                                                                                                  |
| _None_                                                                                                            |
| Introduced in version                                                                                             |
| 0.21                                                                                                              |
| See also                                                                                                          |
| [TechDraw Section](/TechDraw_SectionView "TechDraw SectionView"), [TechDraw View](/TechDraw_View "TechDraw View") |
|                                                                                                                   |

## Description

The **TechDraw ComplexSection** tool inserts a cross-section view based on an existing part view and a profile.

![](/src/assets/images/TechDraw_QuarterSection_example.png)

A Quarter section view created with the Complex Section tool

![](/src/assets/images/TechDraw_AlignedSection_example.png)

An Aligned section view created with the Complex Section tool

![](/src/assets/images/TechDraw_OffsetSection_example.png)

An Offset section view created with the Complex Section tool

## Usage

1. Select a part view and a profile object in the [3D view](/3D_view "3D view") or [Tree view](/Tree_view "Tree view"). Profiles are typically Sketches, but any object whose shape can be made into a wire will work.
2. There are several ways to invoke the tool:
   - Press the ![](/src/assets/images/TechDraw_ComplexSection.svg) [Insert Complex Section](/TechDraw_ComplexSection "TechDraw ComplexSection") button.
   - Select the **TechDraw → TechDraw Views → ![](/src/assets/images/TechDraw_ComplexSection.svg) Insert Complex Section** option from the menu.
3. A task panel opens which will help calculate the various properties. Reasonable values for the view Direction are calculated, but these can be changed.

![](/src/assets/images/TechDraw_ComplexSection_Taskview1.png)
![](/src/assets/images/TechDraw_ComplexSection_Taskview2.png)

## Properties

A Complex Section, formally a `TechDraw::DrawComplexSection` object, is derived from a [Section View](/TechDraw_SectionView#Properties "TechDraw SectionView"), formally a `TechDraw::DrawViewSection` object, and inherits all its properties. It also has the following additional properties:

### Data

Cutting Tool

- Data**Cutting Tool Wire Object**: The document object whose shape will be used to generate the cutting profile.
- Data**Projection Strategy**: Controls how the cut is performed and how the result is projected on the page:
  - `Offset`: Performs a simple cut of the Source shape and projects the result.
  - `Aligned`: Cuts the Source shape using a tool created from each segment (edge) of the cutting profile. The results of each cut are projected in a vertical or horizontal array, depending on the orientation of the cutting profile.
  - `NoParallel`: As Aligned, but profile segments which are parallel to the view direction are skipped.

## Notes

- The [SectionNormal](/TechDraw_SectionView#Data "TechDraw SectionView") property controls which side of the profile is removed and should point generally in the opposite direction of the line of sight represented by the arrows on the section line. Avoid selecting a SectionNormal that is parallel to profile segments (especially the first and last segments) as this prevents the correct calculation of section arrow direction and may generate reversed views.
- See also [TechDraw SectionView](/TechDraw_SectionView#Notes "TechDraw SectionView")

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Complex Section can be created with [macros](/Macros "Macros") and from the [Python](/Python "Python") console by using the following functions:

```
doc = FreeCAD.ActiveDocument
box = doc.Box
profile = doc.Sketch
page = doc.Page

view = doc.addObject("TechDraw::DrawViewPart", "View")
page.addView(view)
view.Source = box
view.Direction = (0, 0, 1)

section = doc.addObject("TechDraw::DrawComplexSection", "ComplexSection")
page.addView(section)
section.BaseView = view
section.CuttingToolWireObject = profile
section.Direction = (0, 1, 0)
section.SectionNormal = (-1, 0, 0)

```

## Examples

For some more information about section views and some use cases, have a look at: [TechDraw section examples](/TechDraw_Section_Examples "TechDraw Section Examples").

![](/src/assets/images/TechDraw_ExampleSection-10.png)
![](/src/assets/images/TechDraw_ExampleSection-13.png)
![](/src/assets/images/TechDraw_ExampleSection-15.png)
![](/src/assets/images/TechDraw_ExampleSection-17.png)
![](/src/assets/images/TechDraw_ExampleSection-34.png)
![](/src/assets/images/TechDraw_ExampleSection-35.png)

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_ComplexSection/en&oldid=1571039>"
