---
title: TechDraw BrokenView
---

|                                                      |
| ---------------------------------------------------- |
| TechDraw BrokenView                                  |
| Menu location                                        |
| TechDraw → TechDraw Views → Insert Broken View       |
| Workbenches                                          |
| [TechDraw](/TechDraw_Workbench "TechDraw Workbench") |
| Default shortcut                                     |
| _None_                                               |
| Introduced in version                                |
| 1.0                                                  |
| See also                                             |
| [TechDraw View](/TechDraw_View "TechDraw View")      |
|                                                      |

## Description

The **TechDraw BrokenView** tool inserts a "broken view" that is either based on an existing [part view](/TechDraw_View "TechDraw View"), or one or more objects, such as [Bodies](/PartDesign_Body "PartDesign Body") or [Parts](/Std_Part "Std Part"). The broken view also requires one or more [sketches](/Sketcher_NewSketch "Sketcher NewSketch") that define the location and size of the areas to be removed. The BrokenView behaves similarly to other Views. The projection direction is taken from the existing part view, the 3D camera direction or the normal of a selected face.

![](/images/TechDraw_BrokenView_example3d.png)

A shape to be broken and the sketches defining the breaks

![](/images/TechDraw_BrokenView_example2d.png)

The result

## Usage

1. Optionally rotate the [3D view](/3D_view "3D view"). The 3D view determines the initial values of the Data**Direction** and Data**XDirection** properties of the broken view.
2. Select the object you want to create a broken view of, or select an existing TechDraw view that contains this object.
3. Add one or more break sketches to the selection by selecting them in the [Tree view](/Tree_view "Tree view"). Each sketch should only contain two parallel lines. You can also use other objects with two parallel edges.
4. There are several ways to invoke the tool:
   - Press the ![](/images/TechDraw_BrokenView.svg) [Insert Broken View](/TechDraw_BrokenView "TechDraw BrokenView") button.
   - Select the **TechDraw → TechDraw Views → ![](/images/TechDraw_BrokenView.svg) Insert Broken View** option from the menu.

## Properties

See also: [Property editor](/Property_editor "Property editor").

A Broken View, formally a `TechDraw::DrawBrokenView` object, is derived from a [Part View](/TechDraw_View#Properties_Part_View "TechDraw View"), formally a `TechDraw::DrawViewPart` object, and inherits all its properties. It also has the following additional properties:

### Data

Broken View

- Data**Breaks** (`LinkList`): Objects in the 3d view that define the start/end points and direction of breaks in this view.
- Data**Gap** (`Length`): The separation distance for breaks in this view (unscaled 3d length).

## Notes

- Breaks must be vertical or horizontal. Oblique breaks are not supported.
- See also [TechDraw View](/TechDraw_View "TechDraw View").

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A BrokenView can be created with [macros](/Macros "Macros") and from the [Python](/Python "Python") console by using the following functions:

```
doc = FreeCAD.ActiveDocument
box = doc.Box
profile = doc.Sketch
page = doc.Page

brokenView = doc.addObject("TechDraw::DrawBrokenView", "BrokenView")
page.addView(brokenView)
brokenView.Source= box
brokenView.Breaks = [doc.Sketch]

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_BrokenView/en&oldid=1490001>"
