---
title: Part Ellipsoid
---

|                                                                                                            |
| ---------------------------------------------------------------------------------------------------------- |
| Part Ellipsoid                                                                                             |
| Menüeintrag                                                                                                |
| Formteil → [Grundkörper erstellen...](/Part_Primitives/de "Part Primitives/de") → Ellipsoid                |
| Arbeitsbereich                                                                                             |
| [Part](/Part_Workbench/de "Part Workbench/de"), [OpenSCAD](/OpenSCAD_Workbench/de "OpenSCAD Workbench/de") |
| Standardtastenkürzel                                                                                       |
| _Keiner_                                                                                                   |
| Eingeführt in Version                                                                                      |
| -                                                                                                          |
| Siehe auch                                                                                                 |
| [Part Grundelemente](/Part_Primitives/de "Part Primitives/de")                                             |
|                                                                                                            |

## Beschreibung

Eine ![](/images/Part_Ellipsoid.svg) **Part Ellipsoid** ist ein parametrischer Volumenkörper, der mit dem Befehl ![](/images/Part_Primitives.svg) [Part Grundelemente](/Part_Primitives/de "Part Primitives/de") erstellt werden kann. Im Koordinatensystem durch ihre Daten-Eigenschaft**Placement** festgelegt, sind die Achsen des Ellipsoids fluchtend mit den X-, Y-, und Z-Achsen und damit sein Mittelpunkt im Ursprung.

A Part Ellipsoid can be truncated at the top and/or bottom by changing its Daten**Angle1** and/or Daten**Angle2** properties. It can be turned into a segment of an ellipsoid by changing its Daten**Angle3** property.

![](/images/Part_Ellipsoid_Example.png)

## Anwendung

Siehe [Part Grundelemente](/Part_Primitives/de#Anwendung "Part Primitives/de").

## Beispiel

![](/images/Part_Ellipsoid_Scripting_Example.png)

Part-Ellipsoid aus dem Skriptbeispiel

Ein Part-Ellipsoid-Objekt, das mit dem [Skriptbeispiel](#Skripten) weiter unten erzeugt wurde wird hier dargestellt.

## Eigenschaften

Siehe auch: [Eigenschafteneditor](/Property_editor/de "Property editor/de").

Ein Part-Ellipsoid-Objekt wird von einem [Part-Formelement](/Part_Feature/de "Part Feature/de") abgeleitet und erbt alle seine Eigenschaften. Außerdem hat es die folgenden zusätzlichen Eigenschaften:

### Daten

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Ellipsoid

- Daten**Radius1** (`Length`): The radius of the ellipsoid in its Z direction. The default is `2mm`.
- Daten**Radius2** (`Length`): The radius of the ellipsoid in its X direction. The default is `4mm`.
- Daten**Radius3** (`Length`): The radius of the ellipsoid in its Y direction. The default is `4mm`.
- Daten**Angle1** (`Angle`): The start angle of the elliptical sides of the ellipsoid. Valid range: `-90° <= value < 90°`. Must be smaller than Daten**Angle2**. The default is `-90°`.
- Daten**Angle2** (`Angle`): The end angle of the elliptical sides of the ellipsoid. Valid range: `-90° < value <= 90°`. Must be larger than Daten**Angle1**. The default is `90°`. If the total angle of the elliptical sides is smaller than `180°` the ellipsoid will be truncated and have a flat face at the top and/or bottom.
- Daten**Angle3** (`Angle`): The total angle of the ellipsoid in its XY plane. Valid range: `0° < value <= 360°`. The default is `360°`. If it is smaller than `360°` the resulting solid will be a segment of an ellipsoid.

## Skripten

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Ellipsoid can be created with the `addObject()` method of the document:

```
ellipsoid = FreeCAD.ActiveDocument.addObject("Part::Ellipsoid", "myEllipsoid")

```

- Where `"myEllipsoid"` is the name for the object.
- The function returns the newly created object.

Beispiel:

```
import FreeCAD as App

doc = App.activeDocument()

ellipsoid = doc.addObject("Part::Ellipsoid", "myEllipsoid")
ellipsoid.Radius1 = 2
ellipsoid.Radius2 = 4
ellipsoid.Radius3 = 6
ellipsoid.Angle1 = -90
ellipsoid.Angle2 = 50
ellipsoid.Angle3 = 300
ellipsoid.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(15, 0, 20))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Ellipsoid/de&oldid=1131486>"
