---
title: Part Prisma
---

|                                                                                                            |
| ---------------------------------------------------------------------------------------------------------- |
| Part Prisma                                                                                                |
| Menüeintrag                                                                                                |
| Formteil → [Grundkörper erzeugen...](/Part_Primitives/de "Part Primitives/de") → Prisma                    |
| Arbeitsbereich                                                                                             |
| [Part](/Part_Workbench/de "Part Workbench/de"), [OpenSCAD](/OpenSCAD_Workbench/de "OpenSCAD Workbench/de") |
| Standardtastenkürzel                                                                                       |
| _Keiner_                                                                                                   |
| Eingeführt in Version                                                                                      |
| 0.14                                                                                                       |
| Siehe auch                                                                                                 |
| [Part Primitives](/Part_Primitives/de "Part Primitives/de")                                                |
|                                                                                                            |

## Beschreibung

Ein ![](/src/assets/images/Part_Prism.svg) **Part Prisma** ist ein parametrischer Volumenkörper, der mit dem Befehl ![](/src/assets/images/Part_Primitives.svg) [Part Grundelemente](/Part_Primitives/de "Part Primitives/de") erstellt werden kann. Im Koordinatensystem durch seine Daten-Eigenschaft**Placement** festgelegt, liegt die Unterseite des Prismas auf der XY-Ebene mit seinem Mittelpunkt im Ursprung und einem seiner Eckpunkte auf der X-Achse.

![](/src/assets/images/Part_Prism_Example.png)

## Anwendung

Siehe [Part Grundelemente](/Part_Primitives/de#Anwendung "Part Primitives/de").

## Beispiel

![](/src/assets/images/Part_Prism_Scripting_Example.png)

Part-Prisma aus dem Skriptbeispiel

Ein Part-Prisma-Objekt, das mit dem [Skriptbeispiel](#Skripten) weiter unten erzeugt wurde, wird hier dargestellt.

## Eigenschaften

Siehe auch: [Eigenschafteneditor](/Property_editor/de "Property editor/de").

Ein Part-Prism-Objekt wird von einem [Part-Formelement](/Part_Feature/de "Part Feature/de") abgeleitet und erbt alle seine Eigenschaften. Außerdem hat es die folgenden zusätzlichen Eigenschaften:

### Daten

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Prism

- Daten**Polygon** (`IntegerConstraint`): The number of sides of the polygon. The default is `6`.
- Daten**Circumradius** (`Length`): The radius of the circle that circumscribes the polygon, the distance from the center of the polygon to one of its vertices. The default is `2mm`.
- Daten**Height** (`Length`): The height of the prism. The default is `10mm`.
- Daten**First Angle** (`Angle`): The angle between the extrusion direction of the prism and its positive Z axis, measured around its Y axis. The angle is positive towards its positive X axis. Valid range: `0° <= value < 90°`. The default is `0°`.
- Daten**Second Angle** (`Angle`): The angle between the extrusion direction of the prism and its positive Z axis, measured around its X axis. The angle is positive towards its positive Y axis. Valid range: `0° <= value < 90°`. The default is `0°`.

## Skripten

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Prism can be created with the `addObject()` method of the document:

```
prism = FreeCAD.ActiveDocument.addObject("Part::Prism", "myPrism")

```

- Where `"myPrism"` is the name for the object.
- The function returns the newly created object.

Beispiel:

```
import FreeCAD as App

doc = App.activeDocument()

prism = doc.addObject("Part::Prism", "myPrism")
prism.Polygon = 5
prism.Circumradius = 10
prism.Height = 50
prism.FirstAngle = 22.5
prism.SecondAngle = 45
prism.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(60, 75, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Prism/de&oldid=1268273>"
