---
title: Part Kreis
---
|  |
| --- |
| Part Kreis |
| Menüeintrag |
| Formteil → [Create primitives](/Part_Primitives/de "Part Primitives/de") → Kreis |
| Arbeitsbereich |
| [Part](/Part_Workbench/de "Part Workbench/de"), [OpenSCAD](/OpenSCAD_Workbench/de "OpenSCAD Workbench/de") |
| Standardtastenkürzel |
| *Keiner* |
| Eingeführt in Version |
| - |
| Siehe auch |
| [Part Grundelemente](/Part_Primitives/de "Part Primitives/de") |
|  |

## Beschreibung

Ein ![](/images/Part_Circle.svg) **Part Kreis** ist ein parametrischer Volumenkörper, der mit dem Befehl ![](/images/Part_Primitives.svg) [Part Grundelemente](/Part_Primitives/de "Part Primitives/de") erstellt werden kann. Im Koordinatensystem durch ihre Daten-Eigenschaft**Placement** festgelegt, liegt der Kreis auf der XY-Ebene mit seinem Mittelpunkt im Ursprung.

Ein Part-Kreis ist eigentlich ein gegen den Uhrzeigersinn verlaufender 360°-Kreisbogen. Er kann in einen Kreissegment gewandelt werden, indem die Daten-Eigenschaft**Angle1** und/oder die Daten-Eigenschaft**Angle2** geändert wird.

![](/images/Part_Circle_Example.png)

## Anwendung

Siehe [Part Grundelemente](/Part_Primitives/de#Anwendung "Part Primitives/de").

A Part Circle can alternatively be created by selecting three points:

1. In the task panel of the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command select the **![](/images/Part_Circle.svg) Circle** option from the dropdown list.
2. Press the From three points button.
3. Select three vertices in the [3D view](/3D_view "3D view"). There is no need to hold down the Ctrl key.
4. A circle is created.
5. The selected vertices are only used at creation time to calculate the Daten**Radius** and Daten**Placement** of the circle.

## Beispiel

![](/images/Part_Circle_Scripting_Example.png)

Part-Kreis aus dem Skriptbeispiel

Ein Part-Kreis-Objekt, das mit dem [Skriptbeispiel](#Skripten) weiter unten erzeugt wurde wird hier dargestellt.

## Eigenschaften

Siehe auch: [Eigenschafteneditor](/Property_editor/de "Property editor/de").

Ein Part-Kreis-Objekt wird von einem [Part-Formelement](/Part_Feature/de "Part Feature/de") abgeleitet und erbt alle seine Eigenschaften. Außerdem hat es die folgenden zusätzlichen Eigenschaften:

### Daten

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Base

* Daten-Eigenschaft**Radius** (`Length`): Der Radius des Kreises oder Kreisbogens. Standard ist `2mm`.
* Daten-Eigenschaft**Angle1** (`Angle`): Der Startwinkel des Kreisbogens. Wertebereich: `0° < value <= 360°`. Standard ist `0°`.
* Daten-Eigenschaft**Angle2** (`Angle`): Der Endwinkel des Kreisbogens: `0° < value <= 360°`. Standard ist `360°`. Sind Daten-Eigenschaft**Angle1** und Daten-Eigenschaft**Angle2** gleich, oder ist ein Winkel `0°` und der andere `360°`, wird ein Vollkreis erstellt.

## Skripten

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Circle can be created with the `addObject()` method of the document:

```
circle = FreeCAD.ActiveDocument.addObject("Part::Circle", "myCircle")

```

* Where `"myCircle"` is the name for the object.
* The function returns the newly created object.

Beispiel:

```
import FreeCAD as App

doc = App.activeDocument()

circle = doc.addObject("Part::Circle", "myCircle")
circle.Radius = 10
circle.Angle1 = 45
circle.Angle2 = 225
circle.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Circle/de&oldid=1248033>"