---
title: Part Spirale
---

|                                                                                                            |
| ---------------------------------------------------------------------------------------------------------- |
| Part Spirale                                                                                               |
| Menüeintrag                                                                                                |
| Formteil → [Grundkörper erstellen...](/Part_Primitives/de "Part Primitives/de") → Spirale                  |
| Arbeitsbereich                                                                                             |
| [Part](/Part_Workbench/de "Part Workbench/de"), [OpenSCAD](/OpenSCAD_Workbench/de "OpenSCAD Workbench/de") |
| Standardtastenkürzel                                                                                       |
| _Keiner_                                                                                                   |
| Eingeführt in Version                                                                                      |
| 0.14                                                                                                       |
| Siehe auch                                                                                                 |
| [Part Grundelemente](/Part_Primitives/de "Part Primitives/de")                                             |
|                                                                                                            |

## Beschreibung

Eine ![](/src/assets/images/Part_Spiral.svg) **Part Spirale** ist ein parametrischer Volumenkörper, der mit dem Befehl ![](/src/assets/images/Part_Primitives.svg) [Part Grundelemente](/Part_Primitives/de "Part Primitives/de") erstellt werden kann. Im Koordinatensystem durch ihre Daten-Eigenschaft**Placement** festgelegt, liegt die Spirale auf der XY-Ebene mit ihrem Mittelpunkt im Ursprung und ihrem Startpunkt auf der X-Achse. Sie öffnet sich gegen den Uhrzeigersinn.

![](/src/assets/images/Part_Spiral_Example.png)

## Anwendung

Siehe [Part Grundelemente](/Part_Primitives/de#Anwendung "Part Primitives/de").

## Beispiel

![](/src/assets/images/Part_Spiral_Scripting_Example.png)

Part-Spirale aus dem Skriptbeispiel

Ein Part-Spirale-Objekt, das mit dem [Skriptbeispiel](#Skripten) weiter unten erzeugt wurde wird hier dargestellt.

## Eigenschaften

Siehe auch: [Eigenschafteneditor](/Property_editor/de "Property editor/de").

Ein Part-Spirale-Objekt wird von einem [Part-Formelement](/Part_Feature/de "Part Feature/de") abgeleitet und erbt alle seine Eigenschaften. Außerdem hat es die folgenden zusätzlichen Eigenschaften:

### Daten

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Spiral

- Daten**Growth** (`Length`): The distance between two consecutive turns of the spiral. The default is `1mm`.
- Daten**Radius** (`Length`): The start radius of the spiral, the distance between its center and its start point. Can be `0mm`. The default is `1mm`.
- Daten**Rotations** (`QuantityConstraint`): The number of rotations, or turns, of the spiral. The default is `2`.
- Daten**Segment Length** (`QuantityConstraint`): The number of turns per spiral subdivision. The default is `1`, meaning each full turn of the spiral is a separate segment. Use `0` to suppress subdivision.

## Skripten

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Spiral can be created with the `addObject()` method of the document:

```
spiral = FreeCAD.ActiveDocument.addObject("Part::Spiral", "mySpiral")

```

- Where `"mySpiral"` is the name for the object.
- The function returns the newly created object.

Beispiel:

```
import FreeCAD as App

doc = App.activeDocument()

spiral = doc.addObject("Part::Spiral", "mySpiral")
spiral.Growth = 2
spiral.Radius = 3
spiral.Rotations = 4
spiral.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Spiral/de&oldid=1131620>"
