---
title: Part Helix
---

|                                                                                                            |
| ---------------------------------------------------------------------------------------------------------- |
| Part Helix                                                                                                 |
| Menüeintrag                                                                                                |
| Formteil → [Grundkörper erstellen...](/Part_Primitives/de "Part Primitives/de") → Helix                    |
| Arbeitsbereich                                                                                             |
| [Part](/Part_Workbench/de "Part Workbench/de"), [OpenSCAD](/OpenSCAD_Workbench/de "OpenSCAD Workbench/de") |
| Standardtastenkürzel                                                                                       |
| _Keiner_                                                                                                   |
| Eingeführt in Version                                                                                      |
| -                                                                                                          |
| Siehe auch                                                                                                 |
| [Part Grundelemente](/Part_Primitives/de "Part Primitives/de")                                             |
|                                                                                                            |

## Beschreibung

Eine ![](/src/assets/images/Part_Helix.svg) **Part Helix** ist ein parametrischer Volumenkörper, der mit dem Befehl ![](/src/assets/images/Part_Primitives.svg) [Part Grundelemente](/Part_Primitives/de "Part Primitives/de") erstellt werden kann. Im Koordinatensystem durch ihre Daten-Eigenschaft**Placement** festgelegt, fluchtet die Achse der Helix mit der Z-Achse und ihr unterer Startpunkt liegt auf der X-Achse.

![](/src/assets/images/Part_Helix_Example.png)

## Anwendung

Siehe [Part Grundelemente](/Part_Primitives/de#Anwendung "Part Primitives/de").

## Beispiel

![](/src/assets/images/Part_Helix_Scripting_Example.png)

Part-Helix aus dem Skriptbeispiel

Ein Part-Helix-Objekt, das mit dem [Skriptbeispiel](#Skripten) weiter unten erzeugt wurde, wird hier dargestellt.

## Hinweise

- A Part Helix can be used to create screw threads. See [Thread for Screw Tutorial](/Thread_for_Screw_Tutorial "Thread for Screw Tutorial").

## Eigenschaften

Siehe auch: [Eigenschafteneditor](/Property_editor/de "Property editor/de").

Ein Part-Helix-Objekt wird von einem [Part-Formelement](/Part_Feature/de "Part Feature/de") abgeleitet und erbt alle seine Eigenschaften. Außerdem hat es die folgenden zusätzlichen Eigenschaften:

### Daten

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Coordinate System

- Daten**Local Coord** (`Enumeration`): The [handedness](https://en.wikipedia.org/wiki/Screw_thread), or direction, of the helix: `Right-handed` or `Left-handed`. The default is `Right-handed`, meaning the helix turns counterclockwise as it goes up.

Helix

- Daten**Pitch** (`Length`): The distance between two consecutive turns of the helix measured along its Z axis. The default is `1mm`.
- Daten**Height** (`Length`): The height of the helix. The default is `2mm`.
- Daten**Radius** (`Length`): The start radius of the helix. The helix has a constant radius if Daten**Angle** is `0°`.
- Daten**Segment Length** (`QuantityConstraint`): The number of turns per helix subdivision. The default is `1`, meaning each full turn of the helix is a separate segment. Use `0` to suppress subdivision.
- Daten**Angle** (`Angle`): The angle that defines of the outer shape of the helix. Valid range: `-90° < value < 90°`. The default is `0°`. If it is `0°` the helix is cylindrical, else it is conical.

## Skripten

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Helix can be created with the `addObject()` method of the document:

```
helix = FreeCAD.ActiveDocument.addObject("Part::Helix", "myHelix")

```

- Where `"myHelix"` is the name for the object.
- The function returns the newly created object.

Beispiel:

```
import FreeCAD as App

doc = App.activeDocument()

helix = doc.addObject("Part::Helix", "myHelix")
helix.Pitch = 2
helix.Height = 3
helix.Radius = 4
helix.SegmentLength = 21
helix.Angle = 45
helix.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Helix/de&oldid=1131592>"
