---
title: Prisma
---
|  |
| --- |
| Part Prism |
| Menu location |
| Part → [Create primitives](/Part_Primitives "Part Primitives") → Prism |
| Workbenches |
| [Part](/Part_Workbench "Part Workbench"), [OpenSCAD](/OpenSCAD_Workbench "OpenSCAD Workbench") |
| Default shortcut |
| *None* |
| Introduced in version |
| 0.14 |
| See also |
| [Part Primitives](/Part_Primitives "Part Primitives") |
|  |

## Description

A ![](/images/Part_Prism.svg) **Part Prism** is a parametric solid that can be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. It is the result of extruding a regular polygon along a straight path. In the coordinate system defined by its Dados**Placement** property, the bottom face of the prism lies on the XY plane with its center at the origin and one of its vertices on the X axis.

![](/images/Part_Prism_Example.png)

## Usage

See [Part Primitives](/Part_Primitives#Usage "Part Primitives").

## Example

![](/images/Part_Prism_Scripting_Example.png)

Part Prism from the scripting example

A Part Prism object created with the [scripting example](#Scripting) below is shown here.

## Properties

See also: [Property editor](/Property_editor "Property editor").

A Part Prism object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Prism

* Dados**Polygon** (`IntegerConstraint`): The number of sides of the polygon. The default is `6`.
* Dados**Circumradius** (`Length`): The radius of the circle that circumscribes the polygon, the distance from the center of the polygon to one of its vertices. The default is `2mm`.
* Dados**Height** (`Length`): The height of the prism. The default is `10mm`.
* Dados**First Angle** (`Angle`): The angle between the extrusion direction of the prism and its positive Z axis, measured around its Y axis. The angle is positive towards its positive X axis. Valid range: `0° <= value < 90°`. The default is `0°`.
* Dados**Second Angle** (`Angle`): The angle between the extrusion direction of the prism and its positive Z axis, measured around its X axis. The angle is positive towards its positive Y axis. Valid range: `0° <= value < 90°`. The default is `0°`.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Prism can be created with the `addObject()` method of the document:

```
prism = FreeCAD.ActiveDocument.addObject("Part::Prism", "myPrism")

```

* Where `"myPrism"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

prism = doc.addObject("Part::Prism", "myPrism")
prism.Polygon = 5
prism.Circumradius = 10
prism.Height = 50
prism.FirstAngle = 22.5
prism.SecondAngle = 45
prism.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(60, 75, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Prism/pt-br&oldid=1268269>"