---
title: Elipse
---
|  |
| --- |
| Part Ellipse |
| Menu location |
| Part → [Create primitives](/Part_Primitives "Part Primitives") → Ellipse |
| Workbenches |
| [Part](/Part_Workbench "Part Workbench"), [OpenSCAD](/OpenSCAD_Workbench "OpenSCAD Workbench") |
| Default shortcut |
| *None* |
| Introduced in version |
| - |
| See also |
| [Part Primitives](/Part_Primitives "Part Primitives") |
|  |

## Description

A ![](/images/Part_Ellipse.svg) **Part Ellipse** is a parametric shape that can be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. In the coordinate system defined by its Dados**Placement** property, the ellipse lies on the XY plane with its center at the origin. Its mayor axis is parallel to the X axis.

A Part Ellipse is in fact a closed counterclockwise elliptical arc, it can be turned into an arc by changing its Dados**Angle1** and/or Dados**Angle2** properties.

![](/images/Part_Ellipse_Example.png)

## Usage

See [Part Primitives](/Part_Primitives#Usage "Part Primitives").

## Example

![](/images/Part_Ellipse_Scripting_Example.png)

Part Ellipse from the scripting example

A Part Ellipse object created with the [scripting example](#Scripting) below is shown here.

## Properties

See also: [Property editor](/Property_editor "Property editor").

A Part Ellipse object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Base

* Dados**MajorRadius** (`Length`): The major radius of the ellipse or elliptical arc. The default is `4mm`.
* Dados**MinorRadius** (`Length`): The minor radius of the ellipse or elliptical arc. The default is `2mm`.
* Dados**Angle1** (`Angle`): The start angle of the elliptical arc. Valid range: `0° < value <= 360°`. The default is `0°`.
* Dados**Angle2** (`Angle`): The end angle of the elliptical arc. Valid range: `0° < value <= 360°`. The default is `360°`. If Dados**Angle1** and Dados**Angle2** are equal, or if one angle is `0°` and the other `360°`, a full ellipse is created.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Ellipse can be created with the `addObject()` method of the document:

```
ellipse = FreeCAD.ActiveDocument.addObject("Part::Ellipse", "myEllipse")

```

* Where `"myEllipse"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

ellipse = doc.addObject("Part::Ellipse", "myEllipse")
ellipse.MajorRadius = 20
ellipse.MinorRadius = 10
ellipse.Angle1 = 45
ellipse.Angle2 = 135
ellipse.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Ellipse/pt-br&oldid=1106677>"