---
title: Díl Kužel
---
|  |
| --- |
| Díl Kužel |
| Umístění Menu |
| Díl -> Kužel |
| Pracovní stoly |
| [Díl](/Part_Workbench/cs "Part Workbench/cs"), Kompletace |
| Výchozí zástupce |
| *Nikdo* |
| Představen ve verzi |
| - |
| Viz také |
| [Díl Vytváření zákl.geom.tvarů](/Part_CreatePrimitives/cs "Part CreatePrimitives/cs") |
|  |

## Description

## Popis

Parametricky zkrácený díl Kužel je dostupný v pracovní ploše Díl z nástrojového pruhu Díl, Menu Díl (submenu zákl.geom.tvary) a dialogové okno Vytváření zákl.geom.tvarů.

The default Part Cone is truncated. It can be turned into a full, untruncated, cone by changing its Údaje**Radius1** or Údaje**Radius2** property to zero. It can be turned into a segment of a cone by changing its Údaje**Angle** property.

![](/images/Part_Cone_Example.png)

## Usage

## Použití

V pracovní ploše Díl klikněte na ikonu kuželu ![](/images/Part_Cone.png).

## Example

![](/images/Part_Cone_Scripting_Example.png)

Part Cone from the scripting example

A Part Cone object created with the [scripting example](#Scripting) below is shown here.

## Notes

* A Part Cone can also be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. With that command you can specify the dimensions and placement at creation time.

## Volby

|  |  |
| --- | --- |
|  | Kužel   * Radius 1 - poloměr oblouku nebo kružnice definující spodní plochu * Radius 2 - poloměr oblouku nebo kružnice definující vrchní plochu * Výška - výška kuželu * Úhel - počet stupňů oblouku nebo kružnice definující horní a dolní plochu komolého kuželu. Defaultních 360 stupňů vytváří kruhovou plochu, menší hodnota vytvoří část kuželu definovoanou horní a dolní plochou s okraji definovanými obloukem o velikosti dané úhlem a oběma poloměry.   See also: [Property editor](/Property_editor "Property editor").  A Part Cone object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties: Data Attachment  The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").  Cone   * Údaje**Radius1** (`Length`): The radius of the bottom face of the cone. Can be `0mm` if Údaje**Radius2** is larger than `0mm`. The default is `2mm`. * Údaje**Radius2** (`Length`): The radius of the top face of the cone. Can be `0mm` if Údaje**Radius1** is larger than `0mm`. The default is `4mm`. * Údaje**Height** (`Length`): The height of the cone. The default is `10mm`. * Údaje**Angle** (`Angle`): The angle of the circular arc that defines the top and bottom face of the cone. Valid range: `0° < value <= 360°`. The default is `360°`. If it is smaller than `360°` the resulting solid will be a segment of a cone.  Scripting See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").  A Part Cone can be created with the `addObject()` method of the document:  ``` cone = FreeCAD.ActiveDocument.addObject("Part::Cone", "myCone")  ```   * Where `"myCone"` is the name for the object. * The function returns the newly created object.   Example:  ``` import FreeCAD as App  doc = App.activeDocument()  cone = doc.addObject("Part::Cone", "myCone") cone.Radius1 = 5 cone.Radius2 = 10 cone.Height = 50 cone.Angle = 270 cone.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 60, 15))  doc.recompute()  ``` |

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Cone/cs&oldid=1466567>"