---
title: Díl Koule
---
|  |
| --- |
| Díl Koule |
| Umístění Menu |
| Díl -> Koule |
| Pracovní stoly |
| [Modul Díl](/Part_Workbench/cs "Part Workbench/cs"), Kompletace |
| Výchozí zástupce |
| *Nikdo* |
| Představen ve verzi |
| - |
| Viz také |
| [Díl Vytváření zákl.geom.tvarů](/Part_CreatePrimitives/cs "Part CreatePrimitives/cs") |
|  |

## Description

Vytvoří jednoduchou parametrickou kouli podle parametrů pozice, úhel1, úhel2, úhel3 a poloměr.

A Part Sphere can be truncated at the top and/or bottom by changing its Údaje**Angle1** and/or Údaje**Angle2** properties. It can be turned into a segment of a sphere by changing its Údaje**Angle3** property.

![](/images/Part_Sphere_Example.png)

## Usage

## Použití

V pracovní ploše [Díl](/Part_Workbench/cs "Part Workbench/cs") klikněte na ikonu koule ![](/images/Part_Sphere.png).
Koule bude při vytvoření umístěna do počátečního bodu (bod 0,0,0). Parametry úhly dovolují vytvořit částečnou kouli místo celé koule (defaultně jsou nastaveny na 360°)

## Example

![](/images/Part_Sphere_Scripting_Example.png)

Part Sphere from the scripting example

A Part Sphere object created with the [scripting example](#Scripting) below is shown here.

## Notes

* A Part Sphere can also be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. With that command you can specify the dimensions and placement at creation time.

## Volby

See also: [Property editor](/Property_editor "Property editor").

A Part Sphere object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Sphere

* Údaje**Radius** (`Length`): The radius of the sphere. The default is `5mm`.
* Údaje**Angle1** (`Angle`): The start angle of the circular arc profile of the sphere. Valid range: `-90° <= value <= 90°`. May not be equal to Údaje**Angle2**. The default is `-90°`.
* Údaje**Angle2** (`Angle`): The end angle of the circular arc profile of the sphere. Valid range: `-90° <= value <= 90°`. May not be equal to Údaje**Angle1**. The default is `90°`. If the total angle of the arc profile is smaller than `180°` the sphere will be truncated and have a flat face at the top and/or bottom.
* Údaje**Angle3** (`Angle`): The total angle of revolution of the sphere. Valid range: `0° < value <= 360°`. The default is `360°`. If it is smaller than `360°` the resulting solid will be a segment of a sphere.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Sphere can be created with the `addObject()` method of the document:

```
sphere = FreeCAD.ActiveDocument.addObject("Part::Sphere", "mySphere")

```

* Where `"mySphere"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

sphere = doc.addObject("Part::Sphere", "mySphere")
sphere.Radius = 20
sphere.Angle1 = -30
sphere.Angle2 = 45
sphere.Angle3 = 90
sphere.Placement = App.Placement(App.Vector(3, 9, 11), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Sphere/cs&oldid=1466550>"