---
title: Díl Kružnice
---
|  |
| --- |
| Díl Kružnice |
| Umístění Menu |
| Díl → [Vytváření zákl.geom.tvarů](/Part_CreatePrimitives/cs "Part CreatePrimitives/cs") → Kružnice |
| Pracovní stoly |
| [Díl](/Part_Workbench/cs "Part Workbench/cs"), [OpenSCAD](/OpenSCAD_Workbench/cs "OpenSCAD Workbench/cs") |
| Výchozí zástupce |
| *Nikdo* |
| Představen ve verzi |
| - |
| Viz také |
| .. |
|  |

## Description

A ![](/images/Part_Circle.svg) **Part Circle** is a parametric shape that can be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. In the coordinate system defined by its Údaje**Placement** property, the circle lies on the XY plane with its center at the origin.

A Part Circle is in fact a closed counterclockwise circular arc, it can be turned into an arc by changing its Údaje**Angle1** and/or Údaje**Angle2** properties.

![](/images/Part_Circle_Example.png)

## Usage

See [Part Primitives](/Part_Primitives#Usage "Part Primitives").

A Part Circle can alternatively be created by selecting three points:

1. In the task panel of the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command select the **![](/images/Part_Circle.svg) Circle** option from the dropdown list.
2. Press the From three points button.
3. Select three vertices in the [3D view](/3D_view "3D view"). There is no need to hold down the Ctrl key.
4. A circle is created.
5. The selected vertices are only used at creation time to calculate the Údaje**Radius** and Údaje**Placement** of the circle.

## Example

![](/images/Part_Circle_Scripting_Example.png)

Part Circle from the scripting example

A Part Circle object created with the [scripting example](#Scripting) below is shown here.

### Základní geometrické tvary

|  |  |
| --- | --- |
|  | Kružnice Parametr  * **Poloměr**: * **Úhel 1**: * **Úhel 2**: * **Ze tří bodů**:  Umístění |

See also: [Property editor](/Property_editor "Property editor").

A Part Circle object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Base

* Údaje**Radius** (`Length`): The radius of the circle or circular arc. The default is `2mm`.
* Údaje**Angle1** (`Angle`): The start angle of the circular arc. Valid range: `0° < value <= 360°`. The default is `0°`.
* Údaje**Angle2** (`Angle`): The end angle of the circular arc. Valid range: `0° < value <= 360°`. The default is `360°`. If Údaje**Angle1** and Údaje**Angle2** are equal, or if one angle is `0°` and the other `360°`, a full circle is created.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Circle can be created with the `addObject()` method of the document:

```
circle = FreeCAD.ActiveDocument.addObject("Part::Circle", "myCircle")

```

* Where `"myCircle"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

circle = doc.addObject("Part::Circle", "myCircle")
circle.Radius = 10
circle.Angle1 = 45
circle.Angle2 = 225
circle.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Circle/cs&oldid=1222571>"