---
title: Díl Torus
---
|  |
| --- |
| Díl\_Torus |
| Umístění Menu |
| Díl -> Torus |
| Pracovní stoly |
| [Modul Díl](/Part_Workbench/cs "Part Workbench/cs"), Kompletace |
| Výchozí zástupce |
| *Nikdo* |
| Představen ve verzi |
| - |
| Viz také |
| [Díl Vytváření zákl.geom.tvarů](/Part_CreatePrimitives/cs "Part CreatePrimitives/cs") |
|  |

## Description

Vytvoří jednoduchý parametrický torus podle parametrů pozice, úhel1, úhel2, úhel3, poloměr1 a poloměr2. Při vytvoření je torus umístěn do počátečního bodu (bod 0,0,0). Parametry úhly dovolují vytvořit částečný torus místo celého (úhly jsou defaultně nastaveny na 360°), poloměr 1 definuje vnitřní díru a poloměr 2 určuje tloušťku torusu.

A Part Torus can be turned into a segment of a torus by changing its Údaje**Angle3** property. By changing its Údaje**Angle1** and/or Údaje**Angle2** properties the swept profile can become a segment of a circle.

![](/images/Part_Torus_Example.png)

## Usage

1. There are several ways to invoke the command:
   * Press the ![](/images/Part_Torus.svg) [Torus](/Part_Torus "Part Torus") button.
   * Select the **Part → Primitives → ![](/images/Part_Torus.svg) Torus** option from the menu.
2. The torus is created.
3. Optionally change the dimensions and Údaje**Placement** of the torus by doing one of the following:
   * Double-click the object in the [Tree view](/Tree_view "Tree view"):
     1. The **Geometric Primitives** task panel opens.
     2. Change one or more properties.
     3. The object is dynamically updated in the [3D view](/3D_view "3D view").
     4. Press the OK button.
   * Change the properties in the [Property editor](/Property_editor "Property editor").
   * Change the Údaje**Placement** with the ![](/images/Std_TransformManip.svg) [Std TransformManip](/Std_TransformManip "Std TransformManip") command.

## Example

![](/images/Part_Torus_Scripting_Example.png)

Part Torus from the scripting example

A Part Torus object created with the [scripting example](#Scripting) below is shown here.

## Notes

* A Part Torus can also be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. With that command you can specify the dimensions and placement at creation time.

## Properties

See also: [Property editor](/Property_editor "Property editor").

A Part Torus object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Torus

* Údaje**Radius1** (`Length`): The radius of the circular path of the torus. The default is `10mm`.
* Údaje**Radius2** (`Length`): The radius of the circular profile of the torus. The default is `2mm`.
* Údaje**Angle1** (`Angle`): The start angle of the circular profile. Valid range: `-180° <= value <= 180°`. The default is `-180°`.
* Údaje**Angle2** (`Angle`): The end angle the circular profile. Valid range: `-180° <= value <= 180°`. The default is `180°`. If the total angle of the circular profile is smaller than `360°` the profile will have a pie-shape.
* Údaje**Angle3** (`Angle`): The angle of the circular path of the torus. Valid range: `0° < value <= 360°`. The default is `360°`. If it is smaller than `360°` the resulting solid will be a segment of a torus.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Torus can be created with the `addObject()` method of the document:

```
torus = FreeCAD.ActiveDocument.addObject("Part::Torus", "myTorus")

```

* Where `"myTorus"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

torus = doc.addObject("Part::Torus", "myTorus")
torus.Radius1 = 20
torus.Radius2 = 10
torus.Angle1 = -90
torus.Angle2 = 45
torus.Angle3 = 270
torus.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Torus/cs&oldid=1466573>"