---
title: Díl Přímka
---
|  |
| --- |
| Díl Přímka |
| Umístění Menu |
| Part → [Vytváření zákl.geom.tvarů](/Part_CreatePrimitives/cs "Part CreatePrimitives/cs") → Přímka |
| Pracovní stoly |
| [Díl](/Part_Workbench/cs "Part Workbench/cs"), [OpenSCAD](/OpenSCAD_Workbench/cs "OpenSCAD Workbench/cs") |
| Výchozí zástupce |
| *Nikdo* |
| Představen ve verzi |
| - |
| Viz také |
| .. |
|  |

## Description

A ![](/images/Part_Line.svg) **Part Line** is a parametric line that can be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. The coordinates of its start and end point are relative to the coordinate system defined by its Údaje**Placement** property.

![](/images/Part_Line_Example.png)

## Usage

See [Part Primitives](/Part_Primitives#Usage "Part Primitives").

## Properties

See also: [Property editor](/Property_editor "Property editor").

A Part Line object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Vertex 1 - Start

* Údaje**X1** (`Distance`): The X coordinate of the start point of the line. The default is `0mm`.
* Údaje**Y1** (`Distance`): The Y coordinate of the start point of the line. The default is `0mm`.
* Údaje**Z1** (`Distance`): The Z coordinate of the start point of the line. The default is `0mm`.

Vertex 2 - Finish

* Údaje**X2** (`Distance`): The X coordinate of the end point of the line. The default is `10mm`.
* Údaje**Y2** (`Distance`): The Y coordinate of the end point of the line. The default is `10mm`.
* Údaje**Z2** (`Distance`): The Z coordinate of the end point of the line. The default is `10mm`.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Line can be created with the `addObject()` method of the document:

```
line = FreeCAD.ActiveDocument.addObject("Part::Line", "myLine")

```

* Where `"myLine"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

line = doc.addObject("Part::Line", "myLine")
line.X1 = 1
line.Y1 = 3
line.Z1 = 6
line.X2 = 2
line.Y2 = 3
line.Z2 = 9

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Line/cs&oldid=1109424>"