---
title: Draft Offset
---

|                                                                                    |
| ---------------------------------------------------------------------------------- |
| Draft Offset                                                                       |
| Menu location                                                                      |
| Modification → Offset Modify → Offset                                              |
| Workbenches                                                                        |
| [Draft](/Draft_Workbench "Draft Workbench"), [BIM](/BIM_Workbench "BIM Workbench") |
| Default shortcut                                                                   |
| O S                                                                                |
| Introduced in version                                                              |
| -                                                                                  |
| See also                                                                           |
| [Part Offset2D](/Part_Offset2D "Part Offset2D")                                    |
|                                                                                    |

## Description

The ![](/images/Draft_Offset.svg) **Draft Offset** command offsets each segment of a selected object over a given distance, or creates an offset copy of the selected object.

![](/images/Draft_Offset_example.jpg)

Offsetting a Draft Wire

## Usage

See also: [Draft Snap](/Draft_Snap "Draft Snap") and [Draft Constrain](/Draft_Constrain "Draft Constrain").

1. Optionally select one object. The object must lie on the current [Draft working plane](/Draft_SelectPlane "Draft SelectPlane").
2. There are several ways to invoke the command:
   - Press the ![](/images/Draft_Offset.svg) [Offset](/Draft_Offset "Draft Offset") button.
   - [Draft](/Draft_Workbench "Draft Workbench"): Select the **Modification → ![](/images/Draft_Offset.svg) Offset** option from the menu.
   - [BIM](/BIM_Workbench "BIM Workbench"): Select the **Modify → ![](/images/Draft_Offset.svg) Offset** option from the menu.
   - Use the keyboard shortcut: O then S.
3. If you have not yet selected an object: select an object in the [3D view](/3D_view "3D view").
4. The **Offset** task panel opens. See [Options](#Options) for more information.
5. To define the offset distance do one of the following:
   - Pick a point in the [3D view](/3D_view "3D view").
   - Enter a numerical value:
     1. Make sure the pointer is on the correct side of the object in the [3D view](/3D_view "3D view").
     2. Do not move the pointer out of the [3D view](/3D_view "3D view").
     3. Enter a **Distance**.
     4. Press Enter to finish the command.

## Options

The single character keyboard shortcuts available in the task panel can be changed. See [Draft Preferences](/Draft_Preferences "Draft Preferences"). The shortcuts mentioned here are the default shortcuts (for version 1.0).

- If the **OCC-style offset** checkbox is checked a special offset style is used: open [Draft Wires](/Draft_Wire "Draft Wire") are offset on both sides, and new edges are connected with rounded corners. This only works for planar objects with at least two edges. Note that with this style a new non-parametric object is created, and if copy mode is off the original object is deleted.
- Press C or click the **Copy** checkbox to toggle copy mode. If copy mode is on, the command will create an offset copy instead of offsetting the original object.
- Holding down Alt before picking points in the [3D view](/3D_view "3D view") will also toggle copy mode. While Alt is held down multiple offset points can be picked. Release Alt to finish the command and see the created copies.
- Hold down Shift to keep the offset distance linked to the current segment.
- Press S to switch [Draft snapping](/Draft_Snap "Draft Snap") on or off.
- Press Esc or the Close button to abort the command.

## Notes

- To create an offset version of a [Draft BSpline](/Draft_BSpline "Draft BSpline") its points are offset individually, and from the new points a new spline is calculated. This new spline is not parallel to the original spline. For an exact parallel offset of a [Draft BSpline](/Draft_BSpline "Draft BSpline") the [Part Offset2D](/Part_Offset2D "Part Offset2D") command should be used.
- The Draft Offset command cannot handle [Draft BezCurves](/Draft_BezCurve "Draft BezCurve"). Use the [Part Offset2D](/Part_Offset2D "Part Offset2D") command instead.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To offset objects use the `offset` method of the Draft module. The method can only handle [Draft Wires](/Draft_Wire "Draft Wire"), [Draft Circles](/Draft_Circle "Draft Circle"), [Draft Rectangles](/Draft_Rectangle "Draft Rectangle"), [Draft Polygons](/Draft_Polygon "Draft Polygon") and [Draft BSplines](/Draft_BSpline "Draft BSpline").

```
offset_obj = offset(obj, delta, copy=False, bind=False, sym=False, occ=False)

```

- `obj` is the object to be offset.
- `delta` contains the offset information:
  - For [Draft Wires](/Draft_Wire "Draft Wire"), [Draft Rectangles](/Draft_Rectangle "Draft Rectangle") and [Draft Polygons](/Draft_Polygon "Draft Polygon") it is an offset vector that must be perpendicular to the first segment of the object.
  - For [Draft Circles](/Draft_Circle "Draft Circle") it is the new radius.
  - For [Draft BSplines](/Draft_BSpline "Draft BSpline") it is a list of new points.
- If `copy` is `True` the original object is kept and a new object is created.
- If `bind` is `True` a face is created by connecting the shape of the original object and the shape of its offset. This only works for open [Draft Wires](/Draft_Wire "Draft Wire").
- If `sym` is `True`, and `bind` is `True` as well, the offset is made on both sides of the original object, the total width being the length of the given vector. This only works for open [Draft Wires](/Draft_Wire "Draft Wire").
- If `occ` is `True` OCC-style offsetting is used. See [Options](#Options). If `occ` is `True` the `bind` and `sym` arguments are ignored.
- `offset_obj` is returned with the original offset object, or with the new object. If `bind` is `True` or `occ` is `True`, the new object is a `Part::Feature` object.

Example:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(1500, 2000, 0)
p3 = App.Vector(4000, 0, 0)

wire = Draft.make_wire([p1, p2, p3])
doc.recompute()

vector = App.Vector(-200, 150, 0)
offset1 = Draft.offset(wire, vector, copy=True, bind=True, sym=True)
offset2 = Draft.offset(wire, 3*vector, copy=True)
offset3 = Draft.offset(wire, 6*vector, copy=True)
offset4 = Draft.offset(wire, 9*vector, copy=True)
offset5 = Draft.offset(wire, 1.5*vector, copy=True, occ=True)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Offset/en&oldid=1473149>"
