---
title: 共通・更新
---
|  |
| --- |
| 共通・更新 |
| メニューの場所 |
| 編集 → 更新 |
| ワークベンチ |
| 全て |
| デフォルトのショートカット |
| F5 |
| 導入バージョン |
| - |
| 参照 |
| *なし* |
|  |

## 概要

The **Std Refresh** command recomputes the active document. The command is disabled if the document does not require a recompute.

## 使い方

1. There are several ways to invoke the command:
   * Press the ![](/images/Std_Refresh.svg) [Refresh](/Std_Refresh "Std Refresh") button.
   * Select the **Edit → ![](/images/Std_Refresh.svg) Refresh** option from the menu.
   * Use the keyboard shortcut: F5.

## オプション

* To force a recompute select the document or one or more objects in the [Tree view](/Tree_view "Tree view"), choose the **![](/images/Std_MarkToRecompute.svg) Mark to recompute** option from the context menu, and invoke the command.
* For objects, but not for documents, you can also choose **Recompute object** from the same context menu.

## 補足

* For a macro that will recompute the active document see: [Macro ForceRecompute](/Macro_ForceRecompute "Macro ForceRecompute").

## スクリプト処理

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To recompute a document use the `recompute` method of the document object.

```
import FreeCAD

doc = FreeCAD.newDocument()
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_Refresh/ja&oldid=1542823>"