---
title: Настройки верстака ПроектнаяДеталь (PartDesign)
---
## Введение

![](/images/Workbench_Part.svg) [Верстак Деталь](/Part_Workbench/ru "Part Workbench/ru") и ![](/images/Workbench_PartDesign.svg) [Верстак ПроектнаяДеталь (PartDesign)](/PartDesign_Workbench/ru "PartDesign Workbench/ru") используют одни и те же настройки. Их можно найти в [Редакторе Настроек](/Preferences_Editor/ru "Preferences Editor/ru"). В меню выберите **Правка → Настройки...**, а затем **![](/images/Preferences-part_design.svg) Деталь/ПроектнаяДеталь (Part/Part Design)**. Этот раздел доступен только в том случае, если в текущей сессии FreeCAD был загружен один из верстаков.

Некоторые дополнительные настройки можно изменить только в [Редакторе параметров](/Std_DlgParameter/ru "Std DlgParameter/ru"). На странице [Тонкой настройки](/Fine-tuning/ru "Fine-tuning/ru") перечислены некоторые из них.

Эта страница обновлена для версии 1.0.

## Доступные настройки

Имеются три вкладки: [Главный](#General), [Форма представления](#Shape_view) и [Внешний вид фигуры](#Shape_appearance).

### Главный

![](/images/Preferences_PartDesign_Page_General.png)

![](/images/Preferences_PartDesign_Page_General_RU.png)
  
На этой странице вы можете настроить следующие параметры:

| Параметр | Описание |
| --- | --- |
| **Автоматически проверить модель после булевой операции** | Если флажок установлен, то [Граничное представление (рус.)](https://ru.wikipedia.org/wiki/Граничное_представление)[(англ.)](https://en.wikipedia.org/wiki/Boundary_representation) (BRep) модели [проверяется](/Part_CheckGeometry/ru "Part CheckGeometry/ru") после выполнения [булевых операций](/Part_Boolean/ru "Part Boolean/ru"). |
| **Автоматически улучшать модель после булевых операций** | Если флажок установлен, то модель [улучшается](/Part_RefineShape/ru "Part RefineShape/ru") после [булевых операций](/Part_Boolean/ru "Part Boolean/ru"). |
| **Автоматически улучшать модель после операций с базовым эскизом** | Если флажок установлен, то модели построенные на базе эскиза будут [улучшатся](/Part_RefineShape/ru "Part RefineShape/ru") после изминения эскиза |
| **Разрешить несколько твёрдых тел в теле конструкции детали по умолчанию (экспериментальная функция)** | Если флажок установлен, то Тела (Bodies) могут состоять из нескольких твёрдых тел. [представлено в версии 1.0](/Release_notes_1.0/ru "Release notes 1.0/ru") |

### Форма представления

![](/images/Preferences_PartDesign_Page_Shape_view.png)

![](/images/Preferences_PartDesign_Page_Shape_view_RU.png)
  
На этой странице вы можете настроить следующие параметры:

| Параметр | Описание |
| --- | --- |
| **Максимальное отклонение в зависимости от ограничительной рамки модели** | Максимальное [линейное отклонение (англ.)](https://www.opencascade.com/doc/occt-7.3.0/overview/html/occt_user_guides__modeling_algos.html#occt_modalg_11_2) [тесселированных](#Tessellation) объектов от их поверхности. |
| **Максимальное угловое смещение** | Максимальное [угловое отклонение (англ.)](https://www.opencascade.com/doc/occt-7.3.0/overview/html/occt_user_guides__modeling_algos.html#occt_modalg_11_2) от одной секции [тесселированного](#Tessellation) объекта к следующей секции. |

### Внешний вид фигуры

![](/images/Preferences_PartDesign_Page_Shape_appearance.png)

![](/images/Preferences_PartDesign_Page_Shape_appearance_RU.png)
  
Объяснение цветов можно найти [здесь](/Part_ColorPerFace/ru#Usage "Part ColorPerFace/ru").

На этой странице вы можете задать следующие параметры:

| Name | Description |
| --- | --- |
| **Цвет фигуры** | Цвет свечения (рассеивания) для новых фигур. Если задана опция **Случайный (Random)**, вместо него используется случайный цвет. |
| **Цвет формы окружающей среды** | Цвет окружающей среды для новых фигур. [представлено в версии 1.0](/Release_notes_1.0/ru "Release notes 1.0/ru") |
| **Цвет формы излучения** | Цвет излучения для новых фигур. [представлено в версии 1.0](/Release_notes_1.0/ru "Release notes 1.0/ru") |
| **Зрительный цвет формы** | Цвет зеркального блеска для новых форм. [представлено в версии 1.0](/Release_notes_1.0/ru "Release notes 1.0/ru") |
| **Прозрачность фигуры** | Прозрачность для новых фигур. [представлено в версии 0.21](/Release_notes_0.21/ru "Release notes 0.21/ru") |
| **Блеск фигуры** | Сила блеска для новых форм. [представлено в версии 1.0](/Release_notes_1.0/ru "Release notes 1.0/ru") |
| **Цвет линии** | Цвет линий для новых фигур. |
| **Ширина линии** | Толщина линий контура для новых фигур. |
| **Цвет вершины** | Цвет для новых [вершин](/Glossary/ru#Vertex "Glossary/ru"). |
| **Размер вершин** | Размер для новых [вершин](/Glossary/ru#Vertex "Glossary/ru"). |
| **Цвет охватывающей рамки** | Цвет [оконтуривающих рамок](/Property_editor/ru#View "Property editor/ru") в 3D-виде. |
| **Размер шрифта охватывающей рамки** | Размер шрифта [ограничивающих рамок](/Property_editor/ru#View "Property editor/ru") в 3D-виде. [представлено в версии 1.0](/Release_notes_1.0/ru "Release notes 1.0/ru") |
| **Двухстороннее отображение** | Если флажок установлен, цвет внутренней поверхности граней будет таким же, как и наружной. Если флажок не установлен, вместо него используется либо [цвет подсветки](/Preferences_Editor/ru#3D_View "Preferences Editor/ru"), если она включена, либо чёрный. |
| **Цвет текста** | Цвет текста для новых примечаний к документу. В настоящее время эти аннотации можно добавить только с помощью [консоли Python](/Python_console/ru "Python console/ru"):  `obj = App.ActiveDocument.addObject("App::Annotation", "Label")` |

## Тесселяция

Для эффективного отображения объекта его поверхность [тесселируется/замощается (рус.)](https://ru.wikipedia.org/wiki/Замощение_(компьютерная_графика)) [(англ.)](https://en.wikipedia.org/wiki/Tessellation_(computer_graphics)), то есть отображается с небольшими изменениями от его реальной поверхности. Это относится не только к моделям ПроектнаяДеталь (PartDesign), но и к другим объектам во FreeCAD.

Нижний предел тесселяции составляет 0,01%. Если вы действительно хотите потратить дополнительное время, вы можете уменьшить нижний предел ещё больше, открыв [Редактор параметров](/Std_DlgParameter/ru "Std DlgParameter/ru").

В редакторе параметров перейдите в **BaseApp → Preferences → Mod → Part**, щёлкните правой кнопкой мыши на **MeshDeviation** и выберите **Change value** из контекстного меню. Установите значение минимальной тесселяции по вашему выбору. Помните, что значение задается в %, то есть для значения 0,005% нужно ввести `0,00005`. Наименьшее возможное значение - `1e-7`. Обратите внимание, что в [Редакторе Настроек](/Preferences_Editor/ru "Preferences Editor/ru") вы всё равно увидите 0,01%, даже если задали меньшее значение.

Retrieved from "<http://wiki.freecad.org/index.php?title=PartDesign_Preferences/ru&oldid=1563256>"