---
title: Visualizza Vista frontale
---

|                                                                                                              |
| ------------------------------------------------------------------------------------------------------------ |
| Vista frontale                                                                                               |
| Posizione nel menu                                                                                           |
| Visualizza → Viste standard → Di fronte                                                                      |
| Ambiente                                                                                                     |
| Tutti                                                                                                        |
| Avvio veloce                                                                                                 |
| 1                                                                                                            |
| Introdotto nella versione                                                                                    |
| -                                                                                                            |
| Vedere anche                                                                                                 |
| [Vista dall'alto](/Std_ViewTop/it "Std ViewTop/it"), [Vista da destra](/Std_ViewRight/it "Std ViewRight/it") |
|                                                                                                              |

## Descrizione

Il comando **Vista frontale** orienta la camera della [Vista 3D](/3D_view/it "3D view/it") nella direzione dell'asse Y positivo.

![](/images/FreeCAD_views_front.svg)

La freccia 1 punta nella direzione della vista frontale.

## Utilizzo

1. Esistono diversi modi per invocare il comando:
   - Premere il pulsante ![](/images/Std_ViewFront.svg) Di fronte.
   - Selezionare l'opzione **Visualizza → Viste standard → ![](/images/Std_ViewFront.svg) Di fronte** dal menu.
   - Selezionare l'opzione **Viste standard → ![](/images/Std_ViewFront.svg) Di fronte** dal menu contestuale della [vista 3D](/3D_view/it "3D view/it").
   - Usare la scorciatoia da tastiera: 1.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Utilizzare il metodo `viewFront` dell'oggetto View per passare alla vista frontale. Sono disponibili anche metodi per gli altri orientamenti principali della vista: `viewTop`, `viewRight`, `viewRear`, `viewBottom` e `viewRight` .

```
import FreeCADGui

view = FreeCADGui.ActiveDocument.ActiveView
view.viewFront()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_ViewFront/it&oldid=1450001>"
