---
title: Modifica Modalità modifica
---
|  |
| --- |
| Modalità modifica |
| Posizione nel menu |
| Modifica → Attiva/disattiva Modalità modifica |
| Ambiente |
| Tutti |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| *Nessuno* |
|  |

## Descrizione

Il comando **Std Edit** attiva o disattiva la modalità di modifica di un oggetto.

## Utilizzo

1. Se nessun oggetto è in modalità modifica: selezionare un singolo oggetto.
2. Selezionare l'opzione **Modifica → ![](/images/Std_Edit.svg) Attiva/disattiva la modalità modifica** dal menu.
3. Viene attivata la modalità di modifica predefinita dell'oggetto selezionato o viene disattivata la modalità di modifica esistente.

## Note

* Alcuni strumenti saranno disabilitati (in grigio) nell'interfaccia utente mentre è attiva la modalità di modifica di un oggetto.
* Non tutti i tipi di oggetto hanno una modalità di modifica.
* Le funzioni disponibili in modalità modifica dipendono dal tipo di oggetto.
* La modalità di modifica di un oggetto può essere attivata anche facendo doppio clic su di esso nella [Vista albero](/Tree_view/it "Tree view/it"). In tal caso la modalità di modifica utilizzata può essere definita con il comando [Impostazione modalità Modifica](/Std_UserEditMode/it "Std UserEditMode/it").

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per attivare la modalità di modifica di un oggetto, utilizzare il metodo `setEdit` dell'oggetto documento. Questo metodo non è disponibile se FreeCAD è in modalità console.

```
import FreeCADGui

FreeCADGui.ActiveDocument.setEdit("myObjectName",0)

```

Il secondo argomento è EditMode. Sono disponibili le seguenti opzioni:

```
0 = Predefinito
1 = Trasforma
2 = Taglio
3 = Colore

```

Per disattivare la modalità di modifica di un oggetto, utilizzare il metodo `resetEdit` dell'oggetto documento.

```
import FreeCADGui

FreeCADGui.ActiveDocument.resetEdit()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_Edit/it&oldid=1496370>"