---
title: Visualizza Visualizza tutto
---

|                                                                               |
| ----------------------------------------------------------------------------- |
| Visualizza tutto                                                              |
| Posizione nel menu                                                            |
| Visualizza → Viste standard → Visualizza tutto                                |
| Ambiente                                                                      |
| Tutti                                                                         |
| Avvio veloce                                                                  |
| V F                                                                           |
| Introdotto nella versione                                                     |
| -                                                                             |
| Vedere anche                                                                  |
| [Visualizza la selezione](/Std_ViewFitSelection/it "Std ViewFitSelection/it") |
|                                                                               |

## Descrizione

Il comando **Visualizza tutto** adatta la camera in modo che tutti gli oggetti siano visibili e si adattino all'interno della [Vista 3D](/3D_view/it "3D view/it") attiva.

## Utilizzo

1. Esistono diversi modi per invocare il comando:
   - Premere il pulsante ![](/images/Std_ViewFitAll.svg) Visualizza tutto.
   - Selezionare l'opzione **Visualizza → Viste standard → ![](/images/Std_ViewFitAll.svg) Visualizza tutto** dal menu.
   - Selezionare l'opzione **![](/images/Std_ViewFitAll.svg) Visualizza tutto** dal menu contestuale della [vista 3D](/3D_view/it "3D view/it").
   - Selezionare l'opzione **![](/images/Std_ViewFitAll.svg) Visualizza tutto** dal menu Mini-cubo del [Cubo di navigazione](/Navigation_Cube/it "Navigation Cube/it").
   - Usare la scorciatoia da tastiera: V e poi F.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Utilizzare il metodo `fitAll` dell'oggetto View per ingrandire e adattare tutto.

```
import FreeCADGui

view = FreeCADGui.ActiveDocument.ActiveView
view.fitAll()

```

Per la vista attiva può essere utilizzato anche il metodo `SendMsgToActiveView` dell'oggetto FreeCADGui.

```
import FreeCADGui

FreeCADGui.SendMsgToActiveView("ViewFit")

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_ViewFitAll/it&oldid=1450049>"
