---
title: Strumenti Aggiungi un documento di testo
---
|  |
| --- |
| Aggiungi un documento di testo |
| Posizione nel menu |
| Strumenti → Aggiungi un documento di testo |
| Ambiente |
| Tutti |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| 0.19 |
| Vedere anche |
| [Forma da testo di Draft](/Draft_ShapeString/it "Draft ShapeString/it"), [Testo di Draft](/Draft_Text/it "Draft Text/it") |
|  |

## Descrizione

Il comando **Aggiungi un documento di testo** crea un oggetto in grado di contenere un testo arbitrario. Questo elemento può essere utilizzato per scrivere delle informazioni generali o della documentazione sul modello.

## Utilizzo

1. Andare nel menu **Strumenti → ![](/images/Std_TextDocument.svg)Aggiungi un documento di testo**.
2. Fare doppio clic sul nuovo oggetto creato nella [Vista ad albero](/Tree_view/it "Tree view/it") per aprire una scheda in cui scrivere il testo.
3. Aggiungere il testo.
4. Chiudere la scheda e salvare il file quando viene richiesto.

## Proprietà

### Vista

Editor

* Vista**Font Name** (`Font`): un nome di carattere, ad esempio, `Ubuntu Mono`.
* Vista**Font Size** (`Float`): una dimensione del carattere in punti, ad esempio, `11`.
* Vista**Read Only** (`Bool`): il valore predefinito è `false`. Se impostato su `true` il testo non può essere modificato.
* Vista**Syntax Highlighter** (`Enumeration`): il valore predefinito è `None`. Se impostato su `Python`, il testo verrà evidenziato come nella [console Python](/Python_console/it "Python console/it").

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Vedere [Part Feature](/Part_Feature/it "Part Feature/it") per le informazioni generali sull'aggiunta di oggetti a un documento.

Un oggetto `App::TextDocument` viene creato con il metodo `addObject()` del documento. Una volta che esiste un TextDocument, le sue informazioni testuali vengono archiviate nel suo attributo `Text`. Questo attributo può essere utilizzato in altri oggetti, ad esempio, come stringa in una ![](/images/Draft_ShapeString.svg) [Forma da testo](/Draft_ShapeString/it "Draft ShapeString/it") di Draft .

```
import FreeCAD as App
import Draft

doc = App.newDocument()
obj = doc.addObject("App::TextDocument", "Text_document")
obj.Text = "textual information"
doc.recompute()

obj2 = Draft.makeShapeString(obj.Text, "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 10)
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_TextDocument/it&oldid=1457775>"