---
title: Visualizza Ruota la vista a sinistra
---

|                                                                    |
| ------------------------------------------------------------------ |
| Ruota a sinistra                                                   |
| Posizione nel menu                                                 |
| Visualizza → Viste standard → Ruota a sinistra                     |
| Ambiente                                                           |
| Tutti                                                              |
| Avvio veloce                                                       |
| Shift+Sinistra                                                     |
| Introdotto nella versione                                          |
| -                                                                  |
| Vedere anche                                                       |
| [Ruota a destra](/Std_ViewRotateRight/it "Std ViewRotateRight/it") |
|                                                                    |

## Descrizione

Il comando **Ruota a sinistra** ruota la camera nella [vista 3D](/3D_view/it "3D view/it") attiva intorno alla direzione della vista con incrementi di 90 gradi verso sinistra (in senso antiorario).

## Utilizzo

1. Esistono diversi modi per invocare il comando:
   - Selezionare l'opzione **Visualizza → Viste standard → ![](/images/Std_ViewRotateLeft.svg) Ruota a sinistra** dal menu.
   - Selezionare l'opzione **Viste standard → ![](/images/Std_ViewRotateLeft.svg) Ruota a sinistra** dal menu contestuale della [vista 3D](/3D_view/it "3D view/it").
   - Usare la scorciatoia da tastiera: Maiusc+Sinistra.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Utilizzare il metodo `viewRotateLeft` dell'oggetto View per ruotare la vista a sinistra. È disponibile anche il metodo `viewRotateRight`.

```
import FreeCADGui

view = FreeCADGui.ActiveDocument.ActiveView
view.viewRotateLeft()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_ViewRotateLeft/it&oldid=1449959>"
