---
title: File Unisci documenti
---
|  |
| --- |
| Unisci documenti |
| Posizione nel menu |
| File → Unisci documento... |
| Ambiente |
| Tutti |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| *Nessuno* |
|  |

## Descrizione

Il comando **Unisci documenti** aggiunge il contenuto di un file FreeCAD nel documento attivo.

## Utilizzo

1. Selezionare l'opzione **File → ![](/images/Std_MergeProjects.svg) Unisci documento...** dal menu.
2. Selezionare un file FreeCAD nella finestra di dialogo.
3. Premere il pulsante Apri.

## Opzioni

* Premere il tasto Esc o il pulsante Annulla per annullare il comando.

## Note

* Un progetto non può essere unito a se stesso, la selezione del file corrente non è consentita.
* FreeCAD cambia automaticamente i nomi interni e, a seconda delle [preferenze](/Preferences_Editor/it#Documento "Preferences Editor/it"), le etichette degli oggetti per evitare conflitti di nomi.

## Scripting

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per unire un progetto utilizzare il metodo `mergeProject` dell'oggetto documento.

```
import FreeCAD

FreeCAD.ActiveDocument.mergeProject("Path_to_FCStd_project_file")

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_MergeProjects/it&oldid=1539299>"