---
title: Visualizza Box contenitore
---

|                                                          |
| -------------------------------------------------------- |
| Box contenitore                                          |
| Posizione nel menu                                       |
| Visualizza → Box contenitore                             |
| Ambiente                                                 |
| Tutti                                                    |
| Avvio veloce                                             |
| _Nessuno_                                                |
| Introdotto nella versione                                |
| 0.19                                                     |
| Vedere anche                                             |
| [Stile di disegno](/Std_DrawStyle/it "Std DrawStyle/it") |
|                                                          |

## Descrizione

Il comando **Box di selezione** attiva o disattiva la modalità di evidenziazione del riquadro di selezione globale. Se questa modalità è attivata, gli oggetti selezionati vengono contrassegnati in una [Vista 3D](/3D_view "3D view") con un riquadro di selezione evidenziato anche se Vista**Selection Style** è impostato su 'Forma'.

## Utilizzo

1. Selezionare l'opzione **Visualizza → ![](/images/Std_SelBoundingBox.svg) Box contenitore** dal menu.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per modificare il parametro ShowSelectionBoundingBox utilizzare il metodo `SetBool` del ParameterGrp appropriato.

```
import FreeCAD, FreeCADGui

grp = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/View")
if grp.GetBool("ShowSelectionBoundingBox"):
    grp.SetBool("ShowSelectionBoundingBox", False)
else:
    grp.SetBool("ShowSelectionBoundingBox", True)

FreeCADGui.updateCommands()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_SelBoundingBox/it&oldid=1450055>"
