---
title: Visualizza Origine degli assi
---

|                                 |
| ------------------------------- |
| Origine degli assi              |
| Posizione nel menu              |
| Visualizza → Origine degli assi |
| Ambiente                        |
| Tutti                           |
| Avvio veloce                    |
| A C                             |
| Introdotto nella versione       |
| -                               |
| Vedere anche                    |
| _Nessuno_                       |
|                                 |

## Descrizione

Il comando **Origine degli assi** attiva o disattiva il sistema di assi nella [vista 3D](/3D_view/it "3D view/it") attiva.

Il sistema di assi è composto da tre frecce che rappresentano gli assi X, Y e Z positivi del sistema di coordinate globale. Il loro punto di partenza comune è l'origine del sistema di coordinate globale.

![](/images/Std_AxisCross_example.svg)

Il sistema di assi (le lettere non fanno parte del sistema di assi)

## Utilizzo

1. Esistono diversi modi per invocare il comando:
   - Selezionare l'opzione **Visualizza → ![](/images/Std_AxisCross.svg) Origine degli assi** dal menu.
   - Usare la scorciatoia da tastiera: A then C.

## Note

- FreeCAD può visualizzare un indicatore di sistema di coordinate più piccolo nell'angolo in basso a destra delle viste 3D: **Modifica → Preferenze... → Display → Vista 3D → Mostra il sistema di coordinate nell'angolo**. Vedere [Editor delle preferenze](/Preferences_Editor/it#Vista_3D "Preferences Editor/it").
- Anche il [cubo di navigazione](/Navigation_Cube/it "Navigation Cube/it") include un indicatore del sistema di coordinate.

## Preferenze

Vedere anche: [Editor delle Preferenze](/Preferences_Editor/it "Preferences Editor/it").

- L'impostazione predefinita per l'origine degli assi può essere modificata: **Modifica → Preferenze... → Visualizza → Vista 3D → Mostra di default il sistema di assi**.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Utilizzare il metodo `setAxisCross` dell'oggetto View per attivare/disattivare la croce dell'asse.

```
import FreeCADGui

view = FreeCADGui.ActiveDocument.ActiveView
view.setAxisCross(True)
view.hasAxisCross()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_AxisCross/it&oldid=1451871>"
