---
title: File Nuovo
---
|  |
| --- |
| Nuovo |
| Posizione nel menu |
| File → Nuovo |
| Ambiente |
| Tutti |
| Avvio veloce |
| Ctrl+N |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Apri](/Std_Open/it "Std Open/it"), [Importa](/Std_Import/it "Std Import/it") |
|  |

## Descrizione

Il comando **Nuovo** crea un nuovo documento vuoto e lo rende il documento attivo.

## Utilizzo

1. Esistono diversi modi per invocare il comando:
   * Premere il pulsante ![](/images/Std_New.svg) Nuovo.
   * Selezionare l'opzione **File → ![](/images/Std_New.svg) Nuovo** dal menu.
   * Usare la scorciatoia da tastiera: Ctrl+N.

## Preferenze

Vedere anche: [Editor delle Preferenze](/Preferences_Editor/it "Preferences Editor/it").

* Per impostazione predefinita, FreeCAD si avvia senza un nuovo documento. Selezionare l'opzione **Modifica → Preferenze... → Generale → Documento → Crea un nuovo documento all'avvio** per modificare questo comportamento.
* Alcune proprietà del documento: nome dell'autore, nome dell'azienda e informazioni sulla licenza, possono essere preimpostate: **Modifica → Preferenze... → Generale → Documento → Diritti d'autore e Licenza**.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Molte proprietà possono anche essere modificate nella finestra di dialogo del comando [Informazioni sul progetto](/Std_ProjectInfo/it "Std ProjectInfo/it").

### Dati

Base

* Dati**Comment** (`String`): qualsiasi commento applicabile.
* Dati**Company** (`String`): nome dell'azienda.
* Dati**Created By** (`String`): nome dell'autore.
* Dati**Creation Date** (`String`): timbro data automatico (sola lettura).
* Dati**File Name** (`String`): il percorso completo del file. Vuoto se il documento non è stato salvato (sola lettura).
* Dati**Id** (`String`): non ancora implementato.
* Dati**Label** (`String`): il nome che apparirà nella [Vista ad albero](/Tree_view/it "Tree view/it"). Sostituito dal nome del documento dopo la riapertura.
* Dati**Last Modified By** (`String`): nome dell'autore.
* Dati**Last Modified Date** (`String`): timbro data automatico (sola lettura).
* Dati**License** (`String`): tipo di licenza.
* Dati**License URL** (`String`): URL della licenza.
* Dati (Hidden)**Material** (`Map`): mappa con le proprietà del materiale.
* Dati (Hidden)**Meta** (`Map`): mappa con metainformazioni aggiuntive.
* Dati**Show Hidden** (`Bool`): Se vero, gli elementi che sono stati nascosti nella [Vista ad albero](/Tree_view/it "Tree view/it") verranno comunque visualizzati. Nascondere gli elementi nell'albero può essere utile quando si lavora su modelli più grandi.
* Dati**Tip** (`Link`): non ancora implementato.
* Dati**Tip Name** (`String`): non ancora implementato.
* Dati**Transient Dir** (`String`): la directory temporanea utilizzata per i dati di ripristino (sola lettura).
* Dati (Hidden)**Uid** (`UUID`): UUID del documento (sola lettura).
* Dati**Unit System** (`Enumeration`): il sistema di unità del documento. Il valore iniziale dipende dal [Sistema di unità predefinito](/Preferences_Editor/it#Generale_2 "Preferences Editor/it"). [disponibile dalla versione 1.0](/Release_notes_1.0/it "Release notes 1.0/it")

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per creare un nuovo documento usa il metodo `newDocument([name], [hidden=False])` dell'applicazione FreeCAD. Il nome del documento deve essere univoco, che viene verificato automaticamente. Se non viene fornito alcun nome, il documento sarà denominato "Senza titolo". Se viene utilizzato `hidden=True`, il nuovo documento non verrà visualizzato nella GUI e non verrà visualizzata alcuna scheda.

```
import FreeCAD
from pathlib import Path

# The folder and filename we will use:
fld = 'D:/testfiles/'
fnm = fld + 'test.FCStd'

# Make sure fld exists:
Path(fld).mkdir(parents=True, exist_ok=True)

doc = FreeCAD.newDocument()
doc.saveAs(fnm)

FreeCAD.closeDocument(doc.Name)

doc = FreeCAD.open(fnm)
doc.save()

FreeCAD.closeDocument(doc.Name)

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_New/it&oldid=1448853>"