---
title: Part Spirale
---
|  |
| --- |
| Part Spirale |
| Emplacement du menu |
| Part → [Créer des primitives...](/Part_Primitives/fr "Part Primitives/fr") → Spirale |
| Ateliers |
| [Part](/Part_Workbench/fr "Part Workbench/fr"), [OpenSCAD](/OpenSCAD_Workbench/fr "OpenSCAD Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| 0.14 |
| Voir aussi |
| [Part Primitives](/Part_Primitives/fr "Part Primitives/fr") |
|  |

## Description

Une ![](/images/Part_Spiral.svg) **Part Spirale** est une forme paramétrique qui peut être créée avec la commande ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives/fr "Part Primitives/fr"). Dans le système de coordonnées défini par sa propriété Données**Placement**, la spirale se trouve sur le plan XY avec son centre à l'origine et son point de départ sur l'axe X. Elle s'élargit en tournant à l'envers. Elle s'élargit en tournant dans le sens inverse des aiguilles d'une montre.

![](/images/Part_Spiral_Example.png)

## Utilisation

Voir [Part Primitives](/Part_Primitives/fr#Utilisation "Part Primitives/fr").

## Exemple

![](/images/Part_Spiral_Scripting_Example.png)

Part Spirale à partir de l'exemple du script

Un objet Part Spirale créé avec l'[exemple du script](#Script) ci-dessous.

## Propriétés

Voir aussi : [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

Un objet Part Spirale est dérivé d'un [Part Feature](/Part_Feature/fr "Part Feature/fr") et hérite de toutes ses propriétés. Il possède également les propriétés supplémentaires suivantes :

### Données

Attachment

L'objet a les mêmes propriétés d'attachement qu'un [Part Part2DObject](/Part_Part2DObject/fr#Donn.C3.A9es "Part Part2DObject/fr").

Spiral

* Données**Growth** (`Length`) : distance entre deux tours consécutifs de la spirale. La valeur par défaut est `1mm`.
* Données**Radius** (`Length`) : rayon de départ de la spirale, la distance entre son centre et son point de départ. Peut être `0mm`. La valeur par défaut est `1mm`.
* Données**Rotations** (`QuantityConstraint`) : nombre de rotations, ou de tours, de la spirale. La valeur par défaut est `2`.
* Données**Segment Length** (`QuantityConstraint`) : nombre de tours par subdivision de la spirale. La valeur par défaut est `1`, ce qui signifie que chaque tour complet de la spirale est un segment séparé. Utilisez `0` pour supprimer la subdivision.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part Ecrire un script](/Part_scripting/fr "Part scripting/fr") et [Débuter avec les scripts FreeCAD](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Une Part Spirale est créée avec la méthode `addObject()` du document :

```
spiral = FreeCAD.ActiveDocument.addObject("Part::Spiral", "mySpiral")

```

* Où `"mySpiral"` est le nom de l'objet.
* La fonction restitue l'objet nouvellement créé.

Exemple :

```
import FreeCAD as App

doc = App.activeDocument()

spiral = doc.addObject("Part::Spiral", "mySpiral")
spiral.Growth = 2
spiral.Radius = 3
spiral.Rotations = 4
spiral.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Spiral/fr&oldid=1222531>"