---
title: Part Cylindre
---
|  |
| --- |
| Part Cylindre |
| Emplacement du menu |
| Part → Primitives → Cylindre |
| Ateliers |
| [Part](/Part_Workbench/fr "Part Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| - |
| Voir aussi |
| [Part Primitives](/Part_Primitives/fr "Part Primitives/fr") |
|  |

## Description

La commande ![](/images/Part_Cylinder.svg) **Part Cylindre** crée un solide cylindrique paramétrique. Il est le résultat de l'extrusion d'un arc de cercle le long d'une trajectoire droite. Dans le système de coordonnées défini par sa propriété Données**Placement**, la face inférieure du cylindre se trouve sur le plan XY avec son centre à l'origine.

Un Part Cylindre peut être transformé en un segment de cylindre en modifiant sa propriété Données**Angle**.

![](/images/Part_Cylinder_Example.png)

## Utilisation

1. Il existe plusieurs façons de lancer la commande :
   * Appuyez sur le bouton ![](/images/Part_Cylinder.svg) Cylindre.
   * Sélectionnez l'option **Part → Primitives → ![](/images/Part_Cylinder.svg) Cylindre** du menu.
2. Le cylindre est créé.
3. Vous pouvez modifier les dimensions et le Données**Placement** du cylindre en effectuant l'une des opérations suivantes :
   * Double-cliquez sur l'objet dans la [vue en arborescence](/Tree_view/fr "Tree view/fr") :
     1. Le panneau de tâches **Primitives géométriques** s'ouvre.
     2. Modifiez une ou plusieurs propriétés.
     3. L'objet est mis à jour dynamiquement dans la [vue 3D](/3D_view/fr "3D view/fr").
     4. Appuyez sur le bouton OK.
     5. Modifiez les propriétés dans l'[éditeur de propriétés](/Property_editor/fr "Property editor/fr").
   * Changez le Données**Placement** avec la commande ![](/images/Std_TransformManip.svg) [Std Transformer](/Std_TransformManip/fr "Std TransformManip/fr").

## Exemple

![](/images/Part_Cylinder_Scripting_Example.png)

Part Cylindre à partir de l'exemple du script

Un objet Part Cylindre créé avec l'[exemple du script](#Script) ci-dessous.

## Remarques

* Un Part Cylindre peut également être créé avec la commande ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives/fr "Part Primitives/fr"). Avec cette commande, vous pouvez spécifier les dimensions et le placement au moment de la création.

## Propriétés

Voir aussi : [Éditeur de propriétés](/Property_editor/fr "Property editor/fr").

Un objet Part Cylindre est dérivé d'un [Part Feature](/Part_Feature/fr "Part Feature/fr") et hérite de toutes ses propriétés. Il possède également les propriétés supplémentaires suivantes :

### Données

Attachment

L'objet a les mêmes propriétés d'attachement qu'un [Part Part2DObject](/Part_Part2DObject/fr#Donn.C3.A9es "Part Part2DObject/fr").

Cylinder

* Données**Radius** (`Length`) : rayon de l'arc de cercle qui définit le cylindre. La valeur par défaut est `2mm`.
* Données**Height** (`Length`) : hauteur du cylindre. La valeur par défaut est `10mm`.
* Données**Angle** (`Angle`) : angle de l'arc de cercle qui définit le cylindre. Plage valide : `0° < value <= 360°`. La valeur par défaut est `360°`. Si elle est inférieure à `360°`, le solide résultant sera un segment de cylindre.

Prism

* Données**First Angle** (`Angle`) : angle entre la direction d'extrusion du cylindre et son axe Z positif, mesuré autour de son axe Y. L'angle est positif vers son axe X positif. L'angle est positif vers son axe X positif. Plage valide : `0° <= value < 90°`. La valeur par défaut est `0°`. [introduit dans la version 0.20](/Release_notes_0.20/fr "Release notes 0.20/fr")
* Données**Second Angle** (`Angle`) : angle entre la direction d'extrusion du cylindre et son axe Z positif, mesuré autour de son axe X. L'angle est positif vers son axe Y positif. L'angle est positif vers son axe Y positif. Plage valide : `0° <= value < 90°`. La valeur par défaut est `0°`. [introduit dans la version 0.20](/Release_notes_0.20/fr "Release notes 0.20/fr")

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part Ecrire un script](/Part_scripting/fr "Part scripting/fr") et [Débuter avec les scripts FreeCAD](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Un Part Cylindre est créé avec la méthode `addObject()` du document :

```
cylinder = FreeCAD.ActiveDocument.addObject("Part::Cylinder", "myCylinder")

```

* Où `"myCylinder"` est le nom de l'objet.
* La fonction restitue l'objet nouvellement créé.

Exemple :

```
import FreeCAD as App

doc = App.activeDocument()

cylinder = doc.addObject("Part::Cylinder", "myCylinder")
cylinder.Radius = 10
cylinder.Height = 50
cylinder.Placement = App.Placement(App.Vector(5, 10, 15), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Cylinder/fr&oldid=1469855>"