---
title: Part Pyramide tronquée
---
|  |
| --- |
| Part Pyramide tronquée |
| Emplacement du menu |
| Part → [Créer des primitives](/Part_Primitives/fr "Part Primitives/fr") → Pyramide tronquée |
| Ateliers |
| [Part](/Part_Workbench/fr "Part Workbench/fr"), [OpenSCAD](/OpenSCAD_Workbench/fr "OpenSCAD Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| - |
| Voir aussi |
| [Part Primitives](/Part_Primitives/fr "Part Primitives/fr") |
|  |

## Description

Une ![](/images/Part_Wedge.svg) **Part Pyramide tronquée** est un solide paramétrique qui peut être créé avec la commande ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives/fr "Part Primitives/fr"). Elle possède quatre à six faces planes. Elle est définie par des plans principaux virtuels avant et arrière sur lesquels est créée une face rectangulaire (par défaut), une simple arête droite ou un simple sommet. Ces formes de base définissent les quatre faces quadrilatérales ou triangulaires qui les relient. Le solide résultant n'est une véritable pyramide tronquée que si l'une des formes de base est une face rectangulaire et l'autre une arête droite. Dans le système de coordonnées défini par sa propriété Données**Placement**, les plans principaux virtuels avant et arrière du coin sont parallèles au plan XZ, et les bords des formes de base sont parallèles à l'axe X ou Z. Toutes ses coordonnées sont relatives à ce système de coordonnées. Toutes ses coordonnées sont relatives à ce système de coordonnées.

![](/images/Part_Wedge_Example.png)

## Utilisation

Voir [Part Primitives](/Part_Primitives/fr#Utilisation "Part Primitives/fr").

## Exemple

![](/images/Part_Wedge_Scripting_Example.png)

Part Pyramide tronquée à partir de l'exemple du script

Un objet Part Pyramide tronquée créé avec l'[exemple du script](#Script) ci-dessous.

## Remarques

* Les valeurs des coordonnées de la Pyramide tronquée doivent être telles qu'un solide valide puisse être créé. Cela signifie que les formes de base avant et arrière peuvent toutes deux être des arêtes simples, mais pas si elles sont parallèles. Et si l'une des formes de base est un sommet, l'autre forme doit être une face rectangulaire.

## Propriétés

Voir aussi : [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

Un objet Part Pyramide tronquée est dérivé d'un [Part Feature](/Part_Feature/fr "Part Feature/fr") et hérite de toutes ses propriétés. Il possède également les propriétés supplémentaires suivantes :

### Données

Attachment

L'objet a les mêmes propriétés d'attachement qu'un [Part Part2DObject](/Part_Part2DObject/fr#Donn.C3.A9es "Part Part2DObject/fr").

Wedge

* Données**Xmin** (`Distance`) : coordonnée X la plus basse de la face avant de la pyramide tronquée. La valeur par défaut est `0mm`.
* Données**Ymin** (`Distance`) : coordonnée Y de la face avant de la pyramide tronquée. La valeur par défaut est `0mm`.
* Données**Zmin** (`Distance`) : coordonnée Z la plus basse de la face avant de la pyramide tronquée. La valeur par défaut est `0mm`.
* Données**X2min** (`Distance`) : coordonnée X la plus petite de la face arrière de la pyramide tronquée. La valeur par défaut est `2mm`.
* Données**Z2min** (`Distance`) : coordonnée Z la plus petite de la face arrière de la pyramide tronquée. La valeur par défaut est `2mm`.
* Données**Xmax** (`Distance`) : coordonnée X la plus élevée de la face avant de la pyramide tronquée. La valeur par défaut est `10mm`.
* Données**Ymax** (`Distance`) : coordonnée Y de la face arrière de la pyramide tronquée. La valeur par défaut est `10mm`.
* Données**Zmax** (`Distance`) : coordonnée Z la plus élevée de la face avant de la pyramide tronquée. La valeur par défaut est `10mm`.
* Données**X2max** (`Distance`) : coordonnée X la plus élevée de la face arrière de la pyramide tronquée. La valeur par défaut est `8mm`.
* Données**Z2max** (`Distance`) : coordonnée Z la plus élevée de la face arrière de la pyramide tronquée. La valeur par défaut est `8mm`.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part Écrire un script](/Part_scripting/fr "Part scripting/fr") et [Débuter avec les scripts FreeCAD](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Une Part Pyramide tronquée est créée avec la méthode `addObject()` du document :

```
wedge = FreeCAD.ActiveDocument.addObject("Part::Wedge", "myWedge")

```

* Où `"myWedge"` est le nom de l'objet.
* La fonction restitue l'objet nouvellement créé.

Exemple :

```
import FreeCAD as App

doc = App.activeDocument()

wedge = doc.addObject("Part::Wedge", "myWedge")
wedge.Xmin = 1
wedge.Ymin = 2
wedge.Zmin = 3
wedge.X2min = 4
wedge.Z2min = 6
wedge.Xmax = 15
wedge.Ymax = 20
wedge.Zmax = 55
wedge.X2max = 10
wedge.Z2max = 12
wedge.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Wedge/fr&oldid=1234238>"