---
title: Part Polygone régulier
---
|  |
| --- |
| Part Polygone régulier |
| Emplacement du menu |
| Part → [Créer des primitives](/Part_Primitives/fr "Part Primitives/fr") → Polygone régulier |
| Ateliers |
| [Part](/Part_Workbench/fr "Part Workbench/fr"), [OpenSCAD](/OpenSCAD_Workbench/fr "OpenSCAD Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| 0.14 |
| Voir aussi |
| [Part Primitives](/Part_Primitives/fr "Part Primitives/fr") |
|  |

## Description

Un ![](/images/Part_RegularPolygon.svg) **Part Polygone régulier** est une forme paramétrique qui peut être créée avec la ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives/fr "Part Primitives/fr"). Dans le système de coordonnées défini par sa propriété Données**Placement**, le polygone se trouve sur le plan XY avec son centre à l'origine et l'un de ses sommets sur l'axe X.

![](/images/Part_RegularPolygon_Example.png)

## Utilisation

Voir [Part Primitives](/Part_Primitives/fr#Utilisation "Part Primitives/fr").

## Exemple

![](/images/Part_RegularPolygon_Scripting_Example.png)

Part Polygone régulier à partir de l'exemple du script

Un objet Part Polygone régulier créé avec l'[exemple du script](#Script) ci-dessous.

## Propriétés

Voir aussi: [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

Un objet Part Polygone régulier est dérivé d'un [Part Feature](/Part_Feature/fr "Part Feature/fr") et hérite de toutes ses propriétés. Il possède également les propriétés supplémentaires suivantes :

### Données

Attachment

L'objet a les mêmes propriétés d'attachement qu'un [Part Part2DObject](/Part_Part2DObject/fr#Donn.C3.A9es "Part Part2DObject/fr").

Regular Polygon

* Données**Polygon** (`IntegerConstraint`) : nombre de côtés du polygone. La valeur par défaut est `6`.
* Données**Circumradius** (`Length`) : rayon du cercle qui circonscrit le polygone, la distance entre le centre du polygone et l'un de ses sommets. La valeur par défaut est `2mm`.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part Ecrire un script](/Part_scripting/fr "Part scripting/fr") et [Débuter avec les scripts FreeCAD](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Un Part Polygone régulier est créé avec la méthode `addObject()` du document :

```
poly = FreeCAD.ActiveDocument.addObject("Part::RegularPolygon", "myPolygon")

```

* Où `"myPolygon"` est le nom de l'objet.
* La fonction restitue l'objet nouvellement créé.

Exemple :

```
import FreeCAD as App

doc = App.activeDocument()

poly = doc.addObject("Part::RegularPolygon", "myPolygon")
poly.Polygon = 5
poly.Circumradius = 8
poly.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(60, 30, 15))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_RegularPolygon/fr&oldid=1282473>"