---
title: Part Tube
---
|  |
| --- |
| Part Tube |
| Emplacement du menu |
| Part → Primitives → Tube |
| Ateliers |
| [Part](/Part_Workbench/fr "Part Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| 0.19 |
| Voir aussi |
| [Part Primitives](/Part_Primitives/fr "Part Primitives/fr") |
|  |

## Description

La commande ![](/images/Part_Tube.svg) **Part Tube** crée un solide tubulaire paramétrique. Dans le système de coordonnées défini par sa propriété Données**Placement**, la face inférieure du tube se trouve sur le plan XY avec son centre à l'origine.

![](/images/Part_Tube_Example.png)

## Utilisation

### Créer

1. Il existe plusieurs façons de lancer la commande :
   * Appuyez sur le bouton ![](/images/Part_Tube.svg) Tube.
   * Sélectionnez l'option **Part → Primitives → ![](/images/Part_Tube.svg) Tube** du menu.
2. Le panneau de tâches **Tube** s'ouvre et un aperçu du tube s'affiche dans la [vue 3D](/3D_view/fr "3D view/fr").
3. Spécifiez les dimensions.
4. L'aperçu est mis à jour dynamiquement.
5. Appuyez sur le bouton OK.
6. Le tube est créé.
7. Vous pouvez modifier le Données**Placement** du tube dans l'[éditeur de propriétés](/Property_editor/fr "Property editor/fr") ou avec la commande ![](/images/Std_TransformManip.svg) [Std Transformer](/Std_TransformManip/fr "Std TransformManip/fr").

### Éditer

1. Double-cliquez sur le tube dans la [Vue en arborescence](/Tree_view/fr "Tree view/fr").
2. Le panneau de tâches **Tube** s'ouvre.
3. Modifiez une ou plusieurs dimensions.
4. Le tube est mis à jour de façon dynamique dans la [Vue 3D](/3D_view/fr "3D view/fr")..
5. Appuyez sur le bouton OK.

## Exemple

![](/images/Part_Tube_Scripting_Example.png)

Part Tube à partir de l'exemple du script

Un objet Part Tube créé avec l'[exemple du script](#Script) ci-dessous.

## Propriétés

Voir aussi : [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

Un objet Part Tube est dérivé d'un [Part Feature](/Part_Feature/fr "Part Feature/fr") et hérite de toutes ses propriétés. Il possède également les propriétés supplémentaires suivantes :

### Données

Attachment

L'objet a les mêmes propriétés d'attachement qu'un [Part Part2DObject](/Part_Part2DObject/fr#Donn.C3.A9es "Part Part2DObject/fr").

Tube

* Données**Height** (`Length`) : hauteur du tube. La valeur par défaut est `10mm`.
* Données**Inner Radius** (`Length`) : rayon intérieur du tube. Doit être plus petit que Données**Outer Radius**. Peut être `0`. La valeur par défaut est `2mm`.
* Données**Outer Radius** (`Length`) : rayon extérieur du tube. Doit être plus grand que Données**Inner Radius**. La valeur par défaut est `5mm`.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part Ecrire un script](/Part_scripting/fr "Part scripting/fr") et [Débuter avec les scripts FreeCAD](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Un Part Tube peut être créé avec la méthode `addTube()` ([introduit dans la version 0.20](/Release_notes_0.20/fr "Release notes 0.20/fr")) du module Shapes :

```
tube = Shapes.addTube(FreeCAD.ActiveDocument, "myTube")

```

* Où `"myTube"` est le nom de l'objet.
* La fonction restitue l'objet nouvellement créé.

Exemple :

```
import FreeCAD as App
from BasicShapes import Shapes

doc = App.activeDocument()

tube = Shapes.addTube(FreeCAD.ActiveDocument, "myTube")
tube.Height = 20
tube.InnerRadius = 2
tube.OuterRadius = 3
tube.Placement = App.Placement(App.Vector(2, 4, 5), App.Rotation(60, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Tube/fr&oldid=1471322>"