---
title: Part Sphère
---
|  |
| --- |
| Part Sphère |
| Emplacement du menu |
| Part → Primitives → Sphère |
| Ateliers |
| [Part](/Part_Workbench/fr "Part Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| - |
| Voir aussi |
| [Part Primitives](/Part_Primitives/fr "Part Primitives/fr") |
|  |

## Description

La commande ![](/images/Part_Sphere.svg) **Part Sphère** crée un solide sphérique paramétrique. C'est le résultat de la rotation d'un profil en arc de cercle autour d'un axe. Dans le système de coordonnées défini par sa propriété Données**Placement**, le centre de la sphère est positionné à l'origine, et son axe de révolution est l'axe Z.

Une Part Sphère peut être tronquée en haut et/ou en bas en modifiant ses propriétés Données**Angle1** et/ou Données**Angle2**. Il peut être transformé en un segment de sphère en modifiant sa propriété Données**Angle3**.

![](/images/Part_Sphere_Example.png)

## Utilisation

1. Il existe plusieurs façons de lancer la commande :
   * Appuyez sur le bouton ![](/images/Part_Sphere.svg) Sphère.
   * Sélectionnez l'option **Part → Primitives → ![](/images/Part_Sphere.svg) Sphère** du menu.
2. La sphère est créée.
3. Vous pouvez modifier les dimensions et le Données**Placement** de la sphère en effectuant l'une des opérations suivantes :
   * Double-cliquez sur l'objet dans la [vue en arborescence](/Tree_view/fr "Tree view/fr") :
     1. Le panneau de tâches **Primitives géométriques** s'ouvre.
     2. Modifiez une ou plusieurs propriétés.
     3. L'objet est mis à jour dynamiquement dans la [vue 3D](/3D_view/fr "3D view/fr").
     4. Appuyez sur le bouton OK.
     5. Modifiez les propriétés dans l'[éditeur de propriétés](/Property_editor/fr "Property editor/fr").
   * Changez le Données**Placement** avec la commande ![](/images/Std_TransformManip.svg) [Std Transformer](/Std_TransformManip/fr "Std TransformManip/fr").

## Exemple

![](/images/Part_Sphere_Scripting_Example.png)

Part Sphère à partir de l'exemple du script

Un objet Part Sphère créé avec l'[exemple du script](#Script) ci-dessous.

## Remarques

* Une Part Sphère peut également être créée avec la commande ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives/fr "Part Primitives/fr"). Avec cette commande, vous pouvez spécifier les dimensions et le placement au moment de la création.

## Propriétés

Voir aussi : [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

Un objet Part Sphère est dérivé d'un [Part Feature](/Part_Feature/fr "Part Feature/fr") et hérite de toutes ses propriétés. Il possède également les propriétés supplémentaires suivantes :

### Données

Attachment

L'objet a les mêmes propriétés d'attachement qu'un [Part Part2DObject](/Part_Part2DObject/fr#Donn.C3.A9es "Part Part2DObject/fr").

Sphere

* Données**Radius** (`Length`) : rayon de la sphère. La valeur par défaut est `5mm`.
* Données**Angle1** (`Angle`) : angle de départ du profil en arc de cercle de la sphère. Plage valide : `-90° <= value <= 90°`. Ne peut être égal à Données**Angle2**. La valeur par défaut est `-90°`.
* Données**Angle2** (`Angle`) : angle de fin du profil en arc de cercle de la sphère. Plage valide : `-90° <= value <= 90°`. Ne peut être égal à Données**Angle1**. La valeur par défaut est `90°`. Si l'angle total du profil en arc est inférieur à `180°`, la sphère sera tronquée et aura une face plate en haut et/ou en bas.
* Données**Angle3** (`Angle`) : angle total de révolution de la sphère. Plage valide : `0° < value <= 360°`. La valeur par défaut est `360°`. S'il est inférieur à `360°`, le solide résultant sera un segment de sphère.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part Ecrire un script](/Part_scripting/fr "Part scripting/fr") et [Débuter avec les scripts FreeCAD](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Une Part Sphère est créée avec la méthode `addObject()` du document :

```
sphere = FreeCAD.ActiveDocument.addObject("Part::Sphere", "mySphere")

```

* Où `"mySphere"` est le nom de l'objet.
* La fonction restitue l'objet nouvellement créé.

Exemple :

```
import FreeCAD as App

doc = App.activeDocument()

sphere = doc.addObject("Part::Sphere", "mySphere")
sphere.Radius = 20
sphere.Angle1 = -30
sphere.Angle2 = 45
sphere.Angle3 = 90
sphere.Placement = App.Placement(App.Vector(3, 9, 11), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Sphere/fr&oldid=1471300>"