---
title: Part Ellipse
---
|  |
| --- |
| Part Ellipse |
| Emplacement du menu |
| Part → [Créer des primitives...](/Part_Primitives/fr "Part Primitives/fr") → Ellipse |
| Ateliers |
| [Part](/Part_Workbench/fr "Part Workbench/fr"), [OpenSCAD](/OpenSCAD_Workbench/fr "OpenSCAD Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| - |
| Voir aussi |
| [Part Primitives](/Part_Primitives/fr "Part Primitives/fr") |
|  |

## Description

Une ![](/images/Part_Ellipse.svg) **Part Ellipse** est une forme paramétrique qui peut être créée avec la commande ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives/fr "Part Primitives/fr"). Dans le système de coordonnées défini par sa propriété Données**Placement**, l'ellipse se trouve sur le plan XY avec son centre à l'origine. Son grand axe est parallèle à l'axe X.

Une Part Ellipse est en fait un arc elliptique fermé dans le sens inverse des aiguilles d'une montre. Elle peut être transformée en arc en modifiant ses propriétés Données**Angle1** et/ou Données**Angle2**.

![](/images/Part_Ellipse_Example.png)

## Utilisation

Voir [Part Primitives](/Part_Primitives/fr#Utilisation "Part Primitives/fr").

## Exemple

![](/images/Part_Ellipse_Scripting_Example.png)

Part Ellipse à partir de l'exemple du script

Un objet Part Ellipse créé avec l'[exemple du script](#Script) ci-dessous.

## Propriétés

Voir aussi : [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

Un objet Part Ellipse est dérivé d'un [Part Feature](/Part_Feature/fr "Part Feature/fr") et hérite de toutes ses propriétés. Il possède également les propriétés supplémentaires suivantes :

### Données

Attachment

L'objet a les mêmes propriétés d'attachement qu'un [Part Part2DObject](/Part_Part2DObject/fr#Donn.C3.A9es "Part Part2DObject/fr").

Base

* Données**MajorRadius** (`Length`) : rayon principal de l'ellipse ou de l'arc elliptique. La valeur par défaut est `4mm`.
* Données**MinorRadius** (`Length`) : rayon mineur de l'ellipse ou de l'arc elliptique. La valeur par défaut est `2mm`.
* Données**Angle1** (`Angle`) : angle de départ de l'arc elliptique. Plage valide : `0° < value <= 360°`. La valeur par défaut est `0°`.
* Données**Angle2** (`Angle`) : angle final de l'arc elliptique. Plage valide : `0° < value <= 360°`. La valeur par défaut est `360°`. Si Données**Angle1** et Données**Angle2** sont égaux, ou si un angle est `0°` et l'autre `360°`, une ellipse complète est créée.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part Ecrire un script](/Part_scripting/fr "Part scripting/fr") et [Débuter avec les scripts FreeCAD](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Un objet Part Ellipse est créé avec la méthode `addObject()` du document :

```
ellipse = FreeCAD.ActiveDocument.addObject("Part::Ellipse", "myEllipse")

```

* Où `"myEllipse"` est le nom de l'objet.
* La fonction restitue l'objet nouvellement créé.

Exemple :

```
import FreeCAD as App

doc = App.activeDocument()

ellipse = doc.addObject("Part::Ellipse", "myEllipse")
ellipse.MajorRadius = 20
ellipse.MinorRadius = 10
ellipse.Angle1 = 45
ellipse.Angle2 = 135
ellipse.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Ellipse/fr&oldid=1563791>"