---
title: Part Tore
---
|  |
| --- |
| Part Tore |
| Emplacement du menu |
| Part → Primitives → Tore |
| Ateliers |
| [Part](/Part_Workbench/fr "Part Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| - |
| Voir aussi |
| [Part Primitives](/Part_Primitives/fr "Part Primitives/fr") |
|  |

## Description

La commande ![](/images/Part_Torus.svg) **Part Tore** crée un solide paramétrique en forme de tore, de beignet. Il est le résultat du balayage d'un profil circulaire autour d'une trajectoire circulaire. Dans le système de coordonnées défini par sa propriété Données**Placement**, la trajectoire circulaire du tore se situe dans le plan XY avec son centre à l'origine.

Un Part Tore peut être transformé en un segment de tore en modifiant sa propriété Données**Angle3**. En modifiant ses propriétés Données**Angle1** et/ou Données**Angle2**, le profil balayé peut devenir un segment de cercle.

![](/images/Part_Torus_Example.png)

## Utilisation

1. Il y a plusieurs façons de lancer la commande :
   * Appuyez sur le bouton ![](/images/Part_Torus.svg) Tore.
   * Sélectionnez l'option **Part → Primitives → ![](/images/Part_Torus.svg) Tore** du menu.
2. Le tore est créé.
3. Vous pouvez modifier les dimensions et le Données**Placement** du tore en effectuant l'une des opérations suivantes :
   * Double-cliquez sur l'objet dans la [vue en arborescence](/Tree_view/fr "Tree view/fr") :
     1. Le panneau de tâches **Primitives géométriques** s'ouvre.
     2. Modifiez une ou plusieurs propriétés.
     3. L'objet est mis à jour dynamiquement dans la [vue 3D](/3D_view/fr "3D view/fr").
     4. Appuyez sur le bouton OK.
   * Modifiez les propriétés dans l'[éditeur de propriétés](/Property_editor/fr "Property editor/fr").
   * Changez le Données**Placement** avec la commande ![](/images/Std_TransformManip.svg) [Std Transformer](/Std_TransformManip/fr "Std TransformManip/fr").

## Exemple

![](/images/Part_Torus_Scripting_Example.png)

Part Tore à partir de l'exemple du script

Un objet Part Tore créé avec l'[exemple du script](#Script) ci-dessous.

## Remarques

* Un Part Tore peut également être créé avec la commande ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives/fr "Part Primitives/fr"). Avec cette commande, vous pouvez spécifier les dimensions et le placement au moment de la création.

## Propriétés

Voir aussi : [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

Un objet Part Tore est dérivé d'un [Part Feature](/Part_Feature/fr "Part Feature/fr") et hérite de toutes ses propriétés. Il possède également les propriétés supplémentaires suivantes :

### Données

Attachment

L'objet a les mêmes propriétés d'attachement qu'un [Part Part2DObject](/Part_Part2DObject/fr#Donn.C3.A9es "Part Part2DObject/fr").

Torus

* Données**Radius1** (`Length`) : rayon de la trajectoire circulaire du tore. La valeur par défaut est `10mm`.
* Données**Radius2** (`Length`) : rayon du profil circulaire du tore. La valeur par défaut est `2mm`.
* Données**Angle1** (`Angle`) : angle de départ du profil circulaire. Plage valide : `-180° <= value <= 180°`. La valeur par défaut est `-180°`.
* Données**Angle2** (`Angle`) : angle de fin du profil circulaire. Plage valide : `-180° <= value <= 180°`. La valeur par défaut est `180°`. Si l'angle total du profil circulaire est inférieur à `360°`, le profil aura une forme de tarte.
* Données**Angle3** (`Angle`) : angle de la trajectoire circulaire du tore. Plage valide : `0° < value <= 360°`. La valeur par défaut est `360°`. Si elle est inférieure à `360°`, le solide résultant sera un segment de tore.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part Ecrire un script](/Part_scripting/fr "Part scripting/fr") et [Débuter avec les scripts FreeCAD](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Un Part Tore est créé avec la méthode `addObject()` du document :

```
torus = FreeCAD.ActiveDocument.addObject("Part::Torus", "myTorus")

```

* Où `"myTorus"` est le nom de l'objet.
* La fonction restitue l'objet nouvellement créé.

Exemple :

```
import FreeCAD as App

doc = App.activeDocument()

torus = doc.addObject("Part::Torus", "myTorus")
torus.Radius1 = 20
torus.Radius2 = 10
torus.Angle1 = -90
torus.Angle2 = 45
torus.Angle3 = 270
torus.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Torus/fr&oldid=1471302>"