---
title: Part Cube
---
|  |
| --- |
| Part Cube |
| Emplacement du menu |
| Part → Primitives → Cube |
| Ateliers |
| [Part](/Part_Workbench/fr "Part Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| - |
| Voir aussi |
| [Part Primitives](/Part_Primitives/fr "Part Primitives/fr") |
|  |

## Description

La commande ![](/images/Part_Box.svg) **Part Cube** crée un solide de type boîte paramétrique, un [parallélépipède rectangle](https://fr.wikipedia.org/wiki/Pav%C3%A9_droit). Dans le système de coordonnées défini par sa propriété Données**Placement**, la face inférieure de la boîte se trouve dans le plan XY, son coin avant gauche étant à l'origine et son bord avant étant parallèle à l'axe des X.

![](/images/Part_Box_Example.png)

## Utilisation

1. Il existe plusieurs façons de lancer la commande :
   * Appuyez sur le bouton ![](/images/Part_Box.svg) Cube.
   * Sélectionnez l'option **Part → Primitives → ![](/images/Part_Box.svg) Cube** du menu.
2. La boîte est créée.
3. Vous pouvez modifier les dimensions et Données**Placement** du cube en effectuant l'une des opérations suivantes :
   * Double-cliquez sur l'objet dans la [vue en arborescence](/Tree_view/fr "Tree view/fr") :
     1. Le panneau de tâches **Primitives géométriques** s'ouvre.
     2. Modifiez une ou plusieurs propriétés.
     3. L'objet est mis à jour dynamiquement dans la [vue 3D](/3D_view/fr "3D view/fr").
     4. Appuyez sur le bouton OK.
     5. Modifiez les propriétés dans l'[éditeur de propriétés](/Property_editor/fr "Property editor/fr").
   * Changez le Données**Placement** avec la commande ![](/images/Std_TransformManip.svg) [Std Transformer](/Std_TransformManip/fr "Std TransformManip/fr").

## Exemple

![](/images/Part_Box_Scripting_Example.png)

Part Cube à partir de l'exemple du script

Un objet Part Box créé avec l'[exemple du script](#Script) ci-dessous.

## Remarques

* Un Part Cube peut également être créé avec la commande ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives/fr "Part Primitives/fr"). Avec cette commande, vous pouvez spécifier les dimensions et le placement au moment de la création.

## Propriétés

Voir aussi: [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

Un objet Part Box est dérivé d'un [Part Feature](/Part_Feature/fr "Part Feature/fr") et hérite de toutes ses propriétés. Il possède également les propriétés supplémentaires suivantes :

### Données

Attachment

L'objet a les mêmes propriétés d'attachement qu'un [Part Part2DObject](/Part_Part2DObject/fr#Donn.C3.A9es "Part Part2DObject/fr").

Box

* Données**Length** (`Length`) : longueur du cube. Il s'agit de la dimension dans sa direction X. Valeur par défaut `10mm`.
* Données**Width** (`Length`) : largeur du cube. Il s'agit de la dimension dans sa direction Y. Valeur par défaut `10mm`.
* Données**Height** (`Length`) : hauteur du cube. Il s'agit de la dimension dans sa direction Z. Valeur par défaut `10mm`.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part Ecrire un script](/Part_scripting/fr "Part scripting/fr") et [Débuter avec les scripts FreeCAD](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Un Part Cube est créé avec la méthode `addObject()` du document :

```
box = FreeCAD.ActiveDocument.addObject("Part::Box", "myBox")

```

* Où `"myBox"` est le nom de l'objet.
* La fonction restitue l'objet juste créé.

Exemple :

```
import FreeCAD as App

doc = App.activeDocument()

box = doc.addObject("Part::Box", "myBox")
box.Length = 4
box.Width = 8
box.Height = 12
box.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Box/fr&oldid=1557301>"