---
title: Part Cercle
---
|  |
| --- |
| Part Cercle |
| Emplacement du menu |
| Part → [Créer des primitives](/Part_Primitives/fr "Part Primitives/fr") → Cercle |
| Ateliers |
| [Part](/Part_Workbench/fr "Part Workbench/fr"), [OpenSCAD](/OpenSCAD_Workbench/fr "OpenSCAD Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| - |
| Voir aussi |
| [Part Primitives](/Part_Primitives/fr "Part Primitives/fr") |
|  |

## Description

Un ![](/images/Part_Circle.svg) **Part Cercle** est une forme paramétrique qui peut être créée avec la commande ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives/fr "Part Primitives/fr"). Dans le système de coordonnées défini par sa propriété Données**Placement**, le cercle se trouve sur le plan XY avec son centre à l'origine.

Un Part Cercle est en fait un arc de cercle fermé dans le sens inverse des aiguilles d'une montre. Il peut être transformé en arc de cercle en modifiant ses propriétés Données**Angle1** et/ou Données**Angle2**.

![](/images/Part_Circle_Example.png)

## Utilisation

Voir [Part Primitives](/Part_Primitives/fr#Utilisation "Part Primitives/fr").

Un Part Cercle peut également être créé en sélectionnant trois points :

1. Dans le panneau des tâches de la commande ![](/images/Part_Primitives.svg) [Créer des primitives](/Part_Primitives/fr "Part Primitives/fr"), sélectionnez l'option **![](/images/Part_Circle.svg) Cercle** dans la liste déroulante.
2. Appuyez sur le bouton À partir de trois points.
3. Sélectionnez trois sommets dans la [vue 3D](/3D_view/fr "3D view/fr"). Il n'est pas nécessaire de maintenir la touche Ctrl enfoncée.
4. Un cercle est créé.
5. Les sommets sélectionnés ne sont utilisés qu'au moment de la création pour calculer les Données**Radius** et Données**Placement** du cercle.

## Exemple

![](/images/Part_Circle_Scripting_Example.png)

Part Cercle à partir de l'exemple du script

Un objet Part Cercle créé avec l'[exemple du script](#Script) ci-dessous.

## Propriétés

Voir aussi: [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

Un objet Part Cercle est dérivé d'un [Part Feature](/Part_Feature/fr "Part Feature/fr") et hérite de toutes ses propriétés. Il possède également les propriétés supplémentaires suivantes :

### Données

Attachment

L'objet a les mêmes propriétés d'attachement qu'un [Part Part2DObject](/Part_Part2DObject/fr#Donn.C3.A9es "Part Part2DObject/fr").

Base

* Données**Radius** (`Length`) : rayon du cercle ou de l'arc de cercle. La valeur par défaut est `2mm`.
* Données**Angle1** (`Angle`) : angle de départ de l'arc de cercle. Plage valide : `0° < value <= 360°`. La valeur par défaut est `0°`.
* Données**Angle2** (`Angle`) : angle final de l'arc de cercle. Plage valide : `0° < value <= 360°`. La valeur par défaut est `360°`. Si Données**Angle1** et Données**Angle2** sont égaux, ou si un angle est `0°` et l'autre `360°`, un cercle complet est créé.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part Ecrire un script](/Part_scripting/fr "Part scripting/fr") et [Débuter avec les scripts FreeCAD](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Un Part Cercle est créé avec la méthode `addObject()` du document :

```
circle = FreeCAD.ActiveDocument.addObject("Part::Circle", "myCircle")

```

* Où `"myCircle"` est le nom de l'objet.
* La fonction restitue l'objet nouvellement créé.

Exemple :

```
import FreeCAD as App

doc = App.activeDocument()

circle = doc.addObject("Part::Circle", "myCircle")
circle.Radius = 10
circle.Angle1 = 45
circle.Angle2 = 225
circle.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Circle/fr&oldid=1495644>"