---
title: Part Ellipsoïde
---
|  |
| --- |
| Part Ellipsoide |
| Emplacement du menu |
| Part → [Créer des primitives...](/Part_Primitives/fr "Part Primitives/fr") → Ellipsoïde |
| Ateliers |
| [Part](/Part_Workbench/fr "Part Workbench/fr"), [OpenSCAD](/OpenSCAD_Workbench/fr "OpenSCAD Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| - |
| Voir aussi |
| [Part Primitives](/Part_Primitives/fr "Part Primitives/fr") |
|  |

## Description

Un ![](/images/Part_Ellipsoid.svg) **Part Ellipsoïde** est un solide paramétrique qui peut être créé avec la commande ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives/fr "Part Primitives/fr"). Dans le système de coordonnées défini par sa propriété Données**Placement**, les axes de l'ellipsoïde sont alignés sur les axes X, Y et Z, et son centre est donc positionné à l'origine.

Un Part Ellipsoïde peut être tronqué en haut et/ou en bas en modifiant ses propriétés Données**Angle1** et/ou Données**Angle2**. Il peut être transformé en un segment d'ellipsoïde en modifiant sa propriété Données**Angle3**.

![](/images/Part_Ellipsoid_Example.png)

## Utilisation

Voir [Part Primitives](/Part_Primitives/fr#Utilisation "Part Primitives/fr").

## Exemple

![](/images/Part_Ellipsoid_Scripting_Example.png)

Part Ellipsoïde à partir de l'exemple du script

Un objet Part Ellipsoïde créé avec l'[exemple du script](#Script) ci-dessous.

## Propriétés

Voir aussi : [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

Un objet Part Ellipsoïde est dérivé d'un [Part Feature](/Part_Feature/fr "Part Feature/fr") et hérite de toutes ses propriétés. Il possède également les propriétés supplémentaires suivantes :

### Données

Attachment

L'objet a les mêmes propriétés d'attachement qu'un [Part Part2DObject](/Part_Part2DObject/fr#Donn.C3.A9es "Part Part2DObject/fr").

Ellipsoid

* Données**Radius1** (`Length`) : rayon de l'ellipsoïde dans sa direction Z. La valeur par défaut est `2mm`.
* Données**Radius2** (`Length`) : rayon de l'ellipsoïde dans sa direction X. La valeur par défaut est `4mm`.
* Données**Radius3** (`Length`) : rayon de l'ellipsoïde dans sa direction Y. La valeur par défaut est `4mm`. La valeur par défaut est `4mm`.
* Données**Angle1** (`Angle`) : angle de départ des côtés elliptiques de l'ellipsoïde. Plage valide : `-90° <= value < 90°`. Doit être inférieur à Données**Angle2**. La valeur par défaut est `-90°`.
* Données**Angle2** (`Angle`) : angle de fin des côtés elliptiques de l'ellipsoïde. Plage valide : `-90° < value <= 90°`. Doit être supérieur à Données**Angle1**. La valeur par défaut est `90°`. Si l'angle total des côtés de l'ellipse est inférieur à `180°`, l'ellipsoïde sera tronqué et aura une face plate en haut et/ou en bas.
* Données**Angle3** (`Angle`) : angle total de l'ellipsoïde dans son plan XY. Plage valide : `0° < value <= 360°`. La valeur par défaut est `360°`. Si elle est inférieure à `360°`, le solide résultant sera un segment d'ellipsoïde.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part Ecrire un script](/Part_scripting/fr "Part scripting/fr") et [Débuter avec les scripts FreeCAD](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Un Part Ellipsoïde est créé avec la méthode `addObject()` du document :

```
ellipsoid = FreeCAD.ActiveDocument.addObject("Part::Ellipsoid", "myEllipsoid")

```

* Où `"myEllipsoid"` est le nom de l'objet.
* La fonction restitue l'objet nouvellement créé.

Exemple :

```
import FreeCAD as App

doc = App.activeDocument()

ellipsoid = doc.addObject("Part::Ellipsoid", "myEllipsoid")
ellipsoid.Radius1 = 2
ellipsoid.Radius2 = 4
ellipsoid.Radius3 = 6
ellipsoid.Angle1 = -90
ellipsoid.Angle2 = 50
ellipsoid.Angle3 = 300
ellipsoid.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(15, 0, 20))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Ellipsoid/fr&oldid=1222595>"