---
title: Part Prisme
---
|  |
| --- |
| Part Prisme |
| Emplacement du menu |
| Part → [Créer des primitives...](/Part_Primitives/fr "Part Primitives/fr") → Prisme |
| Ateliers |
| [Part](/Part_Workbench/fr "Part Workbench/fr"), [OpenSCAD](/OpenSCAD_Workbench/fr "OpenSCAD Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| 0.14 |
| Voir aussi |
| [Part Primitives](/Part_Primitives/fr "Part Primitives/fr") |
|  |

## Description

Un ![](/images/Part_Prism.svg) **Part Prisme** est un solide paramétrique qui peut être créé avec la commande ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives/fr "Part Primitives/fr"). Il est le résultat de l'extrusion d'un polygone régulier le long d'une trajectoire droite. Dans le système de coordonnées défini par sa propriété Données**Placement**, la face inférieure du prisme se trouve sur le plan XY avec son centre à l'origine et l'un de ses sommets sur l'axe X.

![](/images/Part_Prism_Example.png)

## Utilisation

Voir [Part Primitives](/Part_Primitives/fr#Utilisation "Part Primitives/fr").

## Exemple

![](/images/Part_Prism_Scripting_Example.png)

Part Prisme à partir de l'exemple du script

Un objet Part Prisme créé avec l'[exemple du script](#Script) ci-dessous.

## Propriétés

Voir aussi : [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

Un objet Part Prisme est dérivé d'un [Part Feature](/Part_Feature/fr "Part Feature/fr") et hérite de toutes ses propriétés. Il possède également les propriétés supplémentaires suivantes :

### Données

Attachment

L'objet a les mêmes propriétés d'attachement qu'un [Part Part2DObject](/Part_Part2DObject/fr#Donn.C3.A9es "Part Part2DObject/fr").

Prism

* Données**Polygon** (`IntegerConstraint`) : nombre de côtés du polygone. La valeur par défaut est `6`.
* Données**Circumradius** (`Length`) : rayon du cercle qui circonscrit le polygone, la distance entre le centre du polygone et l'un de ses sommets. La valeur par défaut est `2mm`.
* Données**Height** (`Length`) : hauteur du prisme. La valeur par défaut est `10mm`.
* Données**First Angle** (`Angle`) : angle entre la direction d'extrusion du prisme et son axe Z positif, mesuré autour de son axe Y. L'angle est positif vers son axe X positif. L'angle est positif vers son axe X positif. Plage valide : `0° <= value < 90°`. La valeur par défaut est `0°`.
* Données**Second Angle** (`Angle`) : angle entre la direction d'extrusion du prisme et son axe Z positif, mesuré autour de son axe X. L'angle est positif vers son axe Y positif. L'angle est positif vers son axe Y positif. Plage valide : `0° <= value < 90°`. La valeur par défaut est `0°`.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part Ecrire un script](/Part_scripting/fr "Part scripting/fr") et [Débuter avec les scripts FreeCAD](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Un Part Prisme est créé avec la méthode `addObject()` du document :

```
prism = FreeCAD.ActiveDocument.addObject("Part::Prism", "myPrism")

```

* Où `"myPrism"` est le nom de l'objet.
* La fonction restitue l'objet nouvellement créé.

Exemple :

```
import FreeCAD as App

doc = App.activeDocument()

prism = doc.addObject("Part::Prism", "myPrism")
prism.Polygon = 5
prism.Circumradius = 10
prism.Height = 50
prism.FirstAngle = 22.5
prism.SecondAngle = 45
prism.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(60, 75, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Prism/fr&oldid=1269082>"