---
title: Part Plan
---
|  |
| --- |
| Part Plan |
| Emplacement du menu |
| Part → [Créer des primitives](/Part_Primitives/fr "Part Primitives/fr") → Plan |
| Ateliers |
| [Part](/Part_Workbench/fr "Part Workbench/fr"), [OpenSCAD](/OpenSCAD_Workbench/fr "OpenSCAD Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| - |
| Voir aussi |
| [Part Primitives](/Part_Primitives/fr "Part Primitives/fr") |
|  |

## Description

Un ![](/images/Part_Plane.svg) **Part Plan** est un plan rectangulaire paramétrique qui peut être créé avec la commande ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives/fr "Part Primitives/fr"). Dans le système de coordonnées défini par sa propriété Données**Placement**, le plan se trouve sur le plan XY avec son coin avant gauche à l'origine, et son bord avant parallèle à l'axe X.

![](/images/Part_Plane_Example.png)

## Utilisation

Voir [Part Primitives](/Part_Primitives/fr#Utilisation "Part Primitives/fr").

## Exemple

![](/images/Part_Plane_Scripting_Example.png)

Part Plan à partir de l'exemple du script

Un objet Part Plan créé avec l'[exemple du script](#Script) ci-dessous.

## Propriétés

Voir aussi : [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

Un objet Part Plan est dérivé d'un [Part Feature](/Part_Feature/fr "Part Feature/fr") et hérite de toutes ses propriétés. Il possède également les propriétés supplémentaires suivantes :

### Données

Attachment

L'objet a les mêmes propriétés d'attachement qu'un [Part Part2DObject](/Part_Part2DObject/fr#Donn.C3.A9es "Part Part2DObject/fr").

Plane

* Données**Length** (`Length`) : longueur du plan. Il s'agit de la dimension dans sa direction X. La valeur par défaut est `10mm`.
* Données**Width** (`Length`) : largeur du plan. Il s'agit de la dimension dans sa direction Y. La valeur par défaut est `10mm`.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part Ecrire un script](/Part_scripting/fr "Part scripting/fr") et [Débuter avec les scripts FreeCAD](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Un Part Plan est créé avec la méthode `addObject()` du document :

```
plane = FreeCAD.ActiveDocument.addObject("Part::Plane", "myPlane")

```

* Où `"myPlane"` est le nom de l'objet.
* La fonction restitue l'objet nouvellement créé.

Exemple :

```
import FreeCAD as App

doc = App.activeDocument()

plane = doc.addObject("Part::Plane", "myPlane")
plane.Length = 4
plane.Width = 8
plane.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(20, 75, 60))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Plane/fr&oldid=1222597>"