---
title: TechDraw Quota da punti di riferimento
---
|  |
| --- |
| TechDraw Quota da punti di riferimento |
| Posizione nel menu |
| TechDraw → Quotatura → Quota da punti di riferimento - SPERIMENTALE |
| Ambiente |
| [TechDraw](/TechDraw_Workbench/it "TechDraw Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| 0.19 |
| Vedere anche |
| [TechDraw Quota Orizzontale](/TechDraw_HorizontalDimension/it "TechDraw HorizontalDimension/it"), [TechDraw Quota Verticale](/TechDraw_VerticalDimension/it "TechDraw VerticalDimension/it") |
|  |

## Descrizione

Lo strumento **TechDraw Quota da punti di riferimento** aggiunge una quota lineare a una Vista. La quota si basa su due oggetti punto (oggetti [Draft Punto](/Draft_Point/it "Draft Point/it"), [Part Punto](/Part_Point/it "Part Point/it") o [PartDesign Punto](/PartDesign_Point "PartDesign Point")) dal modello 3D.

Lo scopo di questo strumento è fornire una soluzione alternativa alla corruzione delle quote causata dai problemi di "[denominazione topologica](/Topological_naming_problem/it "Topological naming problem/it")". I punti sorgente dovrebbero usare [Espressioni](/Expressions/it "Expressions/it") o altri meccanismi di contenimento per stabilire la loro posizione. Poiché i punti sono [Oggetti documento](/App_DocumentObject/it "App DocumentObject/it") e non modellano i componenti, il loro nome non cambia con i ricalcoli e quindi sono facilmente reperibili.

Vedere [TechDraw Quota allineata](/TechDraw_LengthDimension/it#Limitazioni "TechDraw LengthDimension/it") per ulteriori informazioni sulla quotatura e sulla denominazione topologica.

## Utilizzo

1. Selezionare due oggetti punto nella [Vista 3D](/3D_view/it "3D view/it") o nella [Vista ad albero](/Tree_view/it "Tree view/it").
2. Aggiungere la Vista TechDraw corretta alla selezione selezionandola nella [Vista ad albero](/Tree_view/it "Tree view/it").
3. Esistono diversi modi per richiamare lo strumento:
   * Premere il pulsante ![](/images/TechDraw_LandmarkDimension.svg) Inserisci Quota da punti di riferimento - SPERIMENTALE.
   * Selezionare l'opzione **TechDraw → Quotatura → ![](/images/TechDraw_LandmarkDimension.svg) Inserisci Quota da punti di riferimento - SPERIMENTALE** dal menu.
4. Una quota viene aggiunta alla Vista.
5. La quota può essere trascinata nella posizione desiderata.
6. Se necessario, aggiungere tolleranze come descritto in [questa pagina](/TechDraw_Geometric_dimensioning_and_tolerancing/it#Tolleranze "TechDraw Geometric dimensioning and tolerancing/it").

### Cambiare le proprietà

Per modificare le proprietà di un oggetto quota, fare doppio clic su di esso nel disegno o nella [Vista ad albero](/Tree_view/it "Tree view/it"). Si aprirà la [Finestra di dialogo Quota](/TechDraw_LengthDimension/it#Finestra_di_dialogo_Quota "TechDraw LengthDimension/it").

## Limitazioni

Lo strumento Quota da punti di riferimento è inizialmente limitato alle quotature di "Distanza". Altri tipi possono essere aggiunti se richiesto.

## Note

Vedere [TechDraw Quota allineata](/TechDraw_LengthDimension/it#Note "TechDraw LengthDimension/it").

## Proprietà

Vedere [TechDraw Quota allineata](/TechDraw_LengthDimension/it#Proprietà "TechDraw LengthDimension/it").

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Lo strumento Quota da punti di riferimento può essere utilizzato nelle [macro](/Macros/it "Macros/it") e dalla console [Python](/Python/it "Python/it") tramite la seguente funzione:

```
dim1 = FreeCAD.ActiveDocument.addObject("TechDraw::LandmarkDimension", "Landmark")
dim1.Type = "Distance"
dim1.References2D = [(TDView, "Vertex1")]
dim1.References3D = [(Point3d1, "Vertex1")]
dim1.References3D = [(Point3d2, "Vertex1")]
page.addView(dim1)

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_LandmarkDimension/it&oldid=1446020>"