---
title: TechDraw Punti mediani
---
|  |
| --- |
| TechDraw Punti mediani |
| Posizione nel menu |
| TechDraw → Aggiungi vertici → Aggiungi Vertici nel Punto mediano |
| Ambiente |
| [TechDraw](/TechDraw_Workbench/it "TechDraw Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| 0.19 |
| Vedere anche |
| [TechDraw Vertice cosmetico](/TechDraw_CosmeticVertex/it "TechDraw CosmeticVertex/it"), [TechDraw Quadranti](/TechDraw_Quadrants/it "TechDraw Quadrants/it") |
|  |

## Descrizione

Lo strumento **TechDraw Punti mediani** aggiunge [vertici cosmetici](/TechDraw_CosmeticVertex/it "TechDraw CosmeticVertex/it") nel punto medio di uno o più bordi selezionati.

![](/images/TechDraw_CosmeticMidpoint_Sample.png)

Vertici cosmetici nel punto mediano dei bordi

## Utilizzo

1. Selezionare uno o più bordi in una vista.
2. Esistono diversi modi per richiamare lo strumento:
   * Premere il pulsante ![](/images/TechDraw_Midpoints.svg) Aggiungi Vertici del Punto mediano.
   * Selezionare l'opzione **TechDraw → Aggiungi vertici → ![](/images/TechDraw_Midpoints.svg) Aggiungi Vertici del Punto mediano** dal menu.

## Note

* I vertici cosmetici creati non sono collegati parametricamente ai bordi selezionati.
* Per eliminare un vertice cosmetico selezionarlo e premere Delete. [disponibile dalla versione 1.0](/Release_notes_1.0/it "Release notes 1.0/it")

## Proprietà

I vertici cosmetici non hanno proprietà proprie, in quanto non sono dei Document Objects. Condividono le impostazioni di colore e dimensione con i normali vertici della geometria.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

In questo momento i vertici cosmetici non sono accessibili dalle [macro](/Macros/it "Macros/it") o dalla console [Python](/Python/it "Python/it"). Questo snippet rimuoverà tutti i vertici cosmetici dalla vista.

```
v = App.ActiveDocument.View
v.clearCV()
App.ActiveDocument.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_Midpoints/it&oldid=1452821>"