---
title: TechDrawː Vista interrotta
---
|  |
| --- |
| TechDraw Vista interrotta |
| Posizione nel menu |
| TechDraw → Viste TechDraw → Inserisci Vista interrotta |
| Ambiente |
| [TechDraw](/TechDraw_Workbench/it "TechDraw Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| 1.0 |
| Vedere anche |
| [TechDraw Vista](/TechDraw_View/it "TechDraw View/it") |
|  |

## Descrizione

Lo strumento **TechDraw Vista interrotta** inserisce una "vista interrotta" basata su una [vista](/TechDraw_View/it "TechDraw View/it") esistente o su uno o più oggetti, come [Corpi](/PartDesign_Body/it "PartDesign Body/it") o [Parti](/Std_Part/it "Std Part/it"). La Vista interrotta richiede inoltre uno o più [schizzi](/Sketcher_NewSketch/it "Sketcher NewSketch/it") che definiscano la posizione e la dimensione delle aree da rimuovere. Vista interrotta si comporta in modo simile alle altre visualizzazioni. La direzione di proiezione viene presa dalla vista della parte esistente, dalla direzione della telecamera 3D o dalla normale di una faccia selezionata.

![](/images/TechDraw_BrokenView_example3d.png)

Una forma da interrompere e gli schizzi che definiscono l'interruzione

![](/images/TechDraw_BrokenView_example2d.png)

Il risultato

## Utilizzo

1. Facoltativamente ruotare la [Vista 3D](/3D_view/it "3D view/it"). La vista 3D determina i valori iniziali delle proprietà Dati**Direction** e Dati**XDirection** della vista interrotta.
2. Selezionare l'oggetto di cui si desidera creare una vista interrotta o selezionare una vista TechDraw esistente che contiene questo oggetto.
3. Aggiungere uno o più schizzi di interruzione alla selezione selezionandoli nella [Vista ad albero](/Tree_view/it "Tree view/it"). Ogni schizzo dovrebbe contenere solo due linee parallele. E' possibile anche usare altri oggetti con due bordi paralleli.
4. Esistono diversi modi per richiamare lo strumento:
   * Premere il pulsante ![](/images/TechDraw_BrokenView.svg) Inserisci Vista interrotta.
   * Selezionare l'opzione **TechDraw → Viste TechDraw → ![](/images/TechDraw_BrokenView.svg) Inserisci Vista interrotta** dal menu.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Una Vista Interrotta, formalmente un oggetto `TechDraw::DrawBrokenView`, deriva da un oggetto [Part View](/TechDraw_View/it#Properties_Part_View "TechDraw View/it"), formalmente un oggetto `TechDraw::DrawViewPart` ed eredita tutti le sue proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Broken View

* Dati**Breaks** (`LinkList`): oggetti nella vista 3D che definiscono i punti di inizio/fine e la direzione delle interruzioni in questa vista.
* Dati**Gap** (`Length`): la distanza di separazione per le interruzioni in questa vista (lunghezza 3D non scalata).

## Note

* Le interruzioni devono essere verticali od orizzontali. Le interruzioni oblique non sono supportate.
* Vedere anche [TechDraw Vista](/TechDraw_View/it "TechDraw View/it").

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Vista interrotta può essere creato con [macro](/Macros/it "Macros/it") e dalla console [Python](/Python/it "Python/it") utilizzando le seguenti funzioni:

```
doc = FreeCAD.ActiveDocument
box = doc.Box
profile = doc.Sketch
page = doc.Page

brokenView = doc.addObject("TechDraw::DrawBrokenView", "BrokenView")
page.addView(brokenView)
brokenView.Source= box
brokenView.Breaks = [doc.Sketch]

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_BrokenView/it&oldid=1495306>"