---
title: TechDraw Quota estensione orizzontale
---
|  |
| --- |
| TechDraw Quota estensione orizzontale |
| Posizione nel menu |
| TechDraw → Quotatura → Inserisci Quota estensione orizzontale |
| Ambiente |
| [TechDraw](/TechDraw_Workbench/it "TechDraw Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| 0.19 |
| Vedere anche |
| [TechDraw Quota allineata](/TechDraw_LengthDimension/it "TechDraw LengthDimension/it"), [Quota estensione verticale](/TechDraw_VerticalExtentDimension/it "TechDraw VerticalExtentDimension/it") |
|  |

## Descrizione

Lo strumento **TechDraw Quota estensione orizzontale** aggiunge una quota lineare a una Vista. La quota si estende dal punto più a sinistra degli oggetti selezionati al punto più a destra.

![](/images/TechDraw_Dimension_Horizontal_Extent_example.png)

Quotatura dell'estensione orizzontale e verticale di una B-spline

## Utilizzo

1. Selezionare una Vista o una raccolta di Bordi in una Vista.
2. Esistono diversi modi per richiamare lo strumento:
   * [disponibile dalla versione 1.0](/Release_notes_1.0/it "Release notes 1.0/it"): Se la [preferenza](/TechDraw_Preferences/it#Dimensions "TechDraw Preferences/it") degli **Strumenti di quotatura** è impostata su `Strumento singolo` (predefinito): premere la freccia giù a destra del pulsante ![](/images/TechDraw_Dimension.svg)![](/images/Toolbar_flyout_arrow.svg) e seleziona il pulsante {{MenuCommand|[[Image:TechDraw\_HorizontalExtentDimension.svg|16px] ] Opzione Inserisci Quota estensione orizzontale}} dal menu a discesa.
   * Se questa preferenza ha un valore diverso (e in versione 0.21 e precedenti): premere il pulsante ![](/images/TechDraw_HorizontalExtentDimension.svg) Inserisci Quota estensione orizzontale.
   * Selezionare l'opzione **TechDraw → Quotatura → ![](/images/TechDraw_HorizontalExtentDimension.svg) Inserisci Quota estensione orizzontale** dal menu.
3. Una quota viene aggiunta alla Vista.
4. La quota può essere trascinata nella posizione desiderata.
5. Se necessario, aggiungere tolleranze come descritto in [questa pagina](/TechDraw_Geometric_dimensioning_and_tolerancing/it#Tolleranze "TechDraw Geometric dimensioning and tolerancing/it").

### Cambiare le proprietà

Per modificare le proprietà di un oggetto quota, fare doppio clic su di esso nel disegno o nella [Vista ad albero](/Tree_view/it "Tree view/it"). Si aprirà la [Finestra di dialogo Quota](/TechDraw_LengthDimension/it#Finestra_di_dialogo_Quota "TechDraw LengthDimension/it").

## Limitazioni

Gli oggetti Quota sono vulnerabili al "[problema di denominazione topologica](/Topological_naming_problem/it "Topological naming problem/it")". Vedere [TechDraw Quota allineata](/TechDraw_LengthDimension/it "TechDraw LengthDimension/it").

## Note

Vedere [TechDraw Quota allineata](/TechDraw_LengthDimension/it#Note "TechDraw LengthDimension/it").

## Proprietà

Vedere [TechDraw Quota allineata](/TechDraw_LengthDimension/it#Proprietà "TechDraw LengthDimension/it"). Eccezioni indicate di seguito.

### Dati

Base

* Dati**Measure Type** (`Enumeration`): non ancora implementato per le quote di estensione.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Lo strumento Quota estensione orizzontale può essere utilizzato nelle [macro](/Macros/it "Macros/it") e dalla console [Python](/Python/it "Python/it") tramite le seguenti funzioni:

```
selection = ['Edge1', 'Edge2']                      # or [] for all

TechDraw.makeExtentDim(view1, selection, 0)         # view1 is a DrawViewPart; 0 for horizontal
App.ActiveDocument.DimExtent.Y = -60                # offset dimension line from dimensioned edges in Y direction
App.ActiveDocument.DimExtent.X = 10                 # offset dimension text along dimension line in X direction
App.ActiveDocument.DimExtent.FormatSpec = '%.0f'    # Dimension format

TechDraw.makeExtentDim(view1, selection, 1)         # view1 is a DrawViewPart; 1 for vertical
App.ActiveDocument.DimExtent001.X = -130            # offset dimension line from dimensioned edges in X direction
App.ActiveDocument.DimExtent001.Y = 10              # offset dimension text along dimension line in Y direction
App.ActiveDocument.DimExtent001.FormatSpec = '%.0f'

# Note the dimension names are 'DimExtent', 'DimExtent001' etc in the order created.

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_HorizontalExtentDimension/it&oldid=1498325>"