---
title: TechDraw Tratteggio geometrico
---
|  |
| --- |
| TechDraw Tratteggio geometrico |
| Posizione nel menu |
| TechDraw → Tratteggio → Tratteggio geometrico |
| Ambiente |
| [TechDraw](/TechDraw_Workbench/it "TechDraw Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Tratteggio](/TechDraw_Hatch/it "TechDraw Hatch/it"), [Tipi di tratteggio](/TechDraw_Hatching/it "TechDraw Hatching/it") |
|  |

## Descrizione

Lo strumento **TechDraw Tratteggio geometrico** riempie una regione chiusa in una Vista con un modello basato su una specifica PAT di tratteggio AutoDesk. In alternativa, lo strumento ![](/images/TechDraw_Hatch.svg) [TechDraw Tratteggio](/TechDraw_Hatch/it "TechDraw Hatch/it") utilizza modelli di tratteggio basati su SVG. Vedere [Tipi di tratteggio](/TechDraw_Hatching/it "TechDraw Hatching/it") per i dettagli.

![](/images/TechDraw_GeomHatch_example.png)

Esempio di tratteggio geometrico su una faccia

## Utilizzo

1. Selezionare una regione chiusa in una Vista.
2. Esistono diversi modi per richiamare lo strumento:
   * Premere il pulsante ![](/images/TechDraw_GeometricHatch.svg) TechDraw Tratteggio geometrico.
   * Selezionare l'opzione **TechDraw → Tratteggio → ![](/images/TechDraw_GeometricHatch.svg) Applica Tratteggio geometrico alla Faccia** dal menu.
3. Si apre il pannello delle attività **Applica Tratteggio geometrico alla Faccia**.
4. Facoltativamente, modificare il **File del modello**, il **Nome modello**, la **Scala modello**, il **Spessore linea** e il **Colore linea** .
5. Premere il pulsante OK.

## Note

* Per un riempimento in colore solido utilizzare invece [TechDraw Tratteggio](/TechDraw_Hatch/it "TechDraw Hatch/it") e selezionare solid.svg come **File del modello**.
* Gli oggetti tratteggiati sono vulnerabili al "[problema di denominazione topologica](/Topological_naming_problem/it "Topological naming problem/it")". Per ulteriori informazioni, vedere [TechDraw Lunghezza](/TechDraw_LengthDimension/it "TechDraw LengthDimension/it"). Si consiglia che il tratteggio sia uno degli ultimi passaggi del processo di disegno.
* Una piccola serie di modelli campione è disponibile in:

:   ```
    $INSTALL_DIR/data/Mod/TechDraw/PAT/FCPAT.pat

    ```

ː Dove `$INSTALL_DIR` è la directory in cui è stato installato FreeCAD, per esempioː

:   ```
    /usr/share/freecad/data/Mod/TechDraw/PAT/FCPAT.pat

    ```

## Proprietà

* Dati**Source**: La Vista e la Faccia che devono ricevere il modello di tratteggio.
* Dati**File Pattern**: La posizione del file PAT da utilizzare.
* Dati**Name Pattern**: Il nome dello specifico PAT all'interno di File Pattern.
* Dati**Scale Pattern**: La scala da applicare al modello (deve essere > 0.0).
* Vista**Weight Pattern**: Lo spessore delle linee del modello.
* Vista**Color Pattern**: Il colore delle linee del modello.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

È possibile creare un Tratteggio geometrico con [macro](/Macros/it "Macros/it") e dalla console [Python](/Python/it "Python/it") utilizzando le seguenti funzioni:

```
hatch = FreeCAD.ActiveDocument.addObject("TechDraw::DrawGeomHatch", "GeomHatch")
hatch.Source = (view1, ["Face0"])
hatch.FilePattern = "path/to/myPATfile.pat"
hatch.NamePattern = "Diamond"
page.addView(hatch)

```

È anche possibile utilizzare il motore di tratteggio geometrico di TechDraw per produrre un oggetto composto nello spazio 3D. Bisogna fare attenzione che la faccia di base si trovi sul piano XY, poiché l'algoritmo non è ancora adattato per altri casi:

```
import TechDraw
face = Part.makePlane(10, 10)
patfile = "path/to/myPATfile.pat"
pattern = "Diamond"
scale = 10
hatch = TechDraw.makeGeomHatch(face, scale, pattern, patfile)
Part.show(hatch)

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_GeometricHatch/it&oldid=1490070>"