---
title: TechDraw Blocco di testo
---
|  |
| --- |
| TechDraw Blocco di testo |
| Posizione nel menu |
| TechDraw → Annotazioni → Inserisci Blocco di testo |
| Ambiente |
| [TechDraw](/TechDraw_Workbench/it "TechDraw Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| 0.19 |
| Vedere anche |
| [TechDraw Annotazione](/TechDraw_Annotation/it "TechDraw Annotation/it") |
|  |

## Descrizione

Lo strumento **TechDraw Blocco di testo** aggiunge un blocco di annotazione formattato a una [Linea guida](/TechDraw_LeaderLine/it "TechDraw LeaderLine/it") o ad una Vista.

![](/images/TechDraw_RichTextBlock_sample.png)

Blocco di testo indipendente

## Utilizzo

1. Se nel documento sono presenti più Pagine di disegno: facoltativamente attivare la Pagina desiderata selezionandola nella [Vista ad albero](/Tree_view/it "Tree view/it").
2. Per associare un Blocco di testo a una [Linea guida](/TechDraw_LeaderLine/it "TechDraw LeaderLine/it"), selezionare la linea nella [Vista ad albero](/Tree_view/it "Tree view/it") o sulla Pagina.
3. Esistono diversi modi per richiamare lo strumento:
   * Premere il pulsante ![](/images/TechDraw_RichTextAnnotation.svg) Inserisci Blocco di testo.
   * Selezionare l'opzione **TechDraw → Annotazioni → ![](/images/TechDraw_RichTextAnnotation.svg) Inserisci Blocco di testo** dal menu.
4. Se nel documento sono presenti più Pagine di disegno e non si ha ancora attivato una Pagina, si apre la finestra di dialogo **Scelta pagina**:
   1. Selezionare la pagina desiderata.
   2. Premere il pulsante OK.
5. Si apre un pannello delle azioni.
6. Il pannello delle azioni consente l'immissione rapida di testo.
7. Il pulsante Avvia l'editor di testo avanzato apre un editor completo di funzionalità:
   1. Al termine, premere il pulsante ![](/images/Document-save.svg) per salvare le modifiche e chiudere l'Editor.
8. Premere il pulsante OK per chiudere il pannello delle Azioni.

## Note

* Dopo la creazione, è possibile modificare un Blocco di testo facendo doppio clic sulla pagina.

## Proprietà

* Dati**X,Y**: la posizione del blocco. Relativa alla fine della linea se collegato a una [Linea guida](/TechDraw_LeaderLine/it "TechDraw LeaderLine/it"), altrimenti questa è la posizione sulla pagina.
* Dati**ShowFrame**: disegna un contorno attorno al blocco.
* Dati**MaxWidth**: limita la dimensione orizzontale del blocco. Il valore di -1 è per larghezza illimitata.
* Dati**AnnoText**: il testo HTML del blocco.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Lo strumento Blocco di testo può essere utilizzato nelle [macro](/Macros/it "Macros/it") e dalla console [Python](/Python/it "Python/it").

```
myPage = FreeCAD.ActiveDocument().Page
myBase = FreeCAD.ActiveDocument().View
blockObj = FreeCAD.ActiveDocument.addObject('TechDraw::DrawRichAnno','DrawRichAnno')
FreeCAD.activeDocument().myPage.addView(blockObj)
blockObj.X = 5
blockObj.Y = 5
blockObj.AnnoText = myHTMLText

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_RichTextAnnotation/it&oldid=1487359>"