---
title: TechDraw Quota raggio
---
|  |
| --- |
| TechDraw Quota raggio |
| Posizione nel menu |
| TechDraw → Quotatura → Inserisci Quota raggio |
| Ambiente |
| [TechDraw](/TechDraw_Workbench/it "TechDraw Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Quota diametro](/TechDraw_DiameterDimension/it "TechDraw DiameterDimension/it") |
|  |

## Descrizione

Lo strumento **TechDraw Quota raggio** aggiunge una quota del raggio ad una Vista. La quota può essere applicata a qualsiasi bordo che sia un cerchio o un arco circolare.

![](/images/TechDraw_Dimension_Radius_example.png)

Quotatura di un cerchio, indicando il raggio

## Uso

1. Selezionare un cerchio o un arco circolare. La geometria può essere selezionata nella [Vista 3D](/3D_view/it "3D view/it") o nel disegno. Notare che alcuni archi che sembrano circolari sono in realtà ellissi o B-spline. In questi casi non è possibile creare una Quota raggio.
2. Se si ha selezionato la geometria nella vista 3D: aggiungere la Vista TechDraw corretta alla selezione selezionandola nella [Vista ad albero](/Tree_view/it "Tree view/it").
3. Esistono diversi modi per richiamare lo strumento:
   * [disponibile dalla versione 1.0](/Release_notes_1.0/it "Release notes 1.0/it"): Se la [preferenza](/TechDraw_Preferences/it#Dimensions "TechDraw Preferences/it") degli **Strumenti di quotatura** è impostata su `Strumento singolo` (predefinito): premere la freccia giù a destra del pulsante ![](/images/TechDraw_Dimension.svg)![](/images/Toolbar_flyout_arrow.svg) e selezionare il pulsante **![](/images/TechDraw_RadiusDimension.svg) Inserisci Quota Raggio** dal menu a discesa.
   * Se questa preferenza ha un valore diverso (e in versione 0.21 e precedenti): premere il pulsante ![](/images/TechDraw_RadiusDimension.svg) Inserisci Quota Raggio .
   * Selezionare l'opzione **TechDraw → Quotatura → ![](/images/TechDraw_RadiusDimension.svg) Inserisci Quota raggio** dal menu.
4. Una quota viene aggiunta alla Vista.
5. La quota può essere trascinata nella posizione desiderata.
6. Se necessario, aggiungere tolleranze come descritto in [questa pagina](/TechDraw_Geometric_dimensioning_and_tolerancing/it#Tolleranze "TechDraw Geometric dimensioning and tolerancing/it").

### Visualizzazione quotatura 3D

Vedere [TechDraw LengthDimension](/TechDraw_LengthDimension/it#Display_3D_measurement "TechDraw LengthDimension/it").

### Cambiare le proprietà

Per modificare le proprietà di un oggetto quota, fare doppio clic su di esso nel disegno o nella [Vista ad albero](/Tree_view/it "Tree view/it"). Si aprirà la [Finestra di dialogo Quota](/TechDraw_LengthDimension/it#Finestra_di_dialogo_Quota "TechDraw LengthDimension/it").

## Limitazioni

Gli oggetti Quota sono vulnerabili al "[problema di denominazione topologica](/Topological_naming_problem/it "Topological naming problem/it")". Vedere [TechDraw Quota allineata](/TechDraw_LengthDimension/it "TechDraw LengthDimension/it").

## Note

Vedere [TechDraw Quota allineata](/TechDraw_LengthDimension/it#Note "TechDraw LengthDimension/it").

## Proprietà

Vedere [TechDraw Quota allineata](/TechDraw_LengthDimension/it#Proprietà "TechDraw LengthDimension/it").

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Lo strumento Quota raggio può essere utilizzato nelle [macro](/Macros/it "Macros/it") e dalla console [Python](/Python/it "Python/it") tramite la seguente funzione:

```
dim1 = FreeCAD.ActiveDocument.addObject("TechDraw::DrawViewDimension", "Dimension")
dim1.Type = "Radius"
dim1.References2D=[(view1, "Edge1")]
page.addView(dim1)

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_RadiusDimension/it&oldid=1498334>"