---
title: TechDraw Quadranti
---
|  |
| --- |
| TechDraw Quadranti |
| Posizione nel menu |
| TechDraw → Aggiungi Vertici → Aggiungi Vertici sul quadrante |
| Ambiente |
| [TechDraw](/TechDraw_Workbench/it "TechDraw Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| 0.19 |
| Vedere anche |
| [TechDraw Vertice cosmetico](/TechDraw_CosmeticVertex/it "TechDraw CosmeticVertex/it"), [TechDraw Punto mediano](/TechDraw_Midpoints/it "TechDraw Midpoints/it") |
|  |

## Descrizione

Lo strumento **TechDraw Quadranti** aggiunge tre [vertici cosmetici](/TechDraw_CosmeticVertex/it "TechDraw CosmeticVertex/it") lungo la lunghezza di uno o più bordi selezionati. I vertici sono posizionati al 25%, 50% e 75% della lunghezza dei bordi. Per un bordo circolare ciò si traduce in vertici cosmetici a 90°, 180° e 270°, oltre al vertice geometrico a 0°.

![](/images/TechDraw_CosmeticQuadrant_Sample.png)

Vertici cosmetici nei punti del quadrante di un cerchio

## Utilizzo

1. Selezionare uno o più bordi in una vista. È possibile selezionare qualsiasi bordo, non solo i cerchi.
2. Esistono diversi modi per richiamare lo strumento:
   * Premere il pulsante ![](/images/TechDraw_Quadrants.svg) Aggiungi Vertici sul quadrante.
   * Selezionare l'opzione **TechDraw → Aggiungi Vertici → ![](/images/TechDraw_Quadrants.svg) Aggiungi vertici sul quadrante** dal menu.

## Note

* I vertici cosmetici creati non sono collegati parametricamente ai bordi selezionati.
* Per eliminare un vertice cosmetico selezionarlo e premere Delete. [disponibile dalla versione 1.0](/Release_notes_1.0/it "Release notes 1.0/it")

## Proprietà

I vertici cosmetici non hanno proprietà proprie, in quanto non sono dei Document Objects. Condividono le impostazioni di colore e dimensione con i normali vertici della geometria.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

In questo momento i vertici cosmetici non sono accessibili dalle [macro](/Macros/it "Macros/it") o dalla console [Python](/Python/it "Python/it"). Questo snippet rimuoverà tutti i vertici cosmetici dalla vista.

```
v = App.ActiveDocument.View
v.clearCV()
App.ActiveDocument.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_Quadrants/it&oldid=1452719>"