---
title: TechDraw Gruppo di proiezioni
---
|  |
| --- |
| TechDraw Gruppo di proiezioni |
| Posizione nel menu |
| TechDraw → Viste TechDraw → Gruppo di proiezioni |
| Ambiente |
| [TechDraw](/TechDraw_Workbench/it "TechDraw Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [TechDraw Vista](/TechDraw_View/it "TechDraw View/it") |
|  |

## Descrizione

Lo strumento **TechDraw Gruppo di proiezioni** crea una [proiezione multivista](https://en.wikipedia.org/wiki/Multiview_projection) di uno o più oggetti 3D, utilizzando la tradizionale [first-](https://en.wikipedia.org/wiki/Multiview_orthographic_projection#First-angle_projection) o la [proiezione del terzo angolo](https://en.wikipedia.org/wiki/Multiview_orthographic_projection#Third-angle_projection). Possono essere incluse anche le viste isometriche dei 4 angoli anteriori.

[disponibile dalla versione 1.0](/Release_notes_1.0/it "Release notes 1.0/it"): anche lo strumento [TechDraw Vista](/TechDraw_View/it "TechDraw View/it") può creare un Gruppo di Proiezione. Si consiglia di utilizzare quello strumento.

![](/images/TechDraw_ProjGroup_example.png)

Tre viste ortogonali e una vista isometrica di un oggetto solido

## Utilizzo

Vedere [TechDraw View](/TechDraw_View/it#Usage_Projection_Group_Item_and_Projection_Group "TechDraw View/it"), ma per richiamare lo strumento selezionare l'opzione **TechDraw → TechDraw Views → ![](/images/TechDraw_ProjectionGroup.svg) Inserisci gruppo di proiezione** dal menu.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un Gruppo di Proiezione, formalmente un oggetto `TechDraw::DrawProjGroup`, ha le [proprietà](/TechDraw_View/it#Properties_Part_View "TechDraw View/it") comuni a tutti i tipi di Vista. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Base

* Dati**Source** (`LinkList`): collegamenti agli oggetti disegnabili da rappresentare.
* Dati**XSource** (`XLinkList`): collegamenti agli oggetti disegnabili in un file esterno.
* Dati**Anchor** (`Link`): la vista centrale nel gruppo. Normalmente la vista frontale.
* Dati**ProjectionType** (`Enumeration`): `First Angle` o `Third Angle`.

Collection

* Dati**Views** (`LinkList`): collegamenti alle viste in questo Gruppo di proiezioni.

Distribute

* Dati**Auto Distribute** (`Bool`): se `true`, distanzia automaticamente le singole viste. Utilizzare `false` per posizionarle manualmente.
* Dati**spacing X** (`Length`): spazio orizzontale tra le viste quando posizionate automaticamente. Tenere presente che anche la scala e la dimensione delle altre viste nel gruppo influenzano la spaziatura.
* Dati**spacing Y** (`Length`): spazio verticale tra le viste quando posizionate automaticamente.

## Note

Le Proiezioni ereditano nel loro complesso X, Y, ScaleType, Scale e Rotation dalla vista di base.

Le singole viste all'interno del gruppo ereditano tutte le proprietà della vista della parte, ma l'oggetto ProjectionGroup controlla la scala di tutti i suoi membri viste.

La proprietà RotationVector delle singole viste all'interno del gruppo è obsoleta a partire dalla versione 0.19. Utilizzare invece XDirection.

Notare che la casella centrale visualizza la direzione di proiezione corrente della vista principale. Non può essere utilizzata per cambiare la direzione.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Un Gruppo di proiezioni può essere creato con [macro](/Macros/it "Macros/it") e dalla console [Python](/Python/it "Python/it") utilizzando le seguenti funzioni:

```
import FreeCAD as App

doc = App.ActiveDocument
cyl = doc.addObject("Part::Cylinder", "Cylinder")
doc.recompute()

page = doc.addObject("TechDraw::DrawPage", "Page")
template = doc.addObject("TechDraw::DrawSVGTemplate", "Template")
template.Template = App.getResourceDir() + "Mod/TechDraw/Templates/A4_LandscapeTD.svg"
page.Template = template

# Toggle the visibility of the page to ensure its width and height are updated (hack):
page.Visibility = False
page.Visibility = True

group = doc.addObject("TechDraw::DrawProjGroup", "ProjGroup")
page.addView(group)
group.Source = [cyl]
group.ProjectionType = "Third Angle"

front_view = group.addProjection("Front") # First projection will become the Anchor.
group.Anchor.Direction = (0, 1, 0)
group.Anchor.RotationVector = (1, 0, 0)

left_view = group.addProjection("Left")
top_view = group.addProjection("Top")

group.X = page.PageWidth / 2
group.Y = page.PageHeight / 2

doc.recompute()

```

Nota: il gruppo di proiezioni deve essere sempre aggiunto alla Pagina, `page.addView(group)`, prima di aggiungere proiezioni al Gruppo. Ciò consente al Gruppo di proiezione di utilizzare i valori dei parametri predefiniti derivati ​​dalla pagina principale.

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_ProjectionGroup/it&oldid=1495342>"