---
title: TechDraw Tratteggio
---
|  |
| --- |
| TechDraw Tratteggio |
| Posizione nel menu |
| TechDraw → Tratteggio → Tratteggia una Faccia usando un file immagine |
| Ambiente |
| [TechDraw](/TechDraw_Workbench/it "TechDraw Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Tratteggio geometrico](/TechDraw_GeometricHatch/it "TechDraw GeometricHatch/it"), [Tipi di tratteggio](/TechDraw_Hatching/it "TechDraw Hatching/it") |
|  |

## Descrizione

Lo strumento **TechDraw Tratteggio** riempie una regione chiusa in una Vista con un modello di tratteggio basato su [SVG](/SVG "SVG") o bitmap ([disponibile dalla versione 0.21](/Release_notes_0.21/it "Release notes 0.21/it")). In alternativa, lo strumento ![](/images/TechDraw_GeometricHatch.svg) [TechDraw Tratteggio geometrico](/TechDraw_GeometricHatch/it "TechDraw GeometricHatch/it") utilizza modelli di tratteggio basati su PAT. Vedere [Tipi di tratteggio](/TechDraw_Hatching/it "TechDraw Hatching/it") per i dettagli.

![](/images/TechDraw_Hatch_example.png)

Esempio di tratteggio SVG su una faccia

## Utilizzo

1. Selezionare una regione chiusa in una vista.
2. Esistono diversi modi per richiamare lo strumento:
   * Premere il pulsante ![](/images/TechDraw_Hatch.svg) TechDraw Tratteggio.
   * Seleziona l'opzione **TechDraw → Tratteggio → ![](/images/TechDraw_Hatch.svg) Tratteggia una Faccia utilizzando un file immagine** dal menu.
3. Si apre il pannello delle attività **Applica Tratteggio alla Faccia**.
4. Facoltativamente, modificare il **File del modello**.
5. Facoltativamente, modificaare la **Scala del modello** e il **Colore linea**. Queste impostazioni vengono ignorate per i modelli bitmap.
6. Premere il pulsante OK.

## Note

* Per un riempimento in tinta unita selezionare solid.svg come **File modello**.
* Gli oggetti tratteggiati sono vulnerabili al "[problema di denominazione topologica](/Topological_naming_problem/it "Topological naming problem/it")". Per ulteriori informazioni, vedere [TechDraw Lunghezza](/TechDraw_LengthDimension/it "TechDraw LengthDimension/it"). Si consiglia che il tratteggio sia uno degli ultimi passaggi del processo di disegno.
* I modelli [SVG](/SVG/it "SVG/it") di esempio sono disponibili localmente in:

:   ```
    $INSTALL_DIR/data/Mod/TechDraw/Patterns

    ```

ː Dove `$INSTALL_DIR` è la directory in cui è stato installato FreeCAD, per esempioː

:   ```
    /usr/share/freecad/data/Mod/TechDraw/Patterns

    ```
:   Sono anche disponibili su [GitHub](https://github.com/FreeCAD/FreeCAD/tree/master/src/Mod/TechDraw/Patterns).

## Proprietà

* Dati**Source**: La vista e la faccia che devono ricevere il tratteggio.
* Dati**Hatch Pattern**: Il percorso completo e il nome del file del modello SVG.
* Vista**Hatch Color**: Il colore in cui viene visualizzato il tratteggio.
* Vista**Hatch Scale**: Modifica la dimensione del modello di tratteggio.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

È possibile creare un Tratteggio con [macro](/Macros/it "Macros/it") e dalla console [Python](/Python/it "Python/it") utilizzando le seguenti funzioni:

```
hatch = FreeCAD.ActiveDocument.addObject("TechDraw::DrawHatch", "Hatch")
hatch.Source = (view1, ["Face0"])
hatch.HatchPattern = hatchFileSpec
page.addView(hatch)

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_Hatch/it&oldid=1490105>"