---
title: TechDrawː Sezione complessa
---
|  |
| --- |
| TechDraw Sezione complessa |
| Posizione nel menu |
| TechDraw → Viste TechDraw → Inserisci Sezione complessa |
| Ambiente |
| [TechDraw](/TechDraw_Workbench/it "TechDraw Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| 0.21 |
| Vedere anche |
| [TechDraw Sezione](/TechDraw_SectionView/it "TechDraw SectionView/it"), [TechDraw Vista](/TechDraw_View/it "TechDraw View/it") |
|  |

## Descrizione

Lo strumento **TechDraw Sezione complessa** inserisce una vista in sezione trasversale basata su una vista della parte esistente e un profilo.

![](/images/TechDraw_QuarterSection_example.png)

Una vista in sezione di un quarto creata con lo strumento Sezione complessa

![](/images/TechDraw_AlignedSection_example.png)

Una vista in sezione Deviata creata con lo strumento Sezione complessa

![](/images/TechDraw_OffsetSection_example.png)

Una vista in sezione Sfalsata creata con lo strumento Sezione complessa

## Utilizzo

1. Selezionare una vista della parte e un oggetto profilo nella [Vista 3D](/3D_view/it "3D view/it") o nella [Vista ad albero](/Tree_view/it "Tree view/it"). I profili sono in genere schizzi, ma funzionerà qualsiasi oggetto la cui forma possa essere trasformata in una polilinea.
2. Esistono diversi modi per richiamare lo strumento:
   * Premere il pulsante ![](/images/TechDraw_ComplexSection.svg) Inserisci Sezione complessa.
   * Selezionare l'opzione **TechDraw → Viste TechDraw → ![](/images/TechDraw_ComplexSection.svg) Inserisci Sezione complessa** dal menu.
3. Si apre un pannello delle azioni che aiuterà a calcolare le varie proprietà. Vengono calcolati valori ragionevoli per la direzione della vista, ma questi possono essere modificati.

![](/images/TechDraw_ComplexSection_Taskview1.png)
![](/images/TechDraw_ComplexSection_Taskview2.png)

## Proprietà

Una Sezione Complessa, formalmente un oggetto `TechDraw::DrawComplexSection`, deriva da un oggetto [Vista Sezione](/TechDraw_SectionView/it#Properietà "TechDraw SectionView/it"), formalmente un oggetto `TechDraw::DrawViewSection` ed eredita tutti le sue proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Cutting Tool

* Dati**Cutting Tool Wire Object**: l'oggetto documento la cui forma verrà utilizzata per generare il profilo di taglio.
* Dati**Projection Strategy**: controlla come viene eseguito il taglio e come viene proiettato il risultato sulla pagina:
  + `Offset`: esegue un taglio semplice della forma sorgente e proietta il risultato.
  + `Aligned`: Taglia la forma di origine utilizzando uno strumento creato da ciascun segmento (bordo) del profilo di taglio. I risultati di ogni taglio vengono proiettati in una serie verticale o orizzontale, a seconda dell'orientamento del profilo di taglio.
  + `NoParallel`: come allineato, ma i segmenti del profilo paralleli alla direzione della vista vengono saltati.

## Note

Vedere [TechDraw Vista sezione](/TechDraw_SectionView/it#Note "TechDraw SectionView/it")

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Lo strumento Sezione Complessa può essere utilizzato nelle [macro](/Macros/it "Macros/it") e dalla console [Python](/Python/it "Python/it") tramite le seguenti funzioni:

```
doc = FreeCAD.ActiveDocument
box = doc.Box
profile = doc.Sketch
page = doc.Page

view = doc.addObject("TechDraw::DrawViewPart", "View")
page.addView(view)
view.Source = box
view.Direction = (0, 0, 1)

section = doc.addObject("TechDraw::DrawComplexSection", "ComplexSection")
page.addView(section)
section.BaseView = view
section.CuttingToolWireObject = profile
section.Direction = (0, 1, 0)
section.SectionNormal = (-1, 0, 0)

```

## Esempi

Per ulteriori informazioni sulle Viste di sezione e su alcuni casi d'uso, dare un'occhiata a: [Esempi di sezione TechDraw](/TechDraw_Section_Examples/it "TechDraw Section Examples/it").

![](/images/TechDraw_ExampleSection-10.png)
![](/images/TechDraw_ExampleSection-13.png)
![](/images/TechDraw_ExampleSection-15.png)
![](/images/TechDraw_ExampleSection-17.png)
![](/images/TechDraw_ExampleSection-34.png)
![](/images/TechDraw_ExampleSection-35.png)

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_ComplexSection/it&oldid=1571034>"