---
title: Reinforcement Balkenbewehrung
---
|  |
| --- |
| Reinforcement Balkenbewehrung |
| Menüeintrag |
| 3D/BIM → Bewehrungswerkzeuge → Balkenbewehrung |
| Arbeitsbereich |
| [Reinforcement](/Reinforcement_Workbench/de "Reinforcement Workbench/de"), [BIM](/BIM_Workbench/de "BIM Workbench/de") |
| Standardtastenkürzel |
| *Keiner* |
| Eingeführt in Version |
| 0.19 |
| Siehe auch |
| *Keiner* |
|  |

## Beschreibung

Das Werkzeug Reinforcement Balkenbewehrung erlaubt dem Anwender Bewehrungsstäbe innerhalb eines Balkenobjekts ([Arch-Struktur](/Arch_Structure/de "Arch Structure/de")-Objekt) zu erzeugen.

Dieses Werkzeug ist Teil des Arbeitsbereichs [Reinforcement](/Reinforcement_Workbench/de "Reinforcement Workbench/de"); dieser ist ein [externer Arbeitsbereich](/External_workbenches/de "External workbenches/de"), der mit dem ![](/images/Std_AddonMgr.svg) [Addon-Manager](/Std_AddonMgr/de "Std AddonMgr/de") installiert werden kann.

![](/images/Arch_Rebar_BeamReinforcement_example.png)

Balkenbewehrung innerhalb eines Balkens ([Arch Struktur](/Arch_Structure/de "Arch Structure/de"))

## Anwendung

1. Wähle die rechte Seite eines zuvor erstellten Balkenobjekts ![](/images/Arch_Structure.svg) [Arch Structure](/Arch_Structure "Arch Structure") mit einer Länge entlang der x-Achse. Oder wähle die Vorderseite eines zuvor erstellten Balkenobjekts ![](/images/Arch_Structure.svg) [Arch Structure](/Arch_Structure "Arch Structure") mit einer Länge entlang der y-Achse.

2. Dann ![](/images/Reinforcement_ColumnRebars.svg) [Stützenbewehrung](/Reinforcement_ColumnRebars/de "Reinforcement ColumnRebars/de") in den Armierungswerkzeugen auswählen.

3. Eine Dialog-Box wird sich öffnen, wie unten gezeigt.

:   ![](/images/BeamReinforcementDialog_Stirrups.png)
:   Dialogfeld für das Werkzeug „Bewehrungsstäbe“

4. Wähle die gewünschte Art der Stützenbewehrung aus.

5. Gib Eingaben für Daten zu Bindungen ein.

6. Klicke auf Weiter und das Dialogfeld wird wie unten gezeigt aktualisiert.

:   ![](/images/BeamReinforcementDialog_TopRebars.png)
:   Dialogfeld für Daten zu oberen Bewehrungsstäben

7. Daten für obere Bewehrungsstäbe festlegen.

:   Um den Wert „Number#Diameter@Offset“ zu bearbeiten, klicke auf die Schaltfläche Bearbeiten neben der Beschriftung „Number#Diameter@Offset“. Ein Dialogfeld wie unten gezeigt wird eingeblendet.

:   ![](/images/Beam_TopReinforcement_NumberDiameterOffset.png)

:   Um den Wert für den Bewehrungstyp zu bearbeiten, klicke auf die Schaltfläche Bearbeiten neben der Beschriftung für den Bewehrungstyp. Ein Dialogfeld wie unten gezeigt wird eingeblendet.

:   ![](/images/Beam_TopReinforcement_RebarType.png)

:   Um den Wert für die Hakenausrichtung zu bearbeiten, klicke auf die Schaltfläche Bearbeiten neben der Beschriftung für die Hakenausrichtung. Ein Dialogfeld wie unten gezeigt wird eingeblendet.

:   ![](/images/Beam_TopReinforcement_HookOrientation.png)

:   Um den Wert der Hook-Erweiterung zu bearbeiten, klicke auf die Schaltfläche Bearbeiten neben der Bezeichnung der Hook-Erweiterung. Ein Dialogfeld wie unten gezeigt wird eingeblendet.

:   ![](/images/Beam_TopReinforcement_HookExtension.png)

:   Um den Rundungswert für LRebar zu bearbeiten, klicke auf die Schaltfläche Bearbeiten neben der Rundungsbezeichnung. Ein Dialogfeld wie unten gezeigt wird eingeblendet.

:   ![](/images/Beam_TopReinforcement_LRebarRounding.png)

:   Um den Wert für den Ebenenabstand zu bearbeiten, klicke auf die Schaltfläche Bearbeiten neben der Beschriftung „Ebenenabstand“. Ein Dialogfeld wie unten gezeigt wird eingeblendet.

:   ![](/images/Beam_TopReinforcement_LayerSpacing.png)

8. Klicke auf Weiter und das Dialogfeld wird wie unten gezeigt aktualisiert.

:   ![](/images/BeamReinforcementDialog_BottomRebars.png)
:   Dialogfeld für Daten zu unteren Bewehrungsstäben

9. Lege die Daten für die unteren Bewehrungsstäbe ähnlich den Daten für die oberen Bewehrungsstäbe fest.

10. Klicke auf Weiter und das Dialogfeld wird wie unten gezeigt aktualisiert.

:   ![](/images/BeamReinforcementDialog_LeftRebars.png)
:   Dialogfeld für Daten zu Bewehrungsstäben mit linker Scherung

11. Daten für linksseitige Scherbewehrungsstäbe festlegen.

:   Um den Wert „Number#Diameter@Offset“ zu bearbeiten, klicke auf die Schaltfläche Bearbeiten neben der Beschriftung „Number#Diameter@Offset“. Ein Dialogfeld wie unten gezeigt wird eingeblendet.

:   ![](/images/Beam_ShearReinforcement_NumberDiameterOffset.png)

:   Um den Wert für den Bewehrungstyp zu bearbeiten, klicke auf die Schaltfläche Bearbeiten neben der Beschriftung für den Bewehrungstyp. Ein Dialogfeld wie unten gezeigt wird eingeblendet.

:   ![](/images/Beam_ShearReinforcement_RebarType.png)

:   Um den Wert für die Hakenausrichtung zu bearbeiten, klicke auf die Schaltfläche Bearbeiten neben der Beschriftung für die Hakenausrichtung. Ein Dialogfeld wie unten gezeigt wird eingeblendet.

:   ![](/images/Beam_ShearReinforcement_HookOrientation.png)

:   Um den Wert der Hook-Erweiterung zu bearbeiten, klicke auf die Schaltfläche Bearbeiten neben der Bezeichnung der Hook-Erweiterung. Ein Dialogfeld wie unten gezeigt wird eingeblendet.

:   ![](/images/Beam_ShearReinforcement_HookExtension.png)

:   Um den Rundungswert für LRebar zu bearbeiten, klicke auf die Schaltfläche Bearbeiten neben der Rundungsbezeichnung. Ein Dialogfeld wie unten gezeigt wird eingeblendet.

:   ![](/images/Beam_ShearReinforcement_LRebarRounding.png)

12. Klicke auf Weiter und das Dialogfeld wird wie unten gezeigt aktualisiert.

:   ![](/images/BeamReinforcementDialog_RightRebars.png)
:   Dialogfeld für Daten zu Bewehrungsstäben mit rechter Scherung

13. Lege die Daten für Bewehrungsstäbe mit rechter Scherung ähnlich den Daten für Bewehrungsstäbe mit linker Scherung fest.

14. Klicke auf OK oder Übernehmen, um die Balkenbewehrung zu erzeugen.

15. Abbrechen anklicken, um die Dialog-Box zu verlassen.

## Eigenschaften

**Bügel:**

* Daten**Linke Abdeckung**: Der Abstand zwischen dem linken Ende des Bügels und der linken Seite der Struktur.
* Daten**Rechte Abdeckung**: Der Abstand zwischen dem rechten Ende des Bügels und der rechten Seite der Struktur.
* Daten**Obere Abdeckung**: Der Abstand zwischen dem Bügel und der oberen Seite der Struktur.
* Daten**Untere Abdeckung**: Der Abstand zwischen dem Bügel und der unteren Seite der Struktur.
* Daten**Versatz**: Der Abstand zwischen dem Bügel und der ausgewählten/hinteren Seite der Struktur.
* Daten**Durchmesser**: Durchmesser des Bügels.
* Daten**Biegewinkel**: Der Biegungswinkel definiert den Winkel an den Enden eines Bügels.
* Daten**Verlängerungsfaktor**: Der Verlängerungsfaktor definiert die Länge des Bügelendes, ausgedrückt als multipliziert mit dem Durchmesser.
* Daten**Nummer**: Die Nummer des Bügels.
* Daten**Spacing**: Der Abstand zwischen den Achsen jedes Bügels.

**Obere/untere Bewehrungsstäbe:** An der Ober-/Unterseite des Balkens vorhandene Bewehrungsstäbe

* Daten**NumberDiameterOffset**: Ein Tupel aus der Zeichenfolge Number#Diameter@Offset. Jedes Element des Tupels stellt die Bewehrung für jede neue Schicht dar.
* Daten**Rebar Type**: Liste von Tupeln mit Bewehrungsstabtypen.
* Daten**Hook Orientation**: Liste von Tupeln mit der Ausrichtung von L-förmigen Haken.
* Daten**Hook Extension**: Liste von Tupeln mit der Länge des Hakens von L-förmigen Bewehrungsstäben.
* Daten**Rounding**: Liste von Tupeln mit einem Rundungswert, der auf die Ecken der L-förmigen Bewehrungsstäbe angewendet werden soll, ausgedrückt als multipliziert mit dem Durchmesser.
* Daten**Layer Spacing**: Liste mit dem Abstand zwischen zwei aufeinanderfolgenden Bewehrungsschichten.

**Linke/rechte Bewehrungsstäbe:** Bewehrungsstäbe auf der linken/rechten Seite des Balkens vorhanden

* Daten**NumberDiameterOffset**: Zeichenfolge mit Number#Diameter@Offset für Bewehrungsstäbe.
* Daten**Bewehrungsstabtyp**: Liste der Bewehrungsstabtypen.
* Daten**Hakenausrichtung**: Liste der Ausrichtung von L-förmigen Haken.
* Daten**Hakenverlängerung**: Liste der Hakenlängen von L-förmigen Bewehrungsstäben.
* Daten**Rundung**: Liste eines Rundungswerts, der auf die Ecken der L-förmigen Bewehrungsstäbe angewendet werden soll, ausgedrückt als multipliziert mit dem Durchmesser.
* Daten**Bewehrungsstababstand**: Freier Abstand zwischen aufeinanderfolgenden Bewehrungsstäben.

## Skripten

*Siehe auch:* [Architektur API](/Arch_API/de "Arch API/de"), [Bewehrung API](/Reinforcement_API/de "Reinforcement API/de") und [FreeCAD Grundlagen Skripten](/FreeCAD_Scripting_Basics/de "FreeCAD Scripting Basics/de").

Das Werkzeug „Reinforcement BeamRebars“ kann in [Makros](/index.php?title=Makros/de&action=edit&redlink=1 "Makros/de (page does not exist)") und von der [Python](/Python/de "Python/de")-Konsole aus mithilfe der folgenden Funktion verwendet werden:

### Zweibeinige Bügel erstellen

```
RebarGroup = makeReinforcement(
    l_cover_of_stirrup,
    r_cover_of_stirrup,
    t_cover_of_stirrup,
    b_cover_of_stirrup,
    offset_of_stirrup,
    bent_angle,
    extension_factor,
    dia_of_stirrup,
    number_spacing_check,
    number_spacing_value,
    top_reinforcement_number_diameter_offset,
    top_reinforcement_rebar_type,
    top_reinforcement_layer_spacing,
    bottom_reinforcement_number_diameter_offset,
    bottom_reinforcement_rebar_type,
    bottom_reinforcement_layer_spacing,
    left_rebars_number_diameter_offset,
    left_rebars_type,
    left_rebars_spacing,
    right_rebars_number_diameter_offset,
    right_rebars_type,
    right_rebars_spacing,
    top_reinforcement_l_rebar_rounding=2,
    top_reinforcement_hook_extension=40,
    top_reinforcement_hook_orientation="Front Inside",
    bottom_reinforcement_l_rebar_rounding=2,
    bottom_reinforcement_hook_extension=40,
    bottom_reinforcement_hook_orientation="Front Inside",
    left_l_rebar_rounding=2,
    left_rebars_hook_extension=40,
    left_rebars_hook_orientation="Front Inside",
    right_l_rebar_rounding=2,
    right_rebars_hook_extension=40,
    right_rebars_hook_orientation="Front Inside",
    structure=None,
    facename=None,
)

```

* Creates a `RebarGroup` object from the given `structure`, which is an [Arch Structure](/Arch_Structure "Arch Structure"), and `facename`, which is a face of that structure.
  + If no `structure` nor `facename` are given, it will take the user selected face as input.
* `l_cover_of_stirrup`, `r_cover_of_stirrup`, `t_cover_of_stirrup`, `b_cover_of_stirrup` and `offset_of_stirrup` are inner offset distances for the stirrup elements with respect to the faces of the structure. They are respectively the left, right, top, bottom and front/rear offsets.
* `bent_angle` define the angle of the tip of the reinforcement loop of stirrup.
* `extension_factor` define the length of the tip of the reinforcement loop of stirrup, expressed in times the diameter.
* `dia_of_stirrup` is the diameter of the stirrup.
* `number_spacing_check` if it is `True` it will create as many stirrup as given by `number_spacing_value`; if it is `False` it will create stirrup separated by the numerical value of `number_spacing_value`.
* `number_spacing_value` specifies the number of stirrups, or the value of the separation between them, depending on `number_spacing_check`.
* `top_reinforcement_number_diameter_offset` and `bottom_reinforcement_number_diameter_offset` are tuple of number\_diameter\_offset string. Each element of tuple represents reinforcement for each new layer.

```
   Syntax: (
               "number1#diameter1@offset1+number2#diameter2@offset2+...",
               "number3#diameter3@offset3+number4#diameter4@offset4+...",
               ...,
           )

```

* `top_reinforcement_rebar_type` and `bottom_reinforcement_rebar_type` specifies type of top/bottom reinforcement bars.

```
   Possible values:
   1. 'StraightRebar' or 'LShapeRebar'
   2. ('<rebar_type>', '<rebar_type>', ...) and number of elements of tuple must be equal to number of reinforcement
      layers.
   3. [
          ('<rebar_type>', '<rebar_type>', ...),
          ('<rebar_type>', '<rebar_type>', ...),
          ...,
      ]
      each element of list is a tuple, which specifies rebar type of each reinforcement layer. And each element of
      tuple represents rabar_type for each set of rebars.
   4. [
          <rebar_type>,
          ('<rebar_type>', '<rebar_type>', ...),
          ...,
      ]

```

* `top_reinforcement_layer_spacing` and `bottom_reinforcement_layer_spacing` is the spacing between two consecutive reinforcement layers.

```
   Possible values:
   1. <layer_spacing>
   2. (<spacing in layer1 and layer2>, <spacing in layer2 and layer3>, ...) and number of elements of tuple must be
      equal to one less than number of layers.

```

* `left_rebars_number_diameter_offset` and `right_rebars_number_diameter_offset` are string of number\_diameter\_offset.

```
   Syntax: "number1#diameter1@offset1+number2#diameter2@offset2+..."

```

* `left_rebars_type` and `right_rebars_type` specifies type of left/right reinforcement bars.

```
   Possible values:
   1. 'StraightRebar' or 'LShapeRebar'
   2. ('<rebar_type>', '<rebar_type>', ...) and each element of tuple represents rabar_type for each set of rebars.

```

* `left_rebars_spacing` and `right_rebars_spacing` is clear spacing between consecutive reinforcement bars.
* `top_reinforcement_l_rebar_rounding` and `bottom_reinforcement_l_rebar_rounding` is the parameter that determines the bending radius of the LShaped top/bottom rebars, expressed as times the diameter. Possible syntax are similar to as discussed above for `top_reinforcement_rebar_type` / `bottom_reinforcement_rebar_type`.
* `top_reinforcement_hook_extension` and `bottom_reinforcement_hook_extension` is the length of hook of LShaped rebars. Possible syntax are similar to as discussed above for `top_reinforcement_rebar_type` / `bottom_reinforcement_rebar_type`.
* `top_reinforcement_hook_orientation` and `bottom_reinforcement_hook_orientation` specifies the orientation of LShaped hook; it can be `"Front Inside"`, `"Front Outside"`, `"Rear Inside"` or `"Rear Outside"`. Possible syntax are similar to as discussed above for `top_reinforcement_rebar_type` / `bottom_reinforcement_rebar_type`.
* `left_l_rebar_rounding` and `right_l_rebar_rounding` is the parameter that determines the bending radius of the LShaped left/right rebars, expressed as times the diameter. Possible syntax are similar to as discussed above for `left_rebars_type` / `right_rebars_type`.
* `left_rebars_hook_extension` and `right_rebars_hook_extension` is the length of hook of LShaped rebars. Possible syntax are similar to as discussed above for `left_rebars_type` / `right_rebars_type`.
* `left_rebars_hook_orientation` and `right_rebars_hook_orientation` specifies the orientation of LShaped hook; it can be `"Front Inside"`, `"Front Outside"`, `"Rear Inside"` or `"Rear Outside"`. Possible syntax are similar to as discussed above for `left_rebars_type` / `right_rebars_type`.

#### Example

```
import FreeCAD, Arch
from BeamReinforcement import TwoLeggedBeam

Structure = Arch.makeStructure(length=3000.0,width=200.0,height=400.0)
Structure.ViewObject.Transparency = 80
FreeCAD.ActiveDocument.recompute()

RebarGroup = TwoLeggedBeam.makeReinforcement(
    l_cover_of_stirrup=20,
    r_cover_of_stirrup=20,
    t_cover_of_stirrup=20,
    b_cover_of_stirrup=20,
    offset_of_stirrup=100,
    bent_angle=135,
    extension_factor=4,
    dia_of_stirrup=8,
    number_spacing_check=False,
    number_spacing_value=200,
    top_reinforcement_number_diameter_offset=("1#20@-60+2#16@-60+1#20@-60", "3#16@-100"),
    top_reinforcement_rebar_type="LShapeRebar",
    top_reinforcement_layer_spacing=30,
    bottom_reinforcement_number_diameter_offset=("1#20@-60+2#16@-60+1#20@-60", "3#16@-100"),
    bottom_reinforcement_rebar_type="LShapeRebar",
    bottom_reinforcement_layer_spacing=30,
    left_rebars_number_diameter_offset="1#16@-100+1#16@-100+1#16@-100",
    left_rebars_type="LShapeRebar",
    left_rebars_spacing=30,
    right_rebars_number_diameter_offset="1#16@-100+1#16@-100+1#16@-100",
    right_rebars_type="LShapeRebar",
    right_rebars_spacing=30,
    top_reinforcement_l_rebar_rounding=2,
    top_reinforcement_hook_extension=100,
    top_reinforcement_hook_orientation="Rear Outside",
    bottom_reinforcement_l_rebar_rounding=2,
    bottom_reinforcement_hook_extension=100,
    bottom_reinforcement_hook_orientation="Rear Outside",
    left_l_rebar_rounding=2,
    left_rebars_hook_extension=80,
    left_rebars_hook_orientation=("Rear Inside", "Front Inside", "Rear Inside"),
    right_l_rebar_rounding=2,
    right_rebars_hook_extension=80,
    right_rebars_hook_orientation=("Front Inside", "Rear Inside", "Front Inside"),
    structure=Structure,
    facename="Face6",
)

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Reinforcement_BeamRebars/de&oldid=1525094>"