---
title: 零件球体
---
|  |
| --- |
| Part Sphere |
| Menu location |
| Part → Primitives → Sphere |
| Workbenches |
| [Part](/Part_Workbench "Part Workbench") |
| Default shortcut |
| *None* |
| Introduced in version |
| - |
| See also |
| [Part Primitives](/Part_Primitives "Part Primitives") |
|  |

## Description

## 描述

利用位置、角度1、角度2、角度3与半径参数创建一个简单的参数化球体。

A Part Sphere can be truncated at the top and/or bottom by changing its 数据**Angle1** and/or 数据**Angle2** properties. It can be turned into a segment of a sphere by changing its 数据**Angle3** property.

![](/images/Part_Sphere_Example.png)

## Usage

## 如何使用

在[零件](/Part_Workbench "Part Workbench")工作台中点击球体图标![](/images/Part_Sphere.png)。球体在创建时会被定位在原点(point 0,0,0)处。角度参数确定了所创的是局部球体，而非完整的球体（角度参数的默认设置值为360°）。

## Example

![](/images/Part_Sphere_Scripting_Example.png)

Part Sphere from the scripting example

A Part Sphere object created with the [scripting example](#Scripting) below is shown here.

## Notes

* A Part Sphere can also be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. With that command you can specify the dimensions and placement at creation time.

## 选项

See also: [Property editor](/Property_editor "Property editor").

A Part Sphere object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Sphere

* 数据**Radius** (`Length`): The radius of the sphere. The default is `5mm`.
* 数据**Angle1** (`Angle`): The start angle of the circular arc profile of the sphere. Valid range: `-90° <= value <= 90°`. May not be equal to 数据**Angle2**. The default is `-90°`.
* 数据**Angle2** (`Angle`): The end angle of the circular arc profile of the sphere. Valid range: `-90° <= value <= 90°`. May not be equal to 数据**Angle1**. The default is `90°`. If the total angle of the arc profile is smaller than `180°` the sphere will be truncated and have a flat face at the top and/or bottom.
* 数据**Angle3** (`Angle`): The total angle of revolution of the sphere. Valid range: `0° < value <= 360°`. The default is `360°`. If it is smaller than `360°` the resulting solid will be a segment of a sphere.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Sphere can be created with the `addObject()` method of the document:

```
sphere = FreeCAD.ActiveDocument.addObject("Part::Sphere", "mySphere")

```

* Where `"mySphere"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

sphere = doc.addObject("Part::Sphere", "mySphere")
sphere.Radius = 20
sphere.Angle1 = -30
sphere.Angle2 = 45
sphere.Angle3 = 90
sphere.Placement = App.Placement(App.Vector(3, 9, 11), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Sphere/zh-cn&oldid=1466551>"