---
title: 零件圆柱体
---
|  |
| --- |
| Part Cylinder |
| Menu location |
| Part → Primitives → Cylinder |
| Workbenches |
| [Part](/Part_Workbench "Part Workbench") |
| Default shortcut |
| *None* |
| Introduced in version |
| - |
| See also |
| [Part Primitives](/Part_Primitives "Part Primitives") |
|  |

## Description

## 描述

利用位置、角度、半径与高度参数创建一个简单的参数化圆柱体。

A Part Cylinder can be turned into a segment of a cylinder by changing its 数据**Angle** property.

![](/images/Part_Cylinder_Example.png)

## 如何使用

在[零件](/Part_Workbench "Part Workbench")工作台中点击此图标![](/images/Part_Cylinder.png)。默认情况下，此工具会创建一个对齐于坐标轴的半径为2mm且高度为10mm的完整圆柱体，并令其中心与全局原点(point 0,0,0)重合。

1. There are several ways to invoke the command:
   * Press the ![](/images/Part_Cylinder.svg) [Cylinder](/Part_Cylinder "Part Cylinder") button.
   * Select the **Part → Primitives → ![](/images/Part_Cylinder.svg) Cylinder** option from the menu.
2. The cylinder is created.
3. Optionally change the dimensions and 数据**Placement** of the cylinder by doing one of the following:
   * Double-click the object in the [Tree view](/Tree_view "Tree view"):
     1. The **Geometric Primitives** task panel opens.
     2. Change one or more properties.
     3. The object is dynamically updated in the [3D view](/3D_view "3D view").
     4. Press the OK button.
   * Change the properties in the [Property editor](/Property_editor "Property editor").
   * Change the 数据**Placement** with the ![](/images/Std_TransformManip.svg) [Std TransformManip](/Std_TransformManip "Std TransformManip") command.

## Example

![](/images/Part_Cylinder_Scripting_Example.png)

Part Cylinder from the scripting example

A Part Cylinder object created with the [scripting example](#Scripting) below is shown here.

## Notes

* A Part Cylinder can also be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. With that command you can specify the dimensions and placement at creation time.

## 选项

创建圆柱体后，用户可编辑其数据选项卡中的各属性：

See also: [Property editor](/Property_editor "Property editor").

A Part Cylinder object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Cylinder

* 数据**Radius** (`Length`): The radius of the circular arc that defines the cylinder. The default is `2mm`.
* 数据**Height** (`Length`): The height of the cylinder. The default is `10mm`.
* 数据**Angle** (`Angle`): The angle of the circular arc that defines the cylinder. Valid range: `0° < value <= 360°`. The default is `360°`. If it is smaller than `360°` the resulting solid will be a segment of a cylinder.

Prism

* 数据**First Angle** (`Angle`): The angle between the extrusion direction of the cylinder and its positive Z axis, measured around its Y axis. The angle is positive towards its positive X axis. Valid range: `0° <= value < 90°`. The default is `0°`. [introduced in 0.20](/Release_notes_0.20 "Release notes 0.20")
* 数据**Second Angle** (`Angle`): The angle between the extrusion direction of the cylinder and its positive Z axis, measured around its X axis. The angle is positive towards its positive Y axis. Valid range: `0° <= value < 90°`. The default is `0°`. [introduced in 0.20](/Release_notes_0.20 "Release notes 0.20")

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Cylinder can be created with the `addObject()` method of the document:

```
cylinder = FreeCAD.ActiveDocument.addObject("Part::Cylinder", "myCylinder")

```

* Where `"myCylinder"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

cylinder = doc.addObject("Part::Cylinder", "myCylinder")
cylinder.Radius = 10
cylinder.Height = 50
cylinder.Placement = App.Placement(App.Vector(5, 10, 15), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Cylinder/zh-cn&oldid=1466756>"