---
title: 零件环面
---
|  |
| --- |
| Part Torus |
| Menu location |
| Part → Primitives → Torus |
| Workbenches |
| [Part](/Part_Workbench "Part Workbench") |
| Default shortcut |
| *None* |
| Introduced in version |
| - |
| See also |
| [Part Primitives](/Part_Primitives "Part Primitives") |
|  |

## Description

## 描述

根据position, angle1, angle2, angle3, radius1 与 radius2参数创建一个简单的参数化环面。

A Part Torus can be turned into a segment of a torus by changing its 数据**Angle3** property. By changing its 数据**Angle1** and/or 数据**Angle2** properties the swept profile can become a segment of a circle.

![](/images/Part_Torus_Example.png)

## 如何使用

在[零件工作台](/Part_Workbench "Part Workbench")中点击环面图标![](/images/Part_Torus.png)。这会在原点(point 0,0,0)处创建一个环面。
三个角度参数(angle1, angle2, angle3)与两个半径参数(radius1 , radius2)用于确定参数化环面，详情请看下段文字。

## Example

![](/images/Part_Torus_Scripting_Example.png)

Part Torus from the scripting example

A Part Torus object created with the [scripting example](#Scripting) below is shown here.

## Notes

* A Part Torus can also be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. With that command you can specify the dimensions and placement at creation time.

![](/images/TorusExampleRadius1.jpg)  
将Radius1参数的值指定为20 mm。

See also: [Property editor](/Property_editor "Property editor").

A Part Torus object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Torus

* **Radius1:** 小圆盘圆周运动所绕圆环的半径
* **Radius2:** 定义环面形状的小圆盘的半径
* **Angle1:** 用于切割/定义环面小圆盘的第1个角度参数
* **Angle2:** 用于切割/定义环面小圆盘的第2个角度参数
* **Angle3:** 用于定义环面运动圆周的第3个角度参数

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Torus can be created with the `addObject()` method of the document:

```
torus = FreeCAD.ActiveDocument.addObject("Part::Torus", "myTorus")

```

* Where `"myTorus"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

torus = doc.addObject("Part::Torus", "myTorus")
torus.Radius1 = 20
torus.Radius2 = 10
torus.Angle1 = -90
torus.Angle2 = 45
torus.Angle3 = 270
torus.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Torus/zh-cn&oldid=1466581>"