---
title: 零件圆锥
---
|  |
| --- |
| Part Cone |
| Menu location |
| Part → Primitives → Cone |
| Workbenches |
| [Part](/Part_Workbench "Part Workbench") |
| Default shortcut |
| *None* |
| Introduced in version |
| - |
| See also |
| [Part Primitives](/Part_Primitives "Part Primitives") |
|  |

## Description

## 描述

在零件工作台中，可以通过零件工具栏、Part菜单（中的primitives子菜单）或Create Primitives（创建图元）对话框来创建参数化的截断零件圆锥图元。

The default Part Cone is truncated. It can be turned into a full, untruncated, cone by changing its 数据**Radius1** or 数据**Radius2** property to zero. It can be turned into a segment of a cone by changing its 数据**Angle** property.

![](/images/Part_Cone_Example.png)

## Usage

## 如何使用

点击位于零件工作台中的图标![](/images/Part_Cone.png)。

## Example

![](/images/Part_Cone_Scripting_Example.png)

Part Cone from the scripting example

A Part Cone object created with the [scripting example](#Scripting) below is shown here.

## Notes

* A Part Cone can also be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. With that command you can specify the dimensions and placement at creation time.

## 选项

|  |  |
| --- | --- |
|  | Cone   * Radius 1 - 定义底面弧或圆的半径 * Radius 2 - 定义顶面弧或圆的半径 * Height - 零件圆锥体的高度 * Angle - 定义截断圆锥体顶面与底面上弧或圆的角度值。默认值360创建的顶底皆为圆面，较小值将创建出不完整的部分圆锥，具体形状取决于实际角度与两个半径所定义的弧，乃至顶面与底面。 |

See also: [Property editor](/Property_editor "Property editor").

A Part Cone object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Cone

* 数据**Radius1** (`Length`): The radius of the bottom face of the cone. Can be `0mm` if 数据**Radius2** is larger than `0mm`. The default is `2mm`.
* 数据**Radius2** (`Length`): The radius of the top face of the cone. Can be `0mm` if 数据**Radius1** is larger than `0mm`. The default is `4mm`.
* 数据**Height** (`Length`): The height of the cone. The default is `10mm`.
* 数据**Angle** (`Angle`): The angle of the circular arc that defines the top and bottom face of the cone. Valid range: `0° < value <= 360°`. The default is `360°`. If it is smaller than `360°` the resulting solid will be a segment of a cone.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Cone can be created with the `addObject()` method of the document:

```
cone = FreeCAD.ActiveDocument.addObject("Part::Cone", "myCone")

```

* Where `"myCone"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

cone = doc.addObject("Part::Cone", "myCone")
cone.Radius1 = 5
cone.Radius2 = 10
cone.Height = 50
cone.Angle = 270
cone.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 60, 15))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Cone/zh-cn&oldid=1466563>"