---
title: Команда "Отменить"
---
|  |
| --- |
| Отменить |
| Расположение в меню |
| Правка → Отменить |
| Верстаки |
| Все |
| Быстрые клавиши |
| Ctrl+Z |
| Представлено в версии |
| - |
| См. также |
| [Вернуть](/Std_Redo/ru "Std Redo/ru") |
|  |

## Описание

Команда "Отменить", отменяет последнее действие.

## Применение

1. Существует несколько способов вызова данной команды:
   * Нажатием кнопки ![](/images/Std_Undo.svg) Отменить на панели инструментов.
   * Вызовом через меню **Правка → ![](/images/Std_Undo.svg) Отменить**.
   * Используя комбинацию клавиш клавиатуры: Ctrl+Z.

## Опции

* Чтобы отменить несколько действий, нажмите на маленькую черную стрелку указывающую вниз с правой стороны от кнопки ![](/images/Std_Undo.svg) Отмена и выберите шаг к которому нужно вернуться из списка.

## Настройки

See also: [Preferences Editor](/Preferences_Editor "Preferences Editor").

* Функцию Отмены/Повтора можно отключить, установив **Инструменты → Редактор параметров... → Base App → Preferences → Document → UsingUndo** в состяние `false`, но это не рекомендуется. Этот параметр также можно изменить через [Настройки](/Preferences_Editor/ru#Документ "Preferences Editor/ru").
* Максимальное количество шагов Отмены/Повтора steps можно установить в **Инструменты → Редактор параметров... → BaseApp → Preferences → Document → MaxUndoSize**. Этот параметр также можно изменить через [Настройки](/Preferences_Editor/ru#Документ "Preferences Editor/ru").

## Программирование

*Смотрите так же:* [Основы составления скриптов в FreeCAD](/FreeCAD_Scripting_Basics/ru "FreeCAD Scripting Basics/ru").

Чтобы отменить последнее действие используйте метод `undo` объекта document.

```
import FreeCAD

FreeCAD.ActiveDocument.undo()

```

При запуске FreeCAD в консольном режиме (CLI) механизм отмены/повтора по умолчанию выключен. Его нужно активировать для каждого документа следующим кодом:

```
import FreeCAD

FreeCAD.ActiveDocument.UndoMode = 1

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_Undo/ru&oldid=1448879>"