---
title: Команда "Объединить проект..."
---
|  |
| --- |
| Std MergeProjects |
| Расположение в меню |
| Файл → Объединить проект |
| Верстаки |
| All |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| - |
| См. также |
| *Нет* |
|  |

## Описание

Команда "Объединить проект..." добавляет содержимое FreeCAD файла в текущий документ.

## Применение

1. Select the **File → ![](/images/Std_MergeProjects.svg) Merge document...** option from the menu.
2. Select a FreeCAD file in the dialog box.
3. Press the Open button.

## Опции

* Нажмите Esc или кнопку Отмена, чтобы отменить выполнение команды.

## Примечания

* A project cannot be merged with itself, selecting the current file is not allowed.
* FreeCAD will automatically change the internal names and, depending on the [preferences](/Preferences_Editor#Document "Preferences Editor"), labels of objects to avoid name conflicts.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To merge a project use the `mergeProject` method of the document object.

```
import FreeCAD

FreeCAD.ActiveDocument.mergeProject("Path_to_FCStd_project_file")

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_MergeProjects/ru&oldid=1534348>"