---
title: Команда "Редактировать/закончить редактирование"
---
|  |
| --- |
| Редактировать/закончить редактирование |
| Расположение в меню |
| Редактировать → Редактировать/закончить редактирование |
| Верстаки |
| Все |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| - |
| См. также |
| [Режим редактирования](/index.php?title=Std_UserEditMode/ru&action=edit&redlink=1 "Std UserEditMode/ru (page does not exist)") |
|  |

## Описание

Команда **Редактировать/закончить редактирование** позволяет переключать объект в режим редактирования и обратно.

## Применение

1. Если ни один объект не находится в режиме редактирования: выберите один объект.
2. Выберите пункт меню **Правка → ![](/images/Std_Edit.svg) Редактировать/закончить редактирование**.
3. После чего, для выбранного объекта активируется режим редактирования по умолчанию или деактивируется уже существующий режим редактирования.

## Примечания

* Во время редактирования объекта, некоторые инструменты в пользовательском интерфейсе будут неактивны (выделены серым цветом).
* Не все типы объектов имеют режим редактирования.
* Функциональность, доступная в режиме редактирования, зависит от типа объекта.
* Режим редактирования можно активировать дважды щелкнув объект в [древе проекта](/Tree_view/ru "Tree view/ru").

## Программирование

*Смотрите так же:* [Основы составления скриптов в FreeCAD](/FreeCAD_Scripting_Basics/ru "FreeCAD Scripting Basics/ru").

Для входа в режим редактирования объекта используйте метод `setEdit` объекта документа. Этот метод не доступен, когда FreeCAD в режиме консоли.

```
import FreeCADGui

FreeCADGui.ActiveDocument.setEdit("myObjectName",0)

```

Второй аргумент - это режим редактирования. В зависимости от выбранного значения будет открыт определенный диалог:

```
0 = Диалог "Расположение"
1 = Диалог "Преобразовать"
2 = Cutting
3 = Диалог "Установить цвета"

```

Для деактивации режима редактирования используйте метод `resetEdit` объекта document.

```
import FreeCADGui

FreeCADGui.ActiveDocument.resetEdit()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_Edit/ru&oldid=1496356>"