---
title: Команда "Создать"
---
|  |
| --- |
| Создать |
| Расположение в меню |
| Файл → Создать |
| Верстаки |
| All |
| Быстрые клавиши |
| Ctrl+N |
| Представлено в версии |
| - |
| См. также |
| [Открыть файл](/Std_Open/ru "Std Open/ru"), [Импортировать файл](/Std_Import/ru "Std Import/ru") |
|  |

## Описание

Команда **Создать** создаёт новый пустой документ и делает его активным.

## Применение

1. Существует несколько способов вызвать команду:
   * Нажатием кнопки ![](/images/Std_New.svg) Создать на панели инструментов.
   * Через пункт меню: **Файл → ![](/images/Std_New.svg) Создать**.
   * Используя комбинацию клавиш клавиатуры: Ctrl+N.

## Настройки

See also: [Preferences Editor](/Preferences_Editor "Preferences Editor").

* FreeCAD создает новый пустой документ при старте, при условии, что параметр **Инструменты → Редактор параметров... → BaseApp → Preferences → Document → CreateNewDoc** установлен как `true`. Данный параметр может быть изменен через [Редактор настроек](/Preferences_Editor/ru#Документ "Preferences Editor/ru").
* Некоторые свойства документа, например такие как: имена авторов, названия компаний и информация о лицензии могут быть предварительно указаны в [Редакторе настроек](/Preferences_Editor/ru#Документ "Preferences Editor/ru").

## Свойства

See also: [Property editor](/Property_editor "Property editor").

Большинство свойств также можно изменить в диалоговом окне ["Информация о проекте..." (команда Std ProjectInfo)](/Std_ProjectInfo/ru "Std ProjectInfo/ru").

### Data

Base

* Данные**Comment**: Может содержать комментарий.
* Данные**Company**: Название компании. *Может быть установлено предварительно*.
* Данные**Created By**: Инициалы автора создателя. *Может быть установлено предварительно*.
* Данные**Creation Date**: Автоматическая временная метка. *Нередактируемое значение*.
* Данные**File Name**: Полный путь к файлу. Поле будет пустым, если документ не был ещё сохранен. *Нередактируемое значение*.
* Данные**Id**: Не реализовано на данный момент.
* Данные**Label**: Название которое отображается в [Древе проекта](/Tree_view/ru "Tree view/ru"). По умолчанию используется имя документа.
* Данные**Last Modified By**: Инициалы автора внесшего правки. *Может быть установлено предварительно*.
* Данные**Last Modified Date**: Автоматическая временная метка (время последней правки). *Нередактируемое значение*.
* Данные**License**: Тип лицензии. *Может быть установлено предварительно*.
* Данные**License URL**: URL лицензии. *Может быть установлено предварительно*.
* Данные**Show Hidden**: Если параметр равен True, то элементы, которые были скрыты в [Древе проекта](/Tree_view/ru "Tree view/ru") все равно будут отображаться. Сокрытие элементов в дереве проекта может быть полезно при работе с большими моделями.
* Данные**Tip**: Не реализовано на данный момент.
* Данные**Tip Name**: Не реализовано на данный момент.
* Данные**Transient Dir**: Путь временной папки, используемой для восстановления данных. *Нередактируемое значение*.

## Программирование

*Смотрите так же:* [Основы составления скриптов в FreeCAD](/FreeCAD_Scripting_Basics/ru "FreeCAD Scripting Basics/ru").

Для создания нового документа используйте `newDocument([name], [hidden=False])` метод приложения FreeCAD. Название документа должно быть уникальным, что проверяется автоматически. Если имя не будет указано, документу будет присвоено название "Untitled". Если `hidden=True`, тогда созданный документ не будет отображаться в графическом интерфейсе и его вкладка так же не будет создана.

```
import FreeCAD
from pathlib import Path

# The folder and filename we will use:
fld = 'D:/testfiles/'
fnm = fld + 'test.FCStd'

# Make sure fld exists:
Path(fld).mkdir(parents=True, exist_ok=True)

doc = FreeCAD.newDocument()
doc.saveAs(fnm)

FreeCAD.closeDocument(doc.Name)

doc = FreeCAD.open(fnm)
doc.save()

FreeCAD.closeDocument(doc.Name)

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_New/ru&oldid=1448538>"