---
title: Part Sphere
---
|  |
| --- |
| Part Sphere |
| Menyplacering |
| Part → Primitives → Sphere |
| Arbetsbänkar |
| [Part](/Part_Workbench/sv "Part Workbench/sv") |
| Standard genväg |
| *Ingen* |
| Introducerad i version |
| - |
| Se även |
| [Part\_CreatePrimitives](/Part_CreatePrimitives/sv "Part CreatePrimitives/sv") |
|  |

## Description

The ![](/images/Part_Sphere.svg) **Part Sphere** command creates a parametric sphere solid. It is the result of revolving a circular arc profile around an axis. In the coordinate system defined by its Data**Placement** property, the center of the sphere is positioned at the origin, and its axis of revolution is the Z axis.

A Part Sphere can be truncated at the top and/or bottom by changing its Data**Angle1** and/or Data**Angle2** properties. It can be turned into a segment of a sphere by changing its Data**Angle3** property.

![](/images/Part_Sphere_Example.png)

## Usage

1. There are several ways to invoke the command:
   * Press the ![](/images/Part_Sphere.svg) [Sphere](/Part_Sphere "Part Sphere") button.
   * Select the **Part → Primitives → ![](/images/Part_Sphere.svg) Sphere** option from the menu.
2. The sphere is created.
3. Optionally change the dimensions and Data**Placement** of the sphere by doing one of the following:
   * Double-click the object in the [Tree view](/Tree_view "Tree view"):
     1. The **Geometric Primitives** task panel opens.
     2. Change one or more properties.
     3. The object is dynamically updated in the [3D view](/3D_view "3D view").
     4. Press the OK button.
   * Change the properties in the [Property editor](/Property_editor "Property editor").
   * Change the Data**Placement** with the ![](/images/Std_TransformManip.svg) [Std TransformManip](/Std_TransformManip "Std TransformManip") command.

## Example

![](/images/Part_Sphere_Scripting_Example.png)

Part Sphere from the scripting example

A Part Sphere object created with the [scripting example](#Scripting) below is shown here.

## Notes

* A Part Sphere can also be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. With that command you can specify the dimensions and placement at creation time.

## Properties

See also: [Property editor](/Property_editor "Property editor").

A Part Sphere object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Sphere

* Data**Radius** (`Length`): The radius of the sphere. The default is `5mm`.
* Data**Angle1** (`Angle`): The start angle of the circular arc profile of the sphere. Valid range: `-90° <= value <= 90°`. May not be equal to Data**Angle2**. The default is `-90°`.
* Data**Angle2** (`Angle`): The end angle of the circular arc profile of the sphere. Valid range: `-90° <= value <= 90°`. May not be equal to Data**Angle1**. The default is `90°`. If the total angle of the arc profile is smaller than `180°` the sphere will be truncated and have a flat face at the top and/or bottom.
* Data**Angle3** (`Angle`): The total angle of revolution of the sphere. Valid range: `0° < value <= 360°`. The default is `360°`. If it is smaller than `360°` the resulting solid will be a segment of a sphere.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Sphere can be created with the `addObject()` method of the document:

```
sphere = FreeCAD.ActiveDocument.addObject("Part::Sphere", "mySphere")

```

* Where `"mySphere"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

sphere = doc.addObject("Part::Sphere", "mySphere")
sphere.Radius = 20
sphere.Angle1 = -30
sphere.Angle2 = 45
sphere.Angle3 = 90
sphere.Placement = App.Placement(App.Vector(3, 9, 11), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Sphere/sv&oldid=1471770>"