---
title: Std Recalculer
---
|  |
| --- |
| Std Recalculer |
| Emplacement du menu |
| Édition → Recalculer |
| Ateliers |
| Tous |
| Raccourci par défaut |
| F5 |
| Introduit dans la version |
| - |
| Voir aussi |
| *Aucun* |
|  |

## Description

La commande **Std Recalculer** recalcule le document actif. La commande est désactivée si le document ne nécessite pas de recalcul.

## Utilisation

1. Il existe plusieurs façons de lancer la commande :
   * Appuyez sur le bouton ![](/images/Std_Refresh.svg) Recalculer.
   * Sélectionnez l'option **Édition → ![](/images/Std_Refresh.svg) Recalculer** du menu.
   * Utilisez le raccourci clavier : F5.

## Options

* Pour forcer un recalcul, sélectionnez le document ou un ou plusieurs objets dans la [vue en arborescence](/Tree_view/fr "Tree view/fr"), choisissez l'option **![](/images/Std_MarkToRecompute.svg) Marquer pour recalculer** dans le menu contextuel et lancez la commande.
* Pour les objets, mais pas pour les documents, vous pouvez également choisir **Marquer pour recalculer** dans le même menu contextuel.

## Remarques

* Pour une macro qui recalculera le document actif, voir : [Macro ForceRecompute](/Macro_ForceRecompute/fr "Macro ForceRecompute/fr").

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Pour recalculer un document, utilisez la méthode `recompute` de l'objet document.

```
import FreeCAD

doc = FreeCAD.newDocument()
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_Refresh/fr&oldid=1504338>"