---
title: Std Ajouter un document texte
---
|  |
| --- |
| Std Ajouter un document texte |
| Emplacement du menu |
| Outils → Ajouter un document texte |
| Ateliers |
| Tous |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| 0.19 |
| Voir aussi |
| [Draft Formes à partir de texte](/Draft_ShapeString/fr "Draft ShapeString/fr"), [Draft Texte](/Draft_Text/fr "Draft Text/fr") |
|  |

## Description

La commande **Std Ajouter un document texte** crée un objet capable de contenir du texte arbitraire. Cet élément peut être utilisé pour écrire des informations générales ou de la documentation sur le modèle.

## Utilisation

1. Sélectionnez l'option Outils → ![](/images/Std_TextDocument.svg) Ajouter un document texte du menu
2. Double-cliquez sur l'objet juste créé dans la [vue en arborescence](/Tree_view/fr "Tree view/fr") pour ouvrir un onglet dans lequel écrire du texte.
3. Ajoutez du texte.
4. Fermez l'onglet et enregistrez le fichier lorsque vous y êtes invité.

## Propriétés

### Vue

Editor

* Vue**Font Name** (`Font`) : un nom de police, par exemple, `Ubuntu Mono`.
* Vue**Font Size** (`Float`) : une taille de police en points, par exemple, `11`.
* Vue**Read Only** (`Bool`) : par défaut `false`. Mis à `true`, le texte ne peut pas être modifié tant que cette propriété n'est pas définie sur `false`.
* Vue**Syntax Highlighter** (`Enumeration`) : il est par défaut `None`. S'il est défini sur `Python`, il mettra en surbrillance le texte comme la [console Python](/Python_console/fr "Python console/fr").

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Voir [Part Feature](/Part_Feature/fr "Part Feature/fr") pour les informations générales sur l'ajout d'objets au document.

Un objet `App::TextDocument` est créé avec la méthode `addObject()` du document. Une fois qu'un TextDocument existe, ses informations textuelles sont stockées dans son attribut `Text`. Cet attribut peut être utilisé dans d'autres objets, par exemple, comme chaîne dans une ![](/images/Draft_ShapeString.svg) [Draft Forme à partir d'un texte](/Draft_ShapeString/fr "Draft ShapeString/fr").

```
import FreeCAD as App
import Draft

doc = App.newDocument()
obj = doc.addObject("App::TextDocument", "Text_document")
obj.Text = "textual information"
doc.recompute()

obj2 = Draft.makeShapeString(obj.Text, "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 10)
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_TextDocument/fr&oldid=1459543>"