---
title: Std Ajouter au document
---
|  |
| --- |
| Std Ajouter au document |
| Emplacement du menu |
| Fichier → Ajouter au document... |
| Ateliers |
| Tous |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| - |
| Voir aussi |
| *Aucun* |
|  |

## Description

La commande **Std Ajouter au document** ajoute le contenu d'un fichier FreeCAD dans le document actif.

## Utilisation

1. Sélectionnez l'option **Fichier → ![](/images/Std_MergeProjects.svg) Ajouter au document...** du menu.
2. Sélectionnez un fichier FreeCAD dans la fenêtre de dialogue.
3. Appuyez sur le bouton Ouvrir.

## Options

* Appuyez sur Échap ou sur le bouton Annuler pour annuler la commande.

## Remarques

* Un projet ne peut pas être fusionné avec lui-même, la sélection du fichier en cours n'est pas autorisée.
* FreeCAD changera automatiquement les noms internes et, selon les [préférences](/Preferences_Editor/fr#Document "Preferences Editor/fr"), les étiquettes des objets pour éviter les conflits de noms.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Pour fusionner un projet, utilisez la méthode `mergeProject` de l'objet document.

```
import FreeCAD

FreeCAD.ActiveDocument.mergeProject("Path_to_FCStd_project_file")

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_MergeProjects/fr&oldid=1534950>"