---
title: Std Tout afficher
---
|  |
| --- |
| Std Tout afficher |
| Emplacement du menu |
| Affichage → Vues standards‏‎ → Tout afficher |
| Ateliers |
| Tous |
| Raccourci par défaut |
| V F |
| Introduit dans la version |
| - |
| Voir aussi |
| [Std Affichage de la sélection](/Std_ViewFitSelection/fr "Std ViewFitSelection/fr") |
|  |

## Description

La commande **Std Tout afficher** effectue un zoom et un panoramique de la caméra afin que tous les objets visibles tiennent dans la [vue 3D](/3D_view/fr "3D view/fr") active.

## Utilisation

1. Il existe plusieurs façons de lancer la commande :
   * Appuyez sur le bouton ![](/images/Std_ViewFitAll.svg) Tout afficher.
   * Sélectionnez l'option **Affichage → Vues standards → ![](/images/Std_ViewFitAll.svg) Tout afficher** du menu.
   * Sélectionnez l'option **![](/images/Std_ViewFitAll.svg) Tout afficher** dans le menu contextuel de la [vue 3D](/3D_view/fr "3D view/fr").
   * Sélectionnez l'option **![](/images/Std_ViewFitAll.svg) Tout afficher** dans le menu mini-cube du [cube de navigation](/Navigation_Cube/fr "Navigation Cube/fr").
   * Utilisez le raccourci clavier : V puis F.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Utilisez la méthode `fitAll` de l'objet View pour effectuer un zoom sur tous les objets.

```
import FreeCADGui

view = FreeCADGui.ActiveDocument.ActiveView
view.fitAll()

```

Pour la vue active, la méthode `SendMsgToActiveView` de l'objet FreeCADGui peut également être utilisée.

```
import FreeCADGui

FreeCADGui.SendMsgToActiveView("ViewFit")

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_ViewFitAll/fr&oldid=1449905>"