---
title: Std Basculer la visibilité
---
|  |
| --- |
| Std Basculer la visibilité |
| Emplacement du menu |
| Affichage → Activer/désactiver la visibilité |
| Ateliers |
| Tous |
| Raccourci par défaut |
| Barre d'espace |
| Introduit dans la version |
| - |
| Voir aussi |
| [Std Afficher la sélection](/Std_ShowSelection/fr "Std ShowSelection/fr"), [Std Masquer la sélection](/Std_HideSelection/fr "Std HideSelection/fr"), [Std Basculer tous les objets](/Std_ToggleObjects/fr "Std ToggleObjects/fr"), [Std Afficher tous les objets](/Std_ShowObjects/fr "Std ShowObjects/fr"), [Std Masquer tous les objets](/Std_HideObjects/fr "Std HideObjects/fr") |
|  |

## Description

La commande **Std Basculer la visibilité** bascule la visibilité des objets dans la [vue 3D](/3D_view/fr "3D view/fr").

## Utilisation

1. Sélectionnez un ou plusieurs objets.
   * Les objets invisibles peuvent être sélectionnés dans la [vue en arborescence](/Tree_view/fr "Tree view/fr").
   * Soyez prudent lorsque vous utilisez Ctrl+A pour sélectionner tous les objets dans l'arborescence. Cela sélectionnera également les sous-éléments de [PartDesign Corps](/PartDesign_Body/fr "PartDesign Body/fr") et les objets utilisés par les [Part Opérations booléennes](/Part_Boolean/fr "Part Boolean/fr"). Dans la plupart des cas, ceux-ci doivent rester invisibles.
   * Les objets utilisés pour les [Part Opérations booléennes](/Part_Boolean/fr "Part Boolean/fr") sont également sélectionnés lorsque vous utilisez Ctrl+A dans une vue 3D.
2. Il existe plusieurs façons de lancer la commande :
   * Sélectionnez l'option **Affichage → Visibilité → ![](/images/Std_ToggleVisibility.svg) Activer/désactiver la visibilité** du menu.
   * Sélectionnez l'option **![](/images/Std_ToggleVisibility.svg) Activer/désactiver la visibilité** dans le menu contextuel de l'arborescence ou de la vue 3D.
   * Utilisez le raccourci clavier : Barre d'espace.

## Remarques

* Les objets invisibles sont affichés avec une étiquette grisée et une icône grisée dans la [vue en arborescence](/Tree_view/fr "Tree view/fr").
* Les objets imbriqués dans un [Std Part](/Std_Part/fr "Std Part/fr") ou un [Std Lien](/Std_LinkMake/fr "Std LinkMake/fr") vers un [Std Groupe](/Std_Group/fr "Std Group/fr"), ou un LinkGroup, et les [fonctions](/PartDesign_Feature/fr "PartDesign Feature/fr") d'un [PartDesign Corps](/PartDesign_Body/fr "PartDesign Body/fr") ne seront visibles dans les [vues 3D](/3D_view/fr "3D view/fr") que si leurs parents successifs sont également visibles. Cela signifie qu'une fonction dans un PartDesign Corps qui est imbriquée dans une pièce standard ne sera visible dans les vues 3D que si la fonction elle-même, le PartDesign Corps et la pièce standard sont tous visibles. Et si la partie standard est à son tour imbriquée dans une autre partie standard, alors ce dernier objet doit également être visible.
* Si la visibilité d'un [Std Groupe](/Std_Group/fr "Std Group/fr") (ou d'un objet dérivé de celui-ci tel qu'une [Arch Partie de bâtiment](/Arch_BuildingPart/fr "Arch BuildingPart/fr")) est modifiée, la visibilité de ses objets imbriqués changera en conséquence. Mais leur visibilité peut également être modifiée de manière indépendante.
* L'action ne peut être annulée avec [Std Annuler](/Std_Undo/fr "Std Undo/fr") que si le paramètre **AutoTransactionView** dans le [réglage fin](/Fine-tuning/fr "Fine-tuning/fr") est réglé à `true`.
* La visibilité d'un objet peut également être modifiée via sa propriété Données**Visibility** associée dans l'[éditeur de propriétés](/Property_editor/fr "Property editor/fr").

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Les méthodes `show` et `hide` d'un objet permettent de modifier sa visibilité. La propriété `Visibility` d'un objet peut également être modifiée directement.

```
import FreeCADGui

obj = FreeCADGui.ActiveDocument.myObjectName

if obj.Visibility == True:
    obj.hide()
else:
    obj.show()

# Alternatively:
obj.Visibility = not obj.Visibility

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_ToggleVisibility/fr&oldid=1453024>"