---
title: Std Nouveau
---
|  |
| --- |
| Std Nouveau |
| Emplacement du menu |
| Fichier → Nouveau |
| Ateliers |
| Tous |
| Raccourci par défaut |
| Ctrl+N |
| Introduit dans la version |
| - |
| Voir aussi |
| [Std Ouvrir](/Std_Open/fr "Std Open/fr"), [Std Importer](/Std_Import/fr "Std Import/fr") |
|  |

## Description

La commande **Std Nouveau** crée un nouveau document vide et en fait le document actif.

## Utilisation

1. Lancez la commande de plusieurs manières :
   * Appuyez sur le bouton ![](/images/Std_New.svg) Nouveau
2. \* Sélectionnez l'option **Fichier → ![](/images/Std_New.svg) Nouveau** du menu.
3. \* Utilisez le raccourci clavier : Ctrl+N.

## Préférences

Voir aussi : [Réglage des préférences](/Preferences_Editor/fr "Preferences Editor/fr").

* Par défaut, FreeCAD démarre sans nouveau document. Cochez l'option **Édition → Préférences... → Général → Document → Créer un nouveau document au démarrage** pour modifier ce comportement.
* Certaines propriétés du document : nom de l'auteur, nom de la société et informations de licence, peuvent être prédéfinies : **Édition → Préférences... → Général → Document → Création et licence**.

## Propriétés

Voir aussi : [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

La plupart des propriétés peuvent également être modifiées dans la boîte de dialogue de la commande [Std Informations sur le document](/Std_ProjectInfo/fr "Std ProjectInfo/fr").

### Données

Base

* Données**Comment** (`String`) : tout commentaire éventuel.
* Données**Company** (`String`) : nom de l'entreprise.
* Données**Created By** (`String`) : nom de l'auteur.
* Données**Creation Date** (`String`) : horodatage automatique (en lecture seule).
* Données**Nom du fichier** (`Chaîne`) : chemin complet du fichier. Blanc si le document n'a pas été enregistré (lecture seule).
* Données**Id** (`String`) : pas encore implémenté.
* Données**Label** (`String`) : le nom qui apparaîtra dans la [vue en arborescence](/Tree_view/fr "Tree view/fr"). Remplacé par le nom du document après réouverture.
* Données**Last Modified By** (`String`) : nom de l'auteur.
* Données**Last Modified Date** (`String`) : horodatage automatique (en lecture seule).
* Données**License** (`String`) : type de licence.
* Données**License URL** (`String`) : URL de la licence.
* Données (Hidden)**Material** (`Map`) : associé aux propriétés des matériaux.
* Données (Caché)**Meta** (`Map`) : associé à des méta-informations supplémentaires.
* Données**Show Hidden** (`Bool`) : si true, les éléments qui ont été cachés dans l'arborescence seront quand même affichés. Cacher des éléments dans l'arbre peut s'avérer utile lorsque l'on travaille sur des modèles de grande taille.
* Données**Tip** (`Link`) : pas encore implémenté.
* Données**Tip Name** (`String`) : pas encore implémenté.
* Données**Transient Dir** (`String`) : répertoire de transition utilisé pour les données de récupération (en lecture seule).
* Données (Hidden)**Uid** (`UUID`) : UUID du document (en lecture seule).
* Données**Unit System** (`Enumeration`) : système d'unité du document. La valeur initiale dépend du [système d'unités par défaut](/Preferences_Editor/fr#Général_2 "Preferences Editor/fr"). [introduit dans la version 1.0](/Release_notes_1.0/fr "Release notes 1.0/fr")

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Pour créer un nouveau document, utilisez la méthode `newDocument([name], [hidden=False])` de l'application FreeCAD. Le nom du document doit être unique, ce qui est vérifié automatiquement. Si aucun nom n'est fourni, le document sera nommé "Sans titre". Si `hidden=True` est utilisé, le nouveau document ne sera pas affiché dans l'interface graphique et aucun onglet n'apparaîtra pour ce document.

```
import FreeCAD
from pathlib import Path

# The folder and filename we will use:
fld = 'D:/testfiles/'
fnm = fld + 'test.FCStd'

# Make sure fld exists:
Path(fld).mkdir(parents=True, exist_ok=True)

doc = FreeCAD.newDocument()
doc.saveAs(fnm)

FreeCAD.closeDocument(doc.Name)

doc = FreeCAD.open(fnm)
doc.save()

FreeCAD.closeDocument(doc.Name)

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_New/fr&oldid=1449138>"