---
title: Draft Clona
---
|  |
| --- |
| Draft Clona |
| Posizione nel menu |
| Modifiche → Clona |
| Ambiente |
| [Draft](/Draft_Workbench/it "Draft Workbench/it") |
| Avvio veloce |
| C L |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Draft Scala](/Draft_Scale/it "Draft Scale/it") |
|  |

## Descrizione

Il comando ![](/images/Draft_Clone.svg) **Clona** crea copie collegate, cloni, degli oggetti selezionati. La forma di un clone è parametrica, si aggiornerà se il suo oggetto sorgente cambia. Ma un clone ha la propria posizione, rotazione e scala e le proprie  [Proprietà Vista](/Property_editor/it "Property editor/it"). Per gli oggetti [BIM](/BIM_Workbench/it "BIM Workbench/it") il comando crea un tipo speciale di clone: ​​un clone di Arch.

Il comando può essere utilizzato su oggetti 2D creati con [Draft](/Draft_Workbench/it "Draft Workbench/it") o [Sketcher](/Sketcher_Workbench/it "Sketcher Workbench/it"), ma anche su molti oggetti 3D come quelli creati con [Part](/Part_Workbench/it "Part Workbench/it"), [PartDesign](/PartDesign_Workbench/it "PartDesign Workbench/it") o [BIM](/BIM_Workbench/it "BIM Workbench/it"). I cloni di oggetti 2D possono essere utilizzati in [Corpi di PartDesign](/PartDesign_Body/it "PartDesign Body/it").

![](/images/Draft_Clone_example.jpg)

Clone accanto al suo oggetto sorgente

## Utilizzo

1. Opzionalmente selezionare uno o più oggetti.
2. Esistono diversi modi per invocare il comando:
   * Premere il pulsante ![](/images/Draft_Clone.svg) Clona.
   * Selezionare l'opzione **Modifiche → ![](/images/Draft_Clone.svg) Clona** dal menu.
   * Usare la scorciatoia da tastiera: C poi L.
3. Se non si ha ancora selezionato un oggetto: selezionare un oggetto nella [Vista 3D](/3D_view/it "3D view/it").

## Note

* Il ridimensionamento di un Draft Clone può essere modificato nell'[Editor proprietà](/Property_editor/it "Property editor/it") o, nella [disponibile dalla versione 1.1](/Release_notes_1.1/it "Release notes 1.1/it"), facendo doppio clic su di esso nella [Vista ad albero](/Tree_view/it "Tree view/it") e inserendo nuovi valori nel pannello delle azioni che si apre. Quest'ultima opzione è più efficiente.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto creato con il comando Draft Clone è derivato da un oggetto [Part Part2DObject](/Part_Part2DObject/it "Part Part2DObject/it"), un oggetto [Part Feature](/Part_Feature/it "Part Feature/it") o, se viene creato un Arch Clone, dal tipo di oggetto dell'oggetto sorgente. Eredita tutte le proprietà da quell'oggetto. Un clone derivato da uno dei primi due oggetti ha anche le seguenti proprietà aggiuntive:

### Dati

Draft

* Dati**Fuse** (`Bool`): specifica se le forme sovrapposte nel clone sono fuse o meno.
* Dati**Objects** (`LinkListGlobal`): specifica gli oggetti che vengono clonati.
* Dati**Scale** (`Vector`): specifica i fattori di scala X, Y e Z.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per creare un clone usa il metodo `make_clone` ([disponibile dalla versione 0.19](/Release_notes_0.19/it "Release notes 0.19/it")) del modulo Draft. Questo metodo sostituisce il metodo deprecato `clone`.

```
cloned_object = make_clone(obj, delta=None, forcedraft=False)

```

* `obj` contiene gli oggetti da clonare. È un singolo oggetto o un elenco di oggetti.
* `delta` è il vettore spostamento da applicare al clone.
* Se `forcedraft` è `False` e `obj` contiene un singolo [oggetto BIM](/BIM_Workbench/it "BIM Workbench/it") viene creato un Arch Clone. Imposta `forcedraft` su `True` per creare invece un Draft Clone.
* `cloned_object` viene restituito con l'oggetto clone.

Esempio:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

place = App.Placement(App.Vector(1000, 0, 0), App.Rotation())
polygon1 = Draft.make_polygon(3, 750)
polygon2 = Draft.make_polygon(5, 750, placement=place)

vector = App.Vector(2600, 500, 0)
cloned_object = Draft.clone([polygon1, polygon2], delta=vector)

cloned_object.Fuse = True

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Clone/it&oldid=1551100>"