---
title: Draft Unisci
---
|  |
| --- |
| Draft Unisci |
| Posizione nel menu |
| Modifiche → Unisci Modifica → Unisci |
| Ambiente |
| [Draft](/Draft_Workbench/it "Draft Workbench/it"), [BIM](/BIM_Workbench/it "BIM Workbench/it") |
| Avvio veloce |
| J O |
| Introdotto nella versione |
| 0.18 |
| Vedere anche |
| [Draft Dividi](/Draft_Split/it "Draft Split/it") |
|  |

## Descrizione

Il comando ![](/images/Draft_Join.svg) **Draft Unisci** unisce [Draft Linee](/Draft_Line/it "Draft Line/it") e [Draft Polilinee](/Draft_Wire/it "Draft Wire/it") in una singola polilinea. Questo comando è la controparte del comando [Draft Dividi](/Draft_Split/it "Draft Split/it").

## Utilizzo

1. I punti finali delle [Draft Linee](/Draft_Line/it "Draft Line/it") e/o [Draft Polilinee](/Draft_Wire/it "Draft Wire/it") da unire devono essere esattamente coincidenti. Se necessario, prima regolare i punti per assicurarsi che sia così.
2. Selezionare due o più [Linee](/Draft_Line/it "Draft Line/it") e/o [Polilinee](/Draft_Wire/it "Draft Wire/it").
3. Esistono diversi modi per invocare il comando:
   * Premere il pulsante ![](/images/Draft_Join.svg) Unisci.
   * [Draft](/Draft_Workbench/it "Draft Workbench/it"): Selezionare l'opzione **Modifiche → ![](/images/Draft_Join.svg) Unisci** dal menu.
   * [BIM](/BIM_Workbench/it "BIM Workbench/it"): Selezionare l'opzione **Modifica → ![](/images/Draft_Join.svg) Unisci** dal menu.
   * Usare la scorciatoia da tastiera: J quindi O.

## Note

* [Linee](/Draft_Line/it "Draft Line/it") e [Polilinee](/Draft_Wire/it "Draft Wire/it") possono anche essere unite con il comando [Draft Polilinea](/Draft_Wire/it "Draft Wire/it") o il comando [Promuovi](/Draft_Upgrade/it "Draft Upgrade/it").
* Per unire oggetti che non sono [Linee](/Draft_Line/it "Draft Line/it") o [Polilinee](/Draft_Wire/it "Draft Wire/it") si può provare ad utilizzare su di essi una o più volte i comandi [Promuovi](/Draft_Upgrade/it "Draft Upgrade/it") e/o [Declassa](/Draft_Downgrade/it "Draft Downgrade/it").

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per unire polilinee usare il metodo `join_wires` ([disponibile dalla versione 0.19](/Release_notes_0.19/it "Release notes 0.19/it")) del modulo Draft. Questo metodo sostituisce il metodo deprecato `joinWires`. Questo metodo restituisce `None`.

```
join_wires(wires)

```

* `wires` è un elenco di oggetti polilinea da unire.

Esempio:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(500, 0, 0)
p3 = App.Vector(500, 500, 0)
p4 = App.Vector(0, 500, 0)

wire1 = Draft.make_wire([p1, p2])
wire2 = Draft.make_wire([p2, p3])
wire3 = Draft.make_wire([p3, p4])
wire4 = Draft.make_wire([p4, p1])

Draft.join_wires([wire1, wire3, wire2, wire4])
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Join/it&oldid=1474255>"