---
title: Draft Dividi
---
|  |
| --- |
| Draft Dividi |
| Posizione nel menu |
| Modifiche → Dividi Modifica → Dividi |
| Ambiente |
| [Draft](/Draft_Workbench/it "Draft Workbench/it"), [BIM](/BIM_Workbench/it "BIM Workbench/it") |
| Avvio veloce |
| S P |
| Introdotto nella versione |
| 0.18 |
| Vedere anche |
| [Draft Unisci](/Draft_Join/it "Draft Join/it") |
|  |

## Descrizione

Il comando ![](/images/Draft_Split.svg) **Draft Dividi** divide una [Draft Linea](/Draft_Line/it "Draft Line/it") o [Draft Polilinea](/Draft_Wire/it "Draft Wire/it") in un punto o bordo specificato. Questo comando è la controparte del comando [Draft Unisci](/Draft_Join/it "Draft Join/it").

## Utilizzo

1. Esistono diversi modi per invocare il comando:
   * Premere il pulsante ![](/images/Draft_Split.svg) Dividi.
   * [Draft](/Draft_Workbench/it "Draft Workbench/it"): Selezionare l'opzione **Modifiche → ![](/images/Draft_Split.svg) Dividi** dal menu.
   * [BIM](/BIM_Workbench/it "BIM Workbench/it"): Selezionare l'opzione **Modifica → ![](/images/Draft_Split.svg) Dividi** dal menu.
   * Usare la scorciatoia da tastiera: S poi P.
2. Spostare il puntatore sul bordo corretto di una [Draft Linea](/Draft_Line/it "Draft Line/it") o [Draft Polilinea](/Draft_Wire/it "Draft Wire/it").
3. Il bordo viene evidenziato.
4. Effettuare una delle seguenti operazioni:
   * Se la polilinea è chiusa:
     + Scegliere un punto qualsiasi sul bordo.
     + Il bordo si stacca dalla polilinea e diventa una polilinea separata.
   * Se la polilinea è aperta:
     + Scegliere il punto corretto sul bordo. Vedere [Note](#Note).
     + La polilinea viene divisa nel punto selezionato.

## Note

* Se una polilinea aperta viene divisa e il punto cliccato non si trova esattamente sullo spigolo selezionato, il nuovo punto non sarà collineare con lo spigolo precedente. Usare un'opzione [Aggancia](/Draft_Snap/it "Draft Snap/it") appropriata per impedirlo.
* Per dividere oggetti che non sono [Draft Linee](/Draft_Line/it "Draft Line/it") o [Draft Polilinee](/Draft_Wire/it "Draft Wire/it") si può provare a usare [Promuovi](/Draft_Upgrade/it "Draft Upgrade/it") e/o [Declassa](/Draft_Downgrade/it "Draft Downgrade/it") su di essi.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per dividere una polilinea usare il metodo `split` del modulo Draft. Questo metodo restituisce `None`.

```
split(wire, newPoint, edgeIndex)

```

* `wire` l'oggetto polilinea da dividere.
* `newPoint` il punto in cui dovrebbe verificarsi la divisione.
* `edgeIndex` indice dello spigolo dove dovrebbe avvenire la divisione (in base 1).

Esempio:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(500, 0, 0)
p3 = App.Vector(250, 0, 0)

wire = Draft.make_wire([p1, p2])

Draft.split(wire, p3, 1)
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Split/it&oldid=1474325>"