---
title: Draft Serie circolare
---
|  |
| --- |
| Draft Serie circolare |
| Posizione nel menu |
| Modifiche → Strumenti serie → Serie circolare |
| Ambiente |
| [Draft](/Draft_Workbench/it "Draft Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| 0.19 |
| Vedere anche |
| [Draft Serie ortogonale](/Draft_OrthoArray/it "Draft OrthoArray/it"), [Draft Serie polare](/Draft_PolarArray/it "Draft PolarArray/it"), [Draft Serie su tracciato](/Draft_PathArray/it "Draft PathArray/it"), [Draft Serie di link su tracciato](/Draft_PathLinkArray/it "Draft PathLinkArray/it"), [Draft Serie su punti](/Draft_PointArray/it "Draft PointArray/it"), [Draft Serie di link su punti](/Draft_PointLinkArray/it "Draft PointLinkArray/it") |
|  |

## Descrizione

Il comando ![](/images/Draft_CircularArray.svg) **Serie circolare** crea una serie (array) da un oggetto selezionato posizionando copie lungo circonferenze concentriche. Il comando può facoltativamente creare una Serie di [Link](/App_Link/it "App Link/it"), che è più efficiente di una Serie normale.

Il comando può essere utilizzato su oggetti 2D creati con [Draft](/Draft_Workbench/it "Draft Workbench/it") o [Sketcher](/Sketcher_Workbench/it "Sketcher Workbench/it"), ma anche su molti oggetti 3D come quelli creati con gli ambienti [Part](/Part_Workbench/it "Part Workbench/it"), [PartDesign](/PartDesign_Workbench/it "PartDesign Workbench/it") o [BIM](/BIM_Workbench/it "BIM Workbench/it").

![](/images/Draft_CircularArray_example.png)

Serie circolare.

## Utilizzo

Vedere anche: [Aggancio](/Draft_Snap/it "Draft Snap/it").

1. Facoltativamente selezionare un oggetto.
2. Esistono diversi modi per invocare il comando:
   * Premere il pulsante ![](/images/Draft_CircularArray.svg) Serie circolare.
   * Selezionare l'opzione **Modifiche → Strumenti array → ![](/images/Draft_CircularArray.svg) Serie circolare** dal menu.
3. Si apre il pannello attività **Serie circolare**. Vedere [Opzioni](#Opzioni) per maggiori informazioni.
4. Se non si ha ancora selezionato un oggetto: selezionare un oggetto.
5. Immettere i parametri richiesti nel pannello delle attività.
6. Per completare il comando, eseguire una delle seguenti operazioni:
   * Scegliere un punto nella [Vista 3D](/3D_view/it "3D view/it") per il **Centro di rotazione**.
   * Premere Enter.
   * Premere il pulsante OK.

## Opzioni

* Immettere **Distanza radiale** per specificare la distanza tra gli strati circolari e tra il centro e il primo strato circolare.
* Immettere **Distanza tangenziale** per specificare la distanza tra gli elementi sullo stesso strato circolare. Deve essere maggiore di zero.
* Inserire il **Numero di strati circolari**. L'elemento al centro conta come uno strato. Deve essere almeno `2`. Il massimo che può essere inserito nel pannello delle attività è `99`, ma sono possibili valori più alti modificando la proprietà Dati**Number Circles** della serie.
* Inserire il valore **Simmetria**. Questo numero determina come sono distribuiti gli elementi. Un valore di `3`, ad esempio, genera un modello con tre segmenti di torta uguali a 120°. Valori più grandi per **Simmetria** e **Distanza tangenziale** comportano meno o addirittura nessun elemento sugli strati interni.
* Scegliere un punto nella [Vista 3D](/3D_view/it "3D view/it"), nota che anche questo terminerà il comando, oppure digitare le coordinate per **Centro di rotazione**. L'asse di rotazione della serie passerà per questo punto. Si consiglia di spostare il puntatore fuori dalla [ista 3D](/3D_view/it "3D view/it") prima di inserire le coordinate.
* Premere il pulsante **Resetta il punto** per reimpostare il **Centro di rotazione** all'origine.
* Se la casella di controllo **Fusione** è selezionata, gli elementi sovrapposti nella serie vengono fusi. Questo non funziona per le Serie di link.
* Se la casella **Serie di Link** è spuntata, viene creato una Serie di Link invece di una Serie normale. Una Serie di Link è più efficiente perché i suoi elementi sono oggetti [App Link](/App_Link/it "App Link/it").
* Premere Esc o il pulsante Annulla per annullare il comando.

## Note

See [Draft OrthoArray](/Draft_OrthoArray#Notes "Draft OrthoArray").

* L'asse di rotazione predefinito per la serie è l'asse Z positivo. Questo può essere cambiato modificando la sua proprietà Dati**Axis**.
* Una Serie circolare può essere trasformata in una [Serie ortogonale](/Draft_OrthoArray/it "Draft OrthoArray/it") o in una [Serie polare](/Draft_PolarArray/it "Draft PolarArray/it") modificandone la proprietà Dati**Array Type**.
* Una Serie di link non può essere trasformata in una serie normale o viceversa. Il tipo di serie deve essere deciso al momento della creazione.

## Proprietà

Vedere [Serie ortogonale](/Draft_OrthoArray/it#Propertà "Draft OrthoArray/it").

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per creare una serie circolare usare il metodo `make_array` ([disponibile dalla versione 0.19](/Release_notes_0.19/it "Release notes 0.19/it")) del modulo Draft. Questo metodo sostituisce il metodo deprecato `makeArray`. Il metodo `make_array` può creare [Serie ortognali](/Draft_OrthoArray/it "Draft OrthoArray/it"), [Serie polari](/Draft_PolarArray/it "Draft PolarArray/it") e Serie circolari. Per ogni tipo di serie sono disponibili uno o più wrapper.

Il metodo principale:

```
array = make_array(base_object, arg1, arg2, arg3, arg4=None, arg5=None, arg6=None, use_link=True)

```

Il wrapper per le Serie circolari è:

```
array = make_circular_array(base_object,
                            r_distance=100, tan_distance=50,
                            number=3, symmetry=1,
                            axis=App.Vector(0, 0, 1), center=App.Vector(0, 0, 0),
                            use_link=True)

```

* `base_object` è l'oggetto da disporre in serie. Può anche essere la `Label` (string) di un oggetto nel documento corrente.
* `r_distance` e `tan_distance` sono le distanze radiali e tangenziali tra gli elementi.
* `number` è il numero di strati circolari nel modello, l'oggetto originale conta come primo strato.
* `symmetry` è un numero intero utilizzato in alcuni calcoli che influenzano il modo in cui gli elementi sono distribuiti attorno alle circonferenze. I valori usuali vanno da 1 a 6. Valori più alti non sono consigliati e faranno scomparire gli elementi negli strati interni.
* `axis` e `center` sono vettori che descrivono la direzione dell'asse di rotazione e un punto attraverso il quale passa tale asse.
* Se `use_link` è `True` gli elementi creati sono [App Links](/App_Link/it "App Link/it") invece di normali copie.
* `array` viene restituito con l'oggetto serie creato.

Esempio:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

tri = Draft.make_polygon(3, 600)

array = Draft.make_circular_array(tri, 1800, 1200, 4, 1)
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_CircularArray/it&oldid=1557818>"