---
title: Draftː Polilinea in B-spline
---
|  |
| --- |
| Draft Polilinea in B-spline |
| Posizione nel menu |
| Modifiche → Polilinea in B-spline |
| Ambiente |
| [Draft](/Draft_Workbench/it "Draft Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Draft Polilinea](/Draft_Wire/it "Draft Wire/it"), [Draft BSpline](/Draft_BSpline/it "Draft BSpline/it") |
|  |

## Descrizione

Il comando ![](/images/Draft_WireToBSpline.svg) **Draft Polilinea in B-spline** converte [Draft Polilinee](/Draft_Wire/it "Draft Wire/it") in [Draft B-splines](/Draft_BSpline/it "Draft BSpline/it") e viceversa.

![](/images/Draft_Wire2BSpline_example.jpg)

Conversione di un Draft Polilinea in un Draft B-spline e di una Draft B-spline chiusa in una Draft Polilinea chiusa

## Utilizzo

1. Selezionare una [Draft Polilinea](/Draft_Wire/it "Draft Wire/it") o una [Draft B-spline](/Draft_BSpline/it "Draft BSpline/it").
2. Ci sono diversi modi per invocare il comando:
   * Premere il pulsante ![](/images/Draft_WireToBSpline.svg) Polilinea in B-spline.
   * Selezionare l'opzione **Modifiche → ![](/images/Draft_WireToBSpline.svg) Polilinea in B-spline** dal menu.
3. Viene creato un nuovo oggetto.

## Note

* Il comando potrebbe far risultare una [Draft Polilinea](/Draft_Wire/it "Draft Wire/it") o [Draft B-spline](/Draft_BSpline/it "Draft BSpline/it") autointersecante con una faccia. Tale oggetto non verrà visualizzato correttamente nella [Vista 3D](/3D_view/it "3D view/it"). La sua proprietà Dati**Make Face**, o la sua proprietà Dati**Closed**, deve essere impostata su `false`.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per convertire una Polilinea in una B-spline, o viceversa, passare la proprietà `Points` dell'oggetto sorgente al metodo `make_bspline`, o rispettivamente al metodo `make_wire`, del modulo Draft.

Esempio:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(1000, 1000, 0)
p2 = App.Vector(2000, 1000, 0)
p3 = App.Vector(2500, -1000, 0)
p4 = App.Vector(3500, -500, 0)

base_wire = Draft.make_wire([p1, p2, p3, p4])
base_spline = Draft.make_bspline([-p1, -1.3*p2, -1.2*p3, -2.1*p4])

points1 = base_wire.Points
spline_from_wire = Draft.make_bspline(points1)

points2 = base_spline.Points
wire_from_spline = Draft.make_wire(points2)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_WireToBSpline/it&oldid=1457464>"