---
title: Draft Arco per 3 punti
---
|  |
| --- |
| Draft Arco per 3 punti |
| Posizione nel menu |
| Drafting → Strumenti Arco → Arco per 3 punti 2D Drafting → Arco per 3 punti |
| Ambiente |
| [Draft](/Draft_Workbench/it "Draft Workbench/it"), [BIM](/BIM_Workbench/it "BIM Workbench/it") |
| Avvio veloce |
| A T |
| Introdotto nella versione |
| 0.19 |
| Vedere anche |
| [Draft Arco](/Draft_Arc/it "Draft Arc/it"), [Draft Cerchio](/Draft_Circle/it "Draft Circle/it") |
|  |

## Descrizione

Il comando ![](/images/Draft_Arc_3Points.svg) **Arco per 3 punti** crea un arco circolare sul [piano di lavoro](/Draft_SelectPlane/it "Draft SelectPlane/it") corrente passante per 3 punti che ne definiscono la circonferenza. Il centro e il raggio sono calcolati da questi punti.

Un Arco è infatti una [Circonferenza](/Draft_Circle/it "Draft Circle/it") con un Dati**First Angle** diverso dal suo Dati**Last Angle**.

![](/images/Draft_Arc_3Points_example.png)

Arco definito da tre punti giacenti sulla sua circonferenza

## Utilizzo

Vedere anche: [Barra di Draft](/Draft_Tray/it "Draft Tray/it"), [Aggancio](/Draft_Snap/it "Draft Snap/it") e [Vincolare](/Draft_Constrain/it "Draft Constrain/it").

1. Esistono diversi modi per invocare il comando:
   * Premere il pulsante ![](/images/Draft_Arc_3Points.svg) Arco per 3 punti.
   * [Draft](/Draft_Workbench/it "Draft Workbench/it"): Selezionare l'opzione **Drafting → Strumenti Arco → ![](/images/Draft_Arc_3Points.svg) Arco per 3 punti** dal menu.
   * [BIM](/BIM_Workbench/it "BIM Workbench/it"): Selezionare l'opzione **2D Drafting → ![](/images/Draft_Arc_3Points.svg) Arco per 3 punti** dal menu.
   * Usare la scorciatoia da tastiera: A poi T.
2. Si apre il pannello attività **Arco per 3 punti**. Vedi [Opzioni](#Options) per maggiori informazioni.
3. Scegliere il primo punto nella [Vista 3D](/3D_view/it "3D view/it"), oppure digitare le coordinate e premere il pulsante ![](/images/Draft_AddPoint.svg) Inserisci punto.
4. Scegliere il secondo punto nella [Vista 3D](/3D_view/it "3D view/it"), oppure digitare le coordinate e premere il pulsante ![](/images/Draft_AddPoint.svg) Inserisci punto.
5. Scegliere il terzo punto nella [Vista 3D](/3D_view/it "3D view/it"), oppure digitare le coordinate e premere il pulsante ![](/images/Draft_AddPoint.svg) Inserisci punto.

## Opzioni

È possibile modificare le scorciatoie da tastiera a carattere singolo disponibili nel pannello delle attività. Vedere [Preferenze di Draft](/Draft_Preferences/it "Draft Preferences/it"). Le scorciatoie qui menzionate sono le scorciatoie predefinite (per la versione 1.0).

* Per inserire manualmente le coordinate, inserire le componenti X, Y e Z e premere Enter dopo ognuna di esse. Oppure si può premere il pulsante ![](/images/Draft_AddPoint.svg) Inserisci punto quando ha i valori desiderati. Si consiglia di spostare il puntatore fuori dalla [Vista 3D](/3D_view/it "3D view/it") prima di inserire le coordinate.
* Premere R o fare clic sulla casella di controllo **Relativo** per attivare o disattivare la modalità relativa. Se la modalità relativa è attiva, le coordinate sono relative all'ultimo punto, se disponibile, altrimenti sono relative all'origine del sistema di coordinate.
* Premere G o fare clic sulla casella di controllo **Globale** per attivare o disattivare la modalità globale. Se la modalità globale è attiva, le coordinate sono relative al sistema di coordinate globale, altrimenti sono relative al sistema di coordinate [piano di lavoro](/Draft_SelectPlane/it "Draft SelectPlane/it").
* Premere N o fare clic sulla casella di controllo **Continua** per attivare o disattivare la modalità continua. Se la modalità continua è attiva, il comando si riavvierà al termine, consentendo di continuare a creare archi.
* Premere S per attivare o disattivare [Aggancia](/Draft_Snap "Draft Snap").
* Premere Esc o il pulsante Chiudi per interrompere il comando.

## Note

* Un Arco può essere modificato con il comando [Modifica](/Draft_Edit/it "Draft Edit/it").

## Preferenze

Vedere anche: [Impostare le preferenze](/Preferences_Editor/it "Preferences Editor/it") e [Preferenze per l'ambiente Draft](/Draft_Preferences/it "Draft Preferences/it").

* Se l'opzione **Modifica → Preferenze... → Draft → Generale → Crea primitive della parte se possibile** è selezionata, il comando creerà una [Funzione Part](/Part_Feature "Part Feature") non modificabile invece di un Draft Cerchio.

## Proprietà

Vedere [Draft Cerchio](/Draft_Circle/it#Propertietà "Draft Circle/it").

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per creare un Arco per 3 punti usare il metodo `make_arc_3points` del modulo Draft:

```
arc = make_arc_3points(points, placement=None, face=False, support=None, map_mode="Deactivated", primitive=False)

```

* Crea un oggetto `arc` da una data lista di `points`.
* Se viene fornito un `placement`, il centro dell'arco verrà spostato in questo punto. Per ulteriori informazioni vedere [Posizionamento](/Placement/it "Placement/it").
* Se `face` è `True`, l'arco formerà una faccia, cioè apparirà pieno.
* Se viene fornito un `support`, esso è un `LinkSubList`, vale a dire un elenco che indica un oggetto e un sottoelemento di quell'oggetto. Viene utilizzato in modo che l'oggetto appaia riferito a questo supporto.

:   Per esempio: `support=[(obj, ("Face1"))]`.

* Se viene fornito un `map_mode`, è una stringa che definisce un tipo di mappatura, ad esempio:`map_mode='FlatFace'`, `map_mode='ThreePointsPlane'`, etc. Per ulteriori informazioni vedere [Part Associazione](/Part_EditAttachment/it "Part EditAttachment/it").
* Se `primitive` è `True`, l'arco creato sarà un semplice [Part Feature](/Part_Feature/it "Part Feature/it"), e non un oggetto Draft complesso.

Esempio:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

points = [App.Vector(0, 0, 0),
          App.Vector(5, 10, 0),
          App.Vector(10, 0, 0)]

arc = Draft.make_arc_3points(points)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Arc_3Points/it&oldid=1513794>"