---
title: Draft Promuovi
---
|  |
| --- |
| Draft Promuovi |
| Posizione nel menu |
| Modifiche → Promuovi Modifica → Promuovi |
| Ambiente |
| [Draft](/Draft_Workbench/it "Draft Workbench/it"), [BIM](/BIM_Workbench/it "BIM Workbench/it") |
| Avvio veloce |
| U P |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Draft Declassa](/Draft_Downgrade/it "Draft Downgrade/it") |
|  |

## Descrizione

Il comando ![](/images/Draft_Upgrade.svg) **Draft Promuovi** promuove gli oggetti selezionati. Il risultato dipende dal numero di oggetti selezionati e dal loro tipo. Il comando può ad esempio fondere elementi e creare facce. Vale la pena provare ad aggiornare più volte una selezione per vedere se è possibile ottenere un risultato migliore. Vedere l'esempio nell'immagine. Si noti che non tutti gli oggetti possono essere aggiornati. Questo comando è la controparte del comando [Draft Declassa](/Draft_Downgrade/it "Draft Downgrade/it").

![](/images/Draft_Upgrade_example.jpg)

Una polilinea aperta non modificabile viene aggiornata ad una polilinea chiusa e quindi ad una faccia. Anche un contorno quadrato chiuso non modificabile viene aggiornato ad una faccia. Le due facce vengono quindi aggiornate per creare un composto, che viene infine aggiornato ad una singola Polilinea modificabile.

## Utilizzo

1. Opzionalmente selezionare uno o più oggetti.
2. Esistono diversi modi per invocare il comando:
   * Premere il pulsante ![](/images/Draft_Upgrade.svg) Promuovi.
   * [Draft](/Draft_Workbench/it "Draft Workbench/it"): Selezionare l'opzione **Modifica → ![](/images/Draft_Upgrade.svg) Promuovi** dal menu.
   * [BIM](/BIM_Workbench/it "BIM Workbench/it"): Selezionare l'opzione **Modifica → ![](/images/Draft_Upgrade.svg) Promuovi** dal menu.
   * Usare la scorciatoia da tastiera: U poi P.
3. Se non si ha ancora selezionato un oggetto: selezionare un oggetto nella [Vista 3D](/3D_view/it "3D view/it").

## Note

* [Linee](/Draft_Line/it "Draft Line/it") e [Polilinee](/Draft_Wire/it "Draft Wire/it") possono essere unite con questo comando, ma anche con il comando [Unisci](/Draft_Join/it "Draft Join/it") o il comando [Polilinea](/Draft_Wire/it "Draft Wire/it").

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per promuovere gli oggetti usare il metodo `upgrade` del modulo Draft.

```
upgrade_list = upgrade(objects, delete=False, force=None)

```

* `objects` contiene gli oggetti da promuovere. È un singolo oggetto o un elenco di oggetti.
* Se `delete` è `True` gli oggetti di origine vengono eliminati.
* `force` forza un certo modo di promozione chiamando una specifica funzione interna. Può essere: `"makeCompound"`, `"closeGroupWires"`, `"makeSolid"`, `"closeWire"`, `"turnToParts "`, `"makeFusion"`, `"makeShell"`, `"makeFaces"`, `"draftify"`, `"joinFaces "`, `"makeSketchFace"`, `"makeWires"` o `"turnToLine"`.
* Viene restituito `upgrade_list`. È un elenco contenente due elenchi: un elenco di nuovi oggetti e un elenco di oggetti da eliminare. Se `delete` è `True` la seconda lista è vuota.

Esempio:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

circle = Draft.make_circle(1000)
rectangle = Draft.make_rectangle(2000, 800)
doc.recompute()

add_list1, delete_list1 = Draft.upgrade([circle, rectangle], delete=False)

line1 = Draft.make_line(App.Vector(2000, 0, 0), App.Vector(2500, 1500, 0))
line2 = Draft.make_line(App.Vector(2500, 1500, 0), App.Vector(3000, -1000, 0))
doc.recompute()

add_list2, delete_list2 = Draft.upgrade([line1, line2], delete=False)

simple_wire = add_list2[0]
add_list3, delete_list3 = Draft.upgrade(simple_wire, delete=False)

closed_wire = add_list3[0]
add_list4, delete_list4 = Draft.upgrade(closed_wire, delete=False)

face = add_list4[0]
add_list5, delete_list5 = Draft.upgrade(face, delete=False)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Upgrade/it&oldid=1474317>"