---
title: Draft Linea, segmento
---
|  |
| --- |
| Draft Linea |
| Posizione nel menu |
| Drafting → Linea 2D Drafting → Linea |
| Ambiente |
| [Draft](/Draft_Workbench/it "Draft Workbench/it"), [BIM](/BIM_Workbench/it "BIM Workbench/it") |
| Avvio veloce |
| L I |
| Introdotto nella versione |
| 0.7 |
| Vedere anche |
| [Draft Polilinea](/Draft_Wire/it "Draft Wire/it") |
|  |

## Descrizione

Il comando ![](/images/Draft_Line.svg) **Draft Linea** crea una linea dritta.

Una Draft Linea è di fatto una [Polilinea](/Draft_Wire/it "Draft Wire/it") con solo due punti.

![](/images/Draft_Line_example.jpg)

Linea definita da due punti

## Utilizzo

Vedere anche: [Barra di Draft](/Draft_Tray/it "Draft Tray/it"), [Aggancio](/Draft_Snap/it "Draft Snap/it") e [Vincolare](/Draft_Constrain/it "Draft Constrain/it").

1. Esistono diversi modi per invocare il comando:
   * Premere il pulsante ![](/images/Draft_Line.svg) Linea.
   * [Draft](/Draft_Workbench/it "Draft Workbench/it"): Selezionare l'opzione **Drafting → ![](/images/Draft_Line.svg) Linea** dal menu.
   * [BIM](/BIM_Workbench/it "BIM Workbench/it"): Selezionare l'opzione **2D Drafting → ![](/images/Draft_Line.svg) Linea** dal menu.
   * Usare la scorciatoia da tastiera: L poi I.
2. Si apre il pannello attività **Linea**. Vedere [Opzioni](#Options) per maggiori informazioni.
3. Scegliere il primo punto nella [Vista 3D](/3D_view/it "3D view/it"), oppure digitare le coordinate e premere il pulsante ![](/images/Draft_AddPoint.svg) Inserisci punto.
4. Scegliere il secondo punto nella [Vista 3D](/3D_view/it "3D view/it"), oppure digitare le coordinate e premere il pulsante ![](/images/Draft_AddPoint.svg) Inserisci punto.

## Opzioni

È possibile modificare le scorciatoie da tastiera a carattere singolo disponibili nel pannello delle attività. Vedere [Preferenze di Draft](/Draft_Preferences/it "Draft Preferences/it"). Le scorciatoie qui menzionate sono le scorciatoie predefinite (per la versione 1.0).

* Per inserire manualmente le coordinate, inserire le componenti X, Y e Z e premere Enter dopo ognuna di esse. Oppure è possibile premere il pulsante ![](/images/Draft_AddPoint.svg) Inserisci punto quando si hanno i valori desiderati. Si consiglia di spostare il puntatore fuori dalla [Vista 3D](/3D_view/it "3D view/it") prima di inserire le coordinate.
* Per usare le coordinate polari inserire un valore per **Lunghezza** e un valore per **Anglo**, e premere Enter dopo ciascuno.
* Selezionare la casella **Anglo** per vincolare il puntatore all'angolo specificato.
* Premere L per cambiare il focus dalla casella di input **X** alla casella di input **Lunghezza** e viceversa. A seconda della casella di input che riceve il focus, la casella di controllo **Anglo** è selezionata o deselezionata.
* Premere R o fare clic sulla casella di controllo **Relativo** per attivare o disattivare la modalità relativa. Se la modalità relativa è attiva, le coordinate del secondo punto sono relative al primo punto, altrimenti sono relative all'origine del sistema di coordinate.
* Premere G o fare clic sulla casella di controllo **Globale** per attivare o disattivare la modalità globale. Se la modalità globale è attiva, le coordinate sono relative al sistema di coordinate globale, altrimenti sono relative al sistema di coordinate del [piano di lavoro](/Draft_SelectPlane/it "Draft SelectPlane/it").
* Premere N o fare clic sulla casella di controllo **Continua** per attivare o disattivare la modalità continua. Se la modalità continua è attiva, il comando verrà riavviato al termine, consentendo di continuare a creare linee.
* Premere S per attivare o disattivare l'[Aggancio](/Draft_Snap/it "Draft Snap/it").
* Premere Esc o il pulsante Chiudi per interrompere il comando.

## Note

* Una linea può essere modificata con il comando [Draft Modifica](/Draft_Edit/it "Draft Edit/it").
* Linee e [Polilinee](/Draft_Wire/it "Draft Wire/it") possono essere unite con il comando [Polilinea](/Draft_Wire/it "Draft Wire/it"), con il comando [Unisci](/Draft_Join/it "Draft Join/it") o il comando [Promuovi](/Draft_Upgrade/it "Draft Upgrade/it").

## Preferenze

Vedere anche: [Impostare le preferenze](/Preferences_Editor/it "Preferences Editor/it") e [Preferenze per l'ambiente Draft](/Draft_Preferences/it "Draft Preferences/it").

* Per cambiare il focus iniziale del pannello delle attività nella casella di input **Lunghezza**: **Modifica → Preferenze... → Draft → Generale → Imposta il focus sulla Lunghezza invece che sulla coordinata X**. Tenere presente che si deve spostare il puntatore nella [Vista 3D](/3D_view/it "3D view/it") affinché la modifica abbia effetto.
* Se l'opzione **Modifica → Preferenze... → Draft → Generale → Crea primitive della parte se possibile** è selezionata, il comando creerà una [Part Linea](/Part_Line/it "Part Line/it") invece di una Draft Linea.

## Proprietà

Vedere [Polilinea](/Draft_Wire#Proprietà/it "Draft Wire").

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per creare una Draft Linea usare il metodo `make_line` ([introduced in 0.19](/Release_notes_0.19 "Release notes 0.19")) del modulo Draft. Questo metodo sostituisce il metodo deprecato `makeLine`.

```
line = make_line(p1, p2)
line = make_line(LineSegment)
line = make_line(Shape)

```

* Crea un oggetto `Line` tra i punti `p1` e `p2`, ciascuno definito dal suo `FreeCAD.Vector`, con unità in millimetri.
* Crea un oggetto `Line` da un `Part.LineSegment`.
* Crea un oggetto `Line` dal primo vertice all'ultimo vertice della data `Shape`.

Esempio:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(1000, 500, 0)
p3 = App.Vector(-250, -500, 0)
p4 = App.Vector(500, 1000, 0)

line1 = Draft.make_line(p1, p2)
line2 = Draft.make_line(p3, p4)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Line/it&oldid=1513741>"