---
title: Draftː Offset
---
|  |
| --- |
| Draft Offset |
| Posizione nel menu |
| Modifiche → Offset Modifica → Offset |
| Ambiente |
| [Draft](/Draft_Workbench/it "Draft Workbench/it"), [BIM](/BIM_Workbench/it "BIM Workbench/it") |
| Avvio veloce |
| O S |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Part Offset 2D](/Part_Offset2D/it "Part Offset2D/it") |
|  |

## Descrizione

Il comando ![](/images/Draft_Offset.svg) **Offset** sposta ogni segmento di un oggetto selezionato ad una determinata distanza, o crea una copia traslata dell'oggetto selezionato.

![](/images/Draft_Offset_example.jpg)

Offset di una Polilinea

## Utilizzo

Vedere anche: [Aggancio](/Draft_Snap/it "Draft Snap/it") e [Vincolare](/Draft_Constrain/it "Draft Constrain/it").

1. Facoltativamente selezionare un oggetto. L'oggetto deve trovarsi sul [piano di lavoro](/Draft_SelectPlane/it "Draft SelectPlane/it").
2. Esistono diversi modi per invocare il comando:
   * Premere il pulsante ![](/images/Draft_Offset.svg) Offset.
   * [Draft](/Draft_Workbench/it "Draft Workbench/it"): Selezionare l'opzione **Modifiche → ![](/images/Draft_Offset.svg) Offset** dal menu.
   * [BIM](/BIM_Workbench/it "BIM Workbench/it"): Selezionare l'opzione **Modifica → ![](/images/Draft_Offset.svg) Offset** dal menu.
   * Usare la scorciatoia da tastiera: O poi S.
3. Se non si ha ancora selezionato un oggetto: selezionare un oggetto nella [Vista 3D](/3D_view/it "3D view/it").
4. Si apre il pannello attività **Offset**. Vedere [Opzioni](#Opzioni) per maggiori informazioni.
5. Per definire la distanza di offset, eseguire una delle seguenti operazioni:
   * Scegliere un punto nella [Vista 3D](/3D_view/it "3D view/it").
   * Inserire un valore numerico:
     1. Assicurarsi che il puntatore si trovi sul lato corretto dell'oggetto nella [Vista 3D](/3D_view/it "3D view/it").
     2. Non spostare il puntatore fuori dalla [Vista 3D](/3D_view/it "3D view/it").
     3. Inserire una **Distanza**.
     4. Premere Enter per terminare il comando.

## Opzioni

È possibile modificare le scorciatoie da tastiera a carattere singolo disponibili nel pannello delle attività. Vedere [Preferenze di Draft](/Draft_Preferences/it "Draft Preferences/it"). Le scorciatoie qui menzionate sono le scorciatoie predefinite (per la versione 1.0).

* Se la casella di controllo **Offset in OCC** è selezionata, viene utilizzato uno stile di offset speciale: le [Polilinee](/Draft_Wire/it "Draft Wire/it") aperte sono sfalsate su entrambi i lati e i nuovi bordi sono collegati con angoli arrotondati. Questo funziona solo per oggetti planari con almeno due spigoli. Si noti che con questo stile viene creato un nuovo oggetto non parametrico e, se la modalità di copia è disattivata, l'oggetto originale viene eliminato.
* Premere C o fare clic sulla casella di controllo **Copia** per attivare o disattivare la modalità di copia. Se la modalità copia è attiva, il comando creerà una copia sfalsata invece di sfalsare l'oggetto originale.
* Tenendo premuto Alt prima di selezionare i punti nella [Vista 3D](/3D_view/it "3D view/it") si attiverà anche la modalità di copia. Mentre si tiene premuto Alt è possibile selezionare più punti di offset. Rilasciare Alt per terminare il comando e vedere le copie create.
* Tenere premuto Maiusc per mantenere la distanza di offset collegata al segmento corrente.
* Premere S per attivare o disattivare [Aggancia](/Draft_Snap/it "Draft Snap/it").
* Premere Esc o il pulsante Chiudi per interrompere il comando.

## Note

* Per creare una versione offset di una [BSpline](/Draft_BSpline/it "Draft BSpline/it") i suoi punti vengono sfalsati singolarmente e dai nuovi punti viene calcolata una nuova spline. Questa nuova spline non è parallela alla spline originale. Per un esatto offset parallelo di una [BSpline](/Draft_BSpline/it "Draft BSpline/it") si dovrebbe utilizzare il comando [Part Offset2D](/Part_Offset2D/it "Part Offset2D/it").
* Il comando Draft Offset non può gestire [BezCurves](/Draft_BezCurve/it "Draft BezCurve/it"). Utilizzare invece il comando [Part Offset2D](/Part_Offset2D/it "Part Offset2D/it").

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per sfalsare gli oggetti usare il metodo `offset` del modulo Draft. Il metodo può gestire solo [Polilinee](/Draft_Wire/it "Draft Wire/it"), [Cerchi](/Draft_Circle/it "Draft Circle/it"), [Rettangoli](/Draft_Rectangle/it "Draft Rectangle/it"),  [Poligoni](/Draft_Polygon/it "Draft Polygon/it") e [BSplines](/Draft_BSpline/it "Draft BSpline/it").

```
offset_obj = offset(obj, delta, copy=False, bind=False, sym=False, occ=False)

```

* `obj` è l'oggetto da sfalsare.
* `delta` contiene le informazioni sull'offset:
  + Per [Polilinee](/Draft_Wire/it "Draft Wire/it"), [Rettangoli](/Draft_Rectangle/it "Draft Rectangle/it") e [Poligoni](/Draft_Polygon/it "Draft Polygon/it") è un vettore di offset che deve essere perpendicolare al primo segmento dell'oggetto.
  + Per [Cerchi](/Draft_Circle/it "Draft Circle/it") è il nuovo raggio.
  + Per [BSplines](/Draft_BSpline/it "Draft BSpline/it") è un elenco di nuovi punti.
* Se `copy` è `True` l'oggetto originale viene mantenuto e viene creato un nuovo oggetto.
* Se `bind` è `True` viene creata una faccia collegando la forma dell'oggetto originale e la forma del suo offset. Funziona solo per [Polilinee](/Draft_Wire/it "Draft Wire/it").
* Se `sym` è `True`, e anche `bind` è `True`, l'offset viene eseguito su entrambi i lati dell'oggetto originale, la larghezza totale è la lunghezza del vettore dato. Funziona solo per [Polilinee](/Draft_Wire/it "Draft Wire/it").
* Se `occ` è `True` viene utilizzato l'offset in stile OCC. Vedere [Opzioni](#Opzioni). Se `occ` è `True` gli argomenti `bind` e `sym` vengono ignorati.

Esempio:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(1500, 2000, 0)
p3 = App.Vector(4000, 0, 0)

wire = Draft.make_wire([p1, p2, p3])
doc.recompute()

vector = App.Vector(-200, 150, 0)
offset1 = Draft.offset(wire, vector, copy=True, bind=True, sym=True)
offset2 = Draft.offset(wire, 3*vector, copy=True)
offset3 = Draft.offset(wire, 6*vector, copy=True)
offset4 = Draft.offset(wire, 9*vector, copy=True)
offset5 = Draft.offset(wire, 1.5*vector, copy=True, occ=True)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Offset/it&oldid=1475209>"