---
title: Draft Serie polare
---
|  |
| --- |
| Draft Serie polare |
| Posizione nel menu |
| Modifiche → Strumenti serie → Serie polare Modifiche → Serie polare |
| Ambiente |
| [Draft](/Draft_Workbench/it "Draft Workbench/it"), [BIM](/BIM_Workbench/it "BIM Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| 0.19 |
| Vedere anche |
| [Draft Serie ortogonale](/Draft_OrthoArray/it "Draft OrthoArray/it"), [Draft Serie circolare](/Draft_CircularArray/it "Draft CircularArray/it"), [Draft Serie su tracciato](/Draft_PathArray/it "Draft PathArray/it"), [Draft Serie di link su tracciato](/Draft_PathLinkArray/it "Draft PathLinkArray/it"), [Draft Serie su punti](/Draft_PointArray/it "Draft PointArray/it"), [Draft Serie di link su punti](/Draft_PointLinkArray/it "Draft PointLinkArray/it") |
|  |

## Descrizione

Il comando ![](/images/Draft_PolarArray.svg) **Serie polare** crea una serie (array) da un oggetto selezionato posizionando copie lungo una circonferenza. Il comando può facoltativamente creare una Serie di [Link](/App_Link "App Link"), che è più efficiente di una normale Serie.

Il comando può essere utilizzato su oggetti 2D creati con [Draft](/Draft_Workbench/it "Draft Workbench/it") o [Sketcher](/Sketcher_Workbench/it "Sketcher Workbench/it"), ma anche su molti oggetti 3D come quelli creati con gli ambienti [Part](/Part_Workbench/it "Part Workbench/it"), [PartDesign](/PartDesign_Workbench/it "PartDesign Workbench/it") o [BIM](/BIM_Workbench/it "BIM Workbench/it").

![](/images/Draft_PolarArray_example.png)

Serie polare

## Utilizzo

Vedere anche: [Aggancio](/Draft_Snap/it "Draft Snap/it").

1. Facoltativamente selezionare un oggetto.
2. Esistono diversi modi per invocare il comando:
   * Premere il pulsante ![](/images/Draft_PolarArray.svg) Serie polare.
   * [Draft](/Draft_Workbench/it "Draft Workbench/it"): Selezionare l'opzione **Modifiche → Strumenti serie → ![](/images/Draft_PolarArray.svg) Serie polare** dal menu.
   * [BIM](/BIM_Workbench/it "BIM Workbench/it"): Selezionare l'opzione **Modifica → ![](/images/Draft_PolarArray.svg) Serie polare** dal menu.
3. Si apre il pannello attività **Serie polare**. Vedere [Opzioni](#Opzioni) per maggiori informazioni.
4. Se non si ha ancora selezionato un oggetto: selezionare un oggetto.
5. Immettere i parametri richiesti nel pannello delle attività.
6. Per completare il comando, eseguire una delle seguenti operazioni:
   * Scegliere un punto nella [Vista 3D](/3D_view/it "3D view/it") per il **Centro di rotazione**.
   * Premere Enter.
   * Premere il pulsante OK.

## Opzioni

* Immettere **Angolo polare** per specificare l'angolo totale della serie. L'angolo è positivo in senso antiorario.
* Inserire il **Numero di elementi**. Deve essere almeno `2`. Il massimo che può essere inserito nel pannello delle attività è `99`, ma sono possibili valori più alti modificando la proprietà Dati**Number Polar** della serie.
* Scegliere un punto nella [Vista 3D](/3D_view/it "3D view/it"), notare che anche questo terminerà il comando, oppure digitare le coordinate per **Centro di rotazione**. L'asse di rotazione della serie passerà per questo punto. Si consiglia di spostare il puntatore fuori dalla [Vista 3D](/3D_view/it "3D view/it") prima di inserire le coordinate.
* Premere il pulsante **Resetta il punto** per reimpostare il **Centro di rotazione** all'origine.
* Se la casella di controllo **Fuse** è selezionata, gli elementi sovrapposti nella serie vengono fusi. Questo non funziona per le serie di link.
* Se la casella **Serie di link** è spuntata, viene creato una Serie di link invece di una normale serie. Una Serie di Link è più efficiente perché i suoi elementi sono oggetti [App Link](/App_Link/it "App Link/it").
* Premiere Esc o il pulsante Annulla per interrompere il comando.

## Note

See [Draft OrthoArray](/Draft_OrthoArray#Notes "Draft OrthoArray").

* L'asse di rotazione predefinito per la serie è l'asse Z positivo. Questo può essere cambiato modificando la sua proprietà Dati**Axis**.
* Una Serie polare può essere trasformata in una [Serie ortogonale](/Draft_OrthoArray/it "Draft OrthoArray/it") o in una [Serie circolare](/Draft_CircularArray/it "Draft CircularArray/it") modificandone la proprietà Dati**Array Type**.
* Una Serie di link non può essere trasformata in una serie normale o viceversa. Il tipo di serie deve essere deciso al momento della creazione.

## Proprietà

Vedere [Serie ortogonale](/Draft_OrthoArray/it#Propertà "Draft OrthoArray/it").

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

### Serie parametrica

Per creare una serie polare parametrica usare il metodo `make_array` ([disponibile dalla versione 0.19](/Release_notes_0.19/it "Release notes 0.19/it")) del modulo Draft. Questo metodo sostituisce il metodo deprecato `makeArray`. Il metodo `make_array` può creare [Serie ortogonali](/Draft_OrthoArray/it "Draft OrthoArray/it"), Serie polari e [Serie circolari](/Draft_CircularArray/it "Draft CircularArray/it"). Per ogni tipo di serie sono disponibili uno o più wrapper.

Il metodo principale:

```
array = make_array(base_object, arg1, arg2, arg3, arg4=None, arg5=None, arg6=None, use_link=True)

```

Il wrapper per le Serie polari è:

```
array = make_polar_array(base_object,
                         number=5, angle=360, center=App.Vector(0, 0, 0),
                         use_link=True)

```

* `base_object` è l'oggetto da disporre in serie. Può anche essere la `Label` (string) di un oggetto nel documento corrente.
* `number` è il numero di elementi nel modello, incluso l'oggetto originale.
* `angle` è l'angolo dell'arco polare in gradi.
* `center` è il vettore che definisce il centro del motivo.
* Se `use_link` è `True` gli elementi creati sono [App Links](/App_Link/it "App Link/it") invece di normali copie.
* `array` viene restituito con l'oggetto serie creato.

Esempio:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

tri = Draft.make_polygon(3, 600)
center = App.Vector(-1600, 0, 0)

array = Draft.make_polar_array(tri, 8, 270, center)
doc.recompute()

```

### Serie non parametrica

Per creare una serie polare non parametrica usare il metodo `array` del modulo Draft. Questo metodo restituisce `None`.

```
array(objectslist, center, angle, number)

```

Esempio:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

tri = Draft.make_polygon(3, 600)
center = App.Vector(-1600, 0, 0)

Draft.array(tri, center, 270, 8)
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_PolarArray/it&oldid=1557804>"