---
title: Draft Arco
---
|  |
| --- |
| Draft Arco |
| Posizione nel menu |
| Drafting → Strumenti Arco → Arco 2D Drafting → Arco |
| Ambiente |
| [Draft](/Draft_Workbench/it "Draft Workbench/it"), [BIM](/BIM_Workbench/it "BIM Workbench/it") |
| Avvio veloce |
| A R |
| Introdotto nella versione |
| 0.7 |
| Vedere anche |
| [Draft Arco da 3 punti](/Draft_Arc_3Points/it "Draft Arc 3Points/it"), [Draft Cerchio](/Draft_Circle/it "Draft Circle/it") |
|  |

## Descrizione

Il comando ![](/images/Draft_Arc.svg) **Arco** crea un arco circolare nel [piano di lavoro](/Draft_SelectPlane/it "Draft SelectPlane/it") corrente da un centro, un raggio, un angolo iniziale e un angolo di apertura . Il raggio e gli angoli possono essere definiti selezionando i punti.

Un Arco è infatti una [Circonferenza](/Draft_Circle/it "Draft Circle/it") con un Dati**First Angle** diverso dal suo Dati**Last Angle**.

![](/images/Draft_Arc_example.jpg)

Arco definito da quattro punti: centro, raggio, punto iniziale dell'arco e punto finale dell'arco

## Utilizzo

Vedere anche: [Barra di Draft](/Draft_Tray/it "Draft Tray/it"), [Aggancio](/Draft_Snap/it "Draft Snap/it") e [Vincolare](/Draft_Constrain/it "Draft Constrain/it").

1. Esistono diversi modi per invocare il comando:
   * Premere il pulsante ![](/images/Draft_Arc.svg) Arco.
   * [Draft](/Draft_Workbench/it "Draft Workbench/it"): Selezionare l'opzione **Drafting → Strumenti arco → ![](/images/Draft_Arc.svg) Arco** dal menu.
   * [BIM](/BIM_Workbench/it "BIM Workbench/it"): Selezionare l'opzione **2D Drafting → ![](/images/Draft_Arc.svg) Arco** dal menu.
   * Usare la scorciatoia da tastiera: A poi R.
2. Si apre il pannello attività **Arco**. Vedere [Opzioni](#Options) per maggiori informazioni.
3. Scegliere il primo punto, il centro dell'arco, nella [Vista 3D](/3D_view/it "3D view/it"), oppure digitare le coordinate e premere il pulsante ![](/images/Draft_AddPoint.svg) Inserisci punto.
4. Scegliere il secondo punto nella [Vista 3D](/3D_view/it "3D view/it"), o inserire un **Raggio**.
5. Scegliere il terzo punto nella [Vista 3D](/3D_view/it "3D view/it"), o inserire un **Angolo iniziale**.
6. Scegliere il quarto punto nella [Vista 3D](/3D_view/it "3D view/it"), o inserire un **Angolo di apertura**.

## Opzioni

È possibile modificare le scorciatoie da tastiera a carattere singolo disponibili nel pannello delle attività. Vedere [Preferenze di Draft](/Draft_Preferences/it "Draft Preferences/it"). Le scorciatoie qui menzionate sono le scorciatoie predefinite (per la versione 1.0).

* Per inserire manualmente le coordinate del centro, inserire le componenti X, Y e Z, e premere Enter dopo ciascuna. Oppure si può premere il pulsante ![](/images/Draft_AddPoint.svg) Inserisci punto quando ha i valori desiderati. Si consiglia di spostare il puntatore fuori dalla [Vista 3D](/3D_view/it "3D view/it") prima di inserire le coordinate.
* Premere G o fare clic sulla casella di controllo **Globale** per attivare o disattivare la modalità globale. Se la modalità globale è attiva, le coordinate sono relative al sistema di coordinate globale, altrimenti sono relative al sistema di coordinate del [piano di lavoro](/Draft_SelectPlane/it "Draft SelectPlane/it").
* Premere N o fare clic sulla casella di controllo **Continua** per attivare o disattivare la modalità continua. Se la modalità continua è attiva, il comando si riavvierà al termine, consentendo di continuare a creare archi.
* Premere S per attivare o disattivare lo [Snap](/Draft_Snap/it "Draft Snap/it").
* Premere Esc o il pulsante Chiudi per interrompere il comando.

## Note

* Un Arco può essere modificato con il comando [Modifica](/Draft_Edit/it "Draft Edit/it").

## Preferenze

Vedere anche: [Impostare le preferenze](/Preferences_Editor/it "Preferences Editor/it") e [Preferenze per l'ambiente Draft](/Draft_Preferences/it "Draft Preferences/it").

* Se l'opzione **Modifica → Preferenze... → Draft → Generale → Crea primitive della parte se possibile** è selezionata, il comando creerà un [Part Cerchio](/Part_Circle/it "Part Circle/it") invece di uno Draft Cerchio.

## Proprietà

Vedere [Draft Circonferenza](/Draft_Circle/it#Propertietà "Draft Circle/it").

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per creare un Draft Arco usare il metodo `make_circle` ([disponibile dalla versione 0.19](/Release_notes_0.19/it "Release notes 0.19/it")) del modulo Draft. Questo metodo sostituisce il metodo deprecato `makeCircle`.

Esempio:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

arc1 = Draft.make_circle(200, startangle=0, endangle=90)
arc2 = Draft.make_circle(500, startangle=20, endangle=160)
arc3 = Draft.make_circle(750, startangle=-30, endangle=-150)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Arc/it&oldid=1513784>"