---
title: Draft Gruppo automatico
---
|  |
| --- |
| Draft Gruppo automatico |
| Posizione nel menu |
| *Nessuno* |
| Ambiente |
| [Draft](/Draft_Workbench/it "Draft Workbench/it"), [BIM](/BIM_Workbench/it "BIM Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| 0.17 |
| Vedere anche |
| [Draft Livello](/Draft_Layer/it "Draft Layer/it"), [Gruppo](/Std_Group/it "Std Group/it") |
|  |

## Descrizione

Il comando **Draft Gruppo automatico** modifica il [Draft Layer](/Draft_Layer/it "Draft Layer/it") attivo o, [opzionalmente](#Preferenze), il  [Gruppo](/Std_Group/it "Std Group/it") attivo o l'oggetto simil-gruppo [BIM](/BIM_Workbench/it "BIM Workbench/it"). I nuovi oggetti [Draft](/Draft_Workbench/it "Draft Workbench/it") e [BIM](/BIM_Workbench/it "BIM Workbench/it") vengono automaticamente posizionati in questo layer attivo o gruppo.

Questo comando era originariamente destinato ai gruppi, da cui il nome, ma è stato riprogettato nella versione 0.19 di FreeCAD quando è stato introdotto un sistema a layer. Poiché la gestione dei layer è ora l'impostazione predefinita per il comando, il resto di questa pagina si concentra principalmente su di essi

![](/images/Draft_Tray_Menu.png)

Il menu dei layer della barra di Draft (immagine aggiornata per la versione 1.1)

## Utilizzo

1. Facoltativamente selezionare il layer che si vuole rendere attivo nella [Vista ad albero](/Tree_view/it "Tree view/it").
2. Esistono diversi modi per richiamare il comando:
   * Premere il pulsante ![](/images/Draft_tray_button_layer.png) nella [Barra di Draft](/Draft_Tray/it "Draft Tray/it"). Questo pulsante può avere un aspetto diverso. Se è presente un layer attivo, verrà visualizzato il nome del layer e un'icona con linea e faccia del colore del layer.
   * Se si ha selezionato un layer: selezionare l'opzione **![](/images/Button_right.svg) Attiva questo layer** dal menu contestuale [Vista ad albero](/Tree_view/it "Tree view/it").
3. Se non si ha ancora selezionato un layer, si apre il menu dei layer. Effettuare una delle seguenti operazioni:
   * Selezionare **![](/images/Button_invalid.svg) Nessuno** per lavorare senza un layer attivo.
   * Selezionare un layer esistente da rendere attivo.
   * Selezionare **![](/images/Draft_NewLayer.svg) Nuovo layer...** per creare un nuovo layer:
     1. Si apre la finestra di dialogo **Crea nuovo layer**. [disponibile dalla versione 1.1](/Release_notes_1.1/it "Release notes 1.1/it")
     2. Inserire un **Nome layer**.
     3. Premere il pulsante OK.
     4. Il nuovo layer è attivato. [disponibile dalla versione 1.1](/Release_notes_1.1/it "Release notes 1.1/it")
4. Se il layer attivo è stato modificato, il pulsante nel [Draft Vassoio](/Draft_Tray/it "Draft Tray/it") viene aggiornato.

## Note

* È anche possibile creare un nuovo [layer](/Draft_Layer/it "Draft Layer/it") facendo clic con il pulsante destro del mouse sul contenitore del layer nella [Vista ad albero](/Tree_view/it "Tree view/it") e selezionando **![](/images/Draft_NewLayer.svg) Aggiungi nuovo layer** opzione dal menu contestuale.
* Se la [Modalità di costruzione Draft](/Draft_ToggleConstructionMode/it "Draft ToggleConstructionMode/it") è attivata, il [layer](/Draft_Layer/it "Draft Layer/it") attivo viene ignorato.

## Preferenze

Vedere anche: [Impostare le preferenze](/Preferences_Editor/it "Preferences Editor/it") e [Preferenze per l'ambiente Draft](/Draft_Preferences/it "Draft Preferences/it").

* Questo comando può opzionalmente gestire anche i gruppi: **Modifica → Preferenze... → Draft → Generale → Includi gruppi nell'elenco dei layer**.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Se [Draft](/Draft_Workbench/it "Draft Workbench/it") è attivo, l'oggetto dell'applicazione FreeCADGui ha una proprietà `draftToolBar`. Questo oggetto `draftToolBar` ha una proprietà `autogroup`, che contiene il nome dell'autogroup attivo, o è `None` se nessun autogroup è attivo. Per modificare il gruppo automatico attivo utilizza il metodo `setAutoGroup` dell'oggetto `draftToolBar`. Per inserire gli oggetti nell'autogroup attivo utilizza il metodo `autogroup` del modulo Draft.

```
# This code only works if the Draft Workbench is active!

import FreeCAD as App
import FreeCADGui as Gui
import Draft

doc = App.newDocument()

polygon1 = Draft.make_polygon(5, radius=1000)
polygon2 = Draft.make_polygon(3, radius=500)
polygon3 = Draft.make_polygon(6, radius=220)

layer = Draft.make_layer()
Gui.draftToolBar.setAutoGroup(layer.Name)

Draft.autogroup(polygon1)
Draft.autogroup(polygon2)
Draft.autogroup(polygon3)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_AutoGroup/it&oldid=1552932>"