---
title: Draftː Punto
---
|  |
| --- |
| Draft Punto |
| Posizione nel menu |
| Drafting → Punto 2D Drafting → Punto |
| Ambiente |
| [Draft](/Draft_Workbench/it "Draft Workbench/it"), [BIM](/BIM_Workbench/it "BIM Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| 0.7 |
| Vedere anche |
| *Nessuno* |
|  |

## Descrizione

Il comando ![](/images/Draft_Point.svg) **Punto** crea un semplice punto. I punti Draft possono essere utili come riferimento per posizionare linee, polilinee o altri oggetti.

![](/images/Draft_point_example.jpg)

## Utilizzo

Vedere anche: [Barra di Draft](/Draft_Tray/it "Draft Tray/it"), [Aggancio](/Draft_Snap/it "Draft Snap/it") e [Vincolare](/Draft_Constrain/it "Draft Constrain/it").

1. Esistono diversi modi per invocare il comando:
   * Premere il pulsante ![](/images/Draft_Point.svg) Punto.
   * [Draft](/Draft_Workbench/it "Draft Workbench/it"): Selezionare l'opzione **Drafting → ![](/images/Draft_Point.svg) Punto** dal menu.
   * [BIM](/BIM_Workbench/it "BIM Workbench/it"): Selezionare l'opzione **2D Drafting → ![](/images/Draft_Point.svg) Punto** dal menu.
2. Si apre il pannello attività **Punto**. Vedere [Opzioni](#Options) per maggiori informazioni.
3. Scegliere un punto nella [Vista 3D](/3D_view/it "3D view/it"), oppure digitare le coordinate e premere il pulsante ![](/images/Draft_AddPoint.svg) Inserisci punto.

## Opzioni

È possibile modificare le scorciatoie da tastiera a carattere singolo disponibili nel pannello delle attività. Vedere [Preferenze di Draft](/Draft_Preferences/it "Draft Preferences/it"). Le scorciatoie qui menzionate sono le scorciatoie predefinite (per la versione 1.0).

* Per inserire manualmente le coordinate, inserire le componenti X, Y e Z e premere Enter dopo ognuna di esse. Oppure si può premere il pulsante ![](/images/Draft_AddPoint.svg) Inserisci punto quando ha i valori desiderati. Si consiglia di spostare il puntatore fuori dalla [Vista 3D](/3D_view/it "3D view/it") prima di inserire le coordinate.
* Premere G o fare clic sulla casella di controllo **Globale** per attivare o disattivare la modalità globale. Se la modalità globale è attiva, le coordinate sono relative al sistema di coordinate globale, altrimenti sono relative al sistema di coordinate [piano di lavoro](/Draft_SelectPlane/it "Draft SelectPlane/it").
* Premere N o fare clic sulla casella di controllo **Continua** per attivare o disattivare la modalità continua. Se la modalità continua è attiva, il comando si riavvierà al termine, consentendo di continuare a creare punti.
* Premere S per attivare o disattivare [Aggancia](/Draft_Snap "Draft Snap").
* Premere Esc o il pulsante Chiudi per interrompere il comando.

## Note

* Usare ![](/images/Draft_Snap_Endpoint.svg) [Aggancia Punto Finale](/Draft_Snap_Endpoint/it "Draft Snap Endpoint/it") per eseguire l'aggancio ai Punti Draft.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Draft Punto è derivato da un [Part Part2DObject](/Part_Part2DObject/it "Part Part2DObject/it") e ne eredita tutte le proprietà. Ha anche le seguenti proprietà aggiuntive:

### Dati

Draft

* Dati**X** : specifica la coordinata X del punto.
* Dati**Y** : specifica la coordonata Y del punto.
* Dati**Z** : specifica la coordonata Z del punto.

### Vista

Draft

* Vista**Pattern** (`Enumeration`): not used.
* Vista**Pattern Size** (`Float`): not used.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per creare un Draft Punto usare il metodo `make_point` ([disponibile dalla versione 0.19](/Release_notes_0.19/it "Release notes 0.19/it")) del modulo Draft. Questo metodo sostituisce il metodo deprecato `makePoint`.

```
point = make_point(X=0, Y=0, Z=0, color=None, name="Point", point_size=5)
point = make_point(point, Y=0, Z=0, color=None, name="Point", point_size=5)

```

* Crea un oggetto `point` con le coordinate specicate in `X`, `Y` e `Z`, con unità in millimetri. Se non vengono fornite coordinate, il punto viene creato all'origine (0,0,0).
  + Se `X` è un `point` definito da un `FreeCAD.Vector`, esso viene usato.
* `color` è una tupla `(R, G, B)` che indica il colore del punto nella scala RGB; ogni valore nella tupla deve essere compreso nell'intervallo tra `0` e `1`.
* `name` è il nome dell'oggetto.
* `point_size` è la dimensione dell'oggetto in pixel, se viene caricata l'interfaccia utente grafica.

Esempio:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

point1 = Draft.make_point(1600, 1400, 0)

p2 = App.Vector(-3200, 1800, 0)
point2 = Draft.make_point(p2, color=(0.5, 0.3, 0.6), point_size=10)

doc.recompute()

```

Esempio:

Questo codice crea `N` punti casuali all'interno di un quadrato di lato `2L`. Crea un anello creando `N` punti, che possono apparire ovunque da `-L` a `+ L` su X e Y. Inoltre sceglie un colore e una dimensione casuali per ciascun punto. Cambiare `N` per cambiare il numero di punti e cambiare `L` per cambiare l'area coperta dai punti.

```
import random
import FreeCAD as App
import Draft

doc = App.newDocument()

L = 1000
centered = App.Placement(App.Vector(-L, -L, 0), App.Rotation())
rectangle = Draft.make_rectangle(2*L, 2*L, placement=centered)

N = 10
for i in range(N):
    x = 2*L*random.random() - L
    y = 2*L*random.random() - L
    z = 0
    r = random.random()
    g = random.random()
    b = random.random()
    size = 15*random.random() + 5
    Draft.make_point(x, y, z, color=(r, g, b), point_size=size)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Point/it&oldid=1513810>"