---
title: Draft Lega facce
---
|  |
| --- |
| Draft Lega facce |
| Posizione nel menu |
| Drafting → Lega facce 3D/BIM → Strumenti 3D generici → Lega facce |
| Ambiente |
| [Draft](/Draft_Workbench/it "Draft Workbench/it"), [BIM](/BIM_Workbench/it "BIM Workbench/it") |
| Avvio veloce |
| Draft: F F |
| Introdotto nella versione |
| 0.14 |
| Vedere anche |
| *Nessuno* |
|  |

## Descrizione

Il comando ![](/images/Draft_Facebinder.svg) **Lega facce** crea un oggetto superficie dalle facce selezionate. Un Lega facce è parametrico, si aggiornerà se si modificano i suoi oggetti sorgente.

Può essere utilizzato per creare un'estrusione da una raccolta di facce. Questa estrusione può ad esempio rappresentare una finitura della parete nel design architettonico.

![](/images/Draft_facebinder_example.jpg)

Facebinder creato da facce di pareti

## Utilizzo

1. Seleziona una o più facce.
2. Esistono diversi modi per invocare il comando:
   * Premere il pulsante ![](/images/Draft_Facebinder.svg) Lega facce.
   * [Draft](/Draft_Workbench/it "Draft Workbench/it"): Selezionare l'opzione **Drafting → ![](/images/Draft_Facebinder.svg) Lega facce** dal menu.
   * [BIM](/BIM_Workbench/it "BIM Workbench/it"): Selezionare l'opzione **3D/BIM → Strumenti 3D generici → ![](/images/Draft_Facebinder.svg) Facebinder** dal menu.
   * Draftː Usare la scorciatoia da tastiera: F poi F.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

![](/images/Draft_Facebinder_Corners.png)

Sulla sinistra un facebinder estruso con angoli chiusi (rosa),  
a destra un facebinder estruso con angoli aperti (arancio).  
Gli angoli chiusi sono una funzionalità della versione V1.1.

Un oggetto Lega facce è derivato da una [Funzione Part](/Part_Feature/it "Part Feature/it") e ne eredita tutte le proprietà. Ha anche le seguenti proprietà aggiuntive:

### Dati

Draft

* Dati**Area** (`Area`): (sola lettura) specifica l'area totale delle facce collegate del facebinder.
* Dati**Extrusion** (`Distance`): specifica lo spessore di estrusione del facebinder. [disponibile dalla versione 1.1](/Release_notes_1.1/it "Release notes 1.1/it"): Se il facebinder ha facce connesse e Dati**Sew** è `true`, viene effettuato un tentativo di chiudere gli angoli dell'estrusione. Se ciò non è possibile, le facce vengono estruse separatamente.
* Dati**Faces** (`LinkSubList`): specifica le facce collegate del facebinder.
* Dati**Offset** (`Distance`): specifica una distanza di offset da applicare tra il facebinder e le facce originali, prima dell'estrusione.
* Dati**Remove Splitter** (`Bool`): specifica se rimuovere le linee di divisione che dividono le facce complanari del facebinder.
* Dati**Sew** (`Bool`): specifica se eseguire un'operazione di cucitura topologica sul facebinder.

### Vista

Draft

* Vista**Pattern** (`Enumeration`): specifica la [Campitura](/Draft_Pattern/it "Draft Pattern/it") con cui riempire le facce del facebinder. Questa proprietà funziona solo se Vista**Display Mode** è `Flat Lines`.
* Vista**Pattern Size** (`Float`): specifica la dimensione della [Campitura](/Draft_Pattern/it "Draft Pattern/it").

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per creare un Draft Lega facce usare il metodo `make_facebinder` ([disponibile dalla versione 0.19](/Release_notes_0.19/it "Release notes 0.19/it")) del modulo Draft. Questo metodo sostituisce il metodo deprecato `makeFacebinder`.

```
facebinder = make_facebinder(selectionset)

```

* Crea un oggetto `facebinder` dalla `selectionset`, che è una lista di `SelectionObject` come quelli restituiti da `FreeCADGui.Selection.getSelectionEx()`.
  + `selectionset` può anche essere un `PropertyLinkSubList`.

Un `PropertyLinkSubList` è un elenco di tuple; ogni tupla contiene come primo elemento un `oggetto` e come secondo elemento un elenco (o tupla) di stringhe; queste stringhe indicano i nomi dei sotto-elementi (facce) di quell'oggetto.

```
PropertyLinkSubList = [tuple1, tuple2, tuple3, ...]
PropertyLinkSubList = [(object1, list1), (object2, list2), (object3, list3), ...]
PropertyLinkSubList = [(object1, ['Face1', 'Face4', 'Face6']), ...]
PropertyLinkSubList = [(object1, ('Face1', 'Face4', 'Face6')), ...]

```

Lo spessore di Facebinder può essere aggiunto sovrascrivendo il suo attributo `Extrusion`; il valore è inserito in millimetri.

Il posizionamento di Facebinder può essere cambiato sovrascrivendo il suo attributo `Placement`, o sovrascrivendo singolarmente i suoi attributi `Placement.Base` e `Placement.Rotation`.

Esempio:

```
import FreeCAD as App
import FreeCADGui as Gui
import Draft

doc = App.newDocument()

# Insert a solid box
box = doc.addObject("Part::Box", "Box")
box.Length = 2300
box.Width = 800
box.Height = 1000

# selection = Gui.Selection.getSelectionEx()
selection = [(box, ("Face1", "Face6"))]
facebinder = Draft.make_facebinder(selection)
facebinder.Extrusion = 50

doc.recompute()

facebinder.Placement.Base = App.Vector(1000, -1000, 100)
facebinder.ViewObject.ShapeColor = (0.99, 0.99, 0.4)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Facebinder/it&oldid=1562532>"