---
title: Draft Capovolgi quota
---
|  |
| --- |
| Draft Capovolgi quota |
| Posizione nel menu |
| Modifiche → Capovolgi quota |
| Ambiente |
| [Draft](/Draft_Workbench/it "Draft Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| *Nessuno* |
|  |

## Descrizione

Il comando ![](/images/Draft_FlipDimension.svg) **Draft Capovolgi quota** ruota il testo delle [Draft Quote](/Draft_Dimension/it "Draft Dimension/it") selezionate di 180° intorno alla linea di quota. Può essere utilizzato per correggere quote il cui testo appare speculare. Il comando non funziona correttamente per le quote angolari.

## Utilizzo

1. Selezionare una o più [Draft Quote](/Draft_Dimension "Draft Dimension").
2. Esistono diversi modi per invocare il comando:
   * Premere il pulsante ![](/images/Draft_FlipDimension.svg) Capovolgi quota.
   * Selezionare l'opzione **Modifiche → ![](/images/Draft_FlipDimension.svg) Capovolgi quota** dal menu.

## Note

* Le [Draft Quote](/Draft_Dimension/it "Draft Dimension/it") hanno anche una proprietà Dati**Flip Text**. Quando impostato su `true` il testo viene ruotato di 180° rispetto alla direzione normale. Questo può essere combinato con l'effetto di questo comando.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per capovolgere una [Draft Quota](/Draft_Dimension/it "Draft Dimension/it") invertire la sua proprietà `Normal`.

Esempio:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(1000, 0, 0)
p3 = App.Vector(500, 300, 0)
dimension = Draft.make_dimension(p1, p2, p3)
dimension.ViewObject.FontSize = 200

dimension.Normal = dimension.Normal.negative()
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_FlipDimension/it&oldid=1457400>"