---
title: Draft Draft in Sketch
---
|  |
| --- |
| Draft Draft in sketch |
| Posizione nel menu |
| Modifiche → Draft in sketch Modifica → Draft in sketch |
| Ambiente |
| [Draft](/Draft_Workbench/it "Draft Workbench/it"), [BIM](/BIM_Workbench/it "BIM Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| *Nessuno* |
|  |

## Descrizione

Il comando ![](/images/Draft_Draft2Sketch.svg) **Draft Draft in Sketch** converte oggetti [Draft](/Draft_Workbench/it "Draft Workbench/it") in [Schizzi di Sketcher](/Sketcher_NewSketch/it "Sketcher NewSketch/it") e viceversa.

![](/images/Draft_Draft2Sketch_example.png)

Conversione di oggetti Draft in Schizzi di Sketcher

## Utilizzo

1. Facoltativamente, selezionare uno o più oggetti Draft o [Schizzi di Sketcher](/Sketcher_NewSketch "Sketcher NewSketch").
2. Ci sono diversi modi per invocare il comando:
   * Premere il pulsante ![](/images/Draft_Draft2Sketch.svg) [Draft in sketch](/Draft_Draft2Sketch "Draft Draft2Sketch").
   * [Draft](/Draft_Workbench/it "Draft Workbench/it"): Selezionare l'opzione **Modifiche → ![](/images/Draft_Draft2Sketch.svg) Draft in sketch** dal menu.
   * [BIM](/BIM_Workbench/it "BIM Workbench/it"): Selezionare l'opzione **Modifica → ![](/images/Draft_Draft2Sketch.svg) Draft in sketch** dal menu.
3. Se non si ha ancora selezionato un oggetto: selezionare un oggetto nella [Vista 3D](/3D_view/it "3D view/it").
4. Viene creato un nuovo oggetto.

## Note

* Possono essere convertiti anche oggetti non Draft che sono totalmente planari.
* Il comando può gestire solo oggetti composti da linee rette, archi circolari, archi ellittici, B-Spline e curve di Bézier.
* [Draft BezCurve](/Draft_BezCurve/it "Draft BezCurve/it") saranno approssimate da [BSplines di Sketcher](/Sketcher_CreateBSpline/it "Sketcher CreateBSpline/it").
* Il [KicadStepUp Workbench](/KicadStepUp_Workbench/it "KicadStepUp Workbench/it") esterno contiene un comando per convertire un [Draft BSpline](/Draft_BSpline/it "Draft BSpline/it") in una serie di [Archi di Sketcher](/Sketcher_CreateArc/it "Sketcher CreateArc/it"). Per ulteriori informazioni, vedere l'argomento del forum [BSplines to Shape2DView and Sketcher](https://forum.freecadweb.org/viewtopic.php?f=9&t=25082).
* [Questo altro argomento del forum](https://forum.freecadweb.org/viewtopic.php?f=3&t=58781#p505207) contiene una macro per tale conversione.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per convertire gli oggetti in uno schizzo usare il metodo `make_sketch` ([disponibile dalla versione 0.19](/Release_notes_0.19/it "Release notes 0.19/it")) del modulo Draft. Questo metodo sostituisce il metodo deprecato `makeSketch`.

```
sketch = make_sketch(objects_list, autoconstraints=False, addTo=None, delete=False, name="Sketch", radiusPrecision=-1, tol=1e-3)

```

* `objects_list` contiene gli oggetti da convertire. È un singolo oggetto o un elenco di oggetti. Sono supportati gli oggetti `Draft`, `Part::Feature` e `Part.Shape`.
* Se `autoconstraints` è `True` vengono aggiunti vincoli coincidenti ai nodi appartenenti allo stesso oggetto sorgente.
* `addTo` è l'oggetto schizzo esistente a cui viene aggiunta la geometria. Se non fornito viene creato un nuovo schizzo.
* Se `delete` è `True` gli oggetti di origine vengono eliminati.
* `name` è il nome del nuovo sketch.
* `radiusPrecision` indica come devono essere gestiti i vincoli di raggio:
  + Usare `-1` per disabilitare i vincoli di raggio.
  + Usare `0` per aggiungere vincoli di raggio individuali.
  + Utilizzare un numero positivo per arrotondare i raggi in base a questa precisione e per aggiungere vincoli uguali tra curve con raggi uguali.
* `tol` è la tolleranza utilizzata per verificare se le forme sono planari e complanari. Usare `-1` per un'analisi rigorosa.
* `sketch` viene restituito con l'oggetto sketch.

Per convertire uno schizzo in oggetti Draft usare il metodo `draftify` del modulo Draft.

```
draftify(objectslist, makeblock=False, delete=True)

```

* `objectslist` contiene gli oggetti da convertire. È un singolo oggetto o un elenco di oggetti.
* Se `makeblock` è `True` gli oggetti convertiti sono raggruppati in un `Part::Part2DObject`.
* Se `delete` è `True` gli oggetti di origine vengono eliminati.

Esempio:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

rectangle = Draft.make_rectangle(2000, 1000)
circle = Draft.make_circle(500)
doc.recompute()

sketch_from_draft = Draft.make_sketch([rectangle, circle], autoconstraints=True, delete=False, radiusPrecision=0)
doc.recompute()

draft_from_sketch = Draft.draftify(sketch_from_draft, delete=False)
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Draft2Sketch/it&oldid=1474251>"