---
title: Draft Raccordo
---
|  |
| --- |
| Draft Raccordo |
| Posizione nel menu |
| Drafting → Raccordo 2D Drafting → Raccordo |
| Ambiente |
| [Draft](/Draft_Workbench/it "Draft Workbench/it"), [BIM](/BIM_Workbench/it "BIM Workbench/it") |
| Avvio veloce |
| F I |
| Introdotto nella versione |
| 0.19 |
| Vedere anche |
| [Draft Linea](/Draft_Line/it "Draft Line/it"), [Draft Polilinea](/Draft_Wire/it "Draft Wire/it") |
|  |

## Descrizione

Il comando ![](/images/Draft_Fillet.svg) **Raccordo** crea un raccordo, un angolo arrotondato o smusso, tra due bordi selezionati.

In versione 0.21 e precedenti il comando funziona correttamente solo se entrambi i bordi selezionati sono rettilinei.

In versione 1.0 e precedenti se gli oggetti selezionati hanno più bordi, verrà utilizzato il primo bordo. Questo potrebbe non essere il bordo selezionato nella [Vista 3D](/3D_view/it "3D view/it").

![](/images/Draft_Fillet_example.png)

Diversi raccordi e smussi creati tra due bordi

### Utilizzo

1. Selezionare due bordi che si incontrano in un unico punto.
2. Esistono diversi modi per invocare il comando:
   * Premere il pulsante ![](/images/Draft_Fillet.svg) Raccordo.
   * [Draft](/Draft_Workbench/it "Draft Workbench/it"): Selezionare l'opzione **Drafting → ![](/images/Draft_Fillet.svg) Raccordo** dal menu.
   * [BIM](/BIM_Workbench/it "BIM Workbench/it"): Selezionare l'opzione **2D Drafting → ![](/images/Draft_Fillet.svg) Raccordo** dal menu.
   * Usare la scorciatoia da tastiera: F poi I.
3. Inserire il **Raggio raccordo**. Tenere presente che il comando non avrà successo se il raggio è troppo grande per gli oggetti bordo selezionati.
4. Facoltativamente selezionare l'opzione **Elimina gli oggetti originali**.
5. Facoltativamente selezionare l'opzione **Crea smusso**.
6. Se è stata selezionata una delle due opzioni precedenti: Fare clic nella casella di immissione **Raggio raccordo**.
7. Premere Enter.

## Opzioni

* Premere Esc o il pulsante Chiudi per interrompere il comando.

## Note

* Un Draft Raccordo non può essere modificato né è collegato (link) ai bordi utilizzati per crearlo.
* Una [Polilinea](/Draft_Wire/it "Draft Wire/it") che ha almeno tre punti può essere raccordata o smussata modificandone rispettivamente Dati**Fillet Radius** o Dati**Chamfer Size**. Poiché [Linee](/Draft_Line/it "Draft Line/it") e [Polilinee](/Draft_Wire "Draft Wire"), possono essere unite con il comando [Polilinea](/Draft_Wire/it "Draft Wire/it"), il comando [Unisci](/Draft_Join/it "Draft Join/it") o il comando [Promuovi](/Draft_Upgrade/it "Draft Upgrade/it") forniscono un metodo alternativo per creare raccordi e smussi.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Raccordo deriva da un [Part Part2DObject](/Part_Part2DObject/it "Part Part2DObject/it") e ne eredita tutte le proprietà. Ha anche le seguenti proprietà aggiuntive:

### Dati

Draft

* Dati**End** (`VectorDistance`): (sola lettura) specifica il punto finale del raccordo.
* Dati**Fillet Radius** (`Lenght`): (sola lettura) raggio con cui è stato creato il raccordo.
* Dati**Length** (`Length`): (sola lettura) specifica la lunghezza totale del raccordo.
* Dati**Start** (`VectorDistance`): (sola lettura) specifica il punto iniziale del raccordo.

### Vista

Draft

* Vista**Arrow Size** (`Length`): specifica la dimensione del simbolo visualizzato alla fine del raccordo.
* Vista**Arrow Type** (`Enumeration`): specifica il tipo di simbolo visualizzato alla fine del raccordo, che può essere `Dot`, `Circle`, `Arrow`, `Tick` o `Tick-2`.
* Vista**End Arrow** (`Bool`): specifica se mostrare un simbolo alla fine del raccordo, in modo che possa essere utilizzato come linea di annotazione.
* Vista**Pattern** (`Enumeration`): non utilizzato.
* Vista**Pattern Size** (`Float`): non utilizzato.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Per creare un Raccordo Draft usare il metodo `make_fillet` del modulo Draft:

```
fillet = make_fillet([edge1, edge2], radius=100, chamfer=False, delete=False)

```

* Crea un oggetto `Fillet` tra gli oggetti bordo `edge1` e `edge2`, utilizzando `radius` per la curvatura.
* Se `chamfer` è `True` creerà un bordo dritto invece di un bordo arrotondato.
* Se `delete` è `True` eliminerà i dati `edge1` e `edge2` e lascerà solo il nuovo oggetto.

Esempio:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(1000, 1000, 0)
p3 = App.Vector(2000, 0, 0)

edge1 = Draft.make_line(p1, p2)
edge2 = Draft.make_line(p2, p3)

doc.recompute()

fillet = Draft.make_fillet([edge1, edge2], radius=500)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Fillet/it&oldid=1511575>"