---
title: Placement API
---
:::caution
(October 2019) Do not edit this page. The information is incomplete and outdated. For the latest API, see theautogenerated API documentation, or generate the documentation yourself, seeSource documentation.
:::

În FreeCAD, Plasamentul definește poziția și rotația unui obiect. Conceptul de Plasament este explicat în detaliu aici: [Placement](/Placement "Placement").

Exemplu de setare a destinației de plasare a obiectului de document:

```
myObj = FreeCAD.ActiveDocument.ActiveObject
pl = FreeCAD.Placement()
pl.move(FreeCAD.Vector(2,0,0))
myObj.Placement = pl

```

![](/images/Class.png)  **Placement (***) sau (Placement) sau (Matrice) sau (Base, Rotation) sau (Base, Rotation, Centre) sau (Base, Axes, Angle* **)**

**Description**: Construește un plasament, vid sau cu arguemntele date, sau o copie a amplasamentului dat.

![](/images/Property.png)  **Base**

**Returns**: . Un vector reprezentâtnd poziție du Plasementului

![](/images/Property.png)  **Rotation**

**Returns**: . Un quaternion ( număr complex format din patru unități sclare) reprezentând rotația Plasamentului

![](/images/Method.png)  **inverse (****)**

**Description**: calculază plasamentul invers

**Returns**: . Un placement

![](/images/Method.png)  **move (** *Vector* **)**

**Description**: deplasează plasamentul de-a lungul unui vector dat

**Returns**: nimic

{{APIFunction | multVec | Vector | aplică plasamentul la vectorul dat| vectorul rezultant}.} {{APIFunction | multiplcați | Placement | multiplică acest plasamentul cu altul| plasamentul rezultatnt}.}

![](/images/Method.png)  **toMatrix (****)**

**Description**:

**Returns**: . O matrice reprezentând transformarea plasamentului

Retrieved from "<http://wiki.freecad.org/index.php?title=Placement_API/ro&oldid=632495>"