---
title: Part Casetă
---
|  |
| --- |
| Part Box |
| Menu location |
| Part → Primitives → Cube |
| Workbenches |
| [Part](/Part_Workbench "Part Workbench"), Complete |
| Default shortcut |
| *None* |
| Introduced in version |
| - |
| See also |
| [Part CreatePrimitives](/Part_CreatePrimitives "Part CreatePrimitives") |
|  |

## Description

## Descriere

Comanda Box din Atelierul [Part Workbench](/Part_Workbench "Part Workbench") inserează o casetă parametrică, [rectangular cuboid](http://en.wikipedia.org/wiki/Cuboid#Rectangular_cuboid), o primitivă geometrică în documentul activ. Implicit, comanda Box va insera un cub de 10x10x10 mm, poziționaat în origine, cu denumirea/eticheta "cube".
Acești parametri pot fi modificați după adăugarea obiectului.

![](/images/Part_Box_Example.png)

## Usage

1. There are several ways to invoke the command:
   * Press the ![](/images/Part_Box.svg) [Cube](/Part_Box "Part Box") button.
   * Select the **Part → Primitives → ![](/images/Part_Box.svg) Cube** option from the menu.
2. The box is created.
3. Optionally change the dimensions and Date**Placement** of the box by doing one of the following:
   * Double-click the object in the [Tree view](/Tree_view "Tree view"):
     1. The **Geometric Primitives** task panel opens.
     2. Change one or more properties.
     3. The object is dynamically updated in the [3D view](/3D_view "3D view").
     4. Press the OK button.
   * Change the properties in the [Property editor](/Property_editor "Property editor").
   * Change the Date**Placement** with the ![](/images/Std_TransformManip.svg) [Std TransformManip](/Std_TransformManip "Std TransformManip") command.

## Example

![](/images/Part_Box_Scripting_Example.png)

Part Box from the scripting example

A Part Box object created with the [scripting example](#Scripting) below is shown here.

## Notes

* A Part Box can also be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. With that command you can specify the dimensions and placement at creation time.

## Properties

See also: [Property editor](/Property_editor "Property editor").

A Part Box object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Box

Box

* Date**Length**:Parametrul lungime este dimensiunea Box în direcția x.
* Date**Width**: Parametrul lățime este dimensiunea Box în direcția y.
* Date**Height**: Parametrul înălțime este dimensiunea Box în direcția z.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

## Scripting

Comanda Box poate fi utilizat în [macros](/Macros "Macros") și din consola python utilizând următoarea funcție:

```
box = FreeCAD.ActiveDocument.addObject("Part::Box", "myBox")

```

* Unde "myBox" este o denumire/etichetă pentru obiectul Box.
* Are ca rezulta obiectul nou creat de tip Box.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

box = doc.addObject("Part::Box", "myBox")
box.Length = 4
box.Width = 8
box.Height = 12
box.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Box/ro&oldid=1466530>"