---
title: Part Torul
---
|  |
| --- |
| Part Torus |
| poziția meniului |
| Part → Torus |
| Ateliere |
| [Part](/Part_Workbench/ro "Part Workbench/ro"), Complete |
| scurtătură |
| *Nici unul* |
| Prezentat în versiune |
| - |
| A se vedea, de asemenea, |
| [Part CreatePrimitives](/Part_CreatePrimitives/ro "Part CreatePrimitives/ro") |
|  |

## Description

## Descriere

Creează un tor simplu parametric, cu parametrii de poziție, unghi1, unghi2, unghi 3, raza1 și raza2.

A Part Torus can be turned into a segment of a torus by changing its Date**Angle3** property. By changing its Date**Angle1** and/or Date**Angle2** properties the swept profile can become a segment of a circle.

![](/images/Part_Torus_Example.png)

## Cum se folosește

În bara de lucru [Part](/Part_Workbench "Part Workbench") faceți clic pe pictograma torus ![](/images/Part_Torus.png). Torusul va fi poziționat la origine (punctul 0,0,0) la crearea.
Parametrii unghiului (unghiul1, unghiul2, unghiul3), precum și parametrii razei (raza1, raza2) permit parametrizarea torusului, a se vedea paragraful următor.

## Example

![](/images/Part_Torus_Scripting_Example.png)

Part Torus from the scripting example

A Part Torus object created with the [scripting example](#Scripting) below is shown here.

## Notes

* A Part Torus can also be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. With that command you can specify the dimensions and placement at creation time.

![](/images/TorusExampleRadius1.jpg)
The parameter Radius1 has a value of 20 mm.

See also: [Property editor](/Property_editor "Property editor").

A Part Torus object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Torus

* **Radius1:** Raza cercului în jurul căruia circulă discul
* **Radius2:** Raza discului care definește forma torului
* **Angle1:** un unghi pentru a tăia / defini discul torului
* **Angle2:** al doilea unghi pentru a tăia / defini discul torului
* **Angle3:** al treilea unghi pentru a defini circumferința torului.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Torus can be created with the `addObject()` method of the document:

```
torus = FreeCAD.ActiveDocument.addObject("Part::Torus", "myTorus")

```

* Where `"myTorus"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

torus = doc.addObject("Part::Torus", "myTorus")
torus.Radius1 = 20
torus.Radius2 = 10
torus.Angle1 = -90
torus.Angle2 = 45
torus.Angle3 = 270
torus.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Torus/ro&oldid=1466578>"