---
title: Part Elipsoidul
---
|  |
| --- |
| Part Ellipsoid |
| Menu location |
| Part → [Create Primitives](/Part_CreatePrimitives "Part CreatePrimitives") → Ellipsoid |
| Workbenches |
| [Part](/Part_Workbench "Part Workbench"), [OpenSCAD](/OpenSCAD_Workbench "OpenSCAD Workbench") |
| Default shortcut |
| *None* |
| Introduced in version |
| - |
| See also |
| .. |
|  |

## Descriere

Un solid parametric este Elipsoidul care este disponibil din dialogul Create Primitives în Atelierul de lucru Part.

A ![](/images/Part_Ellipsoid.svg) **Part Ellipsoid** is a parametric solid that can be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. In the coordinate system defined by its Date**Placement** property, the axes of the ellipsoid are aligned with the X, Y and Z axes, and therefore its center is positioned at the origin.

A Part Ellipsoid can be truncated at the top and/or bottom by changing its Date**Angle1** and/or Date**Angle2** properties. It can be turned into a segment of an ellipsoid by changing its Date**Angle3** property.

![](/images/Part_Ellipsoid_Example.png)

## Usage

See [Part Primitives](/Part_Primitives#Usage "Part Primitives").

## Example

![](/images/Part_Ellipsoid_Scripting_Example.png)

Part Ellipsoid from the scripting example

A Part Ellipsoid object created with the [scripting example](#Scripting) below is shown here.

## Proprietăți

See also: [Property editor](/Property_editor "Property editor").

A Part Ellipsoid object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Ellipsoid

* Date**Radius1** (`Length`): The radius of the ellipsoid in its Z direction. The default is `2mm`.
* Date**Radius2** (`Length`): The radius of the ellipsoid in its X direction. The default is `4mm`.
* Date**Radius3** (`Length`): The radius of the ellipsoid in its Y direction. The default is `4mm`.
* Date**Angle1** (`Angle`): The start angle of the elliptical sides of the ellipsoid. Valid range: `-90° <= value < 90°`. Must be smaller than Date**Angle2**. The default is `-90°`.
* Date**Angle2** (`Angle`): The end angle of the elliptical sides of the ellipsoid. Valid range: `-90° < value <= 90°`. Must be larger than Date**Angle1**. The default is `90°`. If the total angle of the elliptical sides is smaller than `180°` the ellipsoid will be truncated and have a flat face at the top and/or bottom.
* Date**Angle3** (`Angle`): The total angle of the ellipsoid in its XY plane. Valid range: `0° < value <= 360°`. The default is `360°`. If it is smaller than `360°` the resulting solid will be a segment of an ellipsoid.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Ellipsoid can be created with the `addObject()` method of the document:

```
ellipsoid = FreeCAD.ActiveDocument.addObject("Part::Ellipsoid", "myEllipsoid")

```

* Where `"myEllipsoid"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

ellipsoid = doc.addObject("Part::Ellipsoid", "myEllipsoid")
ellipsoid.Radius1 = 2
ellipsoid.Radius2 = 4
ellipsoid.Radius3 = 6
ellipsoid.Angle1 = -90
ellipsoid.Angle2 = 50
ellipsoid.Angle3 = 300
ellipsoid.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(15, 0, 20))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Ellipsoid/ro&oldid=1106483>"