---
title: Part Elice/Helix
---
|  |
| --- |
| Part Elice |
| poziția meniului |
| Part → [Create Primitives](/Part_CreatePrimitives/ro "Part CreatePrimitives/ro") → Helix |
| Ateliere |
| [Part](/Part_Workbench/ro "Part Workbench/ro"), [OpenSCAD](/OpenSCAD_Workbench/ro "OpenSCAD Workbench/ro") |
| scurtătură |
| *Nici unul* |
| Prezentat în versiune |
| - |
| A se vedea, de asemenea, |
| *Nici unul* |
|  |

## Descriere

Un element primitiv geometric este Elicea care este disponibilă din dialogul Create Primitives în Atelierul de lucru Part.

A ![](/images/Part_Helix.svg) **Part Helix** is a parametric shape that can be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. In the coordinate system defined by its Date**Placement** property, the axis of the helix matches the Z axis and its bottom point, the start point, lies on the X axis.

![](/images/Part_Helix_Example.png)

## Cum se folosește

See [Part Primitives](/Part_Primitives#Usage "Part Primitives").

## Example

![](/images/Part_Helix_Scripting_Example.png)

Part Helix from the scripting example

A Part Helix object created with the [scripting example](#Scripting) below is shown here.

## Opțiuni

* A Part Helix can be used to create screw threads. See [Thread for Screw Tutorial](/Thread_for_Screw_Tutorial "Thread for Screw Tutorial").

## Properties

See also: [Property editor](/Property_editor "Property editor").

A Part Helix object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Coordinate System

* Date**Local Coord** (`Enumeration`): The [handedness](https://en.wikipedia.org/wiki/Screw_thread), or direction, of the helix: `Right-handed` or `Left-handed`. The default is `Right-handed`, meaning the helix turns counterclockwise as it goes up.

Helix

* Date**Pitch** (`Length`): The distance between two consecutive turns of the helix measured along its Z axis. The default is `1mm`.
* Date**Height** (`Length`): The height of the helix. The default is `2mm`.
* Date**Radius** (`Length`): The start radius of the helix. The helix has a constant radius if Date**Angle** is `0°`.
* Date**Segment Length** (`QuantityConstraint`): The number of turns per helix subdivision. The default is `1`, meaning each full turn of the helix is a separate segment. Use `0` to suppress subdivision.
* Date**Angle** (`Angle`): The angle that defines of the outer shape of the helix. Valid range: `-90° < value < 90°`. The default is `0°`. If it is `0°` the helix is cylindrical, else it is conical.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Helix can be created with the `addObject()` method of the document:

```
helix = FreeCAD.ActiveDocument.addObject("Part::Helix", "myHelix")

```

* Where `"myHelix"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

helix = doc.addObject("Part::Helix", "myHelix")
helix.Pitch = 2
helix.Height = 3
helix.Radius = 4
helix.SegmentLength = 21
helix.Angle = 45
helix.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Helix/ro&oldid=1106575>"