---
title: Part Cerc
---
|  |
| --- |
| Part Circle |
| Menu location |
| Part → [Create Primitives](/Part_CreatePrimitives "Part CreatePrimitives") → Circle |
| Workbenches |
| [Part](/Part_Workbench "Part Workbench"), [OpenSCAD](/OpenSCAD_Workbench "OpenSCAD Workbench") |
| Default shortcut |
| *None* |
| Introduced in version |
| - |
| See also |
| .. |
|  |

## Descriere

Un element primitiv geometric este Circle care este disponibil din dialogul Create Primitives în Atelierul de lucru Part.

Această comandă va crea o muchie curbată circulară. Cu valorile implicite, muchia curbată circulară va fi închisă și, prin urmare, va fi un cerc. Dacă proprietățile Unghi 0 sau Unghi 1 sunt modificate din valorile implicite (0 și 360) marginea va fi o curbă deschisă, un arc de cerc.

A Part Circle is in fact a closed counterclockwise circular arc, it can be turned into an arc by changing its Date**Angle1** and/or Date**Angle2** properties.

![](/images/Part_Circle_Example.png)

## Usage

See [Part Primitives](/Part_Primitives#Usage "Part Primitives").

A Part Circle can alternatively be created by selecting three points:

1. In the task panel of the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command select the **![](/images/Part_Circle.svg) Circle** option from the dropdown list.
2. Press the From three points button.
3. Select three vertices in the [3D view](/3D_view "3D view"). There is no need to hold down the Ctrl key.
4. A circle is created.
5. The selected vertices are only used at creation time to calculate the Date**Radius** and Date**Placement** of the circle.

## Example

![](/images/Part_Circle_Scripting_Example.png)

Part Circle from the scripting example

A Part Circle object created with the [scripting example](#Scripting) below is shown here.

### Proprietăți

Crearea unui cerc sau a unui arc de cerc parametric.

Utilizăm meniul ![](/images/Part_CreatePrimitives.png) Crea primitive... → Cerchio. Și apare o fereastră de dialog. Se deschide un dialog care vă permite să setați:

### Primitive Geometrice

|  |  |
| --- | --- |
|  | Cercul Parametri  * **Raza** * **Unghiul 1** * **Unghiul 2** * **Cerc definit din trei puncte** |

See also: [Property editor](/Property_editor "Property editor").

A Part Circle object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Base

* **Radius**: raza muchiei curbate (arc or circle)
* **Angle 0**: Unghiul de pornire a muchiei curbate, (degrees anti-clockwise), valoara implictă este 0
* **Angle 1**: Unghiul de capăt al muchiei curbate, (degrees sens antiorar/trigonometric), valoarea implictă este 360

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Circle can be created with the `addObject()` method of the document:

```
circle = FreeCAD.ActiveDocument.addObject("Part::Circle", "myCircle")

```

* Where `"myCircle"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

circle = doc.addObject("Part::Circle", "myCircle")
circle.Radius = 10
circle.Angle1 = 45
circle.Angle2 = 225
circle.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Circle/ro&oldid=1225734>"