---
title: Part Elipsă
---
|  |
| --- |
| Part Ellipse |
| Menu location |
| Part → [Create Primitives](/Part_CreatePrimitives "Part CreatePrimitives") → Ellipse |
| Workbenches |
| [Part](/Part_Workbench "Part Workbench"), [OpenSCAD](/OpenSCAD_Workbench "OpenSCAD Workbench") |
| Default shortcut |
| *None* |
| Introduced in version |
| - |
| See also |
| .. |
|  |

## Descriere

Un element primitiv geometric este Elipsa care este disponibil din dialogul Create Primitives în Atelierul de lucru Part.

Această comandă va crea o muchie curbată circulară. Cu valorile implicite, muchia curbată circulară va fi închisă și, prin urmare, va fi o elipsă. Dacă proprietățile Unghi 0 sau Unghi 1 sunt modificate din valorile implicite (0 și 360) marginea va fi o curbă deschisă, un arc de elipsă.

A Part Ellipse is in fact a closed counterclockwise elliptical arc, it can be turned into an arc by changing its Date**Angle1** and/or Date**Angle2** properties.

![](/images/Part_Ellipse_Example.png)

## Usage

See [Part Primitives](/Part_Primitives#Usage "Part Primitives").

## Example

![](/images/Part_Ellipse_Scripting_Example.png)

Part Ellipse from the scripting example

A Part Ellipse object created with the [scripting example](#Scripting) below is shown here.

## Properties

See also: [Property editor](/Property_editor "Property editor").

A Part Ellipse object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Base

* Date**MajorRadius** (`Length`): The major radius of the ellipse or elliptical arc. The default is `4mm`.
* Date**MinorRadius** (`Length`): The minor radius of the ellipse or elliptical arc. The default is `2mm`.
* Date**Angle1** (`Angle`): The start angle of the elliptical arc. Valid range: `0° < value <= 360°`. The default is `0°`.
* Date**Angle2** (`Angle`): The end angle of the elliptical arc. Valid range: `0° < value <= 360°`. The default is `360°`. If Date**Angle1** and Date**Angle2** are equal, or if one angle is `0°` and the other `360°`, a full ellipse is created.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Ellipse can be created with the `addObject()` method of the document:

```
ellipse = FreeCAD.ActiveDocument.addObject("Part::Ellipse", "myEllipse")

```

* Where `"myEllipse"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

ellipse = doc.addObject("Part::Ellipse", "myEllipse")
ellipse.MajorRadius = 20
ellipse.MinorRadius = 10
ellipse.Angle1 = 45
ellipse.Angle2 = 135
ellipse.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Ellipse/ro&oldid=1106672>"