---
title: TechDraw Vue interrompue
---
|  |
| --- |
| TechDraw Vue interrompue |
| Emplacement du menu |
| TechDraw → Vues de Techdraw → Insérer une vue interrompue |
| Ateliers |
| [TechDraw](/TechDraw_Workbench/fr "TechDraw Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| 1.0 |
| Voir aussi |
| [TechDraw Vue](/TechDraw_View/fr "TechDraw View/fr") |
|  |

## Description

L'outil **TechDraw Vue interrompue** insère une "vue interrompue" qui est soit basée sur une [vue d'une pièce](/TechDraw_View/fr "TechDraw View/fr") existante, soit sur un ou plusieurs objets, tels que des [corps](/PartDesign_Body/fr "PartDesign Body/fr") ou des [Parts](/Std_Part/fr "Std Part/fr"). La vue interrompue nécessite également une ou plusieurs [esquisses](/Sketcher_NewSketch/fr "Sketcher NewSketch/fr") qui définissent l'emplacement et la taille des zones à supprimer. La vue interrompue se comporte de la même manière que les autres vues. La direction de projection est tirée de la vue de la pièce existante, de la direction de la caméra 3D ou de la normale d'une face sélectionnée.

![](/images/TechDraw_BrokenView_example3d.png)

Une forme à fragmenter et les esquisses définissant les cassures

![](/images/TechDraw_BrokenView_example2d.png)

Le résultat

## Utilisation

1. Vous pouvez faire pivoter la [vue 3D](/3D_view/fr "3D view/fr"). La vue 3D détermine les valeurs initiales des propriétés Données**Direction** et Données**XDirection** de la vue interrompue.
2. Sélectionnez l'objet pour lequel vous souhaitez créer une vue interrompue ou sélectionnez une vue TechDraw existante qui contient cet objet.
3. Ajoutez une ou plusieurs esquisses de rupture à la sélection en les sélectionnant dans la [vue en arborescence](/Tree_view/fr "Tree view/fr"). Chaque esquisse ne doit contenir que deux lignes parallèles. Vous pouvez également utiliser d'autres objets comportant deux bords parallèles.
4. Il existe plusieurs façons de lancer l'outil :
   * Appuyez sur le ![](/images/TechDraw_BrokenView.svg) Insérer une vue interrompue.
   * Sélectionnez l'option **TechDraw → Vues de Techdraw → ![](/images/TechDraw_BrokenView.svg) Insérer une vue interrompue** du menu.

## Propriétés

Voir aussi : [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

Une vue interrompue, en fait un objet `TechDraw::DrawBrokenView`, est dérivée d'une [vue de Part](/TechDraw_View/fr#Propriétés_Vue_de_Part "TechDraw View/fr") et hérite de toutes ses propriétés. Elle possède également les propriétés supplémentaires suivantes :

### Données

Broken View

* Données**Breaks** (`LinkList`) : objets de la vue 3D qui définissent les points de départ et d'arrivée ainsi que la direction des cassures dans cette vue.
* Données**Gap** (`Length`) : distance de séparation entre les cassures dans cette vue (longueur 3D non mise à l'échelle).

## Remarques

* Les cassures doivent être verticales ou horizontales. Les cassures inclinées ne sont pas prises en charge.
* Voir aussi [TechDraw Vue](/TechDraw_View/fr "TechDraw View/fr").

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Une Vue interrompue peut être créée à partir de [macros](/Macros/fr "Macros/fr") et de la console [Python](/Python/fr "Python/fr") en utilisant la fonction suivante :

```
doc = FreeCAD.ActiveDocument
box = doc.Box
profile = doc.Sketch
page = doc.Page

brokenView = doc.addObject("TechDraw::DrawBrokenView", "BrokenView")
page.addView(brokenView)
brokenView.Source= box
brokenView.Breaks = [doc.Sketch]

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_BrokenView/fr&oldid=1490314>"