---
title: TechDraw Cote à partir des points du repère
---
|  |
| --- |
| TechDraw Dimension de repère |
| Emplacement du menu |
| TechDraw → Dimensions → Insérer une cote à partir des points du repère - EXPÉRIMENTAL |
| Ateliers |
| [TechDraw](/TechDraw_Workbench/fr "TechDraw Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| 0.19 |
| Voir aussi |
| [TechDraw Cote horizontale](/TechDraw_HorizontalDimension/fr "TechDraw HorizontalDimension/fr"), [TechDraw Cote verticale](/TechDraw_VerticalDimension/fr "TechDraw VerticalDimension/fr") |
|  |

## Description

L'outil **TechDraw Insérer une cote à partir des points du repère** ajoute une cote linéaire à une vue. La cote est basée sur deux objets points (objets [Draft Point](/Draft_Point/fr "Draft Point/fr"), [Part Point](/Part_Point/fr "Part Point/fr") ou [PartDesign Point](/PartDesign_Point/fr "PartDesign Point/fr")) du modèle 3D.

Le but de cet outil est de fournir une solution de contournement à la corruption des cotes provoquée par des problèmes de « [dénomination topologique](/Topological_naming_problem/fr "Topological naming problem/fr") ». Les points sources doivent utiliser des [Expressions](/Expressions/fr "Expressions/fr") ou d'autres mécanismes contenant pour établir leur position. Étant donné que les points sont des [Objets Document](/App_DocumentObject/fr "App DocumentObject/fr") et non des composants de forme, leur nom ne change pas avec les recalculs et donc ils sont faciles à trouver.

Voir [TechDraw Cote de longueur](/TechDraw_LengthDimension/fr#Propri.C3.A9t.C3.A9s "TechDraw LengthDimension/fr") pour en savoir plus sur les dimensions et les noms topologiques.

## Utilisation

1. Sélectionnez deux objets ponctuels dans la [vue 3D](/3D_view/fr "3D view/fr") ou la [vue en arborescence](/Tree_view/fr "Tree view/fr").
2. Ajoutez la bonne vue TechDraw à la sélection en la sélectionnant dans la [vue en arborescence](/Tree_view/fr "Tree view/fr").
3. Il y a plusieurs façons de lancer l'outil :
   * Appuyez sur le bouton ![](/images/TechDraw_LandmarkDimension.svg) Insérer une cote à partir des points du repère - EXPÉRIMENTAL.
   * Sélectionnez l'option **TechDraw → Dimensions → ![](/images/TechDraw_LandmarkDimension.svg) Insérer une cote à partir des points du repère - EXPÉRIMENTAL** du menu.
4. Une cote est ajoutée à la vue.
5. La cote peut être déplacée jusqu'à la position souhaitée.
6. Si nécessaire, ajoutez des tolérances comme décrit sur [cette page](/TechDraw_Geometric_dimensioning_and_tolerancing/fr#Tolérances "TechDraw Geometric dimensioning and tolerancing/fr").

### Changer les propriétés

Pour modifier les propriétés d'un objet dimension, double-cliquez dessus dans le dessin ou dans la [vue en arborescence](/Tree_view/fr "Tree view/fr"). Cela ouvrira la [boîte de dialogue Dimension](/TechDraw_LengthDimension/fr#Bo.C3.AEte_de_dialogue_Dimension "TechDraw LengthDimension/fr").

## Limitations

L'outil Insérer une cote à partir des points du repère est initialement limité aux cotes « Distance ». D'autres types peuvent être ajoutés si la demande le justifie.

## Remarques

Voir [TechDraw Cote de longueur](/TechDraw_LengthDimension/fr#Remarques/fr "TechDraw LengthDimension/fr").

## Propriétés

Voir [TechDraw Cote de longueur](/TechDraw_LengthDimension/fr#Propri.C3.A9t.C3.A9s/fr "TechDraw LengthDimension/fr").

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

L'outil Insérer une cote à partir des points du repère peut être utilisé dans des [macros](/Macros/fr "Macros/fr") et à partir de la console [Python](/Python/fr "Python/fr") à l'aide des fonctions suivantes :

```
dim1 = FreeCAD.ActiveDocument.addObject("TechDraw::LandmarkDimension", "Landmark")
dim1.Type = "Distance"
dim1.References2D = [(TDView, "Vertex1")]
dim1.References3D = [(Point3d1, "Vertex1")]
dim1.References3D = [(Point3d2, "Vertex1")]
page.addView(dim1)

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_LandmarkDimension/fr&oldid=1342740>"