---
title: TechDraw Hachures géométriques
---
|  |
| --- |
| TechDraw Hachures géométriques |
| Emplacement du menu |
| TechDraw → Hachures → Appliquer un motif de hachure géométrique à une face |
| Ateliers |
| [TechDraw](/TechDraw_Workbench/fr "TechDraw Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| - |
| Voir aussi |
| [TechDraw Hachures par motif](/TechDraw_Hatch/fr "TechDraw Hatch/fr"), [TechDraw Hachures](/TechDraw_Hatching/fr "TechDraw Hatching/fr") |
|  |

## Description

L'outil **TechDraw Hachures géométriques** remplit une région fermée dans une vue avec un motif basé sur une spécification de hachures AutoDesk PAT. Vous pouvez également utiliser l'outil [TechDraw Hachures par motif](/TechDraw_Hatch/fr "TechDraw Hatch/fr") utilise des motifs de hachures basés sur le SVG. Voir [TechDraw Hachures](/TechDraw_Hatching/fr "TechDraw Hatching/fr") pour plus de détails.

![](/images/TechDraw_GeomHatch_example.png)

Motif de hachures géométriques sur une face

## Utilisation

1. Sélectionner une région fermée dans une vue.
2. Il existe plusieurs façons de lancer l'outil :
   * Appuyez sur le bouton ![](/images/TechDraw_GeometricHatch.svg) Appliquer un motif de hachure géométrique à une face.
   * Sélectionnez la **TechDraw → Hachures → ![](/images/TechDraw_GeometricHatch.svg) Appliquer un motif de hachure géométrique à une face**  dans le menu.
3. Le panneau de tâches **Appliquer un motif de hachure géométrique à une face**  s'ouvre.
4. Vous pouvez modifier **Fichier de motifs**, **Nom du motif**, **Echelle du motif**, **Poids du trait** et **Couleur du trait**.
5. Appuyez sur le bouton OK.

## Remarques

* Pour un remplissage en couleur unie, utilisez plutôt [TechDraw Hachures par motif](/TechDraw_Hatch/fr "TechDraw Hatch/fr") et sélectionnez solid.svg comme **Pattern File**.
* Les objets hachurés sont vulnérables au "[problème de nommage topologique](/Topological_naming_problem/fr "Topological naming problem/fr")". Voir [TechDraw Cote de longueur](/TechDraw_LengthDimension/fr "TechDraw LengthDimension/fr") pour plus d'informations. Il est recommandé que le hachurage soit l'une des dernières étapes de votre processus de dessin.
* Un petite nombre de modèles est disponible sur :

:   ```
    $INSTALL_DIR/data/Mod/TechDraw/PAT/FCPAT.pat

    ```
:   Où `$INSTALL_DIR` est le répertoire dans lequel FreeCAD a été installé, par exemple :
:   ```
    /usr/share/freecad/data/Mod/TechDraw/PAT/FCPAT.pat

    ```

## Propriétés

* Données**Source** : vue et la face pour recevoir le motif de hachures.
* Données**File Pattern** : emplacement du fichier PAT à utiliser.
* Données**Name Pattern** : nom de la spécification PAT dans File Pattern.
* Données**Scale Pattern** : échelle à appliquer au motif (doit être> 0.0).
* Vue**Weight Pattern** : épaisseur des lignes de motif.
* Vue**Color Pattern** : couleur des lignes de motif.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Une Hachure géométrique peut être créée à partir de [macros](/Macros/fr "Macros/fr") et à partir de la console [Python](/Python/fr "Python/fr") à l'aide des fonctions suivantes :

```
hatch = FreeCAD.ActiveDocument.addObject("TechDraw::DrawGeomHatch", "GeomHatch")
hatch.Source = (view1, ["Face0"])
hatch.FilePattern = "path/to/myPATfile.pat"
hatch.NamePattern = "Diamond"
page.addView(hatch)

```

Il est également possible d'utiliser le moteur de hachures géométriques de TechDraw pour produire un objet composé dans l'espace 3D. Il faut faire attention que la face de base se trouve sur le plan XY, car l'algorithme n'est pas encore adapté aux autres cas :

```
import TechDraw
face = Part.makePlane(10, 10)
patfile = "path/to/myPATfile.pat"
pattern = "Diamond"
scale = 10
hatch = TechDraw.makeGeomHatch(face, scale, pattern, patfile)
Part.show(hatch)

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_GeometricHatch/fr&oldid=1488458>"