---
title: TechDraw Vue en coupe complexe
---
|  |
| --- |
| TechDraw Vue en coupe complexe |
| Emplacement du menu |
| TechDraw → Vues de Techdraw → Insérer une vue en coupe complexe |
| Ateliers |
| [TechDraw](/TechDraw_Workbench/fr "TechDraw Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| 0.21 |
| Voir aussi |
| [TechDraw Vue en coupe](/TechDraw_SectionView/fr "TechDraw SectionView/fr"), [TechDraw Vue](/TechDraw_View/fr "TechDraw View/fr") |
|  |

## Description

L'outil **TechDraw Vue en coupe complexe** insère une vue en coupe transversale basée sur une vue de la pièce existante et un profil.

![](/images/TechDraw_QuarterSection_example.png)

Une vue en quart de coupe créée avec l'outil Vue en coupe complexe

![](/images/TechDraw_AlignedSection_example.png)

Une vue en coupe alignée créée avec l'outil Vue en coupe complexe

![](/images/TechDraw_OffsetSection_example.png)

Une vue en coupe décalée créée avec l'outil Vue en coupe complexe

## Utilisation

1. Sélectionnez une vue de la pièce et un objet de profil dans la [vue 3D](/3D_view/fr "3D view/fr") ou la [vue en arborescence](/Tree_view/fr "Tree view/fr"). Les profils sont généralement des esquisses, mais tout objet dont la forme peut être transformée en polyligne fonctionnera.
2. Il existe plusieurs façons de lancer l'outil :
   * Appuyez sur le bouton ![](/images/TechDraw_ComplexSection.svg) Insérer une vue en coupe complexe.
   * Sélectionnez l'option **TechDraw → Vues de Techdraw → ![](/images/TechDraw_ComplexSection.svg) Insérer une vue en coupe complexe** dans le menu.
3. Un panneau de tâches s'ouvre et vous aide à calculer les différentes propriétés. Des valeurs raisonnables pour la direction de la vue sont calculées, mais elles peuvent être modifiées.

![](/images/TechDraw_ComplexSection_Taskview1.png)
![](/images/TechDraw_ComplexSection_Taskview2.png)

## Propriétés

Une vue en coupe complexe, en fait un objet `TechDraw::DrawComplexSection`, est dérivée d'une [vue en coupe](/TechDraw_SectionView/fr#Propriétés "TechDraw SectionView/fr"), objet `TechDraw::DrawViewSection`, et hérite de toutes ses propriétés. Elle possède également les propriétés supplémentaires suivantes :

### Données

Cutting Tool

* Données**Cutting Tool Wire Object** : l'objet document dont la forme sera utilisée pour générer le profil de coupe.
* Données**Projection Strategy** : contrôle la façon dont la découpe est effectuée et comment le résultat est projeté sur la page :
  + `Offset` : effectue une découpe simple de la forme source et projette le résultat.
  + `Aligned` : découpe la forme source à l'aide d'un outil créé à partir de chaque segment (bord) du profil de découpe. Les résultats de chaque coupe sont projetés dans un tableau vertical ou horizontal, selon l'orientation du profil de coupe.
  + `NoParallel` : comme Aligned, mais les segments de profil qui sont parallèles à la direction de la vue sont ignorés.

## Remarques

Voir [TechDraw Vue en coupe](/TechDraw_SectionView/fr#Remarques "TechDraw SectionView/fr")

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Une Vue en coupe complexe peut être créée à partir de [macros](/Macros/fr "Macros/fr") et à partir de la console [Python](/Python/fr "Python/fr") à l'aide des fonctions suivantes :

```
doc = FreeCAD.ActiveDocument
box = doc.Box
profile = doc.Sketch
page = doc.Page

view = doc.addObject("TechDraw::DrawViewPart", "View")
page.addView(view)
view.Source = box
view.Direction = (0, 0, 1)

section = doc.addObject("TechDraw::DrawComplexSection", "ComplexSection")
page.addView(section)
section.BaseView = view
section.CuttingToolWireObject = profile
section.Direction = (0, 1, 0)
section.SectionNormal = (-1, 0, 0)

```

## Exemples

Pour plus d'informations sur les coupes et certains cas d'utilisation, consultez : [TechDraw Exemples de coupes](/TechDraw_Section_Examples/fr "TechDraw Section Examples/fr").

![](/images/TechDraw_ExampleSection-10.png)
![](/images/TechDraw_ExampleSection-13.png)
![](/images/TechDraw_ExampleSection-15.png)
![](/images/TechDraw_ExampleSection-17.png)
![](/images/TechDraw_ExampleSection-34.png)
![](/images/TechDraw_ExampleSection-35.png)

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_ComplexSection/fr&oldid=1571037>"