---
title: TechDraw Cote de rayon
---
|  |
| --- |
| TechDraw Cote de rayon |
| Emplacement du menu |
| TechDraw → Dimensions → Insérer une cote de rayon |
| Ateliers |
| [TechDraw](/TechDraw_Workbench/fr "TechDraw Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| - |
| Voir aussi |
| [TechDraw Cote de diamètre](/TechDraw_DiameterDimension/fr "TechDraw DiameterDimension/fr") |
|  |

## Description

L'outil **TechDraw Cote de rayon** ajoute une cote de rayon à une vue. Cette cote peut être appliquée à toute arête qui est un cercle ou un arc de cercle.

![](/images/TechDraw_Dimension_Radius_example.png)

Mesurer un cercle, indiquant le rayon

## Comment faire

1. Sélectionnez un cercle ou un arc de cercle. La géométrie peut être sélectionnée dans la [vue 3D](/3D_view/fr "3D view/fr") ou dans le dessin. Notez que certains arcs qui semblent circulaires sont en fait des ellipses ou des B-splines. Dans ce cas, vous ne pouvez pas définir une dimension de rayon.
2. Si vous avez sélectionné une géométrie dans la vue 3D : ajoutez la bonne vue TechDraw à la sélection en la sélectionnant dans la [vue en arborescence](/Tree_view/fr "Tree view/fr").
3. Il y a plusieurs façons de lancer l'outil :
   * [introduit dans la version 1.0](/Release_notes_1.0/fr "Release notes 1.0/fr") : si la [préférence](/TechDraw_Preferences/fr#Cotes "TechDraw Preferences/fr") **Outils de cotation** est réglée sur `Outil unique` (par défaut) : appuyez sur la flèche vers le bas à droite du bouton ![](/images/TechDraw_Dimension.svg)![](/images/Toolbar_flyout_arrow.svg) et sélectionnez l'option **![](/images/TechDraw_ExtensionCreateHorizChainDimension.svg) Cotes horizontales** du menu déroulant.
   * Si cette préférence a une valeur différente (et dans version 0.21 et précédentes) : appuyez sur le bouton ![](/images/TechDraw_RadiusDimension.svg) Insérer une cote de rayon.
   * Sélectionnez l'option **TechDraw → Dimensions → ![](/images/TechDraw_RadiusDimension.svg) Insérer une cote de rayon** du menu.
4. Une cote est ajoutée à la vue.
5. La cote peut être déplacée jusqu'à la position souhaitée.
6. Si nécessaire, ajoutez des tolérances comme décrit sur [cette page](/TechDraw_Geometric_dimensioning_and_tolerancing/fr#Tol.C3.A9rances "TechDraw Geometric dimensioning and tolerancing/fr").

### Affichage des mesures 3D

Voir [TechDraw Cote de longueur](/TechDraw_LengthDimension/fr#Affichage_des_mesures_3D "TechDraw LengthDimension/fr").

### Changer les propriétés

Pour modifier les propriétés d'un objet dimension, double-cliquez dessus dans le dessin ou dans la [Vue en arborescence](/Tree_view/fr "Tree view/fr"). Cela ouvrira la [Boîte de dialogue Dimension](/TechDraw_LengthDimension/fr#Bo.C3.AEte_de_dialogue_Dimension "TechDraw LengthDimension/fr").

## Limitations

Les objets Cote sont vulnérables au "[problèmes de nommage topologique](/Topological_naming_problem/fr "Topological naming problem/fr")". Voir [TechDraw Cote de longueur](/TechDraw_LengthDimension/fr "TechDraw LengthDimension/fr")

## Remarques

Voir [TechDraw Cote de longueur](/TechDraw_LengthDimension/fr#Remarques/fr "TechDraw LengthDimension/fr").

## Propriétés

Voir [Cote de longueur](/TechDraw_LengthDimension/fr#Propri.C3.A9t.C3.A9s/fr "TechDraw LengthDimension/fr").

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

L'outil Cote de rayon peut être utilisé dans des [macros](/Macros/fr "Macros/fr") et à partir de la console [Python](/Python/fr "Python/fr") à l'aide des fonctions suivantes:

```
dim1 = FreeCAD.ActiveDocument.addObject("TechDraw::DrawViewDimension", "Dimension")
dim1.Type = "Radius"
dim1.References2D=[(view1, "Edge1")]
page.addView(dim1)

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_RadiusDimension/fr&oldid=1488528>"