---
title: TechDraw Groupe de projections
---
|  |
| --- |
| TechDraw Groupe de projections |
| Emplacement du menu |
| TechDraw → Vues de Techdraw → Insérer un groupe de projections |
| Ateliers |
| [TechDraw](/TechDraw_Workbench/fr "TechDraw Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| - |
| Voir aussi |
| [TechDraw Vue](/TechDraw_View/fr "TechDraw View/fr") |
|  |

## Description

L'outil **TechDraw Groupe de projections** crée une [projection multi-vue](https://en.wikipedia.org/wiki/Multiview_projection) d'un ou plusieurs objets 3D, en utilisant la projection traditionnelle [projection premier angle](https://en.wikipedia.org/wiki/Multiview_orthographic_projection#First-angle_projection) ou [projection troisième angle](https://en.wikipedia.org/wiki/Multiview_orthographic_projection#Third-angle_projection). Les vues isométriques des 4 coins de devant peuvent également être incluses.

[introduit dans la version 1.0](/Release_notes_1.0/fr "Release notes 1.0/fr") : l'outil [TechDraw Vue](/TechDraw_View/fr "TechDraw View/fr") peut également créer un groupe de projection. Il est conseillé d'utiliser cet outil à la place.

![](/images/TechDraw_ProjGroup_example.png)

Trois vues orthogonales et une vue isométrique d'un objet solide

## Utilisation

Voir [TechDraw Vue](/TechDraw_View/fr#Utilisation_Groupe_de_projection_d'élément_et_Groupe_de_projection "TechDraw View/fr"), mais pour lancer l'outil, sélectionnez l'option **TechDraw → Vues de Techdraw → ![](/images/TechDraw_ProjectionGroup.svg) Insérer un groupe de projections** du menu.

## Propriétés

Voir aussi : [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

Un groupe de projections, en fait un objet `TechDraw::DrawProjGroup`, possède les [propriétés](/TechDraw_View/fr#Propriétés_Vue_de_Part "TechDraw View/fr") communes à tous les types de vues. Elle possède également les propriétés supplémentaires suivantes :

### Données

Base

* Données**Source** (`LinkList`) : liens vers les objets dessinables à représenter.
* Données**XSource** (`XLLinkList`) : liens vers les objets dessinables dans un fichier externe.
* Données**Anchor** (`Link`) : vue centrale du groupe. Normalement, il s'agit de la vue de face.
* Données**ProjectionType** (`Enumeration`): `First Angle` ou `Third Angle`.

Collection

* Données**Views** (`LinkList`) : liens vers les vues de ce Groupe de projections.

Distribute

* Données**Auto Distribute** (`Bool`) : si `true`, espace automatiquement les vues individuelles. Utilisez `false` pour un positionnement manuel.
* Données**spacing X** (`Length`) : espace horizontal entre les vues lorsqu'elles sont positionnées automatiquement. Notez que l'échelle et la taille des autres vues du groupe influencent également l'espacement.
* Données**spacing Y** (`Length`) : espace vertical entre les vues lorsqu'elles sont positionnées automatiquement.

## Remarques

Le groupe de projections dans son ensemble hérite de X, Y, ScaleType, Scale et Rotation à partir de la vue de base.

Chaque vue au sein du groupe hérite de toutes les propriétés de la vue de la pièce, mais l'objet ProjectionGroup contrôle l'échelle de toutes ses vues membres.

La propriété RotationVector des différentes vues du groupe est obsolète à partir de v0.19. Utilisez XDirection à la place.

Notez que la boîte centrale affiche la direction de projection en cours de la vue principale. Elle ne peut pas être utilisée pour changer de direction.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Un Groupe de projections peut être crée à partir de [macros](/Macros/fr "Macros/fr") et de la console [Python](/Python/fr "Python/fr") en utilisant la fonction suivante :

```
import FreeCAD as App

doc = App.ActiveDocument
cyl = doc.addObject("Part::Cylinder", "Cylinder")
doc.recompute()

page = doc.addObject("TechDraw::DrawPage", "Page")
template = doc.addObject("TechDraw::DrawSVGTemplate", "Template")
template.Template = App.getResourceDir() + "Mod/TechDraw/Templates/A4_LandscapeTD.svg"
page.Template = template

# Toggle the visibility of the page to ensure its width and height are updated (hack):
page.Visibility = False
page.Visibility = True

group = doc.addObject("TechDraw::DrawProjGroup", "ProjGroup")
page.addView(group)
group.Source = [cyl]
group.ProjectionType = "Third Angle"

front_view = group.addProjection("Front") # First projection will become the Anchor.
group.Anchor.Direction = (0, 1, 0)
group.Anchor.RotationVector = (1, 0, 0)

left_view = group.addProjection("Left")
top_view = group.addProjection("Top")

group.X = page.PageWidth / 2
group.Y = page.PageHeight / 2

doc.recompute()

```

Remarque : le groupe de projection doit toujours être ajouté à la page, `page.addView(group)`, avant d'ajouter des projections au groupe. Cela permet au groupe de projections d'utiliser les valeurs de paramètre par défaut dérivées de la page parente.

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_ProjectionGroup/fr&oldid=1490517>"