---
title: TechDraw Cote étendue horizontale
---
|  |
| --- |
| TechDraw Cote étendue horizontale |
| Emplacement du menu |
| TechDraw → Dimensions → Insérer une cote étendue horizontale |
| Ateliers |
| [TechDraw](/TechDraw_Workbench/fr "TechDraw Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| 0.19 |
| Voir aussi |
| [TechDraw Cote de longueur](/TechDraw_LengthDimension/fr "TechDraw LengthDimension/fr"), [TechDraw Cote étendue verticale](/TechDraw_VerticalExtentDimension/fr "TechDraw VerticalExtentDimension/fr") |
|  |

## Description

L'outil **TechDraw Cote étendue horizontale** ajoute une cote linéaire à une vue. La cote s'étend du point le plus à gauche des objets sélectionnés jusqu'au point le plus à droite.

![](/images/TechDraw_Dimension_Horizontal_Extent_example.png)

Cotes étendues horizontale et verticale d'une surface B-spline

## Utilisation

1. Sélectionnez une vue ou une collection d'arêtes dans une vue.
2. Il y a plusieurs façons de lancer l'outil :
   * [introduit dans la version 1.0](/Release_notes_1.0/fr "Release notes 1.0/fr") : si la [préférence](/TechDraw_Preferences/fr#Cotes "TechDraw Preferences/fr") **Outils de cotation** est réglée sur `Outil unique` (par défaut) : appuyez sur la flèche vers le bas à droite du bouton ![](/images/TechDraw_Dimension.svg)![](/images/Toolbar_flyout_arrow.svg) et sélectionnez l'option **![](/images/TechDraw_ExtensionCreateHorizChainDimension.svg) Cotes horizontales** du menu déroulant.
   * Si cette préférence a une valeur différente (et dans version 0.21 et précédentes) : appuyez sur le bouton ![](/images/TechDraw_HorizontalExtentDimension.svg) Insérer une cote étendue horizontale.
   * Sélectionnez l'option **TechDraw → Dimensions → ![](/images/TechDraw_HorizontalExtentDimension.svg) Insérer une cote étendue horizontale** du menu.
3. Une cote est ajoutée à la vue.
4. La cote peut être déplacée jusqu'à la position souhaitée.
5. Si nécessaire, ajoutez des tolérances comme décrit sur [cette page](/TechDraw_Geometric_dimensioning_and_tolerancing/fr#Tolérances "TechDraw Geometric dimensioning and tolerancing/fr").

### Changer les propriétés

Pour modifier les propriétés d'un objet dimension, double-cliquez dessus dans le dessin ou dans la [vue en arborescence](/Tree_view/fr "Tree view/fr"). Cela ouvrira la [boîte de dialogue Dimension](/TechDraw_LengthDimension/fr#Bo.C3.AEte_de_dialogue_Dimension "TechDraw LengthDimension/fr").

## Limitations

Les objets Cote sont vulnérables au "[problème de nommage topologique](/Topological_naming_problem/fr "Topological naming problem/fr")". Voir [TechDraw Cote de longueur](/TechDraw_LengthDimension/fr "TechDraw LengthDimension/fr").

## Remarques

Voir [TechDraw Cote de longueur](/TechDraw_LengthDimension/fr#Remarques/fr "TechDraw LengthDimension/fr").

## Propriétiés

Voir [TechDraw Cote de longueur](/TechDraw_LengthDimension/fr#Propri.C3.A9t.C3.A9s "TechDraw LengthDimension/fr"). Exceptions notées ci-dessous.

### Données

Base

* Données**Measure Type** (`Enumeration`) : pas encore implémenté pour les cotes étendues.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

L'outil Cote étendue horizontale peut être utilisé dans des [macros](/Macros/fr "Macros/fr") et à partir de la console [Python](/Python/fr "Python/fr") à l'aide des fonctions suivantes:

```
selection = ['Edge1', 'Edge2']                      # or [] for all

TechDraw.makeExtentDim(view1, selection, 0)         # view1 is a DrawViewPart; 0 for horizontal
App.ActiveDocument.DimExtent.Y = -60                # offset dimension line from dimensioned edges in Y direction
App.ActiveDocument.DimExtent.X = 10                 # offset dimension text along dimension line in X direction
App.ActiveDocument.DimExtent.FormatSpec = '%.0f'    # Dimension format

TechDraw.makeExtentDim(view1, selection, 1)         # view1 is a DrawViewPart; 1 for vertical
App.ActiveDocument.DimExtent001.X = -130            # offset dimension line from dimensioned edges in X direction
App.ActiveDocument.DimExtent001.Y = 10              # offset dimension text along dimension line in Y direction
App.ActiveDocument.DimExtent001.FormatSpec = '%.0f'

# Note the dimension names are 'DimExtent', 'DimExtent001' etc in the order created.

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_HorizontalExtentDimension/fr&oldid=1488474>"