---
title: TechDraw Sommets quadrants
---
|  |
| --- |
| TechDraw Sommets quadrants |
| Emplacement du menu |
| TechDraw → Ajouter des sommets → Ajouter des sommets quadrants |
| Ateliers |
| [TechDraw](/TechDraw_Workbench/fr "TechDraw Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| 0.19 |
| Voir aussi |
| [TechDraw Point cosmétique](/TechDraw_CosmeticVertex/fr "TechDraw CosmeticVertex/fr"), [TechDraw Point milieu](/TechDraw_Midpoints/fr "TechDraw Midpoints/fr") |
|  |

## Description

L'outil **TechDraw Sommets quadrants** ajoute trois [points cosmétiques](/TechDraw_CosmeticVertex/fr "TechDraw CosmeticVertex/fr") sur la longueur d'une ou plusieurs arêtes sélectionnées. Les sommets sont placés à 25 %, 50 % et 75 % de la longueur de l'arête. Pour une arête circulaire, cela se traduit par des sommets cosmétiques à 90°, 180° et 270°, en plus de son sommet géométrique à 0°.

![](/images/TechDraw_CosmeticQuadrant_Sample.png)

Les sommets cosmétiques au quadrant d'un cercle

## Utilisation

1. Sélectionnez une ou plusieurs arêtes dans une vue. Toutes les arêtes peuvent être sélectionnées, pas seulement les cercles.
2. Il y a plusieurs façons de lancer l'outil :
   * Appuyez sur le bouton ![](/images/TechDraw_Quadrants.svg) Ajouter des sommets quadrants.
   * Sélectionnez l'option **TechDraw → Ajouter des sommets → ![](/images/TechDraw_Quadrants.svg) Ajouter des sommets quadrants** du menu.

## Remarques

* Les sommets cosmétiques créés ne sont pas paramétriquement liés aux arêtes sélectionnées.
* Pour supprimer un sommet cosmétique, sélectionnez-le et appuyez sur Supprimer. [introduit dans la version 1.0](/Release_notes_1.0/fr "Release notes 1.0/fr")

## Propriétés

Les points cosmétiques n'ont pas de propriétés propres car ils ne sont pas des objets de document. Ils partagent les paramètres de couleur et de taille avec des points de géométrie réguliers.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Les points cosmétiques ne sont pas accessibles par [macros](/Macros/fr "Macros/fr") ni par la console [Python](/Python/fr "Python/fr") pour le moment. Ce bout de code supprimera tous les points cosmétiques de la vue.

```
v = App.ActiveDocument.View
v.clearCV()
App.ActiveDocument.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_Quadrants/fr&oldid=1413139>"