---
title: TechDraw Points médians
---
|  |
| --- |
| TechDraw Points médians |
| Emplacement du menu |
| TechDraw → Ajouter des sommets → Ajouter des points médians |
| Ateliers |
| [TechDraw](/TechDraw_Workbench/fr "TechDraw Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| 0.19 |
| Voir aussi |
| [TechDraw Point cosmétique](/TechDraw_CosmeticVertex/fr "TechDraw CosmeticVertex/fr"), [TechDraw Sommets quadrants](/TechDraw_Quadrants/fr "TechDraw Quadrants/fr") |
|  |

## Description

L'outil **TechDraw Points médians** ajoute des [points cosmétiques](/TechDraw_CosmeticVertex/fr "TechDraw CosmeticVertex/fr") au point médian d'une ou plusieurs arêtes sélectionnées.

![](/images/TechDraw_CosmeticMidpoint_Sample.png)

Points cosmétiques au milieu d'arêtes

## Utilisation

1. Sélectionner une ou plusieurs arêtes dans une vue.
2. Il y a plusieurs façons de lancer l'outil :
   * Appuyez sur le bouton ![](/images/TechDraw_Midpoints.svg) Ajouter des sommets de points médians.
   * Sélectionnez l'option **TechDraw → Ajouter des sommets → ![](/images/TechDraw_Midpoints.svg) Ajouter des points médians** du menu.

## Remarques

* Les sommets cosmétiques créés ne sont pas paramétriquement liés aux arêtes sélectionnées.
* Pour supprimer un sommet cosmétique, sélectionnez-le et appuyez sur Supprimer. [introduit dans la version 1.0](/Release_notes_1.0/fr "Release notes 1.0/fr")

## Propriétés

Les points cosmétiques n'ont pas de propriétés propres car ils ne sont pas des objets de document. Ils partagent les paramètres de couleur et de taille avec des points de géométrie réguliers.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Les points cosmétiques ne sont pas accessibles par [macros](/Macros/fr "Macros/fr") ni par la console [Python](/Python/fr "Python/fr") pour le moment. Ce bout de code supprimera tous les points cosmétiques de la vue.

```
v = App.ActiveDocument.View
v.clearCV()
App.ActiveDocument.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=TechDraw_Midpoints/fr&oldid=1422572>"