---
title: Part Piano
---
|  |
| --- |
| Part Piano |
| Posizione nel menu |
| Parte → [Crea primitive](/Part_Primitives/it "Part Primitives/it") → Piano |
| Ambiente |
| [Part](/Part_Workbench/it "Part Workbench/it"), [OpenSCAD](/OpenSCAD_Workbench/it "OpenSCAD Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Parte Primitive](/Part_Primitives/it "Part Primitives/it") |
|  |

## Descrizione

Un ![](/images/Part_Plane.svg) **Part Piano** è un piano rettangolare parametrico che può essere creato con il comando ![](/images/Part_Primitives.svg) [Part Primitive](/Part_Primitives/it "Part Primitives/it"). Nel sistema di coordinate definito dalla sua proprietà Dati**Placement**, il piano giace sul piano XY con l'angolo anteriore sinistro all'origine e il bordo anteriore parallelo all'asse X.

![](/images/Part_Plane_Example.png)

## Utilizzo

Vedere [Part Primitive](/Part_Primitives/it#Utilizzo "Part Primitives/it").

## Esempio

![](/images/Part_Plane_Scripting_Example.png)

Part Piano dall'esempio di scripting

Qui viene mostrato un oggetto Part Piano creato con l'[esempio di scripting](#Script) riportato di seguito.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Part Piano deriva da un oggetto [Funzione Part](/Part_Feature/it "Part Feature/it") e ne eredita tutte le proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Attachment

L'oggetto ha le stesse proprietà di collegamento di un [Part Part2DObject](/Part_Part2DObject/it#Dati "Part Part2DObject/it").

Plane

* Dati**Length** (`Length`): la lunghezza del piano. Questa è la dimensione nella sua direzione X. Il valore predefinito è `10mm`.
* Dati**Width** (`Length`): la larghezza del piano. Questa è la dimensione nella sua direzione Y. Il valore predefinito è `10mm`.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Script di Part](/Part_scripting/it "Part scripting/it") e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

È possibile creare una Part Piano con il metodo `addObject()` del documento:

```
plane = FreeCAD.ActiveDocument.addObject("Part::Plane", "myPlane")

```

* Dove `"myPlane"` è il nome dell'oggetto.
* La funzione restituisce l'oggetto appena creato.

Esempio:

```
import FreeCAD as App

doc = App.activeDocument()

plane = doc.addObject("Part::Plane", "myPlane")
plane.Length = 4
plane.Width = 8
plane.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(20, 75, 60))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Plane/it&oldid=1345695>"