---
title: Part Punto
---
|  |
| --- |
| Part Punto |
| Posizione nel menu |
| Parte → [Crea primitive](/Part_Primitives/it "Part Primitives/it") → Punto |
| Ambiente |
| [Part](/Part_Workbench/it "Part Workbench/it"), [OpenSCAD](/OpenSCAD_Workbench/it "OpenSCAD Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Part Primitive](/Part_Primitives/it "Part Primitives/it") |
|  |

## Descrizione

Un ![](/images/Part_Point.svg) **Part Punto** è un punto parametrico che può essere creato con il comando ![](/images/Part_Primitives.svg) [Part Primitive](/Part_Primitives/it "Part Primitives/it"). Le sue coordinate sono relative al sistema di coordinate definito dalla sua proprietà Dati**Placement**.

## Utilizzo

Vedere [Part Primitive](/Part_Primitives/it#Utilizzo "Part Primitives/it").

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Part Punto deriva da un oggetto [Part Feature](/Part_Feature "Part Feature") e ne eredita tutte le proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Attachment

L'oggetto ha le stesse proprietà di collegamento di un [Part Part2DObject](/Part_Part2DObject/it#Dati "Part Part2DObject/it").

Base

* Dati**X** (`Distance`): la coordinata X del punto. Il valore predefinito è `0mm`.
* Dati**Y** (`Distance`): la coordinata Y del punto. Il valore predefinito è `0mm`.
* Dati**Z** (`Distance`): la coordinata Z del punto. Il valore predefinito è `0mm`.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Script di Part](/Part_scripting/it "Part scripting/it") e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

È possibile creare una Part Punto con il metodo `addObject()` del documento:

```
point = FreeCAD.ActiveDocument.addObject("Part::Vertex", "myPoint")

```

* Dove `"myPoint"` è il nome dell'oggetto.
* La funzione restituisce l'oggetto appena creato.

Esempio:

```
import FreeCAD as App

doc = App.activeDocument()

point = doc.addObject("Part::Vertex", "myPoint")
point.X = 1
point.Y = 2
point.Z = 3

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Point/it&oldid=1351456>"