---
title: Part Ellisse
---
|  |
| --- |
| Part Ellisse |
| Posizione nel menu |
| Parte → [Crea primitive](/Part_Primitives/it "Part Primitives/it") → Ellisse |
| Ambiente |
| [Part](/Part_Workbench/it "Part Workbench/it"), [OpenSCAD](/OpenSCAD_Workbench/it "OpenSCAD Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Part Primitive](/Part_Primitives/it "Part Primitives/it") |
|  |

## Descrizione

Una ![](/images/Part_Ellipse.svg) **Part Ellisse** è una forma parametrica che può essere creata con il comando ![](/images/Part_Primitives.svg) [Part Primitive](/Part_Primitives/it "Part Primitives/it"). Nel sistema di coordinate definito dalla sua proprietà Dati**Placement**, l'ellisse si trova sul piano XY con il centro nell'origine. Il suo asse maggiore è parallelo all'asse X.

Una Part Ellisse è infatti un arco ellittico chiuso in senso antiorario, può essere trasformato in un arco modificando le sue proprietà Dati**Angle1** e/o Dati**Angle2**.

![](/images/Part_Ellipse_Example.png)

## Utilizzo

Vedere [Part Primitive](/Part_Primitives/it#Utilizzo "Part Primitives/it").

## Esempio

![](/images/Part_Ellipse_Scripting_Example.png)

Part Ellisse dall'esempio di scripting

Qui viene mostrato un oggetto Part Ellisse creato con l'[esempio di scripting](#Script) riportato di seguito.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Part Ellisse deriva da un oggetto [Funzione Part](/Part_Feature/it "Part Feature/it") e ne eredita tutte le proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Attachment

L'oggetto ha le stesse proprietà di collegamento di un [Part Part2DObject](/Part_Part2DObject/it#Dati "Part Part2DObject/it").

Base

* Dati**MajorRadius** (`Length`): il raggio maggiore dell'ellisse o dell'arco ellittico. Il valore predefinito è `4mm`.
* Dati**MinorRadius** (`Length`): il raggio minore dell'ellisse o dell'arco ellittico. Il valore predefinito è `2mm`.
* Dati**Angle1** (`Angle`): l'angolo iniziale dell'arco ellittico. Intervallo valido: `0° < valore <= 360°`. Il valore predefinito è `0°`.
* Dati**Angle2** (`Angle`): l'angolo finale dell'arco ellittico. Intervallo valido: `0° < valore <= 360°`. Il valore predefinito è `360°`. Se Dati**Angle1** e Dati**Angle2** sono uguali, o se un angolo è `0°` e l'altro `360°`, viene creata un'ellisse completa.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Script di Part](/Part_scripting/it "Part scripting/it") e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

È possibile creare un Part Ellisse con il metodo `addObject()` del documento:

```
ellipse = FreeCAD.ActiveDocument.addObject("Part::Ellipse", "myEllipse")

```

* Dove `"myEllipse"` è il nome dell'oggetto.
* La funzione restituisce l'oggetto appena creato.

Esempio:

```
import FreeCAD as App

doc = App.activeDocument()

ellipse = doc.addObject("Part::Ellipse", "myEllipse")
ellipse.MajorRadius = 20
ellipse.MinorRadius = 10
ellipse.Angle1 = 45
ellipse.Angle2 = 135
ellipse.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Ellipse/it&oldid=1351393>"