---
title: Part Prisma
---
|  |
| --- |
| Part Prisma |
| Posizione nel menu |
| Parte → [Crea primitive](/Part_Primitives/it "Part Primitives/it") → Prisma |
| Ambiente |
| [Part](/Part_Workbench/it "Part Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| 0.14 |
| Vedere anche |
| [Part Primitive](/Part_Primitives/it "Part Primitives/it") |
|  |

## Descrizione

Un ![](/images/Part_Prism.svg) **Part Prisma** è un solido parametrico che può essere creato con il comando ![](/images/Part_Primitives.svg) [Part Primitive](/Part_Primitives/it "Part Primitives/it") . È il risultato dell'estrusione di un poligono regolare lungo un percorso rettilineo. Nel sistema di coordinate definito dalla sua proprietà Dati**Placement**, la faccia inferiore del prisma si trova sul piano XY con il centro nell'origine e uno dei suoi vertici sull'asse X.

![](/images/Part_Prism_Example.png)

## Utilizzo

Vedere [Part Primitive](/Part_Primitives/it#Utilizzo "Part Primitives/it").

## Esempio

![](/images/Part_Prism_Scripting_Example.png)

Part Prisma dall'esempio di scripting

Qui viene mostrato un oggetto Part Prisma creato con l'[esempio di scripting](#Script) riportato di seguito.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Part Prisma deriva da un oggetto [Funzione Part](/Part_Feature/it "Part Feature/it") e ne eredita tutte le proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Attachment

L'oggetto ha le stesse proprietà di collegamento di un [Part Part2DObject](/Part_Part2DObject/it#Dati "Part Part2DObject/it").

Prism

* Dati**Polygon** (`IntegerConstraint`): il numero di lati del poligono. Il valore predefinito è `6`.
* Dati**Circumradius** (`Length`): il raggio del cerchio che circoscrive il poligono, la distanza dal centro del poligono a uno dei suoi vertici. Il valore predefinito è `2mm`.
* Dati**Height** (`Length`): l'altezza del prisma. Il valore predefinito è `10mm`.
* Dati**First Angle** (`Angle`): l'angolo tra la direzione di estrusione del prisma e il suo asse Z positivo, misurato intorno al suo asse Y. L'angolo è positivo rispetto al suo asse X positivo. Intervallo valido: `0° <= valore < 90°`. Il valore predefinito è `0°`.
* Dati**Second Angle** (`Angle`): l'angolo tra la direzione di estrusione del prisma e il suo asse Z positivo, misurato intorno al suo asse X. L'angolo è positivo rispetto al suo asse Y positivo. Intervallo valido: `0° <= valore < 90°`. Il valore predefinito è `0°`.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Script di Part](/Part_scripting/it "Part scripting/it") e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

È possibile creare una Part Prisma con il metodo `addObject()` del documento:

```
prism = FreeCAD.ActiveDocument.addObject("Part::Prism", "myPrism")

```

* Dove `"myPrism"` è il nome dell'oggetto.
* La funzione restituisce l'oggetto appena creato.

Esempio:

```
import FreeCAD as App

doc = App.activeDocument()

prism = doc.addObject("Part::Prism", "myPrism")
prism.Polygon = 5
prism.Circumradius = 10
prism.Height = 50
prism.FirstAngle = 22.5
prism.SecondAngle = 45
prism.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(60, 75, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Prism/it&oldid=1350828>"