---
title: Partː Tubo
---
|  |
| --- |
| Part Tubo |
| Posizione nel menu |
| Parte → Primitive → Crea tubo |
| Ambiente |
| [Part](/Part_Workbench/it "Part Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| 0.19 |
| Vedere anche |
| [Part Primitive](/Part_Primitives/it "Part Primitives/it") |
|  |

## Descrizione

Il comando ![](/images/Part_Tube.svg) **Part Tubo** crea un tubo parametrico solido. Nel sistema di coordinate definito dalla sua proprietà Dati**Placement**, la faccia inferiore del tubo si trova sul piano XY con il centro nell'origine.

![](/images/Part_Tube_Example.png)

## Utilizzo

### Crea

1. Esistono diversi modi per richiamare il comando:
   * Premere il pulsante ![](/images/Part_Tube.svg) Crea tubo.
   * Selezionare l'opzione **Parte → Primitive → ![](/images/Part_Tube.svg) Crea tubo** dal menu.
2. Si apre il pannello delle attività **Tubo** e un'anteprima del tubo viene visualizzata nella [Vista 3D](/3D_view/it "3D view/it").
3. Specificare le dimensioni.
4. L'anteprima viene aggiornata dinamicamente.
5. Premere il pulsante OK.
6. Il tubo viene creato.
7. Facoltativamente, modificare il Dati**Placement** del tubo nel [Editor delle proprietà](/Property_editor/it "Property editor/it") o con il comando ![](/images/Std_TransformManip.svg) [Trasforma](/Std_TransformManip/it "Std TransformManip/it").

### Modifica

1. Fare doppio clic sul tubo nella [Vista ad albero](/Tree_view/it "Tree view/it")
2. Si apre il pannello delle azioni **Tubo**.
3. Modificare una o più dimensioni.
4. Il tubo viene aggiornato dinamicamente nella [vista 3D](/3D_view/it "3D view/it").
5. Premere il pulsante OK.

## Esempio

![](/images/Part_Tube_Scripting_Example.png)

Part Tubo dall'esempio di scripting

Qui viene mostrato un oggetto Part Tubo creato con l'[esempio di scripting](#Script) riportato di seguito.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Part Tubo deriva da un oggetto [Funzione Part](/Part_Feature/it "Part Feature/it") e ne eredita tutte le proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Attachment

L'oggetto ha le stesse proprietà di collegamento di un [Part Part2DObject](/Part_Part2DObject/it#Dati "Part Part2DObject/it").

Tube

* Dati**Height** (`Length`): l'altezza del tubo. Il valore predefinito è `10mm`.
* Dati**Inner Radius** (`Length`): il raggio interno del tubo. Deve essere inferiore a Dati**Outer Radius**. Può essere `0`. Il valore predefinito è `2mm`.
* Dati**Outer Radius** (`Length`): il raggio esterno del tubo. Deve essere maggiore di Dati**Inner Radius**. Il valore predefinito è `5mm`.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Script di Part](/Part_scripting/it "Part scripting/it") e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

Un Part Tubo può essere creato con il metodo `addTube()` ([disponibile dalla versione 0.20](/Release_notes_0.20/it "Release notes 0.20/it")) del modulo Shapes:

```
tube = Shapes.addTube(FreeCAD.ActiveDocument, "myTube")

```

* Dove `"myTube"` è il nome dell'oggetto.
* La funzione restituisce l'oggetto appena creato.

Esempio:

```
import FreeCAD as App
from BasicShapes import Shapes

doc = App.activeDocument()

tube = Shapes.addTube(FreeCAD.ActiveDocument, "myTube")
tube.Height = 20
tube.InnerRadius = 2
tube.OuterRadius = 3
tube.Placement = App.Placement(App.Vector(2, 4, 5), App.Rotation(60, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Tube/it&oldid=1468242>"