---
title: Part Spirale
---
|  |
| --- |
| Part Spirale |
| Posizione nel menu |
| Parte → [Crea primitive](/Part_Primitives/it "Part Primitives/it") → Spirale |
| Ambiente |
| [Part](/Part_Workbench/it "Part Workbench/it"), [OpenSCAD](/OpenSCAD_Workbench/it "OpenSCAD Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| 0.14 |
| Vedere anche |
| [Part Primitive](/Part_Primitives/it "Part Primitives/it") |
|  |

## Descrizione

Una ![](/images/Part_Spiral.svg) **Part Spirale** è una forma parametrica che può essere creata con il comando ![](/images/Part_Primitives.svg) [Part Primitive](/Part_Primitives/it "Part Primitives/it") . Nel sistema di coordinate definito dalla sua proprietà Dati**Placement**, la spirale giace sul piano XY con il centro nell'origine e il punto iniziale sull'asse X. Si allarga girando in senso antiorario.

![](/images/Part_Spiral_Example.png)

## Utilizzo

Vedere [Part Primitive](/Part_Primitives/it#Utilizzo "Part Primitives/it").

## Esempio

![](/images/Part_Spiral_Scripting_Example.png)

Part Spirale dall'esempio di scripting

Qui viene mostrato un oggetto Part Spirale creato con l'[esempio di scripting](#Script) riportato di seguito.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Part Spirale deriva da un oggetto [Funzione Part](/Part_Feature/it "Part Feature/it") e ne eredita tutte le proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Attachment

L'oggetto ha le stesse proprietà di collegamento di un [Part Part2DObject](/Part_Part2DObject/it#Dati "Part Part2DObject/it").

Spiral

* Dati**Growth** (`Length`): la distanza tra due giri consecutivi della spirale. Il valore predefinito è `1mm`.
* Dati**Radius** (`Length`): il raggio iniziale della spirale, la distanza tra il suo centro e il suo punto iniziale. Può essere `0mm`. Il valore predefinito è `1mm`.
* Dati**Rotations** (`QuantityConstraint`): il numero di rotazioni, o giri, della spirale. Il valore predefinito è `2`.
* Dati**Segment Length** (`QuantityConstraint`): il numero di giri per suddivisione a spirale. Il valore predefinito è `1`, il che significa che ogni giro completo della spirale è un segmento separato. Utilizzare `0` per sopprimere la suddivisione.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Script di Part](/Part_scripting/it "Part scripting/it") e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

È possibile creare una Part Spirale con il metodo `addObject()` del documento:

```
spiral = FreeCAD.ActiveDocument.addObject("Part::Spiral", "mySpiral")

```

* Dove `"mySpiral"` è il nome dell'oggetto.
* La funzione restituisce l'oggetto appena creato.

Esempio:

```
import FreeCAD as App

doc = App.activeDocument()

spiral = doc.addObject("Part::Spiral", "mySpiral")
spiral.Growth = 2
spiral.Radius = 3
spiral.Rotations = 4
spiral.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Spiral/it&oldid=1349773>"