---
title: Part Cono
---
|  |
| --- |
| Part Cono |
| Posizione nel menu |
| Parte → Primitive → Cono |
| Ambiente |
| [Part](/Part_Workbench/it "Part Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Part Primitive](/Part_Primitives/it "Part Primitives/it") |
|  |

## Descrizione

Il comando ![](/images/Part_Cone.svg) **Part Cono** crea un cono parametrico solido. Nel sistema di coordinate definito dalla sua proprietà Dati**Placement**, la faccia inferiore del cono si trova sul piano XY con il centro nell'origine.

Il Part Cono predefinito viene troncato. Può essere trasformato in un cono completo, non troncato, modificando la sua proprietà Dati**Radius1** o Dati**Radius2** su zero. Può essere trasformato in un segmento di cono modificando la sua proprietà Dati**Angle**.

![](/images/Part_Cone_Example.png)

## Utilizzo

1. Esistono diversi modi per richiamare il comando:
   * Premere il pulsante ![](/images/Part_Cone.svg) Cono.
   * Selezionare l'opzione **Parte → Primitive → ![](/images/Part_Cone.svg) Cono** dal menu.
2. Viene creato il cono.
3. Facoltativamente, modificare le dimensioni e il Dati**Placement** del cono effettuando una delle seguenti operazioni:
   * Fare doppio clic sull'oggetto nella [Vista ad albero](/Tree_view/it "Tree view/it"):
     1. Si apre il pannello delle attività **Primitive geometriche**.
     2. Modificare una o più proprietà.
     3. L'oggetto viene aggiornato dinamicamente nella [vista 3D](/3D_view/it "3D view/it").
     4. Premere il pulsante OK.
   * Modificare le proprietà nell'[Editor delle proprietà](/Property_editor/it "Property editor/it").
   * Modificare il Dati**Placement** con il comando ![](/images/Std_TransformManip.svg) [Trasforma](/Std_TransformManip/it "Std TransformManip/it").

## Esempio

![](/images/Part_Cone_Scripting_Example.png)

Part Cono dall'esempio di scripting

Qui viene mostrato un oggetto Part Cono creato con l'[esempio di scripting](#Script) riportato di seguito.

## Note

* È possibile creare un Part Cono anche con il comando ![](/images/Part_Primitives.svg) [Part Primitive](/Part_Primitives/it "Part Primitives/it"). Con questo comando si può specificare le dimensioni e il posizionamento al momento della creazione.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Part Cono deriva da un oggetto [Funzione Part](/Part_Feature/it "Part Feature/it") e ne eredita tutte le proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Attachment

L'oggetto ha le stesse proprietà di collegamento di un [Part Part2DObject](/Part_Part2DObject/it#Dati "Part Part2DObject/it").

Cone

* Dati**Radius1** (`Length`): il raggio della faccia inferiore del cono. Può essere `0mm` se Dati**Radius2** è maggiore di `0mm`. Il valore predefinito è `2mm`.
* Dati**Radius2** (`Length`): il raggio della faccia superiore del cono. Può essere `0mm` se Dati**Radius1** è maggiore di `0mm`. Il valore predefinito è `4mm`.
* Dati**Height** (`Length`): l'altezza del cono. Il valore predefinito è `10mm`.
* Dati**Angle** (`Angle`): l'angolo dell'arco circolare che definisce la faccia superiore e inferiore del cono. Intervallo valido: `0° < valore <= 360°`. Il valore predefinito è `360°`. Se è inferiore a `360°` il solido risultante sarà un segmento di cono.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Script di Part](/Part_scripting/it "Part scripting/it") e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

È possibile creare una Part Cono con il metodo `addObject()` del documento:

```
cone = FreeCAD.ActiveDocument.addObject("Part::Cone", "myCone")

```

* Dove `"myCone"` è il nome dell'oggetto.
* La funzione restituisce l'oggetto appena creato.

Esempio:

```
import FreeCAD as App

doc = App.activeDocument()

cone = doc.addObject("Part::Cone", "myCone")
cone.Radius1 = 5
cone.Radius2 = 10
cone.Height = 50
cone.Angle = 270
cone.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 60, 15))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Cone/it&oldid=1468237>"