---
title: Part Sfera
---
|  |
| --- |
| Part Sfera |
| Posizione nel menu |
| Parte → Primitive → Sfera |
| Ambiente |
| [Part](/Part_Workbench/it "Part Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Part Primitive](/Part_CreatePrimitives/it "Part CreatePrimitives/it") |
|  |

## Descrizione

Il comando ![](/images/Part_Sphere.svg) **Part Sfera** crea una sfera solida parametrica. È il risultato della rotazione di un profilo di arco circolare attorno a un asse. Nel sistema di coordinate definito dalla sua proprietà Dati**Placement**, il centro della sfera è posizionato nell'origine e il suo asse di rivoluzione è l'asse Z.

Una Part Sfera può essere troncata nella parte superiore e/o inferiore modificando le sue proprietà Dati**Angle1** e/o Dati**Angle2**. Può essere trasformata in un segmento di sfera modificando la sua proprietà Dati**Angle3**.

![](/images/Part_Sphere_Example.png)

## Utilizzo

1. Esistono diversi modi per richiamare il comando:
   * Premere il pulsante ![](/images/Part_Sphere.svg) Sfera.
   * Selezionare l'opzione **Part → Primitive → ![](/images/Part_Sphere.svg) Sfera** dal menu.
2. La sfera viene creata.
3. Facoltativamente, modificare le dimensioni e il Dati**Placement** della sfera effettuando una delle seguenti operazioni:
   * Fare doppio clic sull'oggetto nella [Vista ad albero](/Tree_view/it "Tree view/it"):
     1. Si apre il pannello delle attività **Primitive geometriche**.
     2. Modificare una o più proprietà.
     3. L'oggetto viene aggiornato dinamicamente nella [vista 3D](/3D_view/it "3D view/it").
     4. Premere il pulsante OK.
   * Modificare le proprietà nell'[Editor delle proprietà](/Property_editor "Property editor").
   * Modificare il Dati**Placement** con il comando ![](/images/Std_TransformManip.svg) [Trasformna](/Std_TransformManip/it "Std TransformManip/it").

## Esempio

![](/images/Part_Sphere_Scripting_Example.png)

Part Sfera dall'esempio di scripting

Qui viene mostrato un oggetto Part Sfera creato con l'[esempio di scripting](#Script) riportato di seguito.

## Note

* Una Part Sfera può essere creata anche con il comando ![](/images/Part_Primitives.svg) [Part Primitive](/Part_Primitives/it "Part Primitives/it"). Con questo comando si può specificare le dimensioni e il posizionamento al momento della creazione.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Part Sfera deriva da un oggetto [Funzione Part](/Part_Feature/it "Part Feature/it") e ne eredita tutte le proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Attachment

L'oggetto ha le stesse proprietà di collegamento di un [Part Part2DObject](/Part_Part2DObject/it#Dati "Part Part2DObject/it").

Sphere

* Dati**Radius** (`Length`): il raggio della sfera. Il valore predefinito è `5mm`.
* Dati**Angle1** (`Angle`): l'angolo iniziale del profilo dell'arco circolare della sfera. Intervallo valido: `-90° <= valore <= 90°`. Potrebbe non essere uguale a Dati**Angle2**. Il valore predefinito è `-90°`.
* Dati**Angle2** (`Angle`): l'angolo finale del profilo dell'arco circolare della sfera. Intervallo valido: `-90° <= valore <= 90°`. Potrebbe non essere uguale a Dati**Angle1**. Il valore predefinito è `90°`. Se l'angolo totale del profilo dell'arco è inferiore a `180°` la sfera verrà troncata e avrà una faccia piatta nella parte superiore e/o inferiore.
* Dati**Angle3** (`Angle`): l'angolo di rivoluzione totale della sfera. Intervallo valido: `0° < valore <= 360°`. Il valore predefinito è `360°`. Se è inferiore a `360°` il solido risultante sarà un segmento di una sfera.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Script di Part](/Part_scripting/it "Part scripting/it") e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

È possibile creare una Part Sfera con il metodo `addObject()` del documento:

```
sphere = FreeCAD.ActiveDocument.addObject("Part::Sphere", "mySphere")

```

* Dove `"mySphere"` è il nome dell'oggetto.
* La funzione restituisce l'oggetto appena creato.

Esempio:

```
import FreeCAD as App

doc = App.activeDocument()

sphere = doc.addObject("Part::Sphere", "mySphere")
sphere.Radius = 20
sphere.Angle1 = -30
sphere.Angle2 = 45
sphere.Angle3 = 90
sphere.Placement = App.Placement(App.Vector(3, 9, 11), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Sphere/it&oldid=1468240>"