---
title: Part Cerchio
---
|  |
| --- |
| Part Cerchio |
| Posizione nel menu |
| Parte → [Crea primitive](/Part_Primitives/it "Part Primitives/it") → Cerchio |
| Ambiente |
| [Part](/Part_Workbench/it "Part Workbench/it"), [OpenSCAD](/OpenSCAD_Workbench/it "OpenSCAD Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Part Primitive](/Part_Primitives/it "Part Primitives/it") |
|  |

## Descrizione

Un ![](/images/Part_Circle.svg) **Part Cerchio** è una forma parametrica che può essere creata con il comando ![](/images/Part_Primitives.svg) [Part Primitive](/Part_Primitives/it "Part Primitives/it") . Nel sistema di coordinate definito dalla sua proprietà Dati**Placement**, il cerchio giace sul piano XY con il centro nell'origine.

Un Part Cerchio è infatti un arco circolare chiuso in senso antiorario, può essere trasformato in un arco modificando le sue proprietà Dati**Angle1** e/o Dati**Angle2**.

![](/images/Part_Circle_Example.png)

## Utilizzo

Vedere [Part Primitive](/Part_Primitives/it#Utilizzo "Part Primitives/it").

In alternativa è possibile creare un cerchio parziale selezionando tre punti:

1. Nel pannello delle azioni del comando ![](/images/Part_Primitives.svg) [Part Primitive](/Part_Primitives/it "Part Primitives/it") selezionare l'opzione **![](/images/Part_Circle.svg) Cerchio** dal menu a tendina.
2. Premere il pulsante Da tre punti.
3. Selezionare tre vertici nella [Vista 3D](/3D_view/it "3D view/it"). Non è necessario tenere premuto il tasto Ctrl.
4. Viene creato un cerchio.
5. I vertici selezionati vengono utilizzati solo al momento della creazione per calcolare il Dati**Radius** e il Dati**Placement** del cerchio.

## Esempio

![](/images/Part_Circle_Scripting_Example.png)

Part Cerchio dall'esempio di scripting

Qui viene mostrato un oggetto Part Cerchio creato con l'[esempio di scripting](#Script) riportato di seguito.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Part Cerchio deriva da un oggetto [Funzione Part](/Part_Feature/it "Part Feature/it") e ne eredita tutte le proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Attachment

L'oggetto ha le stesse proprietà di collegamento di un [Part Part2DObject](/Part_Part2DObject/it#Dati "Part Part2DObject/it").

Base

* Dati**Radius** (`Length`): il raggio del cerchio o dell'arco circolare. Il valore predefinito è `2mm`.
* Dati**Angle1** (`Angle`): l'angolo iniziale dell'arco circolare. Intervallo valido: `0° < valore <= 360°`. Il valore predefinito è `0°`.
* Dati**Angle2** (`Angle`): l'angolo finale dell'arco circolare. Intervallo valido: `0° < valore <= 360°`. Il valore predefinito è `360°`. Se Dati**Angle1** e Dati**Angle2** sono uguali, o se un angolo è `0°` e l'altro `360°`, viene creato un cerchio completo.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Script di Part](/Part_scripting/it "Part scripting/it") e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

È possibile creare una Part Cerchio con il metodo `addObject()` del documento:

```
circle = FreeCAD.ActiveDocument.addObject("Part::Circle", "myCircle")

```

* Dove `"myCircle"` è il nome dell'oggetto.
* La funzione restituisce l'oggetto appena creato.

Esempio:

```
import FreeCAD as App

doc = App.activeDocument()

circle = doc.addObject("Part::Circle", "myCircle")
circle.Radius = 10
circle.Angle1 = 45
circle.Angle2 = 225
circle.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Circle/it&oldid=1350826>"