---
title: Part Cubo
---
|  |
| --- |
| Part Cubo |
| Posizione nel menu |
| Parte → Primitive → Cubo |
| Ambiente |
| [Part](/Part_Workbench/it "Part Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Part Primitive](/Part_CreatePrimitives/it "Part CreatePrimitives/it") |
|  |

## Descrizione

Il comando ![](/images/Part_Box.svg) **Part Cubo** crea un solido cuboide parametrico, un [cuboide rettangolare](https://en.wikipedia.org/wiki/Cuboid#Rectangular_cuboid). Nel sistema di coordinate definito dalla sua proprietà Dati**Placement**, la faccia inferiore del cuboide si trova sul piano XY con l'angolo anteriore sinistro all'origine e il bordo anteriore parallelo all'asse X.

![](/images/Part_Box_Example.png)

## Utilizzo

1. Esistono diversi modi per richiamare il comando:
   * Premere il pulsante ![](/images/Part_Box.svg) Cubo.
   * Seleziona l'opzione **Parte → Primitive → ![](/images/Part_Box.svg) Cubo** dal menu.
2. Il cubo viene creato.
3. Facoltativamente, modificare le dimensioni e il Dati**Placement** del cubo effettuando una delle seguenti operazioni:
   * Fare doppio clic sull'oggetto nella [Vista ad albero](/Tree_view/it "Tree view/it"):
     1. Si apre il pannello delle attività **Primitive geometriche**.
     2. Modificare una o più proprietà.
     3. L'oggetto viene aggiornato dinamicamente nella [vista 3D](/3D_view/it "3D view/it").
     4. Premere il pulsante OK.
   * Modificare le proprietà nell'[Editor delle proprietà](/Property_editor/it "Property editor/it").
   * Modificare il Dati**Placement** con il comando ![](/images/Std_TransformManip.svg) [Trasforma](/Std_TransformManip/it "Std TransformManip/it").

## Esempio

![](/images/Part_Box_Scripting_Example.png)

Part Cubo dall'esempio di scripting

Qui viene mostrato un oggetto Part Cubo creato con l'[esempio di scripting](#Script) riportato di seguito.

## Note

* È possibile creare un Part Cubo anche con il comando ![](/images/Part_Primitives.svg) [Part Primitive](/Part_Primitives/it "Part Primitives/it"). Con questo comando si possono specificare le dimensioni e il posizionamento al momento della creazione.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Part Cubo deriva da un oggetto [Funzione Part](/Part_Feature/it "Part Feature/it") e ne eredita tutte le proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Attachment

L'oggetto ha le stesse proprietà di collegamento di un [Part Part2DObject](/Part_Part2DObject/it#Dati "Part Part2DObject/it").

Box

* Dati**Length** (`Length`): la lunghezza del cuboide. Questa è la dimensione nella sua direzione X. Il valore predefinito è `10mm`.
* Dati**Width** (`Length`): la larghezza del cuboide. Questa è la dimensione nella sua direzione Y. Il valore predefinito è `10mm`.
* Dati**Height** (`Length`): l'altezza del cuboide. Questa è la dimensione nella sua direzione Z. Il valore predefinito è `10mm`.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Script di Part](/Part_scripting/it "Part scripting/it") e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

È possibile creare una Part Cubo con il metodo `addObject()` del documento:

```
box = FreeCAD.ActiveDocument.addObject("Part::Box", "myBox")

```

* Dove `"myBox"` è il nome dell'oggetto.
* La funzione restituisce l'oggetto appena creato.

Esempio:

```
import FreeCAD as App

doc = App.activeDocument()

box = doc.addObject("Part::Box", "myBox")
box.Length = 4
box.Width = 8
box.Height = 12
box.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Box/it&oldid=1468236>"