---
title: Part Linea
---
|  |
| --- |
| Part Linea |
| Posizione nel menu |
| Parte → [Crea primitive](/Part_Primitives/it "Part Primitives/it") → Linea |
| Ambiente |
| [Part](/Part_Workbench/it "Part Workbench/it"), [OpenSCAD](/OpenSCAD_Workbench/it "OpenSCAD Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Part Primitive](/Part_Primitives/it "Part Primitives/it") |
|  |

## Descrizione

Una ![](/images/Part_Line.svg) **Part Linea** è una linea parametrica che può essere creata con il comando ![](/images/Part_Primitives.svg) [Part Primitive](/Part_Primitives/it "Part Primitives/it"). Le coordinate dei punti iniziale e finale sono relative al sistema di coordinate definito dalla proprietà Dati**Placement**.

![](/images/Part_Line_Example.png)

## Utilizzo

Vedere [Part Primitive](/Part_Primitives/it#Utilizzo "Part Primitives/it").

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Part Linea deriva da un oggetto [Funzione Part](/Part_Feature/it "Part Feature/it") e ne eredita tutte le proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Attachment

L'oggetto ha le stesse proprietà di collegamento di un [Part Part2DObject](/Part_Part2DObject/it#Dati "Part Part2DObject/it").

Vertex 1 - Start

* Dati**X1** (`Distance`): la coordinata X del punto iniziale della linea. Il valore predefinito è `0mm`.
* Dati**Y1** (`Distance`): la coordinata Y del punto iniziale della linea. Il valore predefinito è `0mm`.
* Dati**Z1** (`Distance`): la coordinata Z del punto iniziale della linea. Il valore predefinito è `0mm`.

Vertex 2 - Finish

* Dati**X2** (`Distance`): la coordinata X del punto finale della linea. Il valore predefinito è `10mm`.
* Dati**Y2** (`Distance`): la coordinata Y del punto finale della linea. Il valore predefinito è `10mm`.
* Dati**Z2** (`Distance`): la coordinata Z del punto finale della linea. Il valore predefinito è `10mm`.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Script di Part](/Part_scripting/it "Part scripting/it") e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

È possibile creare una Part Linea con il metodo `addObject()` del documento:

```
line = FreeCAD.ActiveDocument.addObject("Part::Line", "myLine")

```

* Dove `"myLine"` è il nome dell'oggetto.
* La funzione restituisce l'oggetto appena creato.

Esempio:

```
import FreeCAD as App

doc = App.activeDocument()

line = doc.addObject("Part::Line", "myLine")
line.X1 = 1
line.Y1 = 3
line.Z1 = 6
line.X2 = 2
line.Y2 = 3
line.Z2 = 9

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Line/it&oldid=1351807>"