---
title: Part Toro
---
|  |
| --- |
| Part Toro |
| Posizione nel menu |
| Parte → Primitive → Toro |
| Ambiente |
| [Part](/Part_Workbench/it "Part Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Part Primitive](/Part_Primitives/it "Part Primitives/it") |
|  |

## Descrizione

Il comando ![](/images/Part_Torus.svg) **Part Toro** crea un solido toroide parametrico, a forma di ciambella. È il risultato dello spostamento di un profilo circolare attorno a un percorso circolare. Nel sistema di coordinate definito dalla sua proprietà Dati**Placement**, il percorso circolare del toro giace sul piano XY con il centro nell'origine.

Una Part Toro può essere trasformata in un segmento di un toro modificando la sua proprietà Dati**Angle3**. Modificando le sue proprietà Dati**Angle1** e/o Dati**Angle2** il profilo di creazione può diventare un segmento di un cerchio.

![](/images/Part_Torus_Example.png)

## Utilizzo

1. Esistono diversi modi per richiamare il comando:
   * Premere il pulsante ![](/images/Part_Torus.svg) Toro.
   * Selezionare l'opzione **Parte → Primitive → ![](/images/Part_Torus.svg) Toro** dal menu.
2. Viene creato il toro.
3. Facoltativamente, modificare le dimensioni e il Dati**Placement** del toro effettuando una delle seguenti operazioni:
   * Fare doppio clic sull'oggetto nella [Vista ad albero](/Tree_view/it "Tree view/it"):
     1. Si apre il pannello delle attività **Primitive geometriche**.
     2. Modificare una o più proprietà.
     3. L'oggetto viene aggiornato dinamicamente nella [vista 3D](/3D_view/it "3D view/it").
     4. Premere il pulsante OK.
   * Modificare le proprietà nell'[Editor delle proprietà](/Property_editor "Property editor").
   * Modificare il Dati**Placement** con il comando ![](/images/Std_TransformManip.svg) [Trasforma](/Std_TransformManip/it "Std TransformManip/it").

## Esempio

![](/images/Part_Torus_Scripting_Example.png)

Part Toro dall'esempio di scripting

Qui viene mostrato un oggetto Part Toro creato con l'[esempio di scripting](#Script) riportato di seguito.

## Note

* È possibile creare un Part Toro anche con il comando ![](/images/Part_Primitives.svg) [Part Primitive](/Part_Primitives/it "Part Primitives/it"). Con questo comando si può specificare le dimensioni e il posizionamento al momento della creazione.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Part Toro deriva da un oggetto [Funzione Part](/Part_Feature/it "Part Feature/it") e ne eredita tutte le proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Attachment

L'oggetto ha le stesse proprietà di collegamento di un [Part Part2DObject](/Part_Part2DObject/it#Dati "Part Part2DObject/it").

Torus

* Dati**Radius1** (`Length`): il raggio del percorso circolare del toro. Il valore predefinito è `10mm`.
* Dati**Radius2** (`Length`): il raggio del profilo circolare del toro. Il valore predefinito è `2mm`.
* Dati**Angle1** (`Angle`): l'angolo iniziale del profilo circolare. Intervallo valido: `-180° <= valore <= 180°`. Il valore predefinito è `-180°`.
* Dati**Angle2** (`Angle`): l'angolo finale del profilo circolare. Intervallo valido: `-180° <= valore <= 180°`. Il valore predefinito è `180°`. Se l'angolo totale del profilo circolare è inferiore a `360°` il profilo avrà una forma a torta.
* Dati**Angle3** (`Angle`): l'angolo del percorso circolare del toro. Intervallo valido: `0° < valore <= 360°`. Il valore predefinito è `360°`. Se è inferiore a `360°` il solido risultante sarà un segmento di un toro.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Script di Part](/Part_scripting/it "Part scripting/it") e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

È possibile creare una Part Toro con il metodo `addObject()` del documento:

```
torus = FreeCAD.ActiveDocument.addObject("Part::Torus", "myTorus")

```

* Dove `"myTorus"` è il nome dell'oggetto.
* La funzione restituisce l'oggetto appena creato.

Esempio:

```
import FreeCAD as App

doc = App.activeDocument()

torus = doc.addObject("Part::Torus", "myTorus")
torus.Radius1 = 20
torus.Radius2 = 10
torus.Angle1 = -90
torus.Angle2 = 45
torus.Angle3 = 270
torus.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Torus/it&oldid=1468241>"