---
title: Part Cilindro
---
|  |
| --- |
| Part Cilindro |
| Posizione nel menu |
| Parte → Primitive → Cilindro |
| Ambiente |
| [Part](/Part_Workbench/it "Part Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Part Primitive](/Part_CreatePrimitives/it "Part CreatePrimitives/it") |
|  |

## Descrizione

Il comando ![](/images/Part_Cylinder.svg) **Part Cilindro** crea un solido cilindrico parametrico. È il risultato dell'estrusione di un arco circolare lungo un percorso rettilineo. Nel sistema di coordinate definito dalla sua proprietà Dati**Placement**, la faccia inferiore del cilindro si trova sul piano XY con il centro nell'origine.

Un Part Cilindro può essere trasformato in un segmento di cilindro modificando la sua proprietà Dati**Angle**.

![](/images/Part_Cylinder_Example.png)

## Utilizzo

1. Esistono diversi modi per richiamare il comando:
   * Premere il pulsante ![](/images/Part_Cylinder.svg) Cilindro.
   * Selezionare l'opzione **Part → Primitive → ![](/images/Part_Cylinder.svg) Cilindro** dal menu.
2. Il cilindro viene creato.
3. Facoltativamente, modificare le dimensioni e il Dati**Placement** del cilindro effettuando una delle seguenti operazioni:
   * Fare doppio clic sull'oggetto nella [Vista ad albero](/Tree_view/it "Tree view/it"):
     1. Si apre il pannello delle attività **Primitive geometriche**.
     2. Modificare una o più proprietà.
     3. L'oggetto viene aggiornato dinamicamente nella [vista 3D](/3D_view/it "3D view/it").
     4. Premere il pulsante OK.
   * Modificare le proprietà nell'[Editor delle proprietà](/Property_editor/it "Property editor/it").
   * Modificare il Dati**Placement** con il comando ![](/images/Std_TransformManip.svg) [Trasforma](/Std_TransformManip/it "Std TransformManip/it").

## Esempio

![](/images/Part_Cylinder_Scripting_Example.png)

Part Cilindro dall'esempio di scripting

Qui viene mostrato un oggetto Part Cilindro creato con l'[esempio di scripting](#Script) riportato di seguito.

## Note

* È possibile creare un Part Cilindro anche con il comando ![](/images/Part_Primitives.svg) [Part Primitive](/Part_Primitives/it "Part Primitives/it"). Con questo comando si possono specificare le dimensioni e il posizionamento al momento della creazione.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Part Cilindro deriva da un oggetto [Funzione Part](/Part_Feature/it "Part Feature/it") e ne eredita tutte le proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Attachment

L'oggetto ha le stesse proprietà di collegamento di un [Part Part2DObject](/Part_Part2DObject/it#Dati "Part Part2DObject/it").

Cylinder

* Dati**Radius** (`Length`): il raggio dell'arco circolare che definisce il cilindro. Il valore predefinito è `2mm`.
* Dati**Height** (`Length`): l'altezza del cilindro. Il valore predefinito è `10mm`.
* Dati**Angle** (`Angle`): l'angolo dell'arco circolare che definisce il cilindro. Intervallo valido: `0° < valore <= 360°`. Il valore predefinito è `360°`. Se è inferiore a `360°` il solido risultante sarà un segmento di cilindro.

Prism

* Dati**First Angle** (`Angle`): l'angolo tra la direzione di estrusione del cilindro e il suo asse Z positivo, misurato attorno al suo asse Y. L'angolo è positivo rispetto al suo asse X positivo. Intervallo valido: `0° <= valore < 90°`. Il valore predefinito è `0°`. [disponibile dalla versione 0.20](/Release_notes_0.20/it "Release notes 0.20/it")
* Dati**Second Angle** (`Angle`): l'angolo tra la direzione di estrusione del cilindro e il suo asse Z positivo, misurato attorno al suo asse X. L'angolo è positivo rispetto al suo asse Y positivo. Intervallo valido: `0° <= valore < 90°`. Il valore predefinito è `0°`. [disponibile dalla versione 0.20](/Release_notes_0.20/it "Release notes 0.20/it")

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Script di Part](/Part_scripting/it "Part scripting/it") e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

È possibile creare un Part Cilindro con il metodo `addObject()` del documento:

```
cylinder = FreeCAD.ActiveDocument.addObject("Part::Cylinder", "myCylinder")

```

* Dove `"myCylinder"` è il nome dell'oggetto.
* La funzione restituisce l'oggetto appena creato.

Esempio:

```
import FreeCAD as App

doc = App.activeDocument()

cylinder = doc.addObject("Part::Cylinder", "myCylinder")
cylinder.Radius = 10
cylinder.Height = 50
cylinder.Placement = App.Placement(App.Vector(5, 10, 15), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Cylinder/it&oldid=1468238>"