---
title: Part Cuneo
---
|  |
| --- |
| Part Cuneo |
| Posizione nel menu |
| Parte → [Crea primitive](/Part_Primitives/it "Part Primitives/it") → Cuneo |
| Ambiente |
| [Part](/Part_Workbench/it "Part Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Part Primitive](/Part_Primitives/it "Part Primitives/it") |
|  |

## Descrizione

Un ![](/images/Part_Wedge.svg) **Part Cuneo** è un solido parametrico che può essere creato con il comando ![](/images/Part_Primitives.svg) [Part Primitive](/Part_Primitives/it "Part Primitives/it") . Ha da quattro a sei facce planari. È definito dai piani principali virtuali anteriore e posteriore su cui viene creata una faccia rettangolare (impostazione predefinita), un singolo bordo dritto o un singolo vertice. Queste forme di base definiscono le quattro facce quadrilatere o triangolari che le collegano. Il solido risultante è un vero cuneo solo se una delle forme base è una faccia rettangolare e l'altra un bordo dritto. Nel sistema di coordinate definito dalla sua proprietà Dati**Placement**, i piani principali anteriori e posteriori virtuali del cuneo sono piani paralleli al piano XZ e i bordi delle forme base sono paralleli all'asse X o Z. Tutte le sue coordinate sono relative a quel sistema di coordinate.

![](/images/Part_Wedge_Example.png)

## Utilizzo

Vedere [Part Primitive](/Part_Primitives/it#Utilizzo "Part Primitives/it").

## Esempio

![](/images/Part_Wedge_Scripting_Example.png)

Part Cuneo dall'esempio di scripting

Qui viene mostrato un oggetto Part Cuneo creato con l'[esempio di scripting](#Script) riportato di seguito.

## Note

* I valori delle coordinate del cuneo devono essere tali da poter creare un solido valido. Ciò significa che le forme di base anteriore e posteriore possono essere entrambe bordi singoli, ma non se sono parallele. E se una delle forme base è un vertice, l'altra forma deve essere una faccia rettangolare.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Part Cuneo deriva da un oggetto [Funzione Part](/Part_Feature/it "Part Feature/it") e ne eredita tutte le proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Attachment

L'oggetto ha le stesse proprietà di collegamento di un [Part Part2DObject](/Part_Part2DObject/it#Dati "Part Part2DObject/it").

Wedge

* Dati**Xmin** (`Distance`): la coordinata X più bassa della faccia anteriore del cuneo. Il valore predefinito è `0mm`.
* Dati**Ymin** (`Distance`): la coordinata Y della faccia anteriore del cuneo. Il valore predefinito è `0mm`.
* Dati**Zmin** (`Distance`): la coordinata Z più bassa della faccia anteriore del cuneo. Il valore predefinito è `0mm`.
* Dati**X2min** (`Distance`): la coordinata X più bassa della faccia posteriore del cuneo. Il valore predefinito è `2mm`.
* Dati**Z2min** (`Distance`): la coordinata Z più bassa della faccia posteriore del cuneo. Il valore predefinito è `2mm`.
* Dati**Xmax** (`Distance`): la coordinata X più alta della faccia anteriore del cuneo. Il valore predefinito è `10mm`.
* Dati**Ymax** (`Distance`): la coordinata Y della faccia posteriore del cuneo. Il valore predefinito è `10mm`.
* Dati**Zmax** (`Distance`): la coordinata Z più alta della faccia anteriore del cuneo. Il valore predefinito è `10mm`.
* Dati**X2max** (`Distance`): la coordinata X più alta della faccia posteriore del cuneo. Il valore predefinito è `8mm`.
* Dati**Z2max** (`Distance`): la coordinata Z più alta della faccia posteriore del cuneo. Il valore predefinito è `8mm`.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Script di Part](/Part_scripting/it "Part scripting/it") e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

È possibile creare una Part Cuneo con il metodo `addObject()` del documento:

```
wedge = FreeCAD.ActiveDocument.addObject("Part::Wedge", "myWedge")

```

* Dove `"myWedge"` è il nome dell'oggetto.
* La funzione restituisce l'oggetto appena creato.

Esempio:

```
import FreeCAD as App

doc = App.activeDocument()

wedge = doc.addObject("Part::Wedge", "myWedge")
wedge.Xmin = 1
wedge.Ymin = 2
wedge.Zmin = 3
wedge.X2min = 4
wedge.Z2min = 6
wedge.Xmax = 15
wedge.Ymax = 20
wedge.Zmax = 55
wedge.X2max = 10
wedge.Z2max = 12
wedge.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Wedge/it&oldid=1350830>"