---
title: Part Ellissoide
---
|  |
| --- |
| Part Ellissoide |
| Posizione nel menu |
| Parte → [Crea primitive](/Part_Primitives/it "Part Primitives/it") → Ellissoide |
| Ambiente |
| [Part](/Part_Workbench/it "Part Workbench/it"), [OpenSCAD](/OpenSCAD_Workbench/it "OpenSCAD Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Part Primitive](/Part_Primitives/it "Part Primitives/it") |
|  |

## Descrizione

Un ![](/images/Part_Ellipsoid.svg) **Part Ellissoide** è un solido parametrico che può essere creato con il comando ![](/images/Part_Primitives.svg) [Part Primitive](/Part_Primitives/it "Part Primitives/it") . Nel sistema di coordinate definito dalla sua proprietà Dati**Placement**, gli assi dell'ellissoide sono allineati con gli assi X, Y e Z, e quindi il suo centro è posizionato all'origine.

Un Part Ellissoide può essere troncato nella parte superiore e/o inferiore modificando le sue proprietà Dati**Angle1** e/o Dati**Angle2**. Può essere trasformato in un segmento di ellissoide modificando la sua proprietà Dati**Angle3**.

![](/images/Part_Ellipsoid_Example.png)

## Utilizzo

Vedere [Part Primitive](/Part_Primitives/it#Utilizzo "Part Primitives/it").

## Esempio

![](/images/Part_Ellipsoid_Scripting_Example.png)

Part Ellissoide dall'esempio di scripting

Qui viene mostrato un oggetto Part Ellissoide creato con l'[esempio di scripting](#Script) riportato di seguito.

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Part Ellissoide deriva da un oggetto [Funzione Part](/Part_Feature/it "Part Feature/it") e ne eredita tutte le proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Attachment

L'oggetto ha le stesse proprietà di collegamento di un [Part Part2DObject](/Part_Part2DObject/it#Dati "Part Part2DObject/it").

Ellipsoid

* Dati**Radius1** (`Length`): il raggio dell'ellissoide nella sua direzione Z. Il valore predefinito è `2mm`.
* Dati**Radius2** (`Length`): il raggio dell'ellissoide nella sua direzione X. Il valore predefinito è `4mm`.
* Dati**Radius3** (`Length`): il raggio dell'ellissoide nella sua direzione Y. Il valore predefinito è `4mm`.
* Dati**Angle1** (`Angle`): l'angolo iniziale dei lati ellittici dell'ellissoide. Intervallo valido: `-90° <= valore < 90°`. Deve essere inferiore a Dati**Angle2**. Il valore predefinito è `-90°`.
* Dati**Angle2** (`Angle`): l'angolo finale dei lati ellittici dell'ellissoide. Intervallo valido: `-90° < valore <= 90°`. Deve essere maggiore di Dati**Angle1**. Il valore predefinito è `90°`. Se l'angolo totale dei lati ellittici è inferiore a `180°` l'ellissoide verrà troncato e avrà una faccia piatta nella parte superiore e/o inferiore.
* Dati**Angle3** (`Angle`): l'angolo totale dell'ellissoide nel suo piano XY. Intervallo valido: `0° < valore <= 360°`. Il valore predefinito è `360°`. Se è inferiore a `360°` il solido risultante sarà un segmento di un ellissoide.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Script di Part](/Part_scripting/it "Part scripting/it") e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

È possibile creare un Part Ellissoide con il metodo `addObject()` del documento:

```
ellipsoid = FreeCAD.ActiveDocument.addObject("Part::Ellipsoid", "myEllipsoid")

```

* Dove `"myEllipsoid"` è il nome dell'oggetto.
* La funzione restituisce l'oggetto appena creato.

Esempio:

```
import FreeCAD as App

doc = App.activeDocument()

ellipsoid = doc.addObject("Part::Ellipsoid", "myEllipsoid")
ellipsoid.Radius1 = 2
ellipsoid.Radius2 = 4
ellipsoid.Radius3 = 6
ellipsoid.Angle1 = -90
ellipsoid.Angle2 = 50
ellipsoid.Angle3 = 300
ellipsoid.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(15, 0, 20))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Ellipsoid/it&oldid=1347303>"