---
title: Part Elica
---
|  |
| --- |
| Part Elica |
| Posizione nel menu |
| Parte → [Crea primitive](/Part_Primitives/it "Part Primitives/it") → Elica |
| Ambiente |
| [Part](/Part_Workbench/it "Part Workbench/it"), [OpenSCAD](/OpenSCAD_Workbench/it "OpenSCAD Workbench/it") |
| Avvio veloce |
| *Nessuno* |
| Introdotto nella versione |
| - |
| Vedere anche |
| [Part Primitive](/Part_Primitives/it "Part Primitives/it") |
|  |

## Descrizione

Una ![](/images/Part_Helix.svg) **Part Elica** è una forma parametrica che può essere creata con il comando ![](/images/Part_Primitives.svg) [Part Primitive](/Part_Primitives/it "Part Primitives/it") . Nel sistema di coordinate definito dalla sua proprietà Dati**Placement**, l'asse dell'elica corrisponde all'asse Z e il suo punto inferiore, il punto iniziale, si trova sull'asse X.

![](/images/Part_Helix_Example.png)

## Utilizzo

Vedere [Part Primitive](/Part_Primitives/it#Utilizzo "Part Primitives/it").

## Esempio

![](/images/Part_Helix_Scripting_Example.png)

Part Elica dall'esempio di scripting

Qui viene mostrato un oggetto Part Elica creato con l'[esempio di scripting](#Script) riportato di seguito.

## Note

* È possibile utilizzare una Part Elica per creare filettature. Vedere il [Tutorial sulla filettatura](/Thread_for_Screw_Tutorial/it "Thread for Screw Tutorial/it").

## Proprietà

Vedere anche: [Editor delle proprietà](/Property_editor/it "Property editor/it").

Un oggetto Part Elica deriva da un oggetto [Funzione Part](/Part_Feature/it "Part Feature/it") e ne eredita tutte le proprietà. Ha inoltre le seguenti proprietà aggiuntive:

### Dati

Attachment

L'oggetto ha le stesse proprietà di collegamento di un [Part Part2DObject](/Part_Part2DObject/it#Dati "Part Part2DObject/it").

Coordinate System

* Dati**Local Coord** (`Enumeration`): il [senso di rotazione](https://en.wikipedia.org/wiki/Screw_thread), o direzione, dell'elica: `Right-handed` o `Right-handed`. Il valore predefinito è `Right-handed`, il che significa che l'elica gira in senso antiorario mentre sale.

Helix

* Dati**Pitch** (`Length`): la distanza tra due giri consecutivi dell'elica misurata lungo il suo asse Z. Il valore predefinito è `1mm`.
* Dati**Height** (`Length`): l'altezza dell'elica. Il valore predefinito è `2mm`.
* Dati**Radius** (`Length`): il raggio iniziale dell'elica. L'elica ha un raggio costante se Dati**Angle** è `0°`.
* Dati**Segment Length** (`QuantityConstraint`): il numero di giri per suddivisione dell'elica. Il valore predefinito è `1`, il che significa che ogni giro completo dell'elica è un segmento separato. Utilizzare `0` per sopprimere la suddivisione.
* Dati**Angle** (`Angle`): l'angolo che definisce la forma esterna dell'elica. Intervallo valido: `-90° < valore < 90°`. Il valore predefinito è `0°`. Se è `0°` l'elica è cilindrica, altrimenti è conica.

## Script

Vedere anche: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Script di Part](/Part_scripting/it "Part scripting/it") e [Script di base per FreeCAD](/FreeCAD_Scripting_Basics/it "FreeCAD Scripting Basics/it").

È possibile creare una Part Elica con il metodo `addObject()` del documento:

```
helix = FreeCAD.ActiveDocument.addObject("Part::Helix", "myHelix")

```

* Dove `"myHelix"` è il nome dell'oggetto.
* La funzione restituisce l'oggetto appena creato.

Esempio:

```
import FreeCAD as App

doc = App.activeDocument()

helix = doc.addObject("Part::Helix", "myHelix")
helix.Pitch = 2
helix.Height = 3
helix.Radius = 4
helix.SegmentLength = 21
helix.Angle = 45
helix.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Helix/it&oldid=1349717>"