---
title: Part RegularPolygon
---

|                                                                                                |
| ---------------------------------------------------------------------------------------------- |
| Part RegularPolygon                                                                            |
| Menu location                                                                                  |
| Part → [Create primitives](/Part_Primitives "Part Primitives") → Regular polygon               |
| Workbenches                                                                                    |
| [Part](/Part_Workbench "Part Workbench"), [OpenSCAD](/OpenSCAD_Workbench "OpenSCAD Workbench") |
| Default shortcut                                                                               |
| _None_                                                                                         |
| Introduced in version                                                                          |
| 0.14                                                                                           |
| See also                                                                                       |
| [Part Primitives](/Part_Primitives "Part Primitives")                                          |
|                                                                                                |

## Description

A ![](/images/Part_RegularPolygon.svg) **Part RegularPolygon** is a parametric shape that can be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. In the coordinate system defined by its Data**Placement** property, the polygon lies on the XY plane with its center at the origin and one of its vertices on the X axis.

![](/images/Part_RegularPolygon_Example.png)

## Usage

See [Part Primitives](/Part_Primitives#Usage "Part Primitives").

## Example

![](/images/Part_RegularPolygon_Scripting_Example.png)

Part RegularPolygon from the scripting example

A Part RegularPolygon object created with the [scripting example](#Scripting) below is shown here.

## Properties

See also: [Property editor](/Property_editor "Property editor").

A Part RegularPolygon object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Regular Polygon

- Data**Polygon** (`IntegerConstraint`): The number of sides of the polygon. The default is `6`.
- Data**Circumradius** (`Length`): The radius of the circle that circumscribes the polygon, the distance from the center of the polygon to one of its vertices. The default is `2mm`.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part RegularPolygon can be created with the `addObject()` method of the document:

```
poly = FreeCAD.ActiveDocument.addObject("Part::RegularPolygon", "myPolygon")

```

- Where `"myPolygon"` is the name for the object.
- The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

poly = doc.addObject("Part::RegularPolygon", "myPolygon")
poly.Polygon = 5
poly.Circumradius = 8
poly.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(60, 30, 15))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_RegularPolygon/en&oldid=1282471>"
