---
title: Part Cylinder
---

|                                                       |
| ----------------------------------------------------- |
| Part Cylinder                                         |
| Menu location                                         |
| Part → Primitives → Cylinder                          |
| Workbenches                                           |
| [Part](/Part_Workbench "Part Workbench")              |
| Default shortcut                                      |
| _None_                                                |
| Introduced in version                                 |
| -                                                     |
| See also                                              |
| [Part Primitives](/Part_Primitives "Part Primitives") |
|                                                       |

## Description

The ![](/src/assets/images/Part_Cylinder.svg) **Part Cylinder** command creates a parametric cylinder solid. It is the result of extruding a circular arc along a straight path. In the coordinate system defined by its Data**Placement** property, the bottom face of the cylinder lies on the XY plane with its center at the origin.

A Part Cylinder can be turned into a segment of a cylinder by changing its Data**Angle** property.

![](/src/assets/images/Part_Cylinder_Example.png)

## Usage

1. There are several ways to invoke the command:
   - Press the ![](/src/assets/images/Part_Cylinder.svg) [Cylinder](/Part_Cylinder "Part Cylinder") button.
   - Select the **Part → Primitives → ![](/src/assets/images/Part_Cylinder.svg) Cylinder** option from the menu.
2. The cylinder is created.
3. Optionally change the dimensions and Data**Placement** of the cylinder by doing one of the following:
   - Double-click the object in the [Tree view](/Tree_view "Tree view"):
     1. The **Geometric Primitives** task panel opens.
     2. Change one or more properties.
     3. The object is dynamically updated in the [3D view](/3D_view "3D view").
     4. Press the OK button.
   - Change the properties in the [Property editor](/Property_editor "Property editor").
   - Change the Data**Placement** with the ![](/src/assets/images/Std_TransformManip.svg) [Std TransformManip](/Std_TransformManip "Std TransformManip") command.

## Example

![](/src/assets/images/Part_Cylinder_Scripting_Example.png)

Part Cylinder from the scripting example

A Part Cylinder object created with the [scripting example](#Scripting) below is shown here.

## Notes

- A Part Cylinder can also be created with the ![](/src/assets/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. With that command you can specify the dimensions and placement at creation time.

## Properties

See also: [Property editor](/Property_editor "Property editor").

A Part Cylinder object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Cylinder

- Data**Radius** (`Length`): The radius of the circular arc that defines the cylinder. The default is `2mm`.
- Data**Height** (`Length`): The height of the cylinder. The default is `10mm`.
- Data**Angle** (`Angle`): The angle of the circular arc that defines the cylinder. Valid range: `0° < value <= 360°`. The default is `360°`. If it is smaller than `360°` the resulting solid will be a segment of a cylinder.

Prism

- Data**First Angle** (`Angle`): The angle between the extrusion direction of the cylinder and its positive Z axis, measured around its Y axis. The angle is positive towards its positive X axis. Valid range: `0° <= value < 90°`. The default is `0°`. [introduced in 0.20](/Release_notes_0.20 "Release notes 0.20")
- Data**Second Angle** (`Angle`): The angle between the extrusion direction of the cylinder and its positive Z axis, measured around its X axis. The angle is positive towards its positive Y axis. Valid range: `0° <= value < 90°`. The default is `0°`. [introduced in 0.20](/Release_notes_0.20 "Release notes 0.20")

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Cylinder can be created with the `addObject()` method of the document:

```
cylinder = FreeCAD.ActiveDocument.addObject("Part::Cylinder", "myCylinder")

```

- Where `"myCylinder"` is the name for the object.
- The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

cylinder = doc.addObject("Part::Cylinder", "myCylinder")
cylinder.Radius = 10
cylinder.Height = 50
cylinder.Placement = App.Placement(App.Vector(5, 10, 15), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Cylinder/en&oldid=1466766>"
