---
title: Part Plane
---

|                                                                                                |
| ---------------------------------------------------------------------------------------------- |
| Part Plane                                                                                     |
| Menu location                                                                                  |
| Part → [Create primitives](/Part_Primitives "Part Primitives") → Plane                         |
| Workbenches                                                                                    |
| [Part](/Part_Workbench "Part Workbench"), [OpenSCAD](/OpenSCAD_Workbench "OpenSCAD Workbench") |
| Default shortcut                                                                               |
| _None_                                                                                         |
| Introduced in version                                                                          |
| -                                                                                              |
| See also                                                                                       |
| [Part Primitives](/Part_Primitives "Part Primitives")                                          |
|                                                                                                |

## Description

A ![](/images/Part_Plane.svg) **Part Plane** is a parametric rectangular plane that can be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. In the coordinate system defined by its Data**Placement** property, the plane lies on the XY plane with its front left corner at the origin, and its front edge parallel to the X axis.

![](/images/Part_Plane_Example.png)

## Usage

See [Part Primitives](/Part_Primitives#Usage "Part Primitives").

## Example

![](/images/Part_Plane_Scripting_Example.png)

Part Plane from the scripting example

A Part Plane object created with the [scripting example](#Scripting) below is shown here.

## Properties

See also: [Property editor](/Property_editor "Property editor").

A Part Plane object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Plane

- Data**Length** (`Length`): The length of the plane. This is the dimension in its X direction. The default is `10mm`.
- Data**Width** (`Length`): The width of the plane. This is the dimension in its Y direction. The default is `10mm`.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Plane can be created with the `addObject()` method of the document:

```
plane = FreeCAD.ActiveDocument.addObject("Part::Plane", "myPlane")

```

- Where `"myPlane"` is the name for the object.
- The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

plane = doc.addObject("Part::Plane", "myPlane")
plane.Length = 4
plane.Width = 8
plane.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(20, 75, 60))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Plane/en&oldid=1106446>"
