---
title: Part Helix
---

|                                                                                                |
| ---------------------------------------------------------------------------------------------- |
| Part Helix                                                                                     |
| Menu location                                                                                  |
| Part → [Create primitives](/Part_Primitives "Part Primitives") → Helix                         |
| Workbenches                                                                                    |
| [Part](/Part_Workbench "Part Workbench"), [OpenSCAD](/OpenSCAD_Workbench "OpenSCAD Workbench") |
| Default shortcut                                                                               |
| _None_                                                                                         |
| Introduced in version                                                                          |
| -                                                                                              |
| See also                                                                                       |
| [Part Primitives](/Part_Primitives "Part Primitives")                                          |
|                                                                                                |

## Description

A ![](/src/assets/images/Part_Helix.svg) **Part Helix** is a parametric shape that can be created with the ![](/src/assets/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. In the coordinate system defined by its Data**Placement** property, the axis of the helix matches the Z axis and its bottom point, the start point, lies on the X axis.

![](/src/assets/images/Part_Helix_Example.png)

## Usage

See [Part Primitives](/Part_Primitives#Usage "Part Primitives").

## Example

![](/src/assets/images/Part_Helix_Scripting_Example.png)

Part Helix from the scripting example

A Part Helix object created with the [scripting example](#Scripting) below is shown here.

## Notes

- A Part Helix can be used to create screw threads. See [Thread for Screw Tutorial](/Thread_for_Screw_Tutorial "Thread for Screw Tutorial").

## Properties

See also: [Property editor](/Property_editor "Property editor").

A Part Helix object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Coordinate System

- Data**Local Coord** (`Enumeration`): The [handedness](https://en.wikipedia.org/wiki/Screw_thread), or direction, of the helix: `Right-handed` or `Left-handed`. The default is `Right-handed`, meaning the helix turns counterclockwise as it goes up.

Helix

- Data**Pitch** (`Length`): The distance between two consecutive turns of the helix measured along its Z axis. The default is `1mm`.
- Data**Height** (`Length`): The height of the helix. The default is `2mm`.
- Data**Radius** (`Length`): The start radius of the helix. The helix has a constant radius if Data**Angle** is `0°`.
- Data**Segment Length** (`QuantityConstraint`): The number of turns per helix subdivision. The default is `1`, meaning each full turn of the helix is a separate segment. Use `0` to suppress subdivision.
- Data**Angle** (`Angle`): The angle that defines of the outer shape of the helix. Valid range: `-90° < value < 90°`. The default is `0°`. If it is `0°` the helix is cylindrical, else it is conical.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Helix can be created with the `addObject()` method of the document:

```
helix = FreeCAD.ActiveDocument.addObject("Part::Helix", "myHelix")

```

- Where `"myHelix"` is the name for the object.
- The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

helix = doc.addObject("Part::Helix", "myHelix")
helix.Pitch = 2
helix.Height = 3
helix.Radius = 4
helix.SegmentLength = 21
helix.Angle = 45
helix.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Helix/en&oldid=1106579>"
