---
title: Эллипсоид
---
|  |
| --- |
| Эллипсоид |
| Расположение в меню |
| Деталь → [Создать примитивы...](/Part_Primitives/ru "Part Primitives/ru") → Эллипсоид |
| Верстаки |
| [Деталь](/Part_Workbench/ru "Part Workbench/ru"), [OpenSCAD](/OpenSCAD_Workbench/ru "OpenSCAD Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| - |
| См. также |
| [Создать примитивы...](/Part_Primitives/ru "Part Primitives/ru") |
|  |

## Описание

![](/images/Part_Ellipsoid.svg) **Эллипсоид** - это параметрическое твёрдое тело, которое может быть создано с помощью команды ![](/images/Part_Primitives.svg) [Создать примитивы](/Part_Primitives/ru "Part Primitives/ru"). В системе координат, заданной свойством Данные**Размещение**, оси эллипсоида совпадают с осями X, Y и Z, и поэтому его центр расположен в начале координат.

Эллипсоид можно усечь сверху и/или снизу, изменив его свойства Данные**Угол1** и/или Данные**Угол2**. Его можно превратить в сегмент эллипсоида, изменив его свойство Данные**Угол3**.

![](/images/Part_Ellipsoid_Example.png)

## Применение

Смотри [Создать примитивы..](/Part_Primitives#Usage/ru "Part Primitives").

## Пример

![](/images/Part_Ellipsoid_Scripting_Example.png)

Деталь Эллипсоид из примера со скриптом

Здесь показан объект Деталь Эллипсоид, созданный с помощью примера [скрипта](#Scripting), приведенного ниже.

## Свойства

Смотрите также: [Редактор свойств](/Property_editor/ru "Property editor/ru").

Объект Эллипсоид является производным от объекта [Конструктивный элемент](/Part_Feature/ru "Part Feature/ru") и наследует все его свойства. Он также имеет следующие дополнительные свойства:

### Данные

Вложение

Объект имеет те же свойства вложения, что и [Деталь Деталь2DОбъект](/Part_Part2DObject#Data/ru "Part Part2DObject").

Эллипсоид

* Данные**Радиус1** (`Длина`): Радиус эллипсоида в направлении Z. По умолчанию `2мм`.
* Данные**Радиус2** (`Длина`): Радиус эллипсоида в направлении X. По умолчанию `4мм`.
* Данные**Радиус3** (`Длина`): Радиус эллипсоида в направлении Y. По умолчанию `4мм`.
* Данные**Угол1** (`Угол`): Начальный угол эллиптических сторон эллипсоида. Допустимый диапазон: `-90° <= значение < 90°`. Должен быть меньше, чем Данные**Угол2**. По умолчанию `-90°`.
* Данные**Угол2** (`Угол`): Конечный угол эллиптических сторон эллипсоида. Допустимый диапазон: `-90° < значение <= 90°`. Должно быть больше, чем Данные**Угол1**. По умолчанию `90°`. Если суммарный угол сторон эллипса меньше `180°`, эллипсоид будет усечённым и иметь плоскую поверхность сверху и/или снизу.
* Данные**Угол3** (`Угол`): Полный угол эллипсоида в его плоскости XY. Допустимый диапазон: `0° < значение <= 360°`. По умолчанию `360°`. Если оно меньше `360°`, то полученное твёрдое тело будет представлять собой сегмент эллипсоида.

## Написание скриптов

Смотри также: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Скрипты в верстаке Деталь](/Part_scripting/ru "Part scripting/ru") и [Основы работы со скриптами FreeCAD](/FreeCAD_Scripting_Basics/ru "FreeCAD Scripting Basics/ru").

Эллипсоид может быть создан с помощью метода `addObject()` документа:

```
ellipsoid = FreeCAD.ActiveDocument.addObject("Part::Ellipsoid", "myEllipsoid")

```

* Где`"myEllipsoid"` - это имя объекта.
* Функция возвращает только что созданный объект.

Пример:

```
import FreeCAD as App

doc = App.activeDocument()

ellipsoid = doc.addObject("Part::Ellipsoid", "myEllipsoid")
ellipsoid.Radius1 = 2
ellipsoid.Radius2 = 4
ellipsoid.Radius3 = 6
ellipsoid.Angle1 = -90
ellipsoid.Angle2 = 50
ellipsoid.Angle3 = 300
ellipsoid.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(15, 0, 20))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Ellipsoid/ru&oldid=1547296>"