---
title: Вырезать тонкостенный объект
---
|  |
| --- |
| Вырезать тонкостенный объект |
| Расположение в меню |
| Деталь → Соединить → Вырез объекта |
| Верстаки |
| [Деталь](/Part_Workbench/ru "Part Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| 0.16 |
| См. также |
| [Соединить тонкостенные](/Part_JoinConnect/ru "Part JoinConnect/ru"), [Внедрить тонкостенный](/Part_JoinEmbed/ru "Part JoinEmbed/ru"), [Булевы](/Part_Boolean/ru "Part Boolean/ru"), [Толщина](/Part_Thickness/ru "Part Thickness/ru") |
|  |

## Описание

Инструмент [24px](/index.php?title=%D0%98%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5:Part_JoinCutout.svg&action=edit&redlink=1 "Изображение:Part JoinCutout.svg (page does not exist)") **Вырезать тонкостенный объект** создаёт вырез в объекте со стенками (например, трубе) для установки другого объекта со стенками.

![](/images/JoinFeatures_Cutout.png)

## Применение

1. Выберите сначала базовый объект, затем объект для построения выреза. Порядок выделения важен. Достаточно выделить по одному элементу каждого объекта (например, грани).
2. Есть несколько способов вызвать команду:
   * Нажмите кнопку ![](/images/Part_JoinCutout.svg) Вырезать тонкостенный объект.
   * Выберите в меню **Детаь → Соединить → ![](/images/Part_JoinCutout.svg) Вырез объекта**.
3. Создаётся объект верстака Деталь JoinFeature с режимом 'Cutout (Вырез)'. Исходные объекты скрываются, а результат вырезания отображается в [3D виде](/3D_view/ru "3D view/ru").

## Свойства

Основные

* Данные**База**: Ссылка на базовый объект (тот, в котором нужно сделать вырез). Объект должен быть единым цельным.
* Данные**Tool (Инструмент)**: Ссылка на объект-инструмент (объект, который будет помещён в вырез). Объект может быть одним твёрдым телом или [подходящей группой/объединением](/Part_Compound/ru "Part Compound/ru") из твёрдых тел.
* Данные**Mode (Режим)**: Режим работы, соответствует 'Cutout (Вырез)' (изменение, которое превратит инструмент в другую Part\_JoinXXX). Значение 'bypass (игнорировать)' может быть использовано для временного отключения длительных вычислений (будет создано соединение базы и инструмента, что является быстрой операцией).
* Данные**Refine (Улучшить)**: Устанавливает, применять или нет операцию [Улучшить](/Part_RefineShape/ru "Part RefineShape/ru") к конечной форме. Значение по умолчанию определяется флажком 'Автоматическое уточнение формы после выполнения булевой операции' в настройках PartDesign (Проектной Детали). Когда свойство Режим (Mode) имеет значение 'игнорировать (bypass)', Улучшение (Refine) игнорируется (никогда не применяется).

## Пример

1. Создайте трубу применив [толщину](/Part_Thickness/ru "Part Thickness/ru") к [цилиндру](/Part_Cylinder/ru "Part Cylinder/ru"):   
   ![](/images/JoinFeatures_Example_step1.png)
2. Создайте ещё одну трубу, меньшего диаметра, и [разместите](/Placement/ru "Placement/ru") её так, чтобы она проникала в первую трубу:   
   ![](/images/JoinFeatures_Example_step2.png)
3. Выберите первую трубу, а затем вторую (порядок выбора важен), и нажмите кнопку «Вырезать объект» в раскрывающейся панели инструментов Объединить объекты....   
   ![](/images/JoinFeatures_Example_step3_Cutout.png)

## Алгоритм

Алгоритмы, лежащие в основе инструментов объединения, довольно просты, и понимание принципов их работы важно для правильного использования данных инструментов.

1. Базовый объект обрезается [булевым-обрезать](/Part_Cut/ru "Part Cut/ru") с помощью объекта Инструмент (Tool).
Результирующая фигура представляет собой набор ([группу](/Part_Compound/ru "Part Compound/ru")) непересекающихся твёрдых тел (обычно два).

2. Полученное соединение отфильтровывают: оставляя только самое крупное твёрдое тело.

4. Если свойство Улучшить (Refine) равно true, то результирующая форма будет [улучшена](/Part_RefineShape/ru "Part RefineShape/ru").
  
  
![](/images/JoinFeatures-Algo-Cutout.png)

### Примечания

* Если после шага 1 объект остаётся цельным, результат интрумента Вырезать будет эквивалентен [булеву варианту вырезать](/Part_Cut "Part Cut") из Базового тела с помощью Инструмента.
* Сейчас инструмент выдаёт неожиданный результат, если в качестве Базы указана группа (соединение). В будущем это может быть изменено.
* Поскольку самый большой элемент определяется путём сравнения объёмов элементов, то инструмент может работать только с твёрдыми телами. В будущем это может быть изменено.

## Написание скриптов

Инструменты Объединения можно использовать в [макросах](/Macros/ru "Macros/ru") и из консоли Python, используя следующую функцию:

```
JoinFeatures.makePartJoinFeature(name = 'Cutout', mode = 'Cutout')

```

* Создаёт пустой элемент Cutout (или другой элемент Join, в зависимости от выбранного режима). Свойства Base и Tool должны быть назначены явно, после чего.
* Возвращает только что созданный объект.

Пример:

```
import JoinFeatures
j = JoinFeatures.makePartJoinFeature(name = 'Cutout', mode = 'Cutout' )
j.Base = FreeCADGui.Selection.getSelection()[0]
j.Tool = FreeCADGui.Selection.getSelection()[1]

```

Сам инструмент реализован на Python, смотрите /Mod/Part/JoinFeatures.py ([ссылка Github](https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/JoinFeatures.py)) в разделе, где установлен FreeCAD.

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_JoinCutout/ru&oldid=1556459>"