---
title: Соединить тонкостенные объекты
---
|  |
| --- |
| Соединить тонкостенные объекты |
| Расположение в меню |
| Деталь → Соединить → Соединить объекты |
| Верстаки |
| [Деталь](/Part_Workbench/ru "Part Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| 0.16 |
| См. также |
| [Внедрить тонкостенные объекты](/Part_JoinEmbed/ru "Part JoinEmbed/ru"), [Вырезать в тонкостенном объекте](/Part_JoinCutout/ru "Part JoinCutout/ru"), [Булевы операции](/Part_Boolean/ru "Part Boolean/ru"), [Толщина](/Part_Thickness/ru "Part Thickness/ru") |
|  |

## Описание

Инструмент ![](/images/Part_JoinConnect.svg) **Соединить тонкостенные объекты** соединяет внутренности двух объектов со стенками (например, труб). Он также может соединять оболочки и кривые.

![](/images/JoinFeatures_Connect.png)

## Применение

1. Выберите объекты, которые необходимо соединить. Порядок выделения не важен, так как действие инструмента симметрично. Достаточно выделить по одному элементу геометрии каждого объекта (например, грани). Также можно выбрать группу (compound), содержащую все соединяемые фигуры, например [Draft OrthoArray (Ортогональный массив Черновика)](/Draft_OrthoArray/ru "Draft OrthoArray/ru").
2. Есть несколько способов вызвать инструмент:
   * Нажмите кнопку ![](/images/Part_JoinConnect.svg) [Соединить тонкостенные](/Part_JoinConnect "Part JoinConnect").
   * Выберите из меню **Деталь → Соединить → ![](/images/Part_JoinConnect.svg) Соединить объекты**.
3. Создаётся параметрический объект Connect. Исходные объекты скрываются, а результат соединения отображается в [3D виде](/3D_view/ru "3D view/ru").

## Свойства

Соединить

* Данные**Объекты (Objects)**: Список объектов, которые необходимо соединить. Как правило, требуется не менее двух объектов, но подойдет и один, содержащий соединяемые фигуры. (начиная с FreeCAD v0.17.8053, это свойство не отображается в [Редакторе свойств](/Property_editor/ru "Property editor/ru"), и доступ к нему можно получить только через скрипты на [Python](#Scripting)).
* Данные**Улучшить (Refine)**: Устанавливает, применять или нет операцию [Улучшить форму](/Part_RefineShape/ru "Part RefineShape/ru") к конечной форме. Значение по умолчанию определяется флажком 'Автоматическое уточнение формы после выполнения булевой операции' в [Настройках ПроектДетали (PartDesign)](/PartDesign_Preferences/ru "PartDesign Preferences/ru").

## Пример

1. Создайте трубу, применив [толщину](/Part_Thickness/ru "Part Thickness/ru") к [цилиндру](/Part_Cylinder/ru "Part Cylinder/ru"):   
   ![](/images/JoinFeatures_Example_step1.png)
2. Создайте ещё одну трубу меньшего диаметра, и [разместите](/Placement/ru "Placement/ru") её так, чтобы она проникала сквозь одну стенку первой трубы:   
   ![](/images/JoinFeatures_Example_step2.png)
3. Выберите первую и вторую трубу и нажмите кнопку «Соединить объекты» на раскрывающейся панели инструментов Объединить объекты...   
   ![](/images/JoinFeatures_Example_step3_Connect.png)
4. Используйте какой либо инструмент для создания сечений. Например: ([Плоскость сечения](/Std_ToggleClipPlane/ru "Std ToggleClipPlane/ru"), [Архитектура Плоскость Сечения](/Arch_SectionPlane/ru "Arch SectionPlane/ru"), [Архитектура Секущая плоскость](/Arch_CutPlane/ru "Arch CutPlane/ru")) чтобы показать внутренние детали. На рисунке ниже используется плоскость сечения верстака Архитектура (Arch).  
   ![](/images/JoinFeatures_Example_step4_Connect.png)

## Алгоритм

Алгоритмы, лежащие в основе инструментов Объединить, довольно просты, но их понимание важно для правильного использования инструментов. Алгоритм Соединить (Connect), в частности, немного сложнее других, но в целом достаточно думать о нём как о симметричном варианте [алгоритма Внедрить (Embed)](/Part_JoinEmbed/ru#Алгоритм "Part JoinEmbed/ru").

1. Каждый объект разбивается на части пересечениями с другими объектами. (см. [Фрагменты булевой операции](/Part_BooleanFragments/ru "Part BooleanFragments/ru"))

2. Из частей предмета сохраняется только самая большая, все остальные выбрасываются.

3. К результату добавляются фрагменты пересечения, которые касаются как минимум двух объектов. Затем эти части соединяются вместе, чтобы получить результат команды Соединить (Connect).

## Примечания

* Если на шаге 1 каждый объект остается целым, результат Соединения будет эквивалентен [обычному объединению](/Part_Fuse/ru "Part Fuse/ru") объектов.
* Теперь все предоставленные соединения разгруппировываются перед соединением. Это означает, что самопересекающиеся соединения, которые недопустимы для всех других булевых операций, допустимы для Соединения . (Это может быть изменено в будущем.)
* «Самый большой» фрагмент - это тот, который имеет наибольшую массу. То есть, для твёрдых тел сравниваются объёмы, для оболочек и граней - площади, и так далее.
* Начиная с FreeCAD v0.17.8053, и если версия OCC 6.9.0 и выше, Соединение выполняется почти так же быстро, как и все остальные булевы операции. В более ранних версиях Соединение работает примерно в 5 раз медленнее, чем обычные булевы операции, и работает только на твёрдых телах.

## Написание скриптов

Инструмент Соединить можно использовать в [макросах](/Macros/ru "Macros/ru") и из консоли [Python](/Python/ru "Python/ru") с помощью следующей функции:

```
BOPTools.JoinFeatures.makeConnect(name)

```

* Создает пустую функцию Connect. Свойство 'Objects' должно быть назначено явно, после чего.
* Возвращает только что созданный объект.

Соединить также можно применять к обычным фигурам, без необходимости иметь объект документа, с помощью:

```
Part.BOPTools.JoinAPI.connect(list_of_shapes, tolerance = 0.0)

```

Это может быть полезно для создания пользовательских функций на основе скриптов Python.

Пример:

```
import Part
j = Part.BOPTools.JoinFeatures.makeConnect(name= 'Connect')
j.Objects = FreeCADGui.Selection.getSelection()

```

Сам инструмент реализован на Python, смотрите /Mod/Part/BOPTools/JoinFeatures.py ([ссылка Github](https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/BOPTools/JoinFeatures.py)) в разделе, где установлен FreeCAD.

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_JoinConnect/ru&oldid=1555748>"