---
title: Окружность
---
|  |
| --- |
| Окружность |
| Расположение в меню |
| Деталь → [Создать примитивы...](/Part_Primitives/ru "Part Primitives/ru") → Окружность |
| Верстаки |
| [Деталь](/Part_Workbench/ru "Part Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| - |
| См. также |
| *Нет* |
|  |

## Описание

![](/images/Part_Circle.svg) **Окружность**- это параметрическая геометрия, которая может быть создана с помощью команды ![](/images/Part_Primitives.svg) [Создать примитивы](/Part_Primitives/ru "Part Primitives/ru"). В системе координат, заданной свойством Данные**Размещение**, окружность лежит на плоскости XY с центром в начале координат.

Окружность - по факту замкнутая круговая дуга, направленная против часовой стрелки, её можно превратить в обычную дугу, изменив её свойства Данные**Угол1** и/или Данные**Угол2**.

![](/images/Part_Circle_Example.png)

## Применение

Смотри [Создать примитивы..](/Part_Primitives#Usage/ru "Part Primitives").

Также Окружность можно создать, по трём точка:

1. На панели задач команды ![](/images/Part_Primitives.svg) [Создать примитивы](/Part_Primitives/ru "Part Primitives/ru") выберите опцию **![](/images/Part_Circle.svg) Окружность** из выпадающего списка.
2. Нажмите кнопку По трём точкам.
3. Выберите три вершины в [3D виде](/3D_view/ru "3D view/ru"). Не нужно удерживать клавишу Ctrl.
4. Окружность создана.
5. Выбранные вершины используются только во время создания для расчёта Данные**Радиуса** и Данные**Размещения** окружности.

## Пример

![](/images/Part_Circle_Scripting_Example.png)

Элемент Окружность из примера со скриптом

Здесь показан объект Окружность, созданный с помощью примера [скрипта](#Scripting), приведенного ниже.

## Свойства

Смотрите также: [Редактор свойств](/Property_editor/ru "Property editor/ru").

Объект Окружность является производным от объекта [Конструктивный элемент](/Part_Feature/ru "Part Feature/ru") и наследует все его свойства. Она также имеет следующие дополнительные свойства:

### Данные

Вложение

Объект имеет те же свойства вложения, что и [Деталь Деталь2DОбъект](/Part_Part2DObject#Data/ru "Part Part2DObject").

Основные

* Данные**Радиус** (`Длина`): Радиус окружности или дуги окружности. По умолчанию `2мм`.
* Данные**Угол1** (`Угол`): Начальный угол дуги окружности. Допустимый диапазон: `0° < значение <= 360°`. По умолчанию `0°`.
* Данные**Угол2** (`Угол`): Конечный угол дуги окружности. Допустимый диапазон: `0° < значение <= 360°`. По умолчанию используется значение `360°`. Если Данные**Угол1** и Данные**Угол2** равны, или если один угол равен `0°`, а другой `360°`, создаётся полная окружность.

## Написание скриптов

Смотри также: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Скрипты в верстаке Деталь](/Part_scripting/ru "Part scripting/ru") и [Основы работы со скриптами FreeCAD](/FreeCAD_Scripting_Basics/ru "FreeCAD Scripting Basics/ru").

Окружность может быть создана с помощью метода `addObject()` документа:

```
circle = FreeCAD.ActiveDocument.addObject("Part::Circle", "myCircle")

```

* Где`"myCircle"` - это имя объекта.
* Функция возвращает только что созданный объект.

Пример:

```
import FreeCAD as App

doc = App.activeDocument()

circle = doc.addObject("Part::Circle", "myCircle")
circle.Radius = 10
circle.Angle1 = 45
circle.Angle2 = 225
circle.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Circle/ru&oldid=1548089>"