---
title: Эллипс
---
|  |
| --- |
| Эллипс |
| Расположение в меню |
| Деталь → [Создать примитивы](/Part_Primitives/ru "Part Primitives/ru") → Эллипс |
| Верстаки |
| [Деталь](/Part_Workbench/ru "Part Workbench/ru"), [OpenSCAD](/OpenSCAD_Workbench/ru "OpenSCAD Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| - |
| См. также |
| [Создать примитивы](/Part_Primitives/ru "Part Primitives/ru") |
|  |

## Описание

![](/images/Part_Ellipse.svg) **Эллипс** - это параметрическая фигура, которая может быть создана с помощью команды ![](/images/Part_Primitives.svg) [Создать примитивы](/Part_Primitives/ru "Part Primitives/ru"). В системе координат, заданной свойством Данные**Размещение**, эллипс лежит в плоскости XY с центром в начале координат. Его главная ось параллельна оси X.

Эллипс - это замкнутая эллиптическая дуга направленная против часовой стрелки, которую можно превратить в дугу, изменив еёсвойства Данные**Угол1** и/или Данные**Угол2**.

![](/images/Part_Ellipse_Example.png)

## Применение

Смотри [Создать примитивы..](/Part_Primitives#Usage/ru "Part Primitives").

## Пример

![](/images/Part_Ellipse_Scripting_Example.png)

Элемент Эллипс из примера со скриптом

Здесь показан объект Эллипс, созданный с помощью примера [скрипта](#Scripting), приведённого ниже.

## Свойства

Смотрите также: [Редактор свойств](/Property_editor/ru "Property editor/ru").

Объект Эллипс является производным от объекта [Конструктивный элемент](/Part_Feature/ru "Part Feature/ru") и наследует все его свойства. Он также имеет следующие дополнительные свойства:

### Данные

Вложение

Объект имеет те же свойства вложения, что и [Деталь Деталь2DОбъект](/Part_Part2DObject#Data/ru "Part Part2DObject").

Основные

* Данные**Главный Радиус** (`Длина`): Главный радиус эллипса или эллиптической дуги. По умолчанию `4мм`.
* Данные**Малый Радиус** (`Длина`): Малый радиус эллипса или эллиптической дуги. По умолчанию `2мм`.
* Данные**Угол1** (`Угол`): Начальный угол эллиптической дуги. Допустимый диапазон: `0° < значение <= 360°`. По умолчанию `0°`.
* Данные**Угол2** (`Угол`): Конечный угол эллиптической дуги. Допустимый диапазон: `0° < значение <= 360°`. По умолчанию используется значение `360°`. Если Данные**Угол1** и Данные**Угол2** равны, или если один угол равен `0°`, а другой `360°`, создаётся полный эллипс.

## Написание скриптов

Смотри также: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Скрипты в верстаке Деталь](/Part_scripting/ru "Part scripting/ru") и [Основы работы со скриптами FreeCAD](/FreeCAD_Scripting_Basics/ru "FreeCAD Scripting Basics/ru").

Эллипс может быть создан с помощью метода `addObject()` документа:

```
ellipse = FreeCAD.ActiveDocument.addObject("Part::Ellipse", "myEllipse")

```

* Где`"myEllipse"` - это имя объекта.
* Функция возвращает только что созданный объект.

Пример:

```
import FreeCAD as App

doc = App.activeDocument()

ellipse = doc.addObject("Part::Ellipse", "myEllipse")
ellipse.MajorRadius = 20
ellipse.MinorRadius = 10
ellipse.Angle1 = 45
ellipse.Angle2 = 135
ellipse.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Ellipse/ru&oldid=1548223>"