---
title: Спираль винтовая (Helix)
---
|  |
| --- |
| Спираль винтовая |
| Расположение в меню |
| Деталь → [Создать примитивы...](/Part_Primitives/ru "Part Primitives/ru") → Спираль винтовая |
| Верстаки |
| [Деталь](/Part_Workbench/ru "Part Workbench/ru"), [OpenSCAD](/OpenSCAD_Workbench/ru "OpenSCAD Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| - |
| См. также |
| [Создать примитивы](/Part_Primitives/ru "Part Primitives/ru") |
|  |

## Описание

![](/images/Part_Helix.svg) **Винтовая спираль** это параметрическая кривая, которая может быть создана с помощью команды ![](/images/Part_Primitives.svg) [Создать примитивы](/Part_Primitives/ru "Part Primitives/ru"). В системе координат, заданной свойством Данные**Размещение**, ось спирали совпадает с осью Z, а ее нижняя точка, точка начала, лежит на оси X.

![](/images/Part_Helix_Example.png)

## Применение

Смотри [Создать примитивы..](/Part_Primitives#Usage/ru "Part Primitives").

## Пример

![](/images/Part_Helix_Scripting_Example.png)

Элемент Спираль из примера со скриптом

Здесь показан объект Спираль винтовая, созданный с помощью примера [скрипта](#Scripting), приведенного ниже.

## Примечания

* Винтовую спираль можно использовать для создания винтовой резьбы. Смотри [Руководство по созданию резьбы](/Thread_for_Screw_Tutorial/ru "Thread for Screw Tutorial/ru").

## Свойства

Смотрите также: [Редактор свойств](/Property_editor/ru "Property editor/ru").

Объект Спираль винтовая является производным от объекта [Конструктивный элемент](/Part_Feature/ru "Part Feature/ru") и наследует все его свойства. Он также имеет следующие дополнительные свойства:

### Данные

Вложение

Объект имеет те же свойства вложения, что и [Деталь Деталь2DОбъект](/Part_Part2DObject#Data/ru "Part Part2DObject").

Координатна система

* Данные**Система координат** (`Перечисление`): [Направление](https://en.wikipedia.org/wiki/Screw_thread#Handedness), или направление спирали: `Правая резьба` или `Левая резьба`. По умолчанию используется `Правая резьба`, что означает, что спираль вращается против часовой стрелки по мере подъема.

Спираль винтовая

* Данные**Шаг** (`Длина`): Расстояние между двумя последовательными витками спирали, измеренное вдоль ее оси Z. По умолчанию `1мм`.
* Данные**Высота** (`Длина`): Высота спирали. По умолчанию `2мм`.
* Данные**Радиус** (`Длина`): Начальный радиус спирали. Спираль имеет постоянный радиус, если Данные**Угол** равен`0°`.
* Данные**Длина Сегмента** (`Ограничение количества`): Количество витков в каждом сегменте спирали. По умолчанию `1`, то есть каждый полный оборот спирали представляет собой отдельный сегмент. Используйте заначение `0` для подавления дробления.
* Данные**Угол** (`Угол`): Угол, определяющий внешний уклон спирали. Допустимый диапазон: `-90° < значение < 90°`. По умолчанию `0°`. Если угол равен `0°`, то спираль цилиндрическая, иначе коническая.

## Написание скриптов

Смотри также: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Скрипты в верстаке Деталь](/Part_scripting/ru "Part scripting/ru") и [Основы работы со скриптами FreeCAD](/FreeCAD_Scripting_Basics/ru "FreeCAD Scripting Basics/ru").

Спираль может быть создана с помощью метода `addObject()` документа:

```
helix = FreeCAD.ActiveDocument.addObject("Part::Helix", "myHelix")

```

* Где`"myHelix"` - это имя объекта.
* Функция возвращает только что созданный объект.

Пример:

```
import FreeCAD as App

doc = App.activeDocument()

helix = doc.addObject("Part::Helix", "myHelix")
helix.Pitch = 2
helix.Height = 3
helix.Radius = 4
helix.SegmentLength = 21
helix.Angle = 45
helix.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Helix/ru&oldid=1547984>"