---
title: Разрезать и сгруппировать
---
|  |
| --- |
| Разрезать и сгруппировать |
| Расположение в меню |
| Деталь → Разделить → Нарезать, чтобы соединить |
| Верстаки |
| [Part](/Part_Workbench/ru "Part Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| 0.17 |
| См. также |
| [Булево разделение](/Part_BooleanFragments/ru "Part BooleanFragments/ru"), [Булева XOR](/Part_XOR/ru "Part XOR/ru"), [Обрезать](/Part_Cut/ru "Part Cut/ru"), [Булевы операции](/Part_Boolean/ru "Part Boolean/ru") |
|  |

## Описание

Инструмент [[[Image:Part\_Slice.svg|24px]] Нарезать], также известный как **Нарезать и сгруппировать**, используется для разделения фигур путём пересечения с другими фигурами. Например, для куба и плоскости создаётся группа (объединение)из двух твёрдых тел.

![](/images/Part_Slice_Demo.png)

Вверху: части были впоследствии раздвинуты вручную, чтобы показать разрез

Существует две команды для нарезки фигуры: ![](/images/Part_SliceApart.svg) [Разрезать на части](/Part_SliceApart/ru "Part SliceApart/ru") и ![](/images/Part_Slice.svg) Разрезать и сгруппировать. Они обе создают параметрическую функцию 'Slice (Разрезать)', которая помещает нарезанные части в группу (объединение). Однако ![](/images/Part_SliceApart.svg) [Разрезать на части](/Part_SliceApart/ru "Part SliceApart/ru") разрушает полученное объединение на отдельные объекты. «Разрезать и сгруппировать» является полностью параметрической и не вызывает проблем при изменении количества частей. «Разделить на части» не будет обновлять количество объектов при изменении количества частей.

Итоговая фигура занимает тот же объём, что и исходная. Но она разделена в местах пересечения с другими фигурами. Разделенные части помещаются в группу (или compsolid-объединение), так что объект кажется единым целым. Чтобы получить отдельные части, нужно разрушить соединение. Если вы хотите получить доступ к отдельным частям параметрическим способом, вы можете использовать ![](/images/Part_CompoundFilter.svg) [Фильтр компонентов](/Part_CompoundFilter/ru "Part CompoundFilter/ru") для этой цели. Для быстрого непараметрического доступа используйте ![](/images/Draft_Downgrade.svg) [Draft Даунгрейд](/Draft_Downgrade "Draft Downgrade").

Инструмент имеет три режима: "Standard-Стандартный", "Split-Разрезать" и "CompSolid-Группа". Форма выбора отсутствует, они предопределены, но могут быть доступны после выполнения операции на уровне результирующих срезов.

«Standard» и «Split» различаются действием инструмента на рёбра, оболочки и составные тела: если «Split», они разделяются; если «Standard», они остаются вместе (получают дополнительные сегменты).

Составная структура в режимах «Standard» и «Split» следует за составной структурой разрезаемой формы.

В режиме «CompSolid» на выходе получается объединённое твёрдое тело (или объединение группы тел, если полученные твёрдые тела образуют более одного участка смежности). Compsolid - это набор тел, соединенных гранями; они связаны с твёрдыми телами, как кривые связаны с рёбрами, а оболочки связаны с гранями; название, вероятно, является сокращённым словосочетанием «композитное твёрдое тело».

Общее действие инструмента очень похоже на ![](/images/Part_BooleanFragments.svg) [Булево разделение](/Part_BooleanFragments/ru "Part BooleanFragments/ru"), за исключением того, что в результат попадают только части от первой фигуры.

## Применение

1. Сначала выберите объект для разрезания, а затем несколько объектов, которые будут резать.   
    Порядок выбора важен. Группы с самопересечениями не допускаются (самопересечения иногда можно учесть, пропустив соединение через ![](/images/Part_BooleanFragments.svg) [Булево Разделение](/Part_BooleanFragments/ru "Part BooleanFragments/ru"))
2. Вызовите команду Разрезать и сгруппировать одним из способов:
   * Нажмите кнопку ![](/images/Part_Slice.svg) Нарезать на панели инструментов Part
   * Используйте пункт в меню **Деталь → Разделить → Нарезать чтобы соединить**

1. Примечаниеː Объекты для разрезания должны полностью разделять объект, который нужно нарезать. Таким образом, куб не может быть разрезан кривой, но может быть разрезан, например, плоскостью, полученной выдавливанием кривой.

Создается параметрический объект Slice. Исходные объекты скрываются, а результат пересечения показываются в [3D виде](/3D_view/ru "3D view/ru").

### Дерево структура Slice

Команда Разрезать и сгруппировать создаёт разрезанный объект. В следующем примере куб разрезается гранью.

Создаётся ннарезка, и каждый её фрагмент объединяется в группу.

![](/images/Part_SliceTree.png)

## Свойства

Разрезать

* Данные**База**: Разрезаемый объект.
* Данные**Tools-Инструменты**: список режущих объектов. (начиная с FreeCAD v0.17.8053, это свойство не отображается в редакторе свойств и доступно только через Python).
* Данные**Mode-Режим**: «Standard (Стандарт)», «Split (Разрезать)» или «CompSolid (Группа)». Режим "Разрезать" установлен по умолчанию. Стандартный и Разрезатьотличаются действием инструмента на воздействуемые фигуры: если режим Разрезать, то они разделяются; в противном случае они хранятся вместе (получаются дополнительные сегменты).
* Данные**Tolerance (Точность)**: значение "нечёткости". Это дополнительный допуск, который применяется при поиске пересечений в дополнении к допускам, сохранённым во входных фигурах.

̈Примечаниеː Свойства доступны на внутреннем объекте срезов, а не на уровне результата.

## Пример

### Создание мозайки-пазла

1. Переключитесь на верстак ![](/images/Workbench_Sketcher.svg) [Sketcher (Эскизы)](/Sketcher_Workbench/ru "Sketcher Workbench/ru")
   * Создайте новый эскиз.
   * Нарисуйте прямоугольник, который обозначит внешние границы мозайки.
   * Закройте эскиз.  
     ![](/images/Slice_example_step1.png)
2. Переключитесь на верстак ![](/images/Workbench_Part.svg) [Part (Деталь)](/Part_Workbench/ru "Part Workbench/ru").
   * Выберите эскиз и в меню выберите**Деталь → Создать грань из ломанных**.  
     ![](/images/Slice_example_step2.png)
3. Переключитесь обратно на верскак ![](/images/Workbench_Sketcher.svg) [Эскизы](/Sketcher_Workbench/ru "Sketcher Workbench/ru")
   * Создайте ещё один эскиз в той же плоскости.
   * Используя инструмент полилинии, нарисуйте линии, которые разделят мозайку на части.  
     ![](/images/Slice_example_step3.png)
4. Вернитесь на верстак ![](/images/Workbench_Part.svg) [Деталь](/Part_Workbench/ru "Part Workbench/ru").
   * Выделите эскиз разделителя и используйте ![](/images/Part_BooleanFragments.svg) [Булево разделение](/Part_BooleanFragments/ru "Part BooleanFragments/ru"). Это вставит вершины в места пересечения линий эскиза разделителя. Их наличие необходимо для работы на следующем этапе.  
     ![](/images/Slice_example_step4.png)
5. Выберите ранее созданную прямоугольную грань и только созданное BooleanFragments (Булево разделение) эскиза разделителя и примените функцию ![](/images/Part_Slice.svg) Разрезать и сгруппировать.  
   ![](/images/Slice_example_step5.png)
6. Используйте команду ![](/images/Part_ExplodeCompound.svg) [Разгруппировать объединение](/Part_ExplodeCompound/ru "Part ExplodeCompound/ru") к разрезанной грани, чтобы разбить соединение, созданное функцией Разрезать, на отдельные части.

**Примечание:** Шаги 5 и 6 можно выполнить одним щелчком мыши, используя ![](/images/Part_SliceApart.svg) [Разрезать на части](/Part_SliceApart/ru "Part SliceApart/ru")

## Примечания

* Инструмент был представлен в FreeCAD v0.17.8053. FreeCAD необходимо скомпилировать с OCC 6.9.0 или новее; иначе инструмент будет недоступен.
* ̈Свойства доступны на внутреннем объекте срезов, а не на уровне результата.
* Нарезающие объекты должны полностью разделять объект, который нужно нарезать. Таким образом, куб не может быть разрезан кривой, а может быть разрезан, например, гранью, полученной из выдавливания кривой.
* Нарезанный объект должен пройти проверку BOP. См. ![](/images/Part_CheckGeometry.svg) [Проверка геометрии](/Part_CheckGeometry/ru "Part CheckGeometry/ru").

## Написание скриптов

Инструмент можно использовать в [макросах](/Macros/ru "Macros/ru") и из консоли [Python](/Python/ru "Python/ru") с помощью следующей функции:

```
BOPTools.SplitFeatures.makeSlice(name)

```

* Создает пустую функцию Slice. Свойства 'Base' и 'Tools' должны быть назначены впоследствии явно.
* Возвращает вновь созданный объект.

Slice также может применяться к простым формам, без необходимости наличия объекта документа, с помощью:

```
BOPTools.SplitAPI.slice(base_shape, tool_shapes, mode, tolerance = 0.0)

```

Это может быть полезно для создания пользовательских сценарных атрибутов на Python.

Пример:

```
import BOPTools.SplitFeatures
j = BOPTools.SplitFeatures.makeSlice(name= 'Slice')
j.Base = FreeCADGui.Selection.getSelection()[0]
j.Tools = FreeCADGui.Selection.getSelection()[1:]

```

Сам инструмент выполнен на Python, смотрите /Mod/Part/BOPTools/SplitFeatures.py ([GitHub link](https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/BOPTools/SplitFeatures.py)) внутри каталога установки FreeCAD.

## Учебники

* [FreeCad 0.18 Верстак Деталь с использованием Slice и Slice Apart](https://www.youtube.com/watch?v=tzHkQaHgrfQ) (на английском языке), автор: Ха Гэй

* [FreeCAD Slice und Slice Apart und andere Tricks](https://www.youtube.com/watch?v=JJAL5JmqqKQ) (Немецкий язык), автор: Ха Гэй

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Slice/ru&oldid=1557014>"