---
title: Создать трубу
---
|  |
| --- |
| Труба |
| Расположение в меню |
| Деталь → Примитивы → Создать трубу |
| Верстаки |
| [Деталь](/Part_Workbench/ru "Part Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| 0.19 |
| См. также |
| [Примитивы](/Part_CreatePrimitives/ru "Part CreatePrimitives/ru") |
|  |

## Описание

Команда ![](/images/Part_Tube.svg) **Создать трубу** создаёт параметрическую твёрдотельную трубу. В системе координат, заданной свойством Данные**Размещение**, нижняя грань трубы лежит на плоскости XY с центром в начале координат.

![](/images/Part_Tube_Example.png)

## Применение

### Создание

1. Существует несколько способов вызова команды:
   * Нажмите кнопку ![](/images/Part_Tube.svg) Труба.
   * Выберите опцию меню **Деталь → Примитивы → ![](/images/Part_Tube.svg)Создать трубу**.
2. Откроется панель задач **Труба**, и в [3D виде](/3D_view/ru "3D view/ru") появится предварительный просмотр трубы.
3. Задайте размеры.
4. Предварительный просмотр динамически обновляется.
5. Нажмите кнопку OK.
6. Труба создана.
7. По желанию измените Данные**Размещение** трубы в [Редакторе свойств](/Property_editor/ru "Property editor/ru"), или с помощью команды ![](/images/Std_TransformManip.svg) [Преобразовать](/Std_TransformManip "Std TransformManip").

### Редактирование

1. Двойной щелчок по объекту в [Дереве проекта](/Tree_view/ru "Tree view/ru")
2. Откроется панель задач **Труба**.
3. Измените один или несколько размеров.
4. Труба динамически обновится в [3D виде](/3D_view/ru "3D view/ru").
5. Нажмите кнопку OK.

## Пример

![](/images/Part_Tube_Scripting_Example.png)

Деталь Труба из примера со скриптом

Здесь показан объект Деталь Труба, созданный с помощью примера [скрипта](#Scripting), приведенного ниже.

## Свойства

Смотрите также: [Редактор свойств](/Property_editor/ru "Property editor/ru").

Объект Труба является производным от объекта [Конструктивный элемент](/Part_Feature/ru "Part Feature/ru") и наследует все его свойства. Он также имеет следующие дополнительные свойства:

### Данные

Вложение

Объект имеет те же свойства вложения, что и [Деталь Деталь2DОбъект](/Part_Part2DObject#Data/ru "Part Part2DObject").

Труба

* Данные**Высота** (`Длина`): Высота трубы. По умолчанию `10мм`.
* Данные**Внутренний радиус** (`Длина`): Внутренний радиус трубы. Должен быть меньше чем Данные**Внешний радиус**. Может быть равен `0`. По умолчанию `2мм`.
* Данные**Внешний радиус** (`Длина`): Внешний радиус трубы. Должен быть больше чем Данные**Внутренний радиус**. По умолчанию `5мм`.

## Написание скриптов

Смотри также: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Скрипты в верстаке Деталь](/Part_scripting/ru "Part scripting/ru") и [Основы работы со скриптами FreeCAD](/FreeCAD_Scripting_Basics/ru "FreeCAD Scripting Basics/ru").

Труба может быть создана с помощью метода `addTube()` ([представлено в версии 0.20](/Release_notes_0.20/ru "Release notes 0.20/ru")) модуля Shapes:

```
tube = Shapes.addTube(FreeCAD.ActiveDocument, "myTube")

```

* Где`"myTube"` - это имя объекта.
* Функция возвращает только что созданный объект.

Пример:

```
import FreeCAD as App
from BasicShapes import Shapes

doc = App.activeDocument()

tube = Shapes.addTube(FreeCAD.ActiveDocument, "myTube")
tube.Height = 20
tube.InnerRadius = 2
tube.OuterRadius = 3
tube.Placement = App.Placement(App.Vector(2, 4, 5), App.Rotation(60, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Tube/ru&oldid=1546994>"