---
title: Правильный Многоугольник
---
|  |
| --- |
| Правильный Многоугольник |
| Расположение в меню |
| Деталь → [Создать примитивы...](/Part_CreatePrimitives "Part CreatePrimitives") → Правильный Многоугольник |
| Верстаки |
| [Деталь](/Part_Workbench/ru "Part Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| 0.14 |
| См. также |
| [Создать примитивы](/Part_Primitives/ru "Part Primitives/ru") |
|  |

## Описание

![](/images/Part_RegularPolygon.svg) **Правильный Многоугольник** - это параметрическая фигура, которая может быть создана с помощью команды![](/images/Part_Primitives.svg) [Создать примитивы](/Part_Primitives/ru "Part Primitives/ru"). В системе координат, заданной свойством Данные**Размещение**, многоугольник лежит в плоскости XY с центром в начале координат и одной из вершин на оси X.

![](/images/Part_RegularPolygon_Example.png)

## Применение

Смотри [Создать примитивы](/Part_Primitives#Usage/ru "Part Primitives").

## Пример

![](/images/Part_RegularPolygon_Scripting_Example.png)

Элемент Правильный многоугольник из примера со скриптом

Здесь показан объект Линия, созданный с помощью примера [скрипта](#Scripting), приведённого ниже.

## Свойства

Смотрите также: [Редактор свойств](/Property_editor/ru "Property editor/ru").

Объект Правильный многоугольник является производным от объекта [Конструктивный элемент](/Part_Feature/ru "Part Feature/ru") и наследует все его свойства. Он также имеет следующие дополнительные свойства:

### Данные

Вложение

Объект имеет те же свойства вложения, что и [Деталь Деталь2DОбъект](/Part_Part2DObject#Data/ru "Part Part2DObject").

Правильный Многоугольник

* Данные**Полигоны** (`Целочисленное`): Количество сторон многоугольника. По умолчанию `6`.
* Данные**Описанный радиус** (`Длина`): Радиус окружности, которая окружает многоугольник, расстояние от центра многоугольника до одной из его вершин. По умолчанию `2мм`.

## Написание скриптов

Смотри также: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Скрипты в верстаке Деталь](/Part_scripting/ru "Part scripting/ru") и [Основы работы со скриптами FreeCAD](/FreeCAD_Scripting_Basics/ru "FreeCAD Scripting Basics/ru").

Правильный Многоугольникможет быть создан с помощью метода `addObject()` документа:

```
poly = FreeCAD.ActiveDocument.addObject("Part::RegularPolygon", "myPolygon")

```

* Где`"myPolygon"` - это имя объекта.
* Функция возвращает только что созданный объект.

Пример:

```
import FreeCAD as App

doc = App.activeDocument()

poly = doc.addObject("Part::RegularPolygon", "myPolygon")
poly.Polygon = 5
poly.Circumradius = 8
poly.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(60, 30, 15))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_RegularPolygon/ru&oldid=1548348>"