---
title: Призма
---
|  |
| --- |
| Призма |
| Расположение в меню |
| Деталь → [Создать примитивы...](/Part_CreatePrimitives/ru "Part CreatePrimitives/ru") → Призма |
| Верстаки |
| [Деталь](/Part_Workbench/ru "Part Workbench/ru"), [OpenSCAD](/OpenSCAD_Workbench/ru "OpenSCAD Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| 0.14 |
| См. также |
| [Примитивы](/Part_Primitives/ru "Part Primitives/ru"), [Куб](/Part_Box/ru "Part Box/ru") |
|  |

## Описание

![](/images/Part_Prism.svg) **Призма** - это параметрическое твёрдое тело, которое может быть создано с помощью команды ![](/images/Part_Primitives.svg) [Создать примитивы](/Part_Primitives/ru "Part Primitives/ru"). Это результат выдавливания правильного многоугольника по прямой траектории. В системе координат, заданной свойством Данные**Размещение**, нижняя грань призмы лежит в плоскости XY с центром в начале координат и одной из вершин на оси X.

![](/images/Part_Prism_Example.png)

## Применение

Смотри [Создать примитивы..](/Part_Primitives#Usage/ru "Part Primitives").

## Пример

![](/images/Part_Prism_Scripting_Example.png)

Деталь Призма из примера со скриптом

Здесь показан объект Деталь Призма, созданная с помощью примера [скрипта](#Scripting), приведенного ниже.

## Свойства

Смотрите также: [Редактор свойств](/Property_editor/ru "Property editor/ru").

Объект Призма является производным от объекта [Конструктивный элемент](/Part_Feature/ru "Part Feature/ru") и наследует все его свойства. Он также имеет следующие дополнительные свойства:

### Данные

Вложение

Объект имеет те же свойства вложения, что и [Деталь Деталь2DОбъект](/Part_Part2DObject#Data/ru "Part Part2DObject").

Призма

* Данные**Полигоны** (`Целочисленное`): Количество сторон многоугольника. По умолчанию `6`.
* Данные**Радиус** (`Длина`): Радиус описанной окружности многоугольника, расстояние от центра многоугольника до одной из его вершин. По умолчанию `2мм`.
* Данные**Высота** (`Длина`): Высота призмы. По умолчанию `10мм`.
* Данные**Первый угол** (`Угол`): Угол между направлением выдавливания призмы и её положительной осью Z, измеренный вокруг оси Y. Угол положителен по отношению к положительной оси X. Допустимый диапазон: `0° <= значение < 90°`. По умолчанию `0°`.
* Данные**Второй угол** (`Угол`): Угол между направлением выдавливания призмы и её положительной осью Z, измеренный вокруг оси X. Угол положителен по отношению к положительной оси Y. Допустимый диапазон: `0° <= значение < 90°`. По умолчанию `0°`.

## Написание скриптов

Смотри также: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Скрипты в верстаке Деталь](/Part_scripting/ru "Part scripting/ru") и [Основы работы со скриптами FreeCAD](/FreeCAD_Scripting_Basics/ru "FreeCAD Scripting Basics/ru").

Призма может быть создана с помощью метода `addObject()` документа:

```
prism = FreeCAD.ActiveDocument.addObject("Part::Prism", "myPrism")

```

* Где`"myPrism"` - это имя объекта.
* Функция возвращает только что созданный объект.

Пример:

```
import FreeCAD as App

doc = App.activeDocument()

prism = doc.addObject("Part::Prism", "myPrism")
prism.Polygon = 5
prism.Circumradius = 10
prism.Height = 50
prism.FirstAngle = 22.5
prism.SecondAngle = 45
prism.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(60, 75, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Prism/ru&oldid=1547413>"