---
title: Клин
---
|  |
| --- |
| Клин |
| Расположение в меню |
| Деталь → Создать примитивы... → Клин |
| Верстаки |
| [Деталь](/Part_Workbench/ru "Part Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| - |
| См. также |
| [Создать примитивы](/Part_Primitives/ru "Part Primitives/ru") |
|  |

## Описание

![](/images/Part_Wedge.svg) **Клин** это параметрическое твёрдое тело, которое можно создать с помощью команды ![](/images/Part_Primitives.svg) [Создать примитивы](/Part_Primitives/ru "Part Primitives/ru"). Он имеет от четырёх до шести плоских граней. Клин определяется главными, виртуальными, передней и задней, плоскостями, на которых создаётся прямоугольная грань (по умолчанию), одна прямая грань или одна вершина. Эти базовые фигуры определяют четыре четырехугольные или треугольные грани, которые их соединяют. Получившееся твёрдое тело является настоящим клином только в том случае, если одна из базовых фигур - прямоугольная грань, а другая - прямая грань. В системе координат, определяемой свойством Данные**Размещение**, виртуальные передняя и задняя главные плоскости клина параллельны плоскости XZ, а края базовых форм параллельны оси X или Z. Все эти координаты относятся к данной системе координат.

![](/images/Part_Wedge_Example.png)

## Применение

Смотри [Создать примитивы..](/Part_Primitives#Usage/ru "Part Primitives").

## Пример

![](/images/Part_Wedge_Scripting_Example.png)

Элемент Клин из примера со скриптом

Здесь показан объект Клин, созданный с помощью примера [скрипта](#Scripting), приведенного ниже.

## Примечания

* Значения координат клина должны быть такими, чтобы можно было создать правильное твердое тело. Это означает, что передняя и задняя базовые фигуры могут быть одиночными гранями, но не параллельными. И если одна из базовых фигур является вершиной, другая фигура должна быть прямоугольной гранью.

## Свойства

Смотрите также: [Редактор свойств](/Property_editor/ru "Property editor/ru").

Объект Клин является производным от объекта [Конструктивный элемент](/Part_Feature/ru "Part Feature/ru") и наследует все его свойства. Он также имеет следующие дополнительные свойства:

### Данные

Вложение

Объект имеет те же свойства вложения, что и [Деталь Деталь2DОбъект](/Part_Part2DObject#Data/ru "Part Part2DObject").

Клин

* Данные**Xmin** (`Расстояние`): Наименьшая координата X передней грани клина. По умолчанию `0мм`.
* Данные**Ymin** (`Расстояние`): Координата Y передней грани клина. По умолчанию `0мм`.
* Данные**Zmin** (`Расстояние`): Наименьшая координата Z передней грани клина. По умолчанию `0мм`.
* Данные**X2min** (`Расстояние`): Наименьшая координата X задней грани клина. По умолчанию `2мм`.
* Данные**Z2min** (`Расстояние`): Наименьшая координата Z задней грани клина. По умолчанию `2мм`.
* Данные**Xmax** (`Расстояние`): Наибольшая координата X передней грани клина. По умолчанию `10мм`.
* Данные**Ymax** (`Расстояние`): Координата Y задней грани клина. По умолчанию `10мм`.
* Данные**Zmax** (`Расстояние`): Наибольшая координата Z передней грани клина. По умолчанию `10мм`.
* Данные**X2max** (`Расстояние`): Наибольшая координата X задней грани клина. По умолчанию `8мм`.
* Данные**Z2max** (`Расстояние`): Наибольшая координата Z задней грани клина. По умолчанию `8мм`.

## Написание скриптов

Смотри также: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Скрипты в верстаке Деталь](/Part_scripting/ru "Part scripting/ru") и [Основы работы со скриптами FreeCAD](/FreeCAD_Scripting_Basics/ru "FreeCAD Scripting Basics/ru").

Клин может быть создан с помощью метода `addObject()` документа:

```
wedge = FreeCAD.ActiveDocument.addObject("Part::Wedge", "myWedge")

```

* Где`"myWedge"` - это имя объекта.
* Функция возвращает только что созданный объект.

Пример:

```
import FreeCAD as App

doc = App.activeDocument()

wedge = doc.addObject("Part::Wedge", "myWedge")
wedge.Xmin = 1
wedge.Ymin = 2
wedge.Zmin = 3
wedge.X2min = 4
wedge.Z2min = 6
wedge.Xmax = 15
wedge.Ymax = 20
wedge.Zmax = 55
wedge.X2max = 10
wedge.Z2max = 12
wedge.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Wedge/ru&oldid=1547921>"