---
title: Цилиндр
---
|  |
| --- |
| Цилиндр |
| Расположение в меню |
| Деталь → Примитивы → Цилиндр |
| Верстаки |
| [Деталь](/Part_Workbench/ru "Part Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| - |
| См. также |
| [Примитивы](/Part_Primitives/ru "Part Primitives/ru") |
|  |

## Описание

Команда ![](/images/Part_Cylinder.svg) **Деталь Цилиндр** создаёт параметрический твёрдотельный цилиндр. Это результат выдавливания круговой дуги по прямой траектории. В системе координат, заданной свойством Данные**Размещение**, нижняя грань цилиндра лежит на плоскости XY с центром в начале координат.

Деталь Цилиндр можно превратить в сегмент цилиндра, изменив его свойство Данные**Угол**.

![](/images/Part_Cylinder_Example.png)

## Применение

1. Существует несколько способов вызова команды:
   * Нажмите кнопку ![](/images/Part_Cylinder.svg) Цилиндр.
   * Выберите опцию меню **Деталь → Примитивы → ![](/images/Part_Cylinder.svg) Цилиндр**.
2. Цилиндр создан.
3. По желанию измените размеры и Данные**Размещенеи** цилиндра, выполнив одно из следующих действий:
   * Двойной щелчок по объекту в [Дереве проекта](/Tree_view/ru "Tree view/ru"):
     1. Откроется панель задач **Геометрические примитивы**.
     2. Измените одно или несколько свойств.
     3. Объект динамически обновится в [3D виде](/3D_view/ru "3D view/ru").
     4. Нажмите кнопку OK.
   * Измените свойства в [Редакторе свойств](/Property_editor/ru "Property editor/ru").
   * Измените Данные**Размещение** с помощью команды ![](/images/Std_TransformManip.svg) [Преобразование](/Std_TransformManip/ru "Std TransformManip/ru").

## Пример

![](/images/Part_Cylinder_Scripting_Example.png)

Деталь Цилиндр из примера со скриптом

Здесь показан объект Деталь Цилиндр, созданный с помощью примера [скрипта](#Scripting), приведенного ниже.

## Примечания

* Цилиндр также можно создать с помощью команды ![](/images/Part_Primitives.svg) [Примитивы](/Part_Primitives/ru "Part Primitives/ru"). С помощью этой команды можно указать размеры и его размещение во время создания.

## Свойства

Смотрите также: [Редактор свойств](/Property_editor/ru "Property editor/ru").

Объект Цилиндр является производным от объекта [Конструктивный элемент](/Part_Feature/ru "Part Feature/ru") и наследует все его свойства. Он также имеет следующие дополнительные свойства:

### Данные

Вложение

Объект имеет те же свойства вложения, что и [Деталь Деталь2DОбъект](/Part_Part2DObject#Data/ru "Part Part2DObject").

Цилиндр

* Данные**Радиус** (`Длина`): Радиус дуги окружности, определяющей цилиндр. По умолчанию `2мм`.
* Данные**Высота** (`Длина`): Высота цилиндра. По умолчанию `10мм`.
* Данные**Угол** (`Угол`): Угол дуги окружности, определяющей цилиндр. Допустимый диапазон: `0° < значение <= 360°`. По умолчанию `360°`. Если угол меньше `360°` полученное твёрдое тело будет представлять собой сегмент цилиндра.

Призма

* Данные**Первый угол** (`Угол`): Угол между направлением выдавливания цилиндра и его положительной осью Z, измеренный вокруг оси Y. Угол положителен по направлению к положительной оси X. Допустимый диапазон: `0° <= значение < 90°`. По умолчанию `0°`. [представлено в версии 0.20](/Release_notes_0.20/ru "Release notes 0.20/ru")
* Данные**Второй угол** (`Угол`): Угол между направлением выдавливания цилиндра и его положительной осью Z, измеренный вокруг оси X. TУгол положителен по направлению к положительной оси Y. Допустимый диапазон: `0° <= значение < 90°`. По умолчанию `0°`. [представлено в версии 0.20](/Release_notes_0.20/ru "Release notes 0.20/ru")

## Написание скриптов

Смотри также: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Скрипты в верстаке Деталь](/Part_scripting/ru "Part scripting/ru") и [Основы работы со скриптами FreeCAD](/FreeCAD_Scripting_Basics/ru "FreeCAD Scripting Basics/ru").

Цилиндр может быть создан с помощью метода `addObject()` документа:

```
cylinder = FreeCAD.ActiveDocument.addObject("Part::Cylinder", "myCylinder")

```

* Где`"myCylinder"` - это имя объекта.
* Функция возвращает только что созданный объект.

Пример:

```
import FreeCAD as App

doc = App.activeDocument()

cylinder = doc.addObject("Part::Cylinder", "myCylinder")
cylinder.Radius = 10
cylinder.Height = 50
cylinder.Placement = App.Placement(App.Vector(5, 10, 15), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Cylinder/ru&oldid=1546256>"