---
title: Тор
---
|  |
| --- |
| Тор |
| Расположение в меню |
| Деталь → Примитивы → Тор |
| Верстаки |
| [Деталь](/Part_Workbench/ru "Part Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| - |
| См. также |
| [Примитивы](/Part_Primitives/ru "Part Primitives/ru") |
|  |

## Описание

Команда ![](/images/Part_Torus.svg) **Деталь Тор** создаёт параметрический твёрдотельный тор, геометрия баранки или пончика. Это результат построения кругового профиля по круговой траектории. В системе координат, заданной свойством Данные**Размещение**, круговая траектория тора лежит в плоскости XY с центром в начале координат.

Тор можно превратить в сегмент тора, изменив его свойство Данные**Угол3**. Изменив свойства Данные**Угол1** и/или Данные**Угол2**, профиль тора в сечении может стать сегментом окружности.

![](/images/Part_Torus_Example.png)

## Применение

1. Существует несколько способов вызова команды:
   * Нажмите кнопку ![](/images/Part_Torus.svg) Тор.
   * Выберите опцию меню **Деталь → Примитивы → ![](/images/Part_Torus.svg) Тор**.
2. Тор создан.
3. По желанию измените размеры и Данные**Размещение** тора выполнив одно из следующих действий:
   * Двойной щелчок по объекту в [Дереве проекта](/Tree_view/ru "Tree view/ru"):
     1. Откроется панель задач **Геометрические примитивы**.
     2. Измените одно или несколько свойств.
     3. Объект динамически обновится в [3D виде](/3D_view/ru "3D view/ru").
     4. Нажмите кнопку OK.
   * Измените свойства в [Редакторе свойств](/Property_editor/ru "Property editor/ru").
   * Измените Данные**Размещение** с помощью команды ![](/images/Std_TransformManip.svg) [Преобразование](/Std_TransformManip "Std TransformManip").

## Пример

![](/images/Part_Torus_Scripting_Example.png)

Деталь Тор из примера со скриптом

A Part Torus object created with the [scripting example](#Scripting) below is shown here.

## Примечания

* Тор также можно создать с помощью команды ![](/images/Part_Primitives.svg) [Примитивы](/Part_Primitives/ru "Part Primitives/ru"). С помощью этой команды можно указать размеры и его размещение во время создания.

## Свойства

Смотрите также: [Редактор свойств](/Property_editor/ru "Property editor/ru").

Объект Тор является производным от объекта [Конструктивный элемент](/Part_Feature/ru "Part Feature/ru") и наследует все его свойства. Он также имеет следующие дополнительные свойства:

### Данные

Вложение

Объект имеет те же свойства вложения, что и [Деталь Деталь2DОбъект](/Part_Part2DObject#Data/ru "Part Part2DObject").

Тор

* Данные**Радиус1** (`Длина`): Радиус круговой траектории тора. По умолчанию `10мм`.
* Данные**Радиус2** (`Длина`): Радиус кругового профиля тора в сечении. По умолчанию `2мм`.
* Данные**Угол1** (`Угол`): Начальный угол кругового профиля в сечении. Допустимый диапазон: `-180° <= значение <= 180°`. По умолчанию `-180°`.
* Данные**Угол2** (`Угол`): Конечный угол кругового профиля в сечении. Допустимый диапазон: `-180° <= значение <= 180°`. По умолчанию `180°`. Если суммарный угол кругового профиля тора в сечении меньше `360°` профиль будет иметь форму пирога (сектор круга).
* Данные**Угол3** (`Угол`): Угол круговой траектории тора. Допустимый диапазон: `0° < значение <= 360°`. По умолчанию `360°`. Если угол меньше `360°` полученное твердое тело будет представлять собой сегмент тора.

## Написание скриптов

Смотри также: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Скрипты в верстаке Деталь](/Part_scripting/ru "Part scripting/ru") и [Основы работы со скриптами FreeCAD](/FreeCAD_Scripting_Basics/ru "FreeCAD Scripting Basics/ru").

Тор может быть создан с помощью метода `addObject()` документа:

```
torus = FreeCAD.ActiveDocument.addObject("Part::Torus", "myTorus")

```

* Где`"myTorus"` - это имя объекта.
* Функция возвращает только что созданный объект.

Пример:

```
import FreeCAD as App

doc = App.activeDocument()

torus = doc.addObject("Part::Torus", "myTorus")
torus.Radius1 = 20
torus.Radius2 = 10
torus.Angle1 = -90
torus.Angle2 = 45
torus.Angle3 = 270
torus.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Torus/ru&oldid=1547415>"