---
title: Сфера
---
|  |
| --- |
| Сфера |
| Расположение в меню |
| Деталь → Примитивы → Сфера |
| Верстаки |
| [Деталь](/Part_Workbench/ru "Part Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| - |
| См. также |
| [Создать примитивы](/Part_Primitives/ru "Part Primitives/ru") |
|  |

## Описание

Команда ![](/images/Part_Sphere.svg) **Деталь Сфера** создаёт параметрическую твердотельную сферу. Это результат вращения дугообразного профиля вокруг оси. В системе координат, заданной свойством Данные**Размещение**, центр сферы расположен в начале системы координат, а ось вращения - это ось Z.

Часть сферы можно усечь сверху и/или снизу, изменив её свойства Данные**Угол1** и/или Данные**Угол2**. Её можно превратить в сегмент сферы, изменив свойство Данные**Угол3**.

![](/images/Part_Sphere_Example.png)

## Применение

1. Существует несколько способов вызова команды:
   * Нажмите кнопку ![](/images/Part_Sphere.svg) Сфера.
   * Выберите опцию меню **Деталь → Примитивы → ![](/images/Part_Sphere.svg) Сфера**.
2. Сфера создана.
3. По желанию измените размеры и Данные**Размещение** сферы, выполнив одно из следующих действий:
   * Двойной щелчок по объекту в [Дереве проекта](/Tree_view/ru "Tree view/ru"):
     1. Откроется панель задач **Геометрические примитивы**.
     2. Измените одно или несколько свойств.
     3. Объект динамически обновится в [3D виде](/3D_view "3D view").
     4. Нажмите кнопку OK.
   * Измените свойства в [Редакторе свойств](/Property_editor/ru "Property editor/ru").
   * Измените Данные**Размещение** с помощью команды ![](/images/Std_TransformManip.svg) [Преобразование](/Std_TransformManip/ru "Std TransformManip/ru").

## Пример

![](/images/Part_Sphere_Scripting_Example.png)

Деталь Сфера из примера со скриптом

Здесь показан объект Деталь Сфера, созданный с помощью примера [скрипта](#Scripting), приведенного ниже.

## Примечания

* Сферу также можно создать с помощью команды ![](/images/Part_Primitives.svg) [Примитивы](/Part_Primitives/ru "Part Primitives/ru"). С помощью этой команды можно указать размеры и её размещение во время создания.

## Свойства

Смотрите также: [Редактор свойств](/Property_editor/ru "Property editor/ru").

Объект Сфера является производным от объекта [Конструктивный элемент](/Part_Feature/ru "Part Feature/ru") и наследует все его свойства. Она также имеет следующие дополнительные свойства:

### Данные

Вложение

Объект имеет те же свойства вложения, что и [Деталь Деталь2DОбъект](/Part_Part2DObject#Data/ru "Part Part2DObject").

Сфера

* Данные**Радиус** (`Длина`): Радиус сферы. По умолчанию `5мм`.
* Данные**Угол1** (`Угол`): Начальный угол круговой дуги профиля сферы. Допустимый диапазон: `-90° <= значение <= 90°`. Может не быть равным Данные**Углу2**. По умолчанию `-90°`.
* Данные**Угол2** (`Угол`): Конечный угол круговой дуги профиля сферы. Допустимый диапазон: `-90° <= значение <= 90°`. Может не быть равным Данные**Углу1**. По умолчанию `90°`. Если общий угол дугового профиля меньше `180°`, сфера будет усеченной и иметь плоскую поверхность сверху и/или снизу.
* Данные**Угол3** (`Угол`): Полный угол поворота сферы. Допустимый диапазон: `0° < значение <= 360°`. По умолчанию `360°`. Если он меньше `360°`, то полученное твёрдое тело будет сегментом сферы.

## Написание скриптов

Смотри также: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Скрипты в верстаке Деталь](/Part_scripting/ru "Part scripting/ru") и [Основы работы со скриптами FreeCAD](/FreeCAD_Scripting_Basics/ru "FreeCAD Scripting Basics/ru").

Сфера может быть создана с помощью метода `addObject()` документа:

```
sphere = FreeCAD.ActiveDocument.addObject("Part::Sphere", "mySphere")

```

* Где`"mySphere"` - это имя объекта.
* Функция возвращает только что созданный объект.

Пример:

```
import FreeCAD as App

doc = App.activeDocument()

sphere = doc.addObject("Part::Sphere", "mySphere")
sphere.Radius = 20
sphere.Angle1 = -30
sphere.Angle2 = 45
sphere.Angle3 = 90
sphere.Placement = App.Placement(App.Vector(3, 9, 11), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Sphere/ru&oldid=1546324>"