---
title: Внедрить тонкостенный объект
---
|  |
| --- |
| Внедрить тонкостенный объект |
| Расположение в меню |
| Деталь → Соединить → Вырез объекта |
| Верстаки |
| [Деталь](/Part_Workbench/ru "Part Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| 0.16 |
| См. также |
| [Соединить объекты](/Part_JoinConnect/ru "Part JoinConnect/ru"), [Вырезать тонкостенный объект](/Part_JoinCutout/ru "Part JoinCutout/ru"), [Булевы операции](/Part_Boolean/ru "Part Boolean/ru"), [Толщина](/Part_Thickness/ru "Part Thickness/ru") |
|  |

## Описание

Инструмент ![](/images/Part_JoinEmbed.svg) **Внедрить тонкостенынй** встраивает объект с перегородками (например, трубу) в другой объект с перегородками.

![](/images/JoinFeatures_Embed.png)

## Применение

1. Выберите сначала базовый объект, а затем объект для внедрения. Порядок выделения важен. Достаточно выделить по одной части каждого объекта (например, грани).
2. Есть несколько способов вызвать инструмент:
   * Нажмите кнопку ![](/images/Part_JoinEmbed.svg) [Встроить объект](/Part_JoinEmbed "Part JoinEmbed").
   * Выберите в меню **Деталь → Соединить → ![](/images/Part_JoinEmbed.svg) Встроить объект**.
3. Создаётся объект верстака Деталь JoinFeature с режимом 'Embed (Встроить)'. Исходные объекты скрываются, а результат внедрения отображается в [3D виде](/3D_view/ru "3D view/ru").

## Свойства

Основные

* Данные**База**: Ссылка на базовый объект (объект, в который встраивается другой объект). Объект должен быть единым целым.
* Данные**Tool - Инструмент**: Ссылка на внедряемый объект (объект, который будет встраиваться). Объект может быть одним твёрдым телом или [допустимой группой/соединением](/Part_Compound/ru "Part Compound/ru") из твёрдых тел.
* Данные**Mode - Режим**: Режим работы, равный 'Embed' (изменение, которое превратит инструмент в другой Part\_JoinXXX). Значение 'bypass (игнорировать)' может быть использовано для временного отключения длительных вычислений (будет создано соединение базы и инструмента, что является быстрой операцией).
* Данные**Refine - Улучшить**: Устанавливает, применять или нет операцию [Улучшить](/Part_RefineShape/ru "Part RefineShape/ru") к конечной геометрии. Значение по умолчанию определяется флажком 'Автоматическое уточнение формы после выполнения булевой операции' в настройках верстака PartDesign (Проектная Деталь). Когда свойство Mode (Режим) имеет значение 'bypass (игнорировать)', Refine (Улучшить) игнорируется (никогда не применяется).

## Пример

1. Создайте трубу, применив [толщину](/Part_Thickness/ru "Part Thickness/ru") к [цилиндру](/Part_Cylinder/ru "Part Cylinder/ru"):   
   ![](/images/JoinFeatures_Example_step1.png)
2. Создайте ещё одну трубу меньшего диаметра, и [разместите](/Placement/ru "Placement/ru") её так, чтобы она проникала сквозь одну стенку первой трубы:   
   ![](/images/JoinFeatures_Example_step2.png)
3. Выберите первую трубу, затем вторую (порядок выбора важен) и нажмите кнопку «Внедрить объект» в раскрывающейся панели инструментов Объединить объекты...   
   ![](/images/JoinFeatures_Example_step3_Embed.png)
4. Используйте какой либо инструмент для создания сечений. Например: ([Плоскость сечения](/Std_ToggleClipPlane/ru "Std ToggleClipPlane/ru"), [Архитектура Плоскость Сечения](/Arch_SectionPlane/ru "Arch SectionPlane/ru"), [Архитектура Секущая плоскость](/Arch_CutPlane/ru "Arch CutPlane/ru")) чтобы показать внутренние детали. На рисунке ниже используется плоскость сечения верстака Архитектура (Arch).  
   ![](/images/JoinFeatures_Example_step4_Embed.png)

## Алгоритм

Алгоритмы, лежащие в основе инструментов объединения, довольно просты, и понимание принципов их работы важно для правильного использования данных инструментов.

1. Базовый объект обрезается [булевым-обрезать](/Part_Cut/ru "Part Cut/ru") с помощью объекта Инструмент (Tool).

2. Полученное соединение фильтруется: остаётся только самое крупное твёрдое тело. Результирующая фигура представляет собой набор ([соединённую группу](/Part_Compound/ru "Part Compound/ru")) непересекающихся твёрдых тел (обычно два).

3. Это самое большое твёрдое тело с помощью [булевого-объединить](/Part_Fuse/ru "Part Fuse/ru") соединяется с объектом Инструмент (Tool).

4. Если свойство Улучшить (Refine) равно true, то результирующая форма будет [улучшено](/Part_RefineShape/ru "Part RefineShape/ru").

### Примечания

* Если после шага 1 объект остаётся цельным, результат команды Внедриь будет эквивалентен [объединению](/Part_Fuse/ru "Part Fuse/ru") из Базы (Base) и Инструмента (Tool), но потребует больше времени на вычисление.
* Сейчас инструмент выдаёт неожиданный результат, если в качестве Базы указана группа (соединение). В будуще это может быть изменено.
* Поскольку самый большой элемент определяется путём сравнения объёмов элементов, то инструмент может работать только с твёрдыми телами. В будуще это может быть изменено.

## Написание скриптов

Инструменты Объединения можно использовать в [макросах](/Macros/ru "Macros/ru") и из консоли Python, используя следующую функцию:

```
JoinFeatures.makePartJoinFeature(name = 'Embed', mode = 'Embed')

```

* Создаёт пустую функцию Embed (Внедрения) (или другую функцию Join (Соединения), в зависимости от выбранного режима). Свойства Base (База) и Tool (Инструмент) должны быть назначены явно, после чего.
* Возвращает только что созданный объект.

Пример:

```
import JoinFeatures
j = JoinFeatures.makePartJoinFeature(name = 'Embed', mode = 'Embed' )
j.Base = FreeCADGui.Selection.getSelection()[0]
j.Tool = FreeCADGui.Selection.getSelection()[1]

```

Сам инструмент реализован на Python, смотрите /Mod/Part/JoinFeatures.py ([ссылка Github](https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Part/JoinFeatures.py)) в разделе, где установлен FreeCAD.

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_JoinEmbed/ru&oldid=1556447>"