---
title: Конус
---
|  |
| --- |
| Конус |
| Расположение в меню |
| Деталь → Примитивы → Конус |
| Верстаки |
| [Part](/Part_Workbench/ru "Part Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| - |
| См. также |
| [Примитивы](/Part_Primitives/ru "Part Primitives/ru") |
|  |

## Описание

Команда ![](/images/Part_Cone.svg) **Конус** создаёт параметрический твёрдотельный конус. В системе координат, заданной свойствомДанные**Размещение**, нижняя грань конуса лежит на плоскости XY с центром в начале координат.

По умолчанию конус является усечённым. Его можно превратить в полный, неусеченный конус, изменив свойство Данные**Радиус1** или Данные**Радиус2** на ноль. Его можно превратить в сегмент конуса, изменив свойство Данные**Угол**.

![](/images/Part_Cone_Example.png)

## Применение

1. Существует несколько способов вызова команды:
   * Нажмите кнопку ![](/images/Part_Cone.svg) [Конус](/Part_Cone "Part Cone").
   * Выберите опцию меню **Деталь → Примитивы → ![](/images/Part_Cone.svg) Конус**.
2. Конус создан.
3. По желанию измените размеры и Данные**Размещение** конуса выполнив одно из следующих действий:
   * Двойной щелчок по объекту в [Дереве проекта](/Tree_view/ru "Tree view/ru"):
     1. Откроется панель задач **Геометрические примитивы**.
     2. Измените одно или несколько свойств.
     3. Объект динамически обновится в [3D виде](/3D_view/ru "3D view/ru").
     4. Нажмите кнопку OK.
   * Измените свойства в [Редакторе свойств](/Property_editor/ru "Property editor/ru").
   * Измените Данные**Размещение** с помощью команды ![](/images/Std_TransformManip.svg) [Преобразование](/Std_TransformManip/ru "Std TransformManip/ru").

## Пример

![](/images/Part_Cone_Scripting_Example.png)

Деталь Конус из примера со скриптом

Здесь показан объект Деталь Конус, созданный с помощью примера [скрипта](#Scripting), приведенного ниже.

## Примечания

* Конус также можно создать с помощью команды ![](/images/Part_Primitives.svg) [Примитивы](/Part_Primitives/ru "Part Primitives/ru"). С помощью этой команды можно указать размеры и его размещение во время создания.

## Свойства

Смотрите также: [Редактор свойств](/Property_editor/ru "Property editor/ru").

Объект Конус является производным от объекта [Конструктивный элемент](/Part_Feature/ru "Part Feature/ru") и наследует все его свойства. Он также имеет следующие дополнительные свойства:

### Данные

Вложение

Объект имеет те же свойства вложения, что и [Деталь Деталь2DОбъект](/Part_Part2DObject#Data/ru "Part Part2DObject").

Конус

* Данные**Радиус1** (`Длина`): Радиус нижней грани конуса. Может быть равен `0мм`, если Данные**Радиус2** больше `0мм`. По умолчанию `2мм`.
* Данные**Радиус2** (`Длина`): Радиус верхней грани конуса. Может быть равен `0мм`, если Данные**Радиус1** больше `0мм`. По умолчанию `4мм`.
* Данные**Высота** (`Длина`): Высота конуса. По умолчанию `10мм`.
* Данные**Угол** (`Угол`): Угол дуги окружности, определяющей верхнюю и нижнюю грани конуса. Допустимый диапазон: `0° < значение <= 360°`. По умолчанию `360°`. Если он меньше `360°`, то полученное твёрдое тело будет сегментом конуса.

## Написание скриптов

Смотри также: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Скрипты в верстаке Деталь](/Part_scripting/ru "Part scripting/ru") и [Основы работы со скриптами FreeCAD](/FreeCAD_Scripting_Basics/ru "FreeCAD Scripting Basics/ru").

Конус может быть создан с помощью метода `addObject()` документа:

```
cone = FreeCAD.ActiveDocument.addObject("Part::Cone", "myCone")

```

* Где`"myCone"` - это имя объекта.
* Функция возвращает только что созданный объект.

Пример:

```
import FreeCAD as App

doc = App.activeDocument()

cone = doc.addObject("Part::Cone", "myCone")
cone.Radius1 = 5
cone.Radius2 = 10
cone.Height = 50
cone.Angle = 270
cone.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 60, 15))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Cone/ru&oldid=1546374>"