---
title: Плоскость
---
|  |
| --- |
| Плоскость |
| Расположение в меню |
| [Деталь](/Part_Workbench/ru "Part Workbench/ru") → [Создать примитивы...](/Part_Primitives/ru "Part Primitives/ru") → Плоскость |
| Верстаки |
| [Деталь](/Part_Workbench/ru "Part Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| - |
| См. также |
| [Создать примитивы...](/Part_Primitives/ru "Part Primitives/ru") |
|  |

## Описание

![](/images/Part_Plane.svg) **Плоскость** - это параметрическая прямоугольная плоскость, которая может быть создана с помощью команды ![](/images/Part_Primitives.svg) [Создать примитивы..](/Part_Primitives/ru "Part Primitives/ru"). В системе координат, заданной свойством Данные**Размещение**, плоскость лежит на плоскости XY, ее передний левый угол находится в начале координат, а передняя грань параллельна оси X.

![](/images/Part_Plane_Example.png)

## Применение

Смотри [Создать примитивы..](/Part_Primitives#Usage/ru "Part Primitives").

## Пример

![](/images/Part_Plane_Scripting_Example.png)

Элемент Плоскость из примера со скриптом

Здесь показан объект Плоскость, созданный с помощью примера [скрипта](#Scripting), приведенного ниже.

## Свойства

Смотрите также: [Редактор свойств](/Property_editor/ru "Property editor/ru").

Объект Плоскость является производным от объекта [Конструктивный элемент](/Part_Feature/ru "Part Feature/ru") и наследует все его свойства. Он также имеет следующие дополнительные свойства:

### Данные

Вложение

Объект имеет те же свойства вложения, что и [Деталь Деталь2DОбъект](/Part_Part2DObject#Data/ru "Part Part2DObject").

Пслоскость

* Данные**Длина** (`Длина`): Длина плоскости. Это размер в направлении X. По умолчанию `10мм`.
* Данные**Ширина** (`Ширина`): Ширина плоскости. Это размер в направлении Y. По умолчанию `10мм`.

## Написание скриптов

Смотри также: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Скрипты в верстаке Деталь](/Part_scripting/ru "Part scripting/ru") и [Основы работы со скриптами FreeCAD](/FreeCAD_Scripting_Basics/ru "FreeCAD Scripting Basics/ru").

Плоскость может быть создана с помощью метода `addObject()` документа:

```
plane = FreeCAD.ActiveDocument.addObject("Part::Plane", "myPlane")

```

* Где`"myPlane"` - это имя объекта.
* Функция возвращает только что созданный объект.

Пример:

```
import FreeCAD as App

doc = App.activeDocument()

plane = doc.addObject("Part::Plane", "myPlane")
plane.Length = 4
plane.Width = 8
plane.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(20, 75, 60))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Plane/ru&oldid=1547185>"