---
title: Линия (Отрезок)
---
|  |
| --- |
| Линия |
| Расположение в меню |
| Деталь → [Создать примитивы](/Part_Primitives/ru "Part Primitives/ru") → Линия |
| Верстаки |
| [Деталь](/Part_Workbench/ru "Part Workbench/ru"), [OpenSCAD](/OpenSCAD_Workbench/ru "OpenSCAD Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| - |
| См. также |
| [Создать примитивы](/Part_Primitives/ru "Part Primitives/ru") |
|  |

## Описание

![](/images/Part_Line.svg) **Линия** - это параметрическая линия, которая может быть создана с помощью команды ![](/images/Part_Primitives.svg) [Создать примитивы](/Part_Primitives/ru "Part Primitives/ru"). Координаты её начальной и конечной точек относятся к системе координат, заданной её свойством Данные**Размещение**.

![](/images/Part_Line_Example.png)

## Применение

Смотри [Создать примитивы](/Part_Primitives#Usage/ru "Part Primitives").

## Свойства

Смотрите также: [Редактор свойств](/Property_editor/ru "Property editor/ru").

Объект Линия является производным от объекта [Конструктивный элемент](/Part_Feature/ru "Part Feature/ru") и наследует все его свойства. Он также имеет следующие дополнительные свойства:

### Данные

Вложение

Объект имеет те же свойства вложения, что и [Деталь Деталь2DОбъект](/Part_Part2DObject#Data/ru "Part Part2DObject").

Вершина 1 - Начало

* Данные**X1** (`Расстояние`): Координата X начальной точки линии. По умолчанию `0мм`.
* Данные**Y1** (`Расстояние`): Координата Y начальной точки линии. По умолчанию `0мм`.
* Данные**Z1** (`Расстояние`): Координата Z начальной точки линии. По умолчанию `0мм`.

Вершина 2 - Конец

* Данные**X2** (`Расстояние`): Координата X конечной точки линии. По умолчанию `10мм`.
* Данные**Y2** (`Расстояние`): Координата Y конечной точки линии. По умолчанию `10мм`.
* Данные**Z2** (`Расстояние`): Координата Z конечной точки линии. По умолчанию `10мм`.

## Написание скриптов

Смотри также: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Скрипты в верстаке Деталь](/Part_scripting/ru "Part scripting/ru") и [Основы работы со скриптами FreeCAD](/FreeCAD_Scripting_Basics/ru "FreeCAD Scripting Basics/ru").

Линия может быть создана с помощью метода `addObject()` документа:

```
line = FreeCAD.ActiveDocument.addObject("Part::Line", "myLine")

```

* Где`"myLine"` - это имя объекта.
* Функция возвращает только что созданный объект.

Пример:

```
import FreeCAD as App

doc = App.activeDocument()

line = doc.addObject("Part::Line", "myLine")
line.X1 = 1
line.Y1 = 3
line.Z1 = 6
line.X2 = 2
line.Y2 = 3
line.Z2 = 9

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Line/ru&oldid=1548298>"