---
title: Draft FlipDimension
---
|  |
| --- |
| Draft FlipDimension |
| poziția meniului |
| Draft → Utilities → Flip Dimension |
| Ateliere |
| [Draft](/Draft_Workbench "Draft Workbench"), [Arch](/Arch_Workbench "Arch Workbench") |
| scurtătură |
| *Nici unul* |
| Prezentat în versiune |
| - |
| A se vedea, de asemenea, |
| [Dimension](/Draft_Dimension "Draft Dimension") |
|  |

## Description

## Descriere

Când se afișează în modul 2D, textul [Draft dimensions](/Draft_Dimension "Draft Dimension") este afișat aliniat la linia de dimensiuni. Instrumentul Dimensiune încearcă întotdeauna să vă arate textul de dimensiune pe partea corectă a liniei de dimensiune, în funcție de locul în care îl vedeți. În unele cazuri, însă, direcția de vizionare ar putea să nu reflecte intenția spectatorului și orientarea textului de dimensiune ar putea fi inversată. Acest instrument inversează această orientare în obiectele selectate  [dimension](/Draft_Dimension "Draft Dimension").

## Usage

## Cum se utilizează

1. Selectați unul sau mai multe obiecte  [dimension](/Draft_Dimension "Draft Dimension")
2. Apăsați butonul ![](/images/Draft_FlipDimension.png) [Flip Dimension](/Draft_FlipDimension "Draft FlipDimension")

## Notes

* [Draft Dimensions](/Draft_Dimension "Draft Dimension") also have a Date**Flip Text** property. When set to `true` the text is rotated 180° around the normal direction. This can be combined with the effect of this command.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To flip a [Draft Dimension](/Draft_Dimension "Draft Dimension") invert its `Normal` property.

Example:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(1000, 0, 0)
p3 = App.Vector(500, 300, 0)
dimension = Draft.make_dimension(p1, p2, p3)
dimension.ViewObject.FontSize = 200

dimension.Normal = dimension.Normal.negative()
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_FlipDimension/ro&oldid=1000488>"