---
title: Std Fuzionați Proiectul
---
|  |
| --- |
| Fuzionați Proiectul |
| poziția meniului |
| File → Fuzionați Proiectul |
| Ateliere |
| All |
| scurtătură |
| *Nici unul* |
| Prezentat în versiune |
| - |
| A se vedea, de asemenea, |
| *Nici unul* |
|  |

## Descriere

Incorporează un alt proiect FreeCAD în cel actual.

The **Std MergeProjects** command adds the contents of a FreeCAD file into the active document.

## Utilizare

1. Alegeți  File →  Merge project... din meniul principalu.
2. Va apărea un dialog contextual care vă va solicita numele fișierului și locația proiectului FreeCAD care urmează să fie îmbinate în cel curent.

1. Select the **File → ![](/images/Std_MergeProjects.svg) Merge document...** option from the menu.
2. Select a FreeCAD file in the dialog box.
3. Press the Open button.

## Options

* Press Esc or the Cancel button to abort the command.

## Notes

* A project cannot be merged with itself, selecting the current file is not allowed.
* FreeCAD will automatically change the internal names and, depending on the [preferences](/Preferences_Editor#Document "Preferences Editor"), labels of objects to avoid name conflicts.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To merge a project use the `mergeProject` method of the document object.

```
import FreeCAD

FreeCAD.ActiveDocument.mergeProject("Path_to_FCStd_project_file")

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_MergeProjects/ro&oldid=1534351>"