---
title: Std Vizualizarea Ortogonală
---
|  |
| --- |
| Std OrthographicCamera |
| Menu location |
| [View](/Std_View_Menu "Std View Menu") → Orthographic view |
| Workbenches |
| All |
| Default shortcut |
| O |
| Introduced in version |
| - |
| See also |
| [Perspective View](/Std_PerspectiveCamera "Std PerspectiveCamera") |
|  |

## Descriere

Puneți camera foto în modul de vizualizarea ortogonal.  
Ortogonal este (conform Wikipedia):  
... o modalitate de reprezentare a unui obiect tridimensional în două dimensiuni...

The **Std OrthographicCamera** command switches the camera in the active [3D view](/3D_view "3D view") to orthographic view mode. In this mode, objects that are further from the camera do not appear smaller than those that are closer.

![](/images/Std_OrthographicCamera_example.svg)

Two cubes with the same dimensions in orthographic view

## Utilizare

Alegeți  View → ![](/images/View-isometric.png) Orthographic view din meniul principal

1. There are several ways to invoke the command:
   * Select the **View → ![](/images/Std_OrthographicCamera.svg) Orthographic view** option from the menu.
   * Select the **![](/images/Std_OrthographicCamera.svg) Orthographic view** option from the Mini-cube menu of the [Navigation Cube](/Navigation_Cube "Navigation Cube").
   * Use the keyboard shortcut: V then O.

## Preferences

See also: [Preferences Editor](/Preferences_Editor "Preferences Editor").

* The camera type can be changed: **Edit → Preferences... → Display → 3D View → Camera type**. The selected type will be used for all 3D views of all opened documents and also for new documents.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

Use the `setCameraType` method of the View object to change to orthographic or perspective mode.

```
import FreeCADGui

view = FreeCADGui.ActiveDocument.ActiveView
view.setCameraType("Perspective")
view.setCameraType("Orthographic")
view.getCameraType()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_OrthographicCamera/ro&oldid=1449476>"