---
title: Std New
---
|  |
| --- |
| Std New |
| poziția meniului |
| [File](/Std_File_Menu/ro "Std File Menu/ro") → New |
| Ateliere |
| All |
| scurtătură |
| Ctrl+N |
| Prezentat în versiune |
| - |
| A se vedea, de asemenea, |
| [Std Open](/Std_Open/ro "Std Open/ro"),[Std Import](/Std_Import/ro "Std Import/ro") |
|  |

Creează un nou document gol. De asemenea, FreeCAD poate fi configurat pentru a crea un nou document gol la pornire, verificând setarea corespunzătoare din Edit → Preferences → General → Document tab.

The **Std New** command creates a new empty document and makes it the active document.

## Usage

1. There are several ways to invoke the command:
   * Press the ![](/images/Std_New.svg) [New](/Std_New "Std New") button.
   * Select the **File → ![](/images/Std_New.svg) New** option from the menu.
   * Use the keyboard shortcut: Ctrl+N.

## Preferences

See also: [Preferences Editor](/Preferences_Editor "Preferences Editor").

* By default FreeCAD start without a new document. Check the **Edit → Preferences... → General → Document → Create new document at start up** option to change this behavior.
* Some document properties: author name, company name and license information, can be preset: **Edit → Preferences... → General → Document → Authoring and License**.

## Properties

See also: [Property editor](/Property_editor "Property editor").

Most properties can also be changed in the dialog box of the [Std ProjectInfo](/Std_ProjectInfo "Std ProjectInfo") command.

### Data

Base

* Date**Comment** (`String`): Any comment that may apply.
* Date**Company** (`String`): Company name.
* Date**Created By** (`String`): Author name.
* Date**Creation Date** (`String`): Automatic date stamp (read-only).
* Date**File Name** (`String`): The full path of the file. Blank if the document has not been saved (read-only).
* Date**Id** (`String`): Not implemented yet.
* Date**Label** (`String`): The name that will appear in the [Tree view](/Tree_view "Tree view"). Replaced by the name of the document after reopening.
* Date**Last Modified By** (`String`): Author name.
* Date**Last Modified Date** (`String`): Automatic date stamp (read-only).
* Date**License** (`String`): License type.
* Date**License URL** (`String`): License URL.
* Date (Hidden)**Material** (`Map`): Map with material properties.
* Date (Hidden)**Meta** (`Map`): Map with additional meta information.
* Date**Show Hidden** (`Bool`): If true, items that have been hidden in the [Tree view](/Tree_view "Tree view") will be displayed anyway. Hiding items in the tree can be useful when working on larger models.
* Date**Tip** (`Link`): Not implemented yet.
* Date**Tip Name** (`String`): Not implemented yet.
* Date**Transient Dir** (`String`): The transient directory used for recovery data (read-only).
* Date (Hidden)**Uid** (`UUID`): UUID of the document (read-only).
* Date**Unit System** (`Enumeration`): The document unit system. Initial value depends on the [Default unit system](/Preferences_Editor#General_2 "Preferences Editor"). [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0")

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To create a new document use the `newDocument([name], [hidden=False])` method of the FreeCAD application. The document name must be unique, which is checked automatically. If no name is supplied, the document will be named "Untitled". If `hidden=True` is used, the new document won't be displayed in the GUI and no tab will appear for it.

```
import FreeCAD
from pathlib import Path

# The folder and filename we will use:
fld = 'D:/testfiles/'
fnm = fld + 'test.FCStd'

# Make sure fld exists:
Path(fld).mkdir(parents=True, exist_ok=True)

doc = FreeCAD.newDocument()
doc.saveAs(fnm)

FreeCAD.closeDocument(doc.Name)

doc = FreeCAD.open(fnm)
doc.save()

FreeCAD.closeDocument(doc.Name)

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_New/ro&oldid=1448546>"