---
title: Draft FlipDimension
---
|  |
| --- |
| Draft FlipDimension |
| Ubicación en el Menú |
| Draft → Utilities → Flip Dimension |
| Entornos de trabajo |
| [Draft](/Draft_Workbench/es "Draft Workbench/es"), [Arch](/Arch_Workbench/es "Arch Workbench/es") |
| Atajo de teclado por defecto |
| *Ninguno* |
| Introducido en versión |
| - |
| Ver también |
| [Dimension](/Draft_Dimension/es "Draft Dimension/es") |
|  |

## Description

## Descripción

Cuando está en modo 2D, el texto de [Dimensiones de borrador](/Draft_Dimension "Draft Dimension") se muestra alineado con la línea de dimensión. La herramienta Dimensión siempre intenta mostrarle el texto de la dimensión en el lado correcto de la línea de dimensión, dependiendo de dónde lo esté viendo. En algunos casos, sin embargo, la dirección de visualización puede no reflejar la intención del espectador, y la orientación del texto de cota puede invertirse. Esta herramienta invierte esa orientación en los objetos  [dimensión](/Draft_Dimension "Draft Dimension") seleccionados.

## Usage

## Utilización

1. Seleccione uno o más objetos [dimension](/Draft_Dimension "Draft Dimension")
2. Presione el botón ![](/images/Draft_FlipDimension.png) [Flip Dimension](/Draft_FlipDimension "Draft FlipDimension")

## Notes

* [Draft Dimensions](/Draft_Dimension "Draft Dimension") also have a Datos**Flip Text** property. When set to `true` the text is rotated 180° around the normal direction. This can be combined with the effect of this command.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To flip a [Draft Dimension](/Draft_Dimension "Draft Dimension") invert its `Normal` property.

Example:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(1000, 0, 0)
p3 = App.Vector(500, 300, 0)
dimension = Draft.make_dimension(p1, p2, p3)
dimension.ViewObject.FontSize = 200

dimension.Normal = dimension.Normal.negative()
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_FlipDimension/es&oldid=1018309>"