---
title: Borrador ArregloPolar
---
|  |
| --- |
| Borrador ArregloPolar |
| Ubicación en el Menú |
| Modificación → Herramientas de Arreglo → Arreglo Polar |
| Entornos de trabajo |
| [Borrador](/Draft_Workbench/es "Draft Workbench/es"), [Arquitectura](/Arch_Workbench/es "Arch Workbench/es") |
| Atajo de teclado por defecto |
| *Ninguno* |
| Introducido en versión |
| 0.19 |
| Ver también |
| [Borrador OrthoArray](/Draft_OrthoArray/es "Draft OrthoArray/es"), [Borrador ArregloCircular](/Draft_CircularArray/es "Draft CircularArray/es"), [Borrador ArregloRuta](/Draft_PathArray/es "Draft PathArray/es"), [Borrador ArregloEnlaceRuta](/Draft_PathLinkArray/es "Draft PathLinkArray/es"), [Borrador ArregloPunto](/Draft_PointArray/es "Draft PointArray/es"), [Borrador ArregloEnlacePunto](/index.php?title=Draft_PointLinkArray/es&action=edit&redlink=1 "Draft PointLinkArray/es (page does not exist)") |
|  |

## Descripción

El ![](/images/Draft_PolarArray.svg) comando **Borrador ArregloPolar** crea un arreglo a partir de un objeto seleccionado colocando copias a lo largo de una circunferencia. El comando puede crear opcionalmente un arreglo [Enlace](/App_Link/es "App Link/es"), que es más eficiente que un arreglo normal.

El comando puede usarse en objetos 2D creados con el [Ambiente de Trabajo Borrador](/Draft_Workbench/es "Draft Workbench/es") o [Ambiente de Trabajo Dibujo](/Sketcher_Workbench/es "Sketcher Workbench/es"), pero también en muchos objetos 3D como los creados con el [Ambiente de Trabajo Pieza](/Part_Workbench/es "Part Workbench/es"), [Ambiente de Trabajo DiseñoPieza](/PartDesign_Workbench/es "PartDesign Workbench/es") o [Ambiente de Trabajo Arquitectura](/Arch_Workbench/es "Arch Workbench/es").

![](/images/Draft_PolarArray_example.png)

Borrador ArregloPolar

## Utilización

Ver también: [Borrador Atrapar](/Draft_Snap/es "Draft Snap/es")

1. Opcionalmente selecciona un objeto.
2. Hay varias formas de invocar el comando:
   * Pulsar el ![](/images/Draft_PolarArray.svg) Borrador ArregloPolar.
   * Seleccione la opción **Modificación → Herramientas de matriz → ![](/images/Draft_PolarArray.svg) Arreglo polar** en el menú.
3. Se abre el panel de tareas **Arreglo polar**. Ver [Opciones](#Opciones) para más información.
4. Si aún no ha seleccionado ningún objeto: seleccione un objeto.
5. Introduzca los parámetros necesarios en el panel de tareas.
6. Para terminar el comando haga una de las siguientes cosas:
   * Elija un punto en la [Vista 3D](/3D_view/es "3D view/es") para el **Centro de rotación**.
   * Pulsa Entre.
   * Pulsar el botón Aceptar.

## Opciones

* Enter the **Polar angle** to specify the total angle of the array. The angle is positive in the counter-clockwise direction.
* Enter the **Number of elements**. Must be at least `2`. The maximum that can be entered in the task panel is `99`, but higher values are possible by changing the Datos**Number Polar** property of the array.
* Pick a point in the [3D view](/3D_view "3D view"), note that this will also finish the command, or type coordinates for the **Center of rotation**. The rotation axis of the array will pass through this point. It is advisable to move the pointer out of the [3D view](/3D_view "3D view") before entering coordinates.
* Press the **Reset point** button to reset the **Center of rotation** to the origin.
* If the **Fuse** checkbox is checked overlapping elements in the array are fused.
* If the **Link array** checkbox is checked a Link array instead of a regular array is created. A Link array is more efficient because its elements are [App Link](/App_Link "App Link") objects.
* Press Esc or the Cancel button to abort the command.

## Notas

See [Draft OrthoArray](/Draft_OrthoArray#Notes "Draft OrthoArray").

* The default rotation axis for the array is the positive Z axis. This can be changed by editing its Datos**Axis** property.

## Propiedades

See [Draft OrthoArray](/Draft_OrthoArray#Properties "Draft OrthoArray").

## Guión

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

### Parametric array

To create a parametric polar array use the `make_array` method ([introduced in 0.19](/Release_notes_0.19 "Release notes 0.19")) of the Draft module. This method replaces the deprecated `makeArray` method. The `make_array` method can create [Draft OrthoArrays](/Draft_OrthoArray "Draft OrthoArray"), Draft PolarArrays and [Draft CircularArrays](/Draft_CircularArray "Draft CircularArray"). For each array type one or more wrappers are available.

The main method:

```
array = make_array(base_object, arg1, arg2, arg3, arg4=None, arg5=None, arg6=None, use_link=True)

```

The wrapper for polar arrays is:

```
array = make_polar_array(base_object,
                         number=5, angle=360, center=App.Vector(0, 0, 0),
                         use_link=True)

```

* `base_object` is the object to be arrayed. It can also be the `Label` (string) of an object in the current document.
* `number` is the number of elements in the pattern, including the original object.
* `angle` is the angle of the polar arc in degrees.
* `center` is the vector that defines the center of the pattern.
* If `use_link` is `True` the created elements are [App Links](/App_Link "App Link") instead of regular copies.
* `array` is returned with the created array object.

Example:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

tri = Draft.make_polygon(3, 600)
center = App.Vector(-1600, 0, 0)

array = Draft.make_polar_array(tri, 8, 270, center)
doc.recompute()

```

### Non-parametric array

To create a non-parametric polar array use the `array` method of the Draft module. This method returns `None`.

```
array(objectslist, center, angle, number)

```

Ejemplo:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

tri = Draft.make_polygon(3, 600)
center = App.Vector(-1600, 0, 0)

Draft.array(tri, center, 270, 8)
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_PolarArray/es&oldid=1557806>"