---
title: Kreslení PřehoďKótu
---
|  |
| --- |
| Kreslení PřehoďKótu |
| Umístění Menu |
| Draft → Utilities → Flip Dimension |
| Pracovní stoly |
| [Kreslení](/Draft_Workbench/cs "Draft Workbench/cs"), [Architektura](/Arch_Workbench/cs "Arch Workbench/cs") |
| Výchozí zástupce |
| *Nikdo* |
| Představen ve verzi |
| - |
| Viz také |
| [Kóty](/Draft_Dimension/cs "Draft Dimension/cs") |
|  |

## Description

## Popis

Ve 2D módu je zobrazení textu [Kóty](/Draft_Dimension/cs "Draft Dimension/cs") zarovnáno ke kótovací čáře. Nástroj Kóta se snaží vždy zobrazit text na správné straně kótovací čáry v závislosti ze které strany má být viděna. V některých případech však směr pohledu nemusí vyjadřovat smysl pohledu a pak se může hodit změna orientace textu kóty. Tento nástroj obrací orientaci vybraného objektu [kóty](/Draft_Dimension/cs "Draft Dimension/cs").

## Usage

## Použití

1. Vyberte jeden nebo více objektů [kóta](/Draft_Dimension/cs "Draft Dimension/cs")
2. Stiskněte tlačítko ![](/images/Draft_FlipDimension.png) PřehoďKótu

## Notes

* [Draft Dimensions](/Draft_Dimension "Draft Dimension") also have a Údaje**Flip Text** property. When set to `true` the text is rotated 180° around the normal direction. This can be combined with the effect of this command.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To flip a [Draft Dimension](/Draft_Dimension "Draft Dimension") invert its `Normal` property.

Example:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(1000, 0, 0)
p3 = App.Vector(500, 300, 0)
dimension = Draft.make_dimension(p1, p2, p3)
dimension.ViewObject.FontSize = 200

dimension.Normal = dimension.Normal.negative()
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_FlipDimension/cs&oldid=1008300>"