---
title: Draft FlipDimension
---
|  |
| --- |
| Draft FlipDimension |
| Menyplacering |
| Draft -> Utilities -> Flip Dimension |
| Arbetsbänkar |
| [Draft](/Draft_Workbench/sv "Draft Workbench/sv"), [Arch](/Arch_Workbench/sv "Arch Workbench/sv") |
| Standard genväg |
| *Ingen* |
| Introducerad i version |
| - |
| Se även |
| [Dimension](/Draft_Dimension/sv "Draft Dimension/sv") |
|  |

## Description

The ![](/images/Draft_FlipDimension.svg) **Draft FlipDimension** command rotates the dimension text of selected [Draft Dimensions](/Draft_Dimension "Draft Dimension") 180° around the dimension line. It can be used to correct dimensions whose text appears mirrored. The command does not work properly for angular dimensions.

## Usage

1. Select one or more [Draft Dimensions](/Draft_Dimension "Draft Dimension").
2. There are several ways to invoke the command:
   * Press the ![](/images/Draft_FlipDimension.svg) [Flip dimension](/Draft_FlipDimension "Draft FlipDimension") button.
   * Select the **Modification → ![](/images/Draft_FlipDimension.svg) Flip dimension** option from the menu.

## Notes

* [Draft Dimensions](/Draft_Dimension "Draft Dimension") also have a Data**Flip Text** property. When set to `true` the text is rotated 180° around the normal direction. This can be combined with the effect of this command.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To flip a [Draft Dimension](/Draft_Dimension "Draft Dimension") invert its `Normal` property.

Example:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(1000, 0, 0)
p3 = App.Vector(500, 300, 0)
dimension = Draft.make_dimension(p1, p2, p3)
dimension.ViewObject.FontSize = 200

dimension.Normal = dimension.Normal.negative()
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_FlipDimension/sv&oldid=1338146>"