---
title: Draft Scale/sv
---
|  |
| --- |
| Draft Scale |
| Menyplacering |
| Draft → Scale |
| Arbetsbänkar |
| [Draft](/Draft_Workbench/sv "Draft Workbench/sv"), [Arch](/Arch_Workbench/sv "Arch Workbench/sv") |
| Standard genväg |
| S C |
| Introducerad i version |
| - |
| Se även |
| [Draft Clone](/Draft_Clone/sv "Draft Clone/sv") |
|  |

## Beskrivning

Detta verktyg skalar valda objekt runt en baspunkt. Om inga objekt är markerade, så kommer du ombes att välja ett.

The command can be used on 2D objects created with the [Draft Workbench](/Draft_Workbench "Draft Workbench") or [Sketcher Workbench](/Sketcher_Workbench "Sketcher Workbench"), but also on many 3D objects such as those created with the [Part Workbench](/Part_Workbench "Part Workbench"), [PartDesign Workbench](/PartDesign_Workbench "PartDesign Workbench") or [BIM Workbench](/BIM_Workbench "BIM Workbench").

![](/images/Draft_Scale_example.png)

Scaling an object around a base point

## Bruk

See also: [Draft Snap](/Draft_Snap "Draft Snap") and [Draft Constrain](/Draft_Constrain "Draft Constrain").

1. Optionally select one or more objects, or one or more subelements of [Draft Lines](/Draft_Line "Draft Line") or [Draft Wires](/Draft_Wire "Draft Wire").
2. There are several ways to invoke the command:
   * Press the ![](/images/Draft_Scale.svg) [Scale](/Draft_Scale "Draft Scale") button.
   * [Draft](/Draft_Workbench "Draft Workbench"): Select the **Modification → ![](/images/Draft_Scale.svg) Scale** option from the menu.
   * [BIM](/BIM_Workbench "BIM Workbench"): Select the **Modify → ![](/images/Draft_Scale.svg) Scale** option from the menu.
   * Use the keyboard shortcut: S then C.
3. If you have not yet selected an object: select an object in the [3D view](/3D_view "3D view").
4. The **Scale** task panel opens. See [Options](#Options) for more information.
5. If subelements have been selected: check the **Modify subelements** checkbox to switch on subelement mode.
6. Pick the base point in the [3D view](/3D_view "3D view"), or type coordinates and press the ![](/images/Draft_AddPoint.svg) Enter point button.
7. Enter the X, Y and Z scale factors.
8. Press Enter or the OK button to finish the command.

## Options

### First task panel

The single character keyboard shortcuts available in the task panel can be changed. See [Draft Preferences](/Draft_Preferences "Draft Preferences"). The shortcuts mentioned here are the default shortcuts.

* To manually enter the coordinates for the base point enter the X, Y and Z component, and press Enter after each. Or you can press the ![](/images/Draft_AddPoint.svg) Enter point button when you have the desired values. It is advisable to move the pointer out of the [3D view](/3D_view "3D view") before entering coordinates.
* Press G or click the **Global** checkbox to toggle global mode. If global mode is on, coordinates are relative to the global coordinate system, else they are relative to the [working plane](/Draft_SelectPlane "Draft SelectPlane") coordinate system.
* Press S to switch [Draft snapping](/Draft_Snap "Draft Snap") on or off.
* Press the Close button to abort the command.

### Second task panel

* Markera en punkt i ett tomt område i 3d vyn, eller på ett existerande objekt för baspunkten, sedan en annan punkt för skalfaktorn
* x, y och z komponenterna av den andra punkten definierar skalfaktorn. Till exempel, (1,1,1) gör ingenting, (2,2,2) kommer att skala 2x i alla riktningar, (-1,1,1) kommer att spegla i x riktningen.
* Nedtryckning av CTRL kommer att [snäppa](/Draft_Snap/sv "Draft Snap/sv") din punkt till tillgängliga snäpp-punkter.
* Nedtryckning av SKIFT kommer att koppla ihop x och y värdena, så att förhållandet inte ändras
* Om du trycker på ESC så avbryts funktionen.
* Skriv in siffror för att manuellt mata in en koordinat.
* C växlar kopieringsläget på/av. Med kopiering på, så kommer objekt(en) att kopieras istället för att flyttas.
* Nedtryckning av ALT kommer att skapa en kopia, även om kopieringsknappen är av.
* Om ALT är nedtryckt, så kan du göra multipla kopior ända tills ALT släpps.

## Notes

* The command can also scale [Image Planes](/Image_CreateImagePlane "Image CreateImagePlane"), but not in clone mode.

## Preferences

See also: [Preferences Editor](/Preferences_Editor "Preferences Editor") and [Draft Preferences](/Draft_Preferences "Draft Preferences").

* To reselect the base objects after copying objects: **Edit → Preferences... → Draft → General → Select base objects after copying**.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To scale objects use the `scale` method of the Draft module.

```
scaled_list = scale(objectslist, scale=Vector(1,1,1), center=Vector(0,0,0), copy=False)

```

* `objectslist` contains the objects to be scaled. It is either a single object or a list of objects.
* `scale` is the vector that specifies by the X, Y and Z scale factors.
* `center` is the center point of the scaling operation.
* If `copy` is `True` copies are created instead of scaling the original objects.
* `scaled_list` is returned with the original scaled objects, or with the new copies. It is either a single object or a list of objects, depending on `objectslist`.

Example:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

pts = [App.Vector(0, 0, 0), App.Vector(500, 500, 0), App.Vector(600, 0, 0)]
wire1 = Draft.make_wire(pts, closed=True)
doc.recompute()

scale1 = App.Vector(2.3, 0.75, 0)
wire2 = Draft.scale(wire1, scale1, copy=True)
doc.recompute()

scale2 = App.Vector(-2, -1.5, 0)
wires = Draft.scale([wire1, wire2], scale2, copy=True)
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Scale/sv&oldid=1513437>"