---
title: Draft Arc
---
|  |
| --- |
| Draft Arc |
| Menyplacering |
| Draft -> Arc |
| Arbetsbänkar |
| [Draft](/Draft_Workbench/sv "Draft Workbench/sv"), [Arch](/Arch_Workbench/sv "Arch Workbench/sv") |
| Standard genväg |
| A R |
| Introducerad i version |
| - |
| Se även |
| [Draft Circle](/Draft_Circle/sv "Draft Circle/sv") |
|  |

#### Beskrivning

Detta verktyg ritar en cirkelbåge genom att välja fyra punkter: centrum, radien, startvinkel och slutvinkel.

The ![](/images/Draft_Arc.svg) **Draft Arc** command creates a circular arc on the current [working plane](/Draft_SelectPlane "Draft SelectPlane") from a center, a radius, a start angle and an aperture angle. The radius and the angles can be defined by picking points.

A Draft Arc is in fact a [Draft Circle](/Draft_Circle "Draft Circle") with a Data**First Angle** that is not the same as its Data**Last Angle**.

![](/images/Draft_Arc_example.jpg)

![](/images/Draft_Arc_example.jpg)

## Usage

See also: [Draft Tray](/Draft_Tray "Draft Tray"), [Draft Snap](/Draft_Snap "Draft Snap") and [Draft Constrain](/Draft_Constrain "Draft Constrain").

#### Bruk

* Markera punkter i ett tomt område i 3d vyn, eller på ett existernade objekt.
* Cirkelbågsverktyget ärver [Cirkelverktygets](/Draft_Circle/sv "Draft Circle/sv") funktionalitet för de två första stegen, så du kan trycka på ALT för att välja en tangent istället för centrum eller radie.
* Nedtryckning av CTRL kommer att [snäppa](/Draft_Snap/sv "Draft Snap/sv") din punkt till tillgängliga snäpp-punkter.
* Nedtryckning av SKIFT kommer att [begränsa](/Draft_Constrain/sv "Draft Constrain/sv") din nya punkt i relation till föregående punkt.
* Skriv in siffror för att manuellt mata in en koordinat.
* Nedtryckning av ALT när du väljer slutvinkeln kommer att ändra riktningen till moturs.
* Om du trycker på ESC så avbryts funktionen.

## Options

The single character keyboard shortcuts available in the task panel can be changed. See [Draft Preferences](/Draft_Preferences "Draft Preferences"). The shortcuts mentioned here are the default shortcuts (for version 1.0).

* To manually enter the coordinates for the center enter the X, Y and Z component, and press Enter after each. Or you can press the ![](/images/Draft_AddPoint.svg) Enter point button when you have the desired values. It is advisable to move the pointer out of the [3D view](/3D_view "3D view") before entering coordinates.
* Press G or click the **Global** checkbox to toggle global mode. If global mode is on, coordinates are relative to the global coordinate system, else they are relative to the [working plane](/Draft_SelectPlane "Draft SelectPlane") coordinate system.
* Press N or click the **Continue** checkbox to toggle continue mode. If continue mode is on, the command will restart after finishing, allowing you to continue creating arcs.
* Press S to switch [Draft snapping](/Draft_Snap "Draft Snap") on or off.
* Press Esc or the Close button to abort the command.

## Notes

* A Draft Arc can be edited with the [Draft Edit](/Draft_Edit "Draft Edit") command.

## Preferences

See also: [Preferences Editor](/Preferences_Editor "Preferences Editor") and [Draft Preferences](/Draft_Preferences "Draft Preferences").

* If the **Edit → Preferences... → Draft → General → Create Part primitives if possible** option is checked, the command will create a [Part Circle](/Part_Circle "Part Circle") instead of a Draft Circle.

## Properties

See [Draft Circle](/Draft_Circle#Properties "Draft Circle").

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To create a Draft Arc use the `make_circle` method ([introduced in 0.19](/Release_notes_0.19 "Release notes 0.19")) of the Draft module. This method replaces the deprecated `makeCircle` method.

Example:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

arc1 = Draft.make_circle(200, startangle=0, endangle=90)
arc2 = Draft.make_circle(500, startangle=20, endangle=160)
arc3 = Draft.make_circle(750, startangle=-30, endangle=-150)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Arc/sv&oldid=1513308>"