---
title: Std SelBoundingBox
---

|                                                 |
| ----------------------------------------------- |
| Std SelBoundingBox                              |
| Menu location                                   |
| View → Bounding box                             |
| Workbenches                                     |
| All                                             |
| Default shortcut                                |
| _None_                                          |
| Introduced in version                           |
| 0.19                                            |
| See also                                        |
| [Std DrawStyle](/Std_DrawStyle "Std DrawStyle") |
|                                                 |

## Description

The **Std SelBoundingBox** command toggles the global bounding box highlighting mode. If this mode is switched on, selected objects are marked in a [3D view](/3D_view "3D view") with a highlighted bounding box even if their View**Selection Style** is set to 'Shape'.

## Usage

1. Select the **View → ![](/src/assets/images/Std_SelBoundingBox.svg) Bounding box** option from the menu.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To change the ShowSelectionBoundingBox parameter use the `SetBool` method of the appropriate ParameterGrp.

```
import FreeCAD, FreeCADGui

grp = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/View")
if grp.GetBool("ShowSelectionBoundingBox"):
    grp.SetBool("ShowSelectionBoundingBox", False)
else:
    grp.SetBool("ShowSelectionBoundingBox", True)

FreeCADGui.updateCommands()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_SelBoundingBox/en&oldid=1449690>"
