---
title: Std ViewFront
---

|                                                                                            |
| ------------------------------------------------------------------------------------------ |
| Std ViewFront                                                                              |
| Menu location                                                                              |
| View → Standard views → Front                                                              |
| Workbenches                                                                                |
| All                                                                                        |
| Default shortcut                                                                           |
| 1                                                                                          |
| Introduced in version                                                                      |
| -                                                                                          |
| See also                                                                                   |
| [Std ViewTop](/Std_ViewTop "Std ViewTop"), [Std ViewRight](/Std_ViewRight "Std ViewRight") |
|                                                                                            |

## Description

The **Std ViewFront** command points the camera in the active [3D view](/3D_view "3D view") in the direction of the positive Y axis.

![](/src/assets/images/FreeCAD_views_front.svg)

Arrow 1 points in the direction of the front view

## Usage

1. There are several ways to invoke the command:
   - Press the ![](/src/assets/images/Std_ViewFront.svg) [Front](/Std_ViewFront "Std ViewFront") button.
   - Select the **View → Standard views → ![](/src/assets/images/Std_ViewFront.svg) Front** option from the menu.
   - Select the **Standard views → ![](/src/assets/images/Std_ViewFront.svg) Front** option from the [3D view](/3D_view "3D view") context menu.
   - Use the keyboard shortcut: 1.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

Use the `viewFront` method of the View object to change to front view. Methods for the other main view orientations are also available: `viewTop`, `viewRight`, `viewRear`, `viewBottom` and `viewRight`.

```
import FreeCADGui

view = FreeCADGui.ActiveDocument.ActiveView
view.viewFront()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_ViewFront/en&oldid=1449590>"
