---
title: Std Undo
---

|                                  |
| -------------------------------- |
| Std Undo                         |
| Menu location                    |
| Edit → Undo                      |
| Workbenches                      |
| All                              |
| Default shortcut                 |
| Ctrl+Z                           |
| Introduced in version            |
| -                                |
| See also                         |
| [Std Redo](/Std_Redo "Std Redo") |
|                                  |

## Description

The **Std Undo** command undoes the last action.

## Usage

1. There are several ways to invoke the command:
   - Press the ![](/src/assets/images/Std_Undo.svg) [Undo](/Std_Undo "Std Undo") button.
   - Select the **Edit → ![](/src/assets/images/Std_Undo.svg) Undo** option from the menu.
   - Use the keyboard shortcut: Ctrl+Z.

## Options

- To undo multiple actions click on the small black down arrow to the right of the ![](/src/assets/images/Std_Undo.svg) [Undo](/Std_Undo "Std Undo") button and select from the list.

## Preferences

See also: [Preferences Editor](/Preferences_Editor "Preferences Editor").

- The Undo/Redo functionality can be disabled by unchecking the **Edit → Preferences... → General → Document → Using Undo/Redo on documents** option. But this is not recommended.
- The maximum number of Undo/Redo steps is controlled by **Edit → Preferences... → General → Document → Maximum Undo/Redo steps**.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To undo the last action use the `undo` method of the document object. Its counterpart, the `redo` method, is also available.

```
import FreeCAD

FreeCAD.ActiveDocument.undo()

```

When running FreeCAD in pure console mode (CLI), the undo/redo mechanism isn't enabled by default. It must be explicitly activated for each document.

```
import FreeCAD

FreeCAD.ActiveDocument.UndoMode = 1

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_Undo/en&oldid=1448873>"
