---
title: Std MergeProjects
---

|                          |
| ------------------------ |
| Std MergeProjects        |
| Menu location            |
| File → Merge document... |
| Workbenches              |
| All                      |
| Default shortcut         |
| _None_                   |
| Introduced in version    |
| -                        |
| See also                 |
| _None_                   |
|                          |

## Description

The **Std MergeProjects** command adds the contents of a FreeCAD file into the active document.

## Usage

1. Select the **File → ![](/images/Std_MergeProjects.svg) Merge document...** option from the menu.
2. Select a FreeCAD file in the dialog box.
3. Press the Open button.

## Options

- Press Esc or the Cancel button to abort the command.

## Notes

- A project cannot be merged with itself, selecting the current file is not allowed.
- FreeCAD will automatically change the internal names and, depending on the [preferences](/Preferences_Editor#Document "Preferences Editor"), labels of objects to avoid name conflicts.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To merge a project use the `mergeProject` method of the document object.

```
import FreeCAD

FreeCAD.ActiveDocument.mergeProject("Path_to_FCStd_project_file")

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_MergeProjects/en&oldid=1534349>"
