---
title: Std ViewFitAll
---

|                                                                      |
| -------------------------------------------------------------------- |
| Std ViewFitAll                                                       |
| Menu location                                                        |
| View → Standard views → Fit all                                      |
| Workbenches                                                          |
| All                                                                  |
| Default shortcut                                                     |
| V F                                                                  |
| Introduced in version                                                |
| -                                                                    |
| See also                                                             |
| [Std ViewFitSelection](/Std_ViewFitSelection "Std ViewFitSelection") |
|                                                                      |

## Description

The **Std ViewFitAll** command zooms and pans the camera so that all visible objects fit inside the active [3D view](/3D_view "3D view").

## Usage

1. There are several ways to invoke the command:
   - Press the ![](/src/assets/images/Std_ViewFitAll.svg) [Fit all](/Std_ViewFitAll "Std ViewFitAll") button.
   - Select the **View → Standard views → ![](/src/assets/images/Std_ViewFitAll.svg) Fit all** option from the menu.
   - Select the **![](/src/assets/images/Std_ViewFitAll.svg) Fit all** option from the [3D view](/3D_view "3D view") context menu.
   - Select the **![](/src/assets/images/Std_ViewFitAll.svg) Fit all** option from the Mini-cube menu of the [Navigation Cube](/Navigation_Cube "Navigation Cube").
   - Use the keyboard shortcut: V then F.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

Use the `fitAll` method of the View object to zoom to fit all.

```
import FreeCADGui

view = FreeCADGui.ActiveDocument.ActiveView
view.fitAll()

```

For the active view the `SendMsgToActiveView` method of the FreeCADGui object can also be used.

```
import FreeCADGui

FreeCADGui.SendMsgToActiveView("ViewFit")

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Std_ViewFitAll/en&oldid=1449514>"
