---
title: Selection API
---
:::caution
(October 2019) Do not edit this page. The information is incomplete and outdated. For the latest API, see theautogenerated API documentation, or generate the documentation yourself, seeSource documentation.
:::

El submódulo de selección es parte del módulo FreeCADGui. Ejemplo:

```
import FreeCADGui
sel = FreeCADGui.Selection.getSelection()

```

![](/images/Method.png) **addSelection** ( *FreeCAD.Object* )

**Descripción**: Añade un objeto a la selección

**Devuelve**:

![](/images/Method.png) **clearSelection** ( *[string]* )

**Descripción**: Limpia la selección del nombre del documento dado. Si no se da ningún documento la selección completa es limpiada.

**Devuelve**:

![](/images/Method.png) **getSelection** ( *[string]* )

**Descripción**: Devuelve una lista de objetos seleccionados para un nombre de documento dado. Si no se da ningún documento se devuelve la selección completa.

**Devuelve**: Una lista de objetos

![](/images/Method.png) **isSelected** ( *FreeCAD.Object* )

**Descripción**: Comprueba si un objeto dado está seleccionado

**Devuelve**:

![](/images/Method.png) **removeSelection** ( *FreeCAD.Object* )

**Descripción**: Elimina un objeto de la selección

**Devuelve**:

Retrieved from "<http://wiki.freecad.org/index.php?title=Selection_API/es&oldid=632503>"