---
title: Part Cubo
---
|  |
| --- |
| Part Cubo |
| Ubicación en el Menú |
| Pieza → Primitivas → Cubo |
| Entornos de trabajo |
| [Part](/Part_Workbench/es "Part Workbench/es") |
| Atajo de teclado por defecto |
| *Ninguno* |
| Introducido en versión |
| - |
| Ver también |
| [Part Crear primitivas](/Part_Primitives/es "Part Primitives/es") |
|  |

## Descripción

El comando ![](/images/Part_Box.svg) **Part Caja** crea un sólido de caja paramétrica, un [cuboide rectangular](https://en.wikipedia.org/wiki/Cuboid#Rectangular_cuboid). En el sistema de coordenadas definido por su propiedad Datos**Placement**, la cara inferior de la caja se encuentra en el plano XY con su esquina frontal izquierda en el origen y su borde frontal paralelo al eje X.

![](/images/Part_Box_Example.png)

## Uso

Las propiedades se pueden editar después en la pestaña de datos del cubo:

## Ejemplo

![](/images/Part_Box_Scripting_Example.png)

Part Box from the scripting example

A Part Box object created with the [scripting example](#Scripting) below is shown here.

## Notas

* A Part Box can also be created with the ![](/images/Part_Primitives.svg) [Part Primitives](/Part_Primitives "Part Primitives") command. With that command you can specify the dimensions and placement at creation time.

## Propiedades

Ver también: [Editor de propiedades](/Property_editor/es "Property editor/es").

A Part Box object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Datos

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Box

Box

* DATOS**Length o Longitud**: Dimensiones del Cubo en la dirección X.
* DATOS**Width o Anchura**: Dimensiones del Cubo en la dirección Y.
* DATOS**Height o Altura**: Dimensiones del Cubo en la dirección Z.

## Programación

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

## Programación

El comando Box (Cubo) puede ser usado en las
[macros](/Macros "Macros") y desde la consola de Python usando la siguiente función:

```
box = FreeCAD.ActiveDocument.addObject("Part::Box", "myBox")

```

* Donde "myBox" es el nombre del objeto Cubo.
* Devuelve un nuevo objeto creado de tipo Cubo.

Ejemplo:

```
import FreeCAD as App

doc = App.activeDocument()

box = doc.addObject("Part::Box", "myBox")
box.Length = 4
box.Width = 8
box.Height = 12
box.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(75, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Box/es&oldid=1364257>"