---
title: Part API
---
:::caution
(November 2018) This information may be incomplete and outdated. For the latest API, see theautogenerated API documentationorautogenerated Python Part API documentation.
:::

El módulo Pieza es la conexión directa entre FreeCAD y el kernel de OpenCasCade. Proporciona principalmente [TopoShapes](/TopoShape_API/es "TopoShape API/es") el cual es el principal tipo de objeto utilizado por OpenCascade. El módulo de Pieza también contiene una variedad de funciones convenientes para crear y manipular topoShapes. Ejemplo:

```
import Part
mycube = Part.makeBox(2,2,2)
Part.show(mycube)

```

![](/images/Method.png) **\_\_fromPythonOCC\_\_** ( *OCC.Object* )

**Descripción**: Método de ayuda para convertir una forma pythonocc en una forma interna

**Devuelve**: Una forma de Pieza Part.Form

![](/images/Method.png) **\_\_sortEdges\_\_** ( *list of edges* )

**Descripción**: Método de ayuda para ordenar y desordenar listas de aristas para que después dos aristas adyacentes compartan un vértice en común

**Devuelve**: Una lista de aristas

![](/images/Method.png) **\_\_toPythonOCC\_\_** ( *Part.Shape* )

**Descripción**: Método de ayuda para convertir una forma interna a una forma pythonocc

**Devuelve**: Una forma OCC OCC.Shape

![](/images/Method.png) **cast\_to\_shape** ( *Part.Shape* )

**Descripción**: Vaciado del tipo de forma actual

**Devuelve**:

![](/images/Method.png) **export** ( *list,string* )

**Descripción**: Exportar una lista de objetos en un archivo individual.

**Devuelve**:

![](/images/Method.png) **getSortedClusters** ( *list of edges* )

**Descripción**: Método de ayuda para ordenar y agrupar una variedad de aristas

**Devuelve**:

![](/images/Method.png) **insert** ( *string,string* )

**Descripción**: Inserta el archivo (cuya ruta es dada como primer argumento) en el documento indicado (como segundo argumento).

**Devuelve**:

![](/images/Method.png) **makeBox** ( *length,width,height,[pnt,dir]* )

**Descripción**: Crea un cubo ubicado en el punto pnt con las dimensiones (length,width,height). Por defecto el vector pnt es (0,0,0) y el vector dir es (0,0,1)

**Devuelve**: La forma creada

![](/images/Method.png) **makeCircle** ( *radius,[pnt,dir,angle1,angle2]* )

**Descripción**: Crea una circunferencia con un radio dado. Por defecto el vector pnt es Vector(0,0,0), el vector dir es (0,0,1), angle1 es 0 y angle2 es 360

**Devuelve**: La forma creada

![](/images/Method.png) **makeCompound** ( *list* )

**Descripción**: Crea un compuesto de una lista de formas.

**Devuelve**: La forma creada

![](/images/Method.png) **makeCone** ( *radius1,radius2,height,[pnt,dir,angle]* )

**Descripción**: Crea un cono con un radio dado y una altura. Por defecto el vector pnt es (0,0,0), el vector dir es (0,0,1) y angle es 360

**Devuelve**: La forma creada

![](/images/Method.png) **makeCylinder** ( *radius,height,[pnt,dir,angle]* )

**Descripción**: Crea un cilindro con un radio y altura dados. Por defecto el vector pnt es (0,0,0), el vector dir es (0,0,1) y angle es 360

**Devuelve**: La forma creada

![](/images/Method.png) **makeHelix** ( *pitch,height,radius,[angle]* )

**Descripción**: Crea una hélice con un paso, altura y radio dados. Por defecto se utiliza una superficie cilindrica para crear la hélice. Si el cuarto parámetro está definido se utiliza en su lugar una superficie cónica

**Devuelve**: La forma creada

![](/images/Method.png) **makeLine** ( *(x1,y1,z1),(x2,y2,z2)* )

**Descripción**: Crea una línea de dos puntos

**Devuelve**: La forma creada

![](/images/Method.png) **makeLoft** (  *shapelist<profiles>,[boolean<solid>,boolean<ruled>]* )

**Descripción**: Crea una forma recubrimiento (Loft).

**Devuelve**: La forma creada

![](/images/Method.png) **makePlane** ( *length,width,[pnt,dir]* )

**Descripción**: Crea un plano. Por defecto el vector pnt es (0,0,0) y el vector dir es (0,0,1)

**Devuelve**: La forma creada

![](/images/Method.png) **makePolygon** ( *list* )

**Descripción**: Crea un polígono de una lista de vectores

**Devuelve**: La forma creada

![](/images/Method.png) **makeRevolution** ( *Curve,[vmin,vmax,angle,pnt,dir]* )

**Descripción**: Crea una forma de revolución (revolved) rotando la curva o una porción de ella alrededor de un eje dado por (pnt,dir). Por defecto vmin/vmax se establecen para limitar la curva, angle es 360, el vector pnt es (0,0,0) y el vector dir es (0,0,1)

**Devuelve**: La forma creada

![](/images/Method.png) **makeRuledSurface** ( *Edge or Wire,Edge or Wire* )

**Descripción**: Crea una superficie reglada a partir de dos aristas o contornos. Si se utilizan contornos estos deben tener el mismo número de aristas.

**Devuelve**: La forma creada

![](/images/Method.png) **makeShell** ( *list* )

**Descripción**: Crea una cáscara a partir de una lista de caras.

**Devuelve**: La forma creada

![](/images/Method.png) **makeSolid** ( *Part.Shape* )

**Descripción**: Crea un sólido a partir de las cáscaras dentro de una forma.

**Devuelve**: La forma creada

![](/images/Method.png) **makeSphere** ( *radius,[pnt, dir, angle1,angle2,angle3]* )

**Descripción**: Crea una esfera con un radio dado. Por defecto el vector pnt es (0,0,0), el vector dir es (0,0,1), angle1 es 0, angle2 es 90 y angle3 es 360

**Devuelve**: La forma creada

![](/images/Method.png) **makeTorus** ( *radius1,radius2,[pnt,dir,angle1,angle2,angle]* )

**Descripción**: Crea un toto con un radio y ángulos dados. Por defecto el vector pnt es (0,0,0), el vector dir es (0,0,1), angle1 es 0, angle2 es 360 y angle es 360

**Devuelve**: La forma creada

![](/images/Method.png) **makeTube** ( *edge,float* )

**Descripción**: Crea un tubo.

**Devuelve**: the created shape

![](/images/Method.png) **open** ( *string* )

**Descripción**: Crea un nuevo documento y carga el archivo en el documento.

**Devuelve**:

![](/images/Method.png) **read** ( *string* )

**Descripción**: Carga el archivo y devuelve la forma.

**Devuelve**: Una forma

![](/images/Method.png) **show** ( *shape* )

**Descripción**: Añade la forma al documento activo o crea uno si el documento no existe.

**Devuelve**:

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_API/es&oldid=1311589>"