---
title: Part Prisma
---
|  |
| --- |
| Part Prisma |
| Ubicación en el Menú |
| Pieza → [Crear primitivas](/Part_Primitives/es "Part Primitives/es") → Prisma |
| Entornos de trabajo |
| [Part](/Part_Workbench/es "Part Workbench/es") |
| Atajo de teclado por defecto |
| *Ninguno* |
| Introducido en versión |
| 0.14 |
| Ver también |
| [Part Primitivas](/Part_Primitives/es "Part Primitives/es"), [Part Cubo](/Part_Box/es "Part Box/es") |
|  |

## Descripción

Un Prisma de Part es un sólido definido por el corte transversal de un polígono regular y una altura.

![](/images/Part_Prism_Example.png)

## Uso

See [Part Primitives](/Part_Primitives#Usage "Part Primitives").

## Example

![](/images/Part_Prism_Scripting_Example.png)

Part Prism from the scripting example

A Part Prism object created with the [scripting example](#Scripting) below is shown here.

## Propiedades

See also: [Property editor](/Property_editor "Property editor").

A Part Prism object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Prism

* DATOS**Polígono:** El número de aristas que forman las caras del polígono base y superior del prisma.
* DATOS**Circunradio :** Radio de la circunferencia en la que está inscrito el corte transversal del polígono que forma el prisma.
* DATOS**Altura:** Altura del Prisma.
* DATOS**Primer Ángulo**: Ángulo de la primera dirección. [introducido en la versión 0.19](/Release_notes_0.19/es "Release notes 0.19/es")
* DATOS**Segundo Ángulo**: Ángulo de la segunda dirección. [introducido en la versión 0.19](/Release_notes_0.19/es "Release notes 0.19/es")

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Prism can be created with the `addObject()` method of the document:

```
prism = FreeCAD.ActiveDocument.addObject("Part::Prism", "myPrism")

```

* Where `"myPrism"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

prism = doc.addObject("Part::Prism", "myPrism")
prism.Polygon = 5
prism.Circumradius = 10
prism.Height = 50
prism.FirstAngle = 22.5
prism.SecondAngle = 45
prism.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(60, 75, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Prism/es&oldid=1268270>"