---
title: Part Tubo
---
|  |
| --- |
| Part Tubo |
| Ubicación en el Menú |
| Pieza → Primitivas → Crear un tubo |
| Entornos de trabajo |
| [Part](/Part_Workbench/es "Part Workbench/es") |
| Atajo de teclado por defecto |
| *Ninguno* |
| Introducido en versión |
| 0.19 |
| Ver también |
| *Ninguno* |
|  |

## Descripción

El comando Tubo inserta un tubo en el documento activo. El tubo es geométricamente tratado como un corte de un cilindro más pequeño dentro de otro mayor. Por defecto, el comando insertará un tubo de 10 mm de altura con un radio exterior de 5 mm y un radio interior de 2 mm. Estos parámetros pueden ser modificados tras ser introducido el objeto.

![](/images/Part_Tube_Example.png)

## Uso

### Create

Se puede crear un tubo:

* presionando el botón ![](/images/Part_Tube.svg) **Crea un Tubo** en la barra de herramientas; o bien:
* usando el menú **Pieza → Primitivas → Crear un tubo**

### Edit

1. Double-click the tube in the [Tree view](/Tree_view "Tree view")
2. The **Tube** task panel opens.
3. Change one or more dimensions.
4. The tube is dynamically updated in the [3D view](/3D_view "3D view").
5. Press the OK button.

## Example

![](/images/Part_Tube_Scripting_Example.png)

Part Tube from the scripting example

A Part Tube object created with the [scripting example](#Scripting) below is shown here.

## Propiedades

See also: [Property editor](/Property_editor "Property editor").

A Part Tube object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Tube

* Por medio del [Editor de propiedades](/Property_editor/es "Property editor/es"):
  + **Height o Altura:** Selecciona la altura (por defecto es 10 mm).
  + **Inner radius o Radio interior:** Selecciona el radio interior (por defecto es 2 mm).
  + **Outer radius o Radio exterior:** Selecciona el radio exterior (por defecto es 5 mm).
  + **Placement o Localización:** Especifica la orientación y la posición de la caja en el espacio 3D. Ver  [Placement](/Placement/es "Placement/es"). El punto de referencia es la esquina inferior izquierda frontal de la caja.
  + **Label o Etiqueta:** Es el nombre dado a la operación. Este nombre puede ser cambiado si es conveniente.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Tube can be created with the `addTube()` method ([introduced in 0.20](/Release_notes_0.20 "Release notes 0.20")) of the Shapes module:

```
tube = Shapes.addTube(FreeCAD.ActiveDocument, "myTube")

```

* Where `"myTube"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App
from BasicShapes import Shapes

doc = App.activeDocument()

tube = Shapes.addTube(FreeCAD.ActiveDocument, "myTube")
tube.Height = 20
tube.InnerRadius = 2
tube.OuterRadius = 3
tube.Placement = App.Placement(App.Vector(2, 4, 5), App.Rotation(60, 60, 30))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Tube/es&oldid=1222528>"