---
title: Part Plano
---
|  |
| --- |
| Part Plano |
| Ubicación en el Menú |
| Pieza → Crear primitivas... →Plano |
| Entornos de trabajo |
| [Part](/Part_Workbench/es "Part Workbench/es") |
| Atajo de teclado por defecto |
| *Ninguno* |
| Introducido en versión |
| - |
| Ver también |
| [Part Primitivas](/Part_Primitives/es "Part Primitives/es") |
|  |

## Description

## Descripción

Crea un Plano paramétrico simple de 10 x 10 mm, con los parámetros de posición, longitud y anchura.
Por defecto, el Plano es colocado en el origen (0,0,0).

![](/images/Part_Plane_Example.png)

## Uso

See [Part Primitives](/Part_Primitives#Usage "Part Primitives").

## Example

![](/images/Part_Plane_Scripting_Example.png)

Part Plane from the scripting example

A Part Plane object created with the [scripting example](#Scripting) below is shown here.

## Properties

See also: [Property editor](/Property_editor "Property editor").

A Part Plane object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Plane

* Datos**Length** (`Length`): The length of the plane. This is the dimension in its X direction. The default is `10mm`.
* Datos**Width** (`Length`): The width of the plane. This is the dimension in its Y direction. The default is `10mm`.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Plane can be created with the `addObject()` method of the document:

```
plane = FreeCAD.ActiveDocument.addObject("Part::Plane", "myPlane")

```

* Where `"myPlane"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

plane = doc.addObject("Part::Plane", "myPlane")
plane.Length = 4
plane.Width = 8
plane.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(20, 75, 60))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Plane/es&oldid=1106449>"