---
title: Draft Inverser le texte de la dimension
---
|  |
| --- |
| Draft Inverser le texte de la dimension |
| Emplacement du menu |
| Modification → Inverser le texte de la dimension |
| Ateliers |
| [Draft](/Draft_Workbench/fr "Draft Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| - |
| Voir aussi |
| *Aucun* |
|  |

## Description

La commande ![](/images/Draft_FlipDimension.svg) **Draft Inverser le texte de la dimension** fait pivoter le texte de la dimension d'une [Draft Dimension](/Draft_Dimension/fr "Draft Dimension/fr") sélectionnée de 180° autour de la ligne de la dimension. Elle peut être utilisée pour corriger les dimensions dont le texte apparaît en miroir. La commande ne fonctionne pas correctement pour les dimensions angulaires.

## Utilisation

1. Sélectionner une ou plusieurs [Draft Dimensions](/Draft_Dimension/fr "Draft Dimension/fr").
2. Il existe plusieurs façons de lancer la commande :
   * Appuyer sur le bouton ![](/images/Draft_FlipDimension.svg) Inverser le texte de la dimension.
   * Sélectionner l'option **Modification → ![](/images/Draft_FlipDimension.svg) Inverser le texte de la dimension** du menu.

## Remarques

* Les [Draft Dimensions](/Draft_Dimension/fr "Draft Dimension/fr") possèdent également une propriété Données**Flip Text**. Lorsqu'elle est mise à `true`, le texte est tourné de 180° autour de la direction normale. Ceci peut être combiné avec l'effet de cette commande.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Pour inverser une [Draft Dimension](/Draft_Dimension/fr "Draft Dimension/fr"), inversez sa propriété `Normal`.

Exemple :

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(1000, 0, 0)
p3 = App.Vector(500, 300, 0)
dimension = Draft.make_dimension(p1, p2, p3)
dimension.ViewObject.FontSize = 200

dimension.Normal = dimension.Normal.negative()
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_FlipDimension/fr&oldid=1458641>"