---
title: Draft Décaler
---
|  |
| --- |
| Draft Décaler |
| Emplacement du menu |
| Draft/BIM : Modification → Décaler |
| Ateliers |
| [Draft](/Draft_Workbench/fr "Draft Workbench/fr"), [BIM](/BIM_Workbench/fr "BIM Workbench/fr") |
| Raccourci par défaut |
| O S |
| Introduit dans la version |
| - |
| Voir aussi |
| [Part Décaler en 2D](/Part_Offset2D/fr "Part Offset2D/fr") |
|  |

## Description

La commande ![](/images/Draft_Offset.svg) **Draft Décaler** décale chaque segment d'un objet sélectionné sur une distance donnée ou crée une copie décalée de l'objet sélectionné.

![](/images/Draft_Offset_example.jpg)

Décalage d'une Draft Polyligne

## Utilisation

Voir aussi : [Draft Aimantation](/Draft_Snap/fr "Draft Snap/fr") et [Draft Contrainte](/Draft_Constrain/fr "Draft Constrain/fr").

1. Sélectionner un objet au choix. L'objet doit se trouver sur le [Draft plan de travail](/Draft_SelectPlane/fr "Draft SelectPlane/fr") en cours.
2. Il existe plusieurs façons de lancer la commande :
   * Appuyer sur le bouton ![](/images/Draft_Offset.svg) Décaler.
   * [Draft](/Draft_Workbench/fr "Draft Workbench/fr") : sélectionner l'option **Modification → ![](/images/Draft_Offset.svg) Décaler** du menu.
   * [BIM](/BIM_Workbench/fr "BIM Workbench/fr") : sélectionner l'option **Modification → ![](/images/Draft_Offset.svg) Décaler** du menu.
   * Utiliser le raccourci clavier : O puis S.
3. Si vous n'avez pas encore sélectionné d'objet : sélectionner un objet dans la [vue 3D](/3D_view/fr "3D view/fr").
4. Le panneau de tâches **Décalage** s'ouvre. Voir [Options](#Options) pour plus d'informations.
5. Pour définir la distance de décalage, effectuer l'une des opérations suivantes :
   * Choisir un point dans la [vue 3D](/3D_view/fr "3D view/fr").
   * Entrer une valeur numérique :
     1. Vérifier que le pointeur se trouve du bon côté de l'objet dans la [vue 3D](/3D_view/fr "3D view/fr").
     2. Ne pas déplacer le pointeur en dehors de la [vue 3D](/3D_view/fr "3D view/fr").
     3. Saisir une **Distance**.
     4. Appuyer sur Entrée pour terminer la commande.

## Options

Les raccourcis clavier à caractère unique disponibles dans le panneau des tâches peuvent être modifiés. Voir [Draft Préférences](/Draft_Preferences/fr "Draft Preferences/fr"). Les raccourcis mentionnés ici sont les raccourcis par défaut (pour la version 1.0).

* Si la case **Décalage de type OCC** est cochée, un style de décalage spécial est utilisé : les [Draft Polylignes](/Draft_Wire/fr "Draft Wire/fr") ouvertes sont décalées des deux côtés et les nouveaux bords sont connectés avec des coins arrondis. Ceci ne fonctionne que pour les objets planaires avec au moins deux bords. Notez qu'avec ce style, un nouvel objet non paramétrique est créé, et si le mode copier est désactivé, l'objet original est supprimé.
* Appuyer sur C ou cliquez sur la case **Copier** pour activer le mode de copie. Si le mode de copie est activé, la commande créera une copie décalée au lieu de décaler l'objet original.
* Le fait de maintenir Alt enfoncé avant de sélectionner des points dans la [vue 3D](/3D_view/fr "3D view/fr") permet également de basculer en mode copier. Lorsque Alt est maintenu enfoncé, plusieurs points de décalage peuvent être sélectionnés. Relâchez Alt pour terminer la commande et voir les copies créées.
* Maintener Shift enfoncé pour que la distance de décalage reste liée au segment actuel.
* Appuyer sur S pour activer ou désactiver l'[Draft Aimantation](/Draft_Snap/fr "Draft Snap/fr").
* Appuyer sur Échap ou sur le bouton Fermer pour abandonner la commande.

## Remarques

* Pour créer une version décalée d'une [Draft B-spline](/Draft_BSpline/fr "Draft BSpline/fr"), ses points sont décalés individuellement et une nouvelle spline est calculée à partir des nouveaux points. Cette nouvelle spline n'est pas parallèle à la spline d'origine. Pour un décalage parallèle d'une [Draft B-spline](/Draft_BSpline/fr "Draft BSpline/fr"), la commande [Part Décaler en 2D](/Part_Offset2D/fr "Part Offset2D/fr") doit être utilisée.
* La commande Draft Décalage ne peut pas traiter les [Draft Courbes de Bézier](/Draft_BezCurve/fr "Draft BezCurve/fr"). Utilisez plutôt la commande [Part Décaler en 2D](/Part_Offset2D/fr "Part Offset2D/fr").

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Pour décaler les objets, utilisez la méthode `offset` de l'atelier Draft. Cette méthode ne peut traiter que les objets suivants : [Draft Polylignes](/Draft_Wire/fr "Draft Wire/fr"), [Draft Cercles](/Draft_Circle/fr "Draft Circle/fr"), [Draft Rectangles](/Draft_Rectangle/fr "Draft Rectangle/fr"), [Draft Polygones](/Draft_Polygon/fr "Draft Polygon/fr") et [Draft B-splines](/Draft_BSpline/fr "Draft BSpline/fr").

```
offset_obj = offset(obj, delta, copy=False, bind=False, sym=False, occ=False)

```

* `obj` est l'objet à décaler.
* `delta` contient les informations de décalage :
  + Pour les [Draft Polylignes](/Draft_Wire/fr "Draft Wire/fr"), [Draft Rectangles](/Draft_Rectangle/fr "Draft Rectangle/fr") et [Draft Polygones](/Draft_Polygon/fr "Draft Polygon/fr"), c'est un vecteur de décalage qui doit être perpendiculaire au premier segment de l'objet.
  + Pour les [Draft Cercles](/Draft_Circle/fr "Draft Circle/fr"), c'est le nouveau rayon.
  + Pour les [Draft B-splines](/Draft_BSpline/fr "Draft BSpline/fr"), il s'agit d'une liste de nouveaux points.
* Si `copy` est `True`, l'objet original est conservé et un nouvel objet est créé.
* Si `bind` est `True`, une face est créée en connectant la forme de l'objet original et la forme de son décalage. Cela ne fonctionne que pour les [Draft Polylignes](/Draft_Wire/fr "Draft Wire/fr") ouverts.
* Si `sym` est `True` et `bind` est `True` également, le décalage est effectué des deux côtés de l'objet original, la largeur totale étant la longueur du vecteur donné. Ceci ne fonctionne que pour les [Draft Polylignes](/Draft_Wire/fr "Draft Wire/fr") ouverts.
* Si `occ` est `True`, le décalage de type OCC est utilisé. Voir [Options](#Options). Si `occ` est `True`, les arguments `bind` et `sym` sont ignorés.
* `offset_obj` est restitué avec l'objet de décalage original ou avec le nouvel objet. Si `bind` est `True` ou `occ` est `True`, le nouvel objet est un objet `Part::Feature`.

Exemple :

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(1500, 2000, 0)
p3 = App.Vector(4000, 0, 0)

wire = Draft.make_wire([p1, p2, p3])
doc.recompute()

vector = App.Vector(-200, 150, 0)
offset1 = Draft.offset(wire, vector, copy=True, bind=True, sym=True)
offset2 = Draft.offset(wire, 3*vector, copy=True)
offset3 = Draft.offset(wire, 6*vector, copy=True)
offset4 = Draft.offset(wire, 9*vector, copy=True)
offset5 = Draft.offset(wire, 1.5*vector, copy=True, occ=True)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Offset/fr&oldid=1475175>"