---
title: Draft Scinder
---
|  |
| --- |
| Draft Scinder |
| Emplacement du menu |
| Draft/BIM : Modification → Scinder |
| Ateliers |
| [Draft](/Draft_Workbench/fr "Draft Workbench/fr"), [BIM](/BIM_Workbench/fr "BIM Workbench/fr") |
| Raccourci par défaut |
| S P |
| Introduit dans la version |
| 0.18 |
| Voir aussi |
| [Draft Joindre](/Draft_Join/fr "Draft Join/fr") |
|  |

## Description

La commande ![](/images/Draft_Split.svg) **Draft Scinder** permet de diviser une [Draft Ligne](/Draft_Line/fr "Draft Line/fr") ou une [Draft Polyligne](/Draft_Wire/fr "Draft Wire/fr") à un point ou un bord donné. Cette commande est la contrepartie de la commande [Draft Joindre](/Draft_Join/fr "Draft Join/fr").

## Utilisation

1. Il existe plusieurs façons de lancer la commande :
   * Appuyez sur le bouton ![](/images/Draft_Split.svg) Scinder.
   * [Draft](/Draft_Workbench/fr "Draft Workbench/fr"): sélectionnez l'option **Modification → ![](/images/Draft_Split.svg) Scinder** du menu.
   * [BIM](/BIM_Workbench/fr "BIM Workbench/fr"): sélectionnez l'option **Modification → ![](/images/Draft_Split.svg) Scinder** du menu.
   * Utilisez le raccourci clavier : S puis P.
2. Déplacez le pointeur sur le bon bord d'une [Draft Ligne](/Draft_Line/fr "Draft Line/fr") ou d'une [Draft Polyligne](/Draft_Wire/fr "Draft Wire/fr").
3. L'arête est mise en surbrillance.
4. Effectuez l'une des opérations suivantes :
   * Si la ligne est fermée :
     + Choisissez un point quelconque sur l'arête.
     + L'arête est détachée du fil et devient une ligne distincte.
   * Si la ligne est ouverte :
     + Choisissez le bon point sur l'arête. Voir [Remarques](#Remarques).
     + La ligne est coupée au point choisi.

## Remarques

* Si une ligne ouverte est divisée et que le point cliqué ne se trouve pas exactement sur l'arête sélectionnée, le nouveau point ne sera pas colinéaire avec cette ancienne arête. Utilisez une option appropriée de [Draft Aimantation](/Draft_Snap/fr "Draft Snap/fr") pour éviter cela.
* Pour scinder des objets qui ne sont pas des [Draft Lignes](/Draft_Line/fr "Draft Line/fr") ou des [Draft Polylignes](/Draft_Wire/fr "Draft Wire/fr"), vous pouvez essayer d'utiliser [Draft Agréger](/Draft_Upgrade/fr "Draft Upgrade/fr") et/ou [Draft Désagréger](/Draft_Downgrade/fr "Draft Downgrade/fr") sur eux une ou plusieurs fois d'abord.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Pour scinder une ligne, utilisez la méthode `split` de l'atelier Draft. Cette méthode renvoie `None`.

```
split(wire, newPoint, edgeIndex)

```

* `wire` l'objet ligne devant être divisé.
* `newPoint` le point où la séparation doit avoir lieu.
* `edgeIndex` indice de l'arête où la séparation doit avoir lieu (basé sur 1).

Exemple :

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(500, 0, 0)
p3 = App.Vector(250, 0, 0)

wire = Draft.make_wire([p1, p2])

Draft.split(wire, p3, 1)
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Split/fr&oldid=1475189>"