---
title: Draft Surface liée
---
|  |
| --- |
| Draft Surface liée |
| Emplacement du menu |
| Draft : Formes → Surface liée  BIM : 3D/BIM → Outils 3D génériques → Surface liée |
| Ateliers |
| [Draft](/Draft_Workbench/fr "Draft Workbench/fr"), [BIM](/BIM_Workbench/fr "BIM Workbench/fr") |
| Raccourci par défaut |
| Draft : F F |
| Introduit dans la version |
| 0.14 |
| Voir aussi |
| *Aucun* |
|  |

## Description

La commande ![](/images/Draft_Facebinder.svg) **Draft Surface liée** crée un objet surface à partir des faces sélectionnées. Une Draft Surface liée est paramétrique, elle sera mise à jour si vous modifiez son ou ses objets sources.

Elle peut être utilisée pour créer une extrusion à partir d'une combinaison de surfaces. Cette extrusion peut par exemple représenter une finition de mur dans une conception architecturale.

![](/images/Draft_facebinder_example.jpg)

Surfaces liées créées à partir des faces de murs

## Utilisation

1. Sélectionner une ou plusieurs faces.
2. Il existe plusieurs façons de lancer la commande :
   * Appuyer sur le bouton ![](/images/Draft_Facebinder.svg) Surface liée.
   * [Draft](/Draft_Workbench/fr "Draft Workbench/fr") : sélectionner l'option **Formes → ![](/images/Draft_Facebinder.svg) Surface liée** du menu.
   * [BIM](/BIM_Workbench/fr "BIM Workbench/fr") : sélectionner l'option **3D/BIM → Outils 3D génériques → ![](/images/Draft_Facebinder.svg) Surface liée** du menu.
   * Draft : utiliser le raccourci clavier : F puis F.

## Propriétés

Voir aussi : [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

![](/images/Draft_Facebinder_Corners.png)

À gauche, une surface liée extrudée avec des coins fermés (rose)  
À droite, une surface liéeextrudée avec des coins ouverts (orange)  
Les coins fermés sont une fonctionnalité de la V1.1.

Un objet Draft Surface liée est dérivé de [Part Feature](/Part_Feature/fr "Part Feature/fr") et hérite de toutes ses propriétés. Il possède également les propriétés supplémentaires suivantes :

### Données

Draft

* Données**Area** (`Area`) : (en lecture seule) spécifie la surface totale des faces liées de la surface liée.
* Données**Extrusion** (`Distance`) : spécifie l'épaisseur d'extrusion de la surface liée. [introduit dans la version 1.1](/Release_notes_1.1/fr "Release notes 1.1/fr") : si la surface liée a des faces connectées et que Données**Sew** est `true`, une tentative est faite pour fermer les coins de l'extrusion. Si cela n'est pas possible, les faces sont extrudées séparément.
* Données**Faces** (`LinkSubList`) : spécifie les faces liées de la surface liée.
* Données**Offset** (`Distance`) : spécifie une distance de décalage à appliquer entre la lime à facettes et les faces originales, avant l'extrusion.
* Données**Remove Splitter** (`Bool`) : spécifie s'il faut supprimer les lignes de séparation qui divisent les faces coplanaires de la surface liée.
* Données**Sew** (`Bool`) : spécifie s'il faut effectuer une opération de couture topologique sur la surface liée.

### Vue

Draft

* Vue**Pattern** (`Enumeration`) : spécifie le [Draft Motif](/Draft_Pattern/fr "Draft Pattern/fr") avec lequel remplir les surfaces liées. Cette propriété ne fonctionne que si Vue**Display Mode** est `Flat Lines`.
* Vue**Pattern Size** (`Float`) : spécifie la taille du [Draft Motif](/Draft_Pattern/fr "Draft Pattern/fr").

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Pour créer une Draft Surface liée, utilisez la méthode `make_facebinder` ([introduit dans la version 0.19](/Release_notes_0.19/fr "Release notes 0.19/fr")) du module Draft. Cette méthode remplace la méthode dépréciée `makeFacebinder`.

```
facebinder = make_facebinder(selectionset)

```

* Crée un objet `facebinder` à partir du `selectionset` donné qui est une liste de `SelectionObject` tels que ceux renvoyés par `FreeCADGui.Selection.getSelectionEx()`.
  + `selectionset` peut aussi être un `PropertyLinkSubList`.

Un `PropertyLinkSubList` est une liste de tuples. Chaque tuple contient comme premier élément un `object` et comme deuxième élément une liste (ou tuple) de chaînes. Ces chaînes indiquent les noms des sous-éléments (faces) de cet objet.

```
PropertyLinkSubList = [tuple1, tuple2, tuple3, ...]
PropertyLinkSubList = [(object1, list1), (object2, list2), (object3, list3), ...]
PropertyLinkSubList = [(object1, ['Face1', 'Face4', 'Face6']), ...]
PropertyLinkSubList = [(object1, ('Face1', 'Face4', 'Face6')), ...]

```

L'épaisseur de la surface liée peut être ajoutée en écrasant son attribut `Extrusion`. La valeur est entrée en millimètres.

Le placement de la surface liée peut être modifié en remplaçant son attribut `Placement` ou en écrasant ses attributs `Placement.Base` et `Placement.Rotation`.

Exemple :

```
import FreeCAD as App
import FreeCADGui as Gui
import Draft

doc = App.newDocument()

# Insert a solid box
box = doc.addObject("Part::Box", "Box")
box.Length = 2300
box.Width = 800
box.Height = 1000

# selection = Gui.Selection.getSelectionEx()
selection = [(box, ("Face1", "Face6"))]
facebinder = Draft.make_facebinder(selection)
facebinder.Extrusion = 50

doc.recompute()

facebinder.Placement.Base = App.Vector(1000, -1000, 100)
facebinder.ViewObject.ShapeColor = (0.99, 0.99, 0.4)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Facebinder/fr&oldid=1551518>"