---
title: Draft Polyligne <=> B-spline
---
|  |
| --- |
| Draft Polyligne <=> B-spline |
| Emplacement du menu |
| Modification → Convertir une polyligne en B-spline et inversement |
| Ateliers |
| [Draft](/Draft_Workbench/fr "Draft Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| - |
| Voir aussi |
| [Draft Polyligne](/Draft_Wire/fr "Draft Wire/fr"), [Draft B-spline](/Draft_BSpline/fr "Draft BSpline/fr") |
|  |

## Description

La commande ![](/images/Draft_WireToBSpline.svg) **Draft Polyligne <=> B-spline** convertit les [Draft Polylignes](/Draft_Wire/fr "Draft Wire/fr") en [Draft B-splines](/Draft_BSpline/fr "Draft BSpline/fr") et inversement.

![](/images/Draft_Wire2BSpline_example.jpg)

Conversion d'une Draft Polyligne en Draft B-spline, et d'une Draft B-spline fermée en Draft Polyligne fermée.

## Utilisation

1. Sélectionnez une [Draft Polyligne](/Draft_Wire/fr "Draft Wire/fr") ou une [Draft B-spline](/Draft_BSpline/fr "Draft BSpline/fr").
2. Il existe plusieurs façons de lancer la commande :
   * Appuyez sur le bouton ![](/images/Draft_WireToBSpline.svg) Convertir une polyligne en B-spline et inversement.
   * Sélectionnez l'option **Modification → ![](/images/Draft_WireToBSpline.svg) Convertir une polyligne en B-spline et inversement** du menu.
3. Un nouvel objet est créé.

## Remarques

* La commande peut générer une [Draft Polyligne](/Draft_Wire/fr "Draft Wire/fr") ou une [Draft B-spline](/Draft_BSpline/fr "Draft BSpline/fr") fermée et auto-sécante avec une face. Un tel objet ne s'affichera pas correctement dans la [vue 3D](/3D_view/fr "3D view/fr"). Sa propriété Données**Make Face** ou sa propriété Données**Closed** doivent être définies sur `false`.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Pour convertir une polyligne en bspline, ou vice versa, passez la propriété `Points` de l'objet source à la méthode `make_bspline`, respectivement à la méthode `make_wire` de l'atelier Draft.

Exemple :

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(1000, 1000, 0)
p2 = App.Vector(2000, 1000, 0)
p3 = App.Vector(2500, -1000, 0)
p4 = App.Vector(3500, -500, 0)

base_wire = Draft.make_wire([p1, p2, p3, p4])
base_spline = Draft.make_bspline([-p1, -1.3*p2, -1.2*p3, -2.1*p4])

points1 = base_wire.Points
spline_from_wire = Draft.make_bspline(points1)

points2 = base_spline.Points
wire_from_spline = Draft.make_wire(points2)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_WireToBSpline/fr&oldid=1458949>"