---
title: Draft Ligne
---
|  |
| --- |
| Draft Ligne |
| Emplacement du menu |
| Draft : Formes → Ligne  BIM : Formes 2D → Ligne |
| Ateliers |
| [Draft](/Draft_Workbench/fr "Draft Workbench/fr"), [BIM](/BIM_Workbench/fr "BIM Workbench/fr") |
| Raccourci par défaut |
| L I |
| Introduit dans la version |
| 0.7 |
| Voir aussi |
| [Draft Polyligne](/Draft_Wire/fr "Draft Wire/fr") |
|  |

## Description

La commande ![](/images/Draft_Line.svg) **Draft Ligne** crée une ligne droite.

Une Draft Ligne est en fait une [Draft Polyligne](/Draft_Wire/fr "Draft Wire/fr") avec seulement deux points.

![](/images/Draft_Line_example.jpg)

Ligne définie par deux points

## Utilisation

Voir aussi : [Draft La barre](/Draft_Tray/fr "Draft Tray/fr"), [Draft Aimantation](/Draft_Snap/fr "Draft Snap/fr") et [Draft Contrainte](/Draft_Constrain/fr "Draft Constrain/fr").

1. Il existe plusieurs façons de lancer la commande :
   * Appuyer sur le ![](/images/Draft_Line.svg) Ligne.
   * [Draft](/Draft_Workbench/fr "Draft Workbench/fr") : sélectionner l'option **Formes → ![](/images/Draft_Line.svg) Ligne** du menu.
   * [BIM](/BIM_Workbench/fr "BIM Workbench/fr") : sélectionner l'option **Formes 2D → ![](/images/Draft_Line.svg) Ligne** du menu.
   * Utilisez les raccourcis du clavier : L puis I.
2. Le panneau de tâches **Ligne** s'ouvre. Voir [Options](#Options) pour plus d'informations.
3. Choisir le premier point dans la [vue 3D](/3D_view/fr "3D view/fr") ou rentrer des coordonnées et appuyer sur le bouton ![](/images/Draft_AddPoint.svg) Entrer un point.
4. Choisir le deuxième point dans la [vue 3D](/3D_view/fr "3D view/fr") ou rentrer des coordonnées et appuyer sur le bouton ![](/images/Draft_AddPoint.svg) Entrer un point.

## Options

Les raccourcis clavier à caractère unique disponibles dans le panneau des tâches peuvent être modifiés. Voir [Draft Préférences](/Draft_Preferences/fr "Draft Preferences/fr"). Les raccourcis mentionnés ici sont les raccourcis par défaut (pour la version 1.0).

* Pour saisir manuellement des coordonnées, entrez les valeurs X, Y et Z et appuyez sur Entrée après chacune ou vous pouvez appuyer sur le bouton ![](/images/Draft_AddPoint.svg) Entrer un point lorsque vous avez les valeurs souhaitées. Il est conseillé de déplacer le pointeur hors de la [vue 3D](/3D_view/fr "3D view/fr") avant de saisir les coordonnées.
* Pour utiliser des coordonnées polaires, entrez une valeur pour la **Longueur** et une valeur pour l'**Angle** et appuyez sur Entrée après chacune d'elles.
* Cochez la case **Angle** pour contraindre le pointeur à l'angle spécifié.
* Appuyez sur L pour faire passer le curseur de **X** à **Longueur** et inversement. Selon la saisie, la case **Angle** est cochée ou décochée.
* Appuyez sur R ou cliquez sur la case **Relative** pour activer le mode relatif. Si le mode relatif est activé, les coordonnées du deuxième point sont relatives au premier point, sinon elles sont relatives à l'origine du système de coordonnées.
* Appuyez sur G ou cliquez sur la case **Global** pour activer le mode global. Si le mode global est activé, les coordonnées sont relatives au système de coordonnées global, sinon elles sont relatives au système de coordonnées du [plan de travail](/Draft_SelectPlane/fr "Draft SelectPlane/fr").
* Appuyez sur N ou cliquez sur la case **Continuer** pour activer le mode continu. Si le mode continu est activé, la commande redémarre après avoir terminé, ce qui vous permet de continuer à créer des lignes.
* Appuyez sur S pour activer ou désactiver [Draft Aimantation](/Draft_Snap/fr "Draft Snap/fr").
* Appuyez sur Échap ou sur le bouton Fermer pour abandonner la commande.

## Remarques

* Une Draft Ligne peut être éditée avec la commande [Draft Éditer](/Draft_Edit/fr "Draft Edit/fr").
* Les Draft Lignes et les [Draft Polylignes](/Draft_Wire/fr "Draft Wire/fr") peuvent être jointes avec la commande [Draft Polylignes](/Draft_Wire/fr "Draft Wire/fr"), la commande [Draft Joindre](/Draft_Join/fr "Draft Join/fr") ou la commande [Draft Agréger](/Draft_Upgrade/fr "Draft Upgrade/fr").

## Préférences

Voir aussi : [Réglage des préférences](/Preferences_Editor/fr "Preferences Editor/fr") et [Draft Préférences](/Draft_Preferences/fr "Draft Preferences/fr").

* Pour changer le but initial du panneau des tâches de la boîte de saisie **Longueur** : **Édition → Préférences... → Draft → Général → Mettre l’accent sur la longueur plutôt que la coordonnée X**. Notez que vous devez déplacer le pointeur dans la [vue 3D](/3D_view/fr "3D view/fr") pour que la modification prenne effet.
* Si la commande **Édition → Préférences... → Draft → Général → Créer des primitives Part si possible** est cochée, la commande créera une [Part Ligne](/Part_Line/fr "Part Line/fr") au lieu d'une Draft Ligne.

## Propriétés

Voir [Draft Polylignes](/Draft_Wire/fr#Propri.C3.A9t.C3.A9s "Draft Wire/fr").

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Pour créer une Draft Ligne, utilisez la méthode `make_line` ([introduit dans la version 0.19](/Release_notes_0.19/fr "Release notes 0.19/fr")) du module Draft. Cette méthode remplace la méthode dépréciée `makeLine`.

```
line = make_line(p1, p2)
line = make_line(LineSegment)
line = make_line(Shape)

```

* Crée un objet `Line` entre les points `p1` et `p2` chacun défini par son `FreeCAD.Vector`, avec les unités en millimètres.
* Crée un objet `Line` à partir de `Part.LineSegment`.
* Crée un objet `Line` du premier sommet au dernier sommet de la `Shape` donnée.

Exemple :

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(1000, 500, 0)
p3 = App.Vector(-250, -500, 0)
p4 = App.Vector(500, 1000, 0)

line1 = Draft.make_line(p1, p2)
line2 = Draft.make_line(p3, p4)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Line/fr&oldid=1513942>"