---
title: Draft Arc
---
|  |
| --- |
| Draft Arc |
| Emplacement du menu |
| Draft : Formes → Outils pour les arcs → Arc  BIM : Formes 2D → Arc |
| Ateliers |
| [Draft](/Draft_Workbench/fr "Draft Workbench/fr"), [BIM](/BIM_Workbench/fr "BIM Workbench/fr") |
| Raccourci par défaut |
| A R |
| Introduit dans la version |
| 0.7 |
| Voir aussi |
| [Draft Arc par 3 Points](/Draft_Arc_3Points/fr "Draft Arc 3Points/fr"), [Draft Cercle](/Draft_Circle/fr "Draft Circle/fr") |
|  |

## Description

La commande ![](/images/Draft_Arc.svg) **Draft Arc** crée un arc de cercle dans le [plan de travail](/Draft_SelectPlane/fr "Draft SelectPlane/fr") en cours à partir d'un centre, d'un rayon, d'un angle de départ et d'un angle d'ouverture. Le rayon et les angles peuvent être définis en sélectionnant des points.

Un Draft Arc est en fait un [Draft Cercle](/Draft_Circle/fr "Draft Circle/fr") dont Données**First Angle** n'est pas identique à Données**Last Angle**.

![](/images/Draft_Arc_example.jpg)

Arc défini par quatre points, centre, rayon, point initial de l'arc et point final de l'arc

## Utilisation

Voir aussi : [Draft La barre](/Draft_Tray/fr "Draft Tray/fr"), [Draft Aimantation](/Draft_Snap/fr "Draft Snap/fr") et [Draft Contrainte](/Draft_Constrain/fr "Draft Constrain/fr").

1. Il existe plusieurs façons de lancer la commande :
   * Appuyer sur le ![](/images/Draft_Arc.svg) Arc.
   * [Draft](/Draft_Workbench/fr "Draft Workbench/fr") : sélectionner l'option **Formes → Outils pour les arcs → ![](/images/Draft_Arc.svg) Arc** du menu.
   * [BIM](/BIM_Workbench/fr "BIM Workbench/fr") : sélectionner l'option **Formes 2D → ![](/images/Draft_Arc.svg) Arc** du menu.
   * Utiliser le raccourci clavier : A puis R.
2. Le panneau de tâches **Arc** s'ouvre. Voir [Options](#Options) pour plus d'informations.
3. Choisir le premier point, le centre de l'arc, dans la [vue 3D](/3D_view/fr "3D view/fr") ou rentrez des coordonnées et appuyez sur le bouton ![](/images/Draft_AddPoint.svg) Entrer un point.
4. Choisir le deuxième point dans la [vue 3D](/3D_view/fr "3D view/fr") ou entrer un **Rayon**.
5. Choisir le troisième point dans la [vue 3D](/3D_view/fr "3D view/fr") ou entrer un **Angle de départ**.
6. Choisir le quatrième point dans la [vue 3D](/3D_view/fr "3D view/fr") ou entrer un **Angle d'ouverture**.

## Options

Les raccourcis clavier à caractère unique disponibles dans le panneau des tâches peuvent être modifiés. Voir [Draft Préférences](/Draft_Preferences/fr "Draft Preferences/fr"). Les raccourcis mentionnés ici sont les raccourcis par défaut (pour la version 1.0).

* Pour saisir manuellement les coordonnées du centre, entrez les valuers X, Y et Z et appuyez sur Entrée après chacune. Ou vous pouvez appuyer sur le bouton ![](/images/Draft_AddPoint.svg) Entrer un point lorsque vous avez les valeurs souhaitées. Il est conseillé de déplacer le pointeur hors de la [vue 3D](/3D_view/fr "3D view/fr") avant de saisir les coordonnées.
* Appuyez sur G ou cliquez sur la case **Global** pour basculer en mode global. Si le mode global est activé, les coordonnées sont relatives au système de coordonnées global, sinon elles sont relatives au système de coordonnées du [plan de travail](/Draft_SelectPlane/fr "Draft SelectPlane/fr").
* Appuyez sur N ou cliquez sur la case **Continuer** pour activer le mode continu. Si le mode continu est activé, la commande redémarre après avoir terminé, ce qui vous permet de continuer à créer des arcs.
* Appuyez sur S pour activer ou désactiver [Draft Aimantation](/Draft_Snap/fr "Draft Snap/fr").
* Appuyez sur Échap ou sur le bouton Fermer pour interrompre la commande.

## Remarques

* Un Draft Arc peut être édité avec la commande [Draft Éditer](/Draft_Edit/fr "Draft Edit/fr").

## Préférences

Voir aussi : [Réglage des préférences](/Preferences_Editor/fr "Preferences Editor/fr") et [Draft Préférences](/Draft_Preferences/fr "Draft Preferences/fr").

* Si l'option **Édition → Préférences... → Draft → Général → Créer des primitives Part si possible** est cochée, la commande créera un [Part Cercle](/Part_Circle/fr "Part Circle/fr") au lieu d'un Draft Cercle.

## Propriétés

Voir [Draft Cercle](/Draft_Circle/fr#Propri.C3.A9t.C3.A9s "Draft Circle/fr").

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Pour créer un Draft Arc, utilisez la méthode `make_circle` ([introduit dans la version 0.19](/Release_notes_0.19/fr "Release notes 0.19/fr")) du module Draft. Cette méthode remplace la méthode dépréciée `makeCircle`.

Exemple :

```
import FreeCAD as App
import Draft

doc = App.newDocument()

arc1 = Draft.make_circle(200, startangle=0, endangle=90)
arc2 = Draft.make_circle(500, startangle=20, endangle=160)
arc3 = Draft.make_circle(750, startangle=-30, endangle=-150)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Arc/fr&oldid=1513926>"