---
title: Draft Réseau polaire
---
|  |
| --- |
| Draft Réseau polaire |
| Emplacement du menu |
| Draft : Modification → Outils pour les réseaux → Réseau polaire  BIM : Modification → Réseau polaire |
| Ateliers |
| [Draft](/Draft_Workbench/fr "Draft Workbench/fr"), [BIM](/BIM_Workbench/fr "BIM Workbench/fr") |
| Raccourci par défaut |
| *Aucun* |
| Introduit dans la version |
| 0.19 |
| Voir aussi |
| [Draft Réseau orthogonal](/Draft_OrthoArray/fr "Draft OrthoArray/fr"), [Draft Réseau circulaire](/Draft_CircularArray/fr "Draft CircularArray/fr"), [Draft Réseau selon une courbe](/Draft_PathArray/fr "Draft PathArray/fr"), [Draft Réseau lié selon une courbe](/Draft_PathLinkArray/fr "Draft PathLinkArray/fr"), [Draft Réseau de points](/Draft_PointArray/fr "Draft PointArray/fr"), [Draft Réseau lié selon des points](/Draft_PointLinkArray/fr "Draft PointLinkArray/fr") |
|  |

## Description

La commande ![](/images/Draft_PolarArray.svg) **Draft Réseau polaire** crée un réseau à partir d'un objet sélectionné en plaçant des copies le long d'une circonférence. La commande peut éventuellement créer un réseau lié [Link](/App_Link/fr "App Link/fr"), qui est plus efficace qu'un réseau régulier.

Cette commande peut être utilisée sur des objets 2D créés avec l'[atelier Draft](/Draft_Workbench/fr "Draft Workbench/fr") ou l'[atelier Sketcher](/Sketcher_Workbench/fr "Sketcher Workbench/fr"), mais aussi sur de nombreux objets 3D tels que ceux créés avec l'[atelier Part](/Part_Workbench/fr "Part Workbench/fr"), l'[atelier PartDesign](/PartDesign_Workbench/fr "PartDesign Workbench/fr") ou l'[atelier BIM](/BIM_Workbench/fr "BIM Workbench/fr").

![](/images/Draft_PolarArray_example.png)

Un Draft réseau polaire

## Utilisation

Voir aussi : [Draft Aimantation](/Draft_Snap/fr "Draft Snap/fr").

1. Sélectionner un objet au choix.
2. Il existe plusieurs façons de lancer la commande :
   * Appuyer sur le bouton ![](/images/Draft_PolarArray.svg) Réseau polaire.
   * [Draft](/Draft_Workbench/fr "Draft Workbench/fr") : sélectionner l'option **Modification → Outils pour les réseaux → ![](/images/Draft_PolarArray.svg) Réseau polaire** du menu.
   * [BIM](/BIM_Workbench/fr "BIM Workbench/fr") : sélectionner l'option **Modification → ![](/images/Draft_PolarArray.svg) Réseau polaire** du menu.
3. Le panneau de tâches **Réseau polaire** s'ouvre. Voir [Options](#Options) pour plus d'informations.
4. Si vous n'avez pas encore sélectionné d'objet : sélectionner un objet.
5. Saisir les paramètres requis dans le panneau des tâches.
6. Pour terminer la commande, effectuez l'une des opérations suivantes :
   * Choisir un point dans la [vue 3D](/3D_view/fr "3D view/fr") pour le **Centre de rotation**.
   * Appuyer sur Entrée.
   * Appuyer sur le bouton OK.

## Options

* Entrer l'**Angle polaire** pour spécifier l'angle total du réseau. L'angle est positif dans le sens inverse des aiguilles d'une montre.
* Entrer le **Nombre d'éléments**. Doit être au moins `2`. Le maximum qui peut être saisi dans le panneau de tâches est `99`, mais des valeurs plus élevées sont possibles en modifiant la propriété Données**Number Polar** du réseau.
* Choisir un point dans la [vue 3D](/3D_view/fr "3D view/fr"), notez que cela terminera également la commande ou rentrez des coordonnées pour le **Centre de rotation**. L'axe de rotation du réseau passera par ce point. Il est conseillé de déplacer le pointeur hors de la [vue 3D](/3D_view/fr "3D view/fr") avant de saisir les coordonnées.
* Appuyer sur le bouton **Réinitialiser le point** pour réinitialiser le **Centre de rotation** à l'origine.
* Si la case **Union** est cochée, les éléments qui se chevauchent dans le réseau sont fusionnés.
* Si la case **Réseau de liens** est cochée, un réseau de liens est créé au lieu d'un réseau régulier. Un réseau de liens est plus efficace car ses éléments sont des objets [App Link](/App_Link/fr "App Link/fr").
* Appuyez sur Échap ou sur le bouton Annuler pour annuler la commande en cours.

## Remarques

Voir [Draft Réseau orthogonal](/Draft_OrthoArray/fr#Remarques "Draft OrthoArray/fr").

* L'axe de rotation par défaut du réseau est l'axe Z positif. Il peut être modifié en éditant sa propriété Données**Axis**.

## Propriétés

Voir [Draft Réseau orthogonal](/Draft_OrthoArray/fr#Propri.C3.A9t.C3.A9s "Draft OrthoArray/fr").

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

### Réseau paramétrique

Pour créer un réseau orthogonal paramétrique, utilisez la méthode `make_array` ([introduit dans la version 0.19](/Release_notes_0.19/fr "Release notes 0.19/fr")) de l'atelier Draft. Cette méthode remplace la méthode dépréciée `makeArray`. La méthode `make_array` peut créer des [Draft Réseaux orthogonaux](/Draft_OrthoArray/fr "Draft OrthoArray/fr"), Draft Réseaux polaires et [Draft Réseaux circulaires](/Draft_CircularArray/fr "Draft CircularArray/fr"). Pour chaque type de réseau, un ou plusieurs wrappers sont disponibles.

La méthode principale :

```
array = make_array(base_object, arg1, arg2, arg3, arg4=None, arg5=None, arg6=None, use_link=True)

```

L'enveloppe pour les réseaux polaires est :

```
array = make_polar_array(base_object,
                         number=5, angle=360, center=App.Vector(0, 0, 0),
                         use_link=True)

```

* `base_object` est l'objet à mettre en réseau. Il peut également s'agir du `Label` (chaîne de caractères) d'un objet du document courant.
* `number` est le nombre d'éléments dans le motif, y compris l'objet original.
* `angle` est l'angle de l'arc polaire en degrés.
* `center` est le vecteur qui définit le centre du motif.
* Si `use_link` est `True`, les éléments créés sont des [App Links](/App_Link/fr "App Link/fr") au lieu de copies ordinaires.
* `array` est restitué avec l'objet réseau créé.

Exemple :

```
import FreeCAD as App
import Draft

doc = App.newDocument()

tri = Draft.make_polygon(3, 600)
center = App.Vector(-1600, 0, 0)

array = Draft.make_polar_array(tri, 8, 270, center)
doc.recompute()

```

### Réseau non paramétrique

Pour créer un réseau polaire non-paramétrique, utilisez la méthode `array` de l'atelier Draft. Cette méthode renvoie `None`.

```
array(objectslist, center, angle, number)

```

Exemple :

```
import FreeCAD as App
import Draft

doc = App.newDocument()

tri = Draft.make_polygon(3, 600)
center = App.Vector(-1600, 0, 0)

Draft.array(tri, center, 270, 8)
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_PolarArray/fr&oldid=1558068>"