---
title: Draft Cloner
---
|  |
| --- |
| Draft Cloner |
| Emplacement du menu |
| Modification → Cloner |
| Ateliers |
| [Draft](/Draft_Workbench/fr "Draft Workbench/fr") |
| Raccourci par défaut |
| C L |
| Introduit dans la version |
| - |
| Voir aussi |
| [Draft Echelle](/Draft_Scale/fr "Draft Scale/fr") |
|  |

## Description

La commande ![](/images/Draft_Clone.svg) **Draft Cloner** crée des copies liées, des clones, des objets sélectionnés. La forme d'un clone est paramétrique. Elle sera mise à jour si son objet source change. Un clone a sa propre position, rotation et échelle, ainsi que ses propres [propriétés de vue](/Property_editor/fr "Property editor/fr"). Pour les objets de [BIM](/BIM_Workbench/fr "BIM Workbench/fr"), la commande crée un type spécial de clone : un clone Arch.

Cette commande peut être utilisée sur des objets 2D créés avec l'[atelier Draft](/Draft_Workbench/fr "Draft Workbench/fr") ou l'[atelier Sketcher](/Sketcher_Workbench/fr "Sketcher Workbench/fr"), mais aussi sur de nombreux objets 3D tels que ceux créés avec l'[atelier Part](/Part_Workbench/fr "Part Workbench/fr"), l'[atelier PartDesign](/PartDesign_Workbench/fr "PartDesign Workbench/fr") ou l'[atelier BIM](/BIM_Workbench/fr "BIM Workbench/fr"). Les clones d'objets 2D peuvent être utilisés dans des [PartDesign Corps](/PartDesign_Body/fr "PartDesign Body/fr").

![](/images/Draft_Clone_example.jpg)

Un Draft Clone à côté de son objet source

## Utilisation

1. Vous pouvez sélectionner un ou plusieurs objets.
2. Il existe plusieurs façons de lancer la commande :
   * Appuyer sur le bouton ![](/images/Draft_Clone.svg) Cloner.
   * Sélectionner l'option **Modification → ![](/images/Draft_Clone.svg) Cloner** du menu.
   * Utiliser le raccourci clavier : C puis L.
3. Si vous n'avez pas encore sélectionné d'objet : sélectionner un objet dans la [vue 3D](/3D_view/fr "3D view/fr").

## Remarques

* L'échelle d'un Draft Clone peut être modifiée par l'[éditeur de propriétés](/Property_editor/fr "Property editor/fr") ou, [introduit dans la version 1.1](/Release_notes_1.1/fr "Release notes 1.1/fr"), en double-cliquant dessus dans la [vue en arborescence](/Tree_view/fr "Tree view/fr") et en entrant de nouvelles valeurs dans le panneau de tâches qui s'ouvre. Cette dernière option est plus efficace.

## Propriétés

Voir aussi : [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

Un objet créé avec la commande Draft Clone est dérivé d'un objet [Part Part2DObject](/Part_Part2DObject/fr "Part Part2DObject/fr"), d'un objet [Part Feature](/Part_Feature/fr "Part Feature/fr") ou, si un Arch Clone est créé, du type d'objet de l'objet source. Il hérite de toutes les propriétés de cet objet. Un clone dérivé de l'un des deux premiers objets possède également les propriétés supplémentaires suivantes :

### Données

Draft

* Données**Fuse** (`Bool`) : spécifie si les formes qui se chevauchent dans le clone sont fusionnées ou non.
* Données**Objects** (`LinkListGlobal`) : spécifie les objets qui sont clonés.
* Données**Scale** (`Vector`) : spécifie les facteurs d'échelle X, Y et Z.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Pour créer un clone, utilisez la méthode `make_clone` ([introduit dans la version 0.19](/Release_notes_0.19/fr "Release notes 0.19/fr")) de l'atelier Draft. Cette méthode remplace la méthode dépréciée `clone`.

```
cloned_object = make_clone(obj, delta=None, forcedraft=False)

```

* `obj` contient les objets à cloner. Il s'agit soit d'un objet unique, soit d'une liste d'objets.
* `delta` est le vecteur de déplacement à appliquer au clone.
* Si `forcedraft` est `False` et `obj` contient un seul [objet BIM](/BIM_Workbench/fr "BIM Workbench/fr"), un Arch Clone est créé. Définissez `forcedraft` à `True` pour créer un Clone Draft à la place.
* `cloned_object` est restitué avec l'objet clone.

Exemple :

```
import FreeCAD as App
import Draft

doc = App.newDocument()

place = App.Placement(App.Vector(1000, 0, 0), App.Rotation())
polygon1 = Draft.make_polygon(3, 750)
polygon2 = Draft.make_polygon(5, 750, placement=place)

vector = App.Vector(2600, 500, 0)
cloned_object = Draft.clone([polygon1, polygon2], delta=vector)

cloned_object.Fuse = True

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Clone/fr&oldid=1550604>"