---
title: Draft Congé
---
|  |
| --- |
| Draft Congé |
| Emplacement du menu |
| Draft : Formes → Congé  BIM : Formes 2D → Congé |
| Ateliers |
| [Draft](/Draft_Workbench/fr "Draft Workbench/fr"), [BIM](/BIM_Workbench/fr "BIM Workbench/fr") |
| Raccourci par défaut |
| F I |
| Introduit dans la version |
| 0.19 |
| Voir aussi |
| [Draft Ligne](/Draft_Line/fr "Draft Line/fr"), [Draft Polyligne](/Draft_Wire/fr "Draft Wire/fr") |
|  |

## Description

La commande ![](/images/Draft_Fillet.svg) **Draft Congé** crée un congé, un coin arrondi, un chanfrein ou une arête droite entre deux arêtes sélectionnées.

Dans la version 0.21 et précédentes, la commande ne fonctionne correctement que si les deux arêtes sélectionnées sont droites.

Dans la version 1.0 et précédentes, si les objets sélectionnés ont plusieurs arêtes, leur première arête sera utilisée. Il se peut que ce ne soit pas l'arête qui a été choisie dans la [vue 3D](/3D_view/fr "3D view/fr").

![](/images/Draft_Fillet_example.png)

Plusieurs congés et chanfreins créés entre deux arêtes

## Utilisation

1. Sélectionnez deux arêtes qui se rejoignent en un seul point.
2. Il y a plusieurs façons de lancer la commande :
   * Appuyez sur le ![](/images/Draft_Fillet.svg) Congé.
   * [Draft](/Draft_Workbench/fr "Draft Workbench/fr") : sélectionnez l'option **Formes → ![](/images/Draft_Fillet.svg) Congé** du menu.
   * [BIM](/BIM_Workbench/fr "BIM Workbench/fr") : sélectionnez l'option **Formes 2D → ![](/images/Draft_Fillet.svg) Congé** du menu.
   * Utilisez le raccourci clavier : F puis I.
3. Saisissez le **Rayon du congé**. Remarquez que la commande n'aboutira pas si le rayon est trop grand pour les arêtes sélectionnées.
4. Vous pouvez vérifier l'option **Supprimer les objets originaux**.
5. Vous pouvez vérifier l'option **Créer un chanfrein**.
6. Si vous avez sélectionné l'une des deux options précédentes : cliquez dans le champ de saisie **Rayon du congé**.
7. Appuyer sur Entrée.

## Options

* Appuyez sur Échap ou sur le bouton Fermer pour annuler la commande.

## Remarques

* Un Draft Congé ne peut pas être édité et n'est pas lié aux arêtes qui ont été utilisées pour le créer.
* Une [Draft Polyligne](/Draft_Wire/fr "Draft Wire/fr") qui a au moins trois points peut recevoir un congé ou être chanfreinée en modifiant respectivement Données**Fillet Radius** ou Données**Chamfer Size**. Le fait que les [Draft Lignes](/Draft_Line/fr "Draft Line/fr") et [Draft Polylignes](/Draft_Wire/fr "Draft Wire/fr") puissent être jointes avec les commandes [Draft Polylignes](/Draft_Wire/fr "Draft Wire/fr"), [Draft Joindre](/Draft_Join/fr "Draft Join/fr") ou [Draft Agréger](/Draft_Upgrade/fr "Draft Upgrade/fr"), nous avons ici une méthode alternative pour créer des filets et des chanfreins.

## Propriétés

Voir aussi : [Éditeur de propriétés](/Property_editor/fr "Property editor/fr")

Un objet Draft Congé est dérivé d'un [Part Part2DObject](/Part_Part2DObject/fr "Part Part2DObject/fr") et hérite de toutes ses propriétés. Il possède également les propriétés supplémentaires suivantes :

### Données

Draft

* Données**End** (`VectorDistance`) : (lecture seule) spécifie le dernier point du congé.
* Données**Fillet Radius** (`Length`) : (lecture seule) rayon avec lequel le congé a été créé.
* Données**Length** (`Length`) : (lecture seule) spécifie la longueur totale du congé.
* Données**Start** (`VectorDistance`) : (lecture seule) spécifie le point de départ du congé.

### Vue

Draft

* Vue**Arrow Size** (`Length`) : spécifie la taille du symbole affiché à la fin du filet.
* Vue**Arrow Type** (`Enumeration`) : spécifie le type de symbole affiché à la fin du filet qui peut être `Dot`, `Circle`, `Arrow`, `Tick` ou `Tick-2`.
* Vue**End Arrow** (`Bool`) : spécifie s'il faut afficher un symbole à la fin du congé, afin qu'il puisse être utilisé comme ligne d'annotation.
* Vue**Pattern** (`Enumeration`) : non utilisé.
* Vue**Pattern Size** (`Float`) : non utilisé.

## Script

Voir aussi : [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) et [FreeCAD Débuter avec les scripts](/FreeCAD_Scripting_Basics/fr "FreeCAD Scripting Basics/fr").

Pour créer un Draft Congé, utilisez la méthode `make_fillet` du module Draft :

```
fillet = make_fillet([edge1, edge2], radius=100, chamfer=False, delete=False)

```

* Crée un objet `Fillet` entre les objets arêtes `edge1` et `edge2`, en utilisant `radius` pour la courbure.
* Si `chamfer` est `True`, cela créera une arête droite au lieu d'un arête arrondie.
* Si `delete` est `True`, cela supprimera `edge1` et `edge2` données et ne laissera que le nouvel objet.

Exemple :

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(1000, 1000, 0)
p3 = App.Vector(2000, 0, 0)

edge1 = Draft.make_line(p1, p2)
edge2 = Draft.make_line(p2, p3)

doc.recompute()

fillet = Draft.make_fillet([edge1, edge2], radius=500)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Fillet/fr&oldid=1539501>"