---
title: Draft Join/ru
---
|  |
| --- |
| Соединить |
| Расположение в меню |
| Многоугольник, Полигон → Соединить |
| Верстаки |
| [Draft](/Draft_Workbench/ru "Draft Workbench/ru"), [Arch](/Arch_Workbench/ru "Arch Workbench/ru") |
| Быстрые клавиши |
| J O |
| Представлено в версии |
| 0.18 |
| См. также |
| [Разделить](/Draft_Split/ru "Draft Split/ru") |
|  |

## Описание

The ![](/images/Draft_Join.svg) **Draft Join** command joins [Draft Lines](/Draft_Line "Draft Line") and [Draft Wires](/Draft_Wire "Draft Wire") into a single wire. This command is the counterpart of the [Draft Split](/Draft_Split "Draft Split") command.

## Применение

1. The end points of the [Draft Lines](/Draft_Line "Draft Line") and/or [Draft Wires](/Draft_Wire "Draft Wire") to be joined must be exactly coincident. If required first adjust points to ensure that this is the case.
2. Select two or more [Draft Lines](/Draft_Line "Draft Line") and/or [Draft Wires](/Draft_Wire "Draft Wire").
3. There are several ways to invoke the command:
   * Press the ![](/images/Draft_Join.svg) [Join](/Draft_Join "Draft Join") button.
   * [Draft](/Draft_Workbench "Draft Workbench"): Select the **Modification → ![](/images/Draft_Join.svg) Join** option from the menu.
   * [BIM](/BIM_Workbench "BIM Workbench"): Select the **Modify → ![](/images/Draft_Join.svg) Join** option from the menu.
   * Use the keyboard shortcut: J then O.

## Примечания

* [Draft Lines](/Draft_Line "Draft Line") and [Draft Wires](/Draft_Wire "Draft Wire") can also be joined with the [Draft Wire](/Draft_Wire "Draft Wire") command or the [Draft Upgrade](/Draft_Upgrade "Draft Upgrade") command.
* To join objects that are not [Draft Lines](/Draft_Line "Draft Line") or [Draft Wires](/Draft_Wire "Draft Wire") you can try using [Draft Upgrade](/Draft_Upgrade "Draft Upgrade") and/or [Draft Downgrade](/Draft_Downgrade "Draft Downgrade") on them one or more times first.

## Программирование

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To join wires use the `join_wires` method ([introduced in 0.19](/Release_notes_0.19 "Release notes 0.19")) of the Draft module. This methods replaces the deprecated `joinWires` method. This method returns `None`.

```
join_wires(wires)

```

* `wires` is a list of wire objects to be joined.

Пример:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(500, 0, 0)
p3 = App.Vector(500, 500, 0)
p4 = App.Vector(0, 500, 0)

wire1 = Draft.make_wire([p1, p2])
wire2 = Draft.make_wire([p2, p3])
wire3 = Draft.make_wire([p3, p4])
wire4 = Draft.make_wire([p4, p1])

Draft.join_wires([wire1, wire3, wire2, wire4])
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Join/ru&oldid=1473226>"