---
title: Draft Fillet/ru
---
|  |
| --- |
| Draft Fillet |
| Расположение в меню |
| Draft → Fillet |
| Верстаки |
| [Draft](/Draft_Workbench/ru "Draft Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| 0.19 |
| См. также |
| [Draft Line](/Draft_Line/ru "Draft Line/ru"), [Draft Wire](/Draft_Wire/ru "Draft Wire/ru") |
|  |

## Описание

The ![](/images/Draft_Fillet.svg) **Draft Fillet** command creates a fillet, a rounded corner, or a chamfer, a straight edge, between two selected edges.

In 0.21 and below the command only works properly if both selected edges are straight.

In 1.0 and below if the selected objects have multiple edges, their first edge will be used. This may not be the edge that was picked in the [3D view](/3D_view "3D view").

![](/images/Draft_Fillet_example.png)

Several fillets and chamfers created between two edges

## Применение

1. Select two edges that meet in a single point.
2. There are several ways to invoke the command:
   * Press the ![](/images/Draft_Fillet.svg) [Fillet](/Draft_Fillet "Draft Fillet") button.
   * [Draft](/Draft_Workbench "Draft Workbench"): Select the **Drafting → ![](/images/Draft_Fillet.svg) Fillet** option from the menu.
   * [BIM](/BIM_Workbench "BIM Workbench"): Select the **2D Drafting → ![](/images/Draft_Fillet.svg) Fillet** option from the menu.
   * Use the keyboard shortcut: F then I.
3. Enter the **Fillet radius**. Note that the command will not succeed if the radius is too large for the selected edge objects.
4. Optionally check the **Delete original objects** option.
5. Optionally check the **Create chamfer** option.
6. If you have selected one of the two previous options: Click in the **Fillet radius** input box.
7. Press Enter.

## Опции

* Нажмите Esc или кнопку Отмена, чтобы отменить выполнение команды.

## Примечания

* A Draft Fillet cannot be edited nor is it linked to the edges that were used to create it.
* A [Draft Wire](/Draft_Wire "Draft Wire") that has at least three points can be filleted or chamfered by changing its Данные**Fillet Radius** or Данные**Chamfer Size** respectively. Since [Draft Lines](/Draft_Line "Draft Line") and [Draft Wires](/Draft_Wire "Draft Wire"), can be joined with the [Draft Wire](/Draft_Wire "Draft Wire") command, the [Draft Join](/Draft_Join "Draft Join") command or the [Draft Upgrade](/Draft_Upgrade "Draft Upgrade") command, this provides an alternative method for creating fillets and chamfers.

## Свойства

See also: [Property editor](/Property_editor "Property editor").

A Draft Fillet object is derived from a [Part Part2DObject](/Part_Part2DObject "Part Part2DObject") and inherits all its properties. It also has the following additional properties:

### Данные

Draft

* Данные**End** (`VectorDistance`): (read-only) specifies the end point of the fillet.
* Данные**Fillet Radius** (`Length`): (read-only) radius with which the fillet was created.
* Данные**Length** (`Length`): (read-only) specifies the total length of the fillet.
* Данные**Start** (`VectorDistance`): (read-only) specifies the start point of the fillet.

### Вид

Draft

* Вид**Arrow Size** (`Length`): specifies the size of the symbol displayed at the end of the fillet.
* Вид**Arrow Type** (`Enumeration`): specifies the type of symbol displayed at the end of the fillet, which can be `Dot`, `Circle`, `Arrow`, `Tick` or `Tick-2`.
* Вид**End Arrow** (`Bool`): specifies whether to show a symbol at the end of the fillet, so it can be used as an annotation line.
* Вид**Pattern** (`Enumeration`): not used.
* Вид**Pattern Size** (`Float`): not used.

## Программирование

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To create a Draft Fillet use the `make_fillet` method of the Draft module:

```
fillet = make_fillet([edge1, edge2], radius=100, chamfer=False, delete=False)

```

* Creates a `Fillet` object between edge objects `edge1` and `edge2`, using `radius` for the curvature.
* If `chamfer` is `True` it will create a straight edge instead of a rounded edge.
* If `delete` is `True` it will delete the given `edge1` and `edge2`, and leave only the new object.

Пример:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(1000, 1000, 0)
p3 = App.Vector(2000, 0, 0)

edge1 = Draft.make_line(p1, p2)
edge2 = Draft.make_line(p2, p3)

doc.recompute()

fillet = Draft.make_fillet([edge1, edge2], radius=500)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Fillet/ru&oldid=1510652>"