---
title: Draft API
---
:::caution
(November 2018) Эта информация может быть неполной и устаревшей. Для последней версии описания программного интерфейса, смотриавтогенерированную документацию по API.
:::

Эти функции являются частью модуля [верстака Draft](/Draft_Workbench/ru "Draft Workbench/ru") и могут быть использованы в [макросах](/Macros/ru "Macros/ru") или в консоли [Python](/Python/ru "Python/ru"), когда импортирован модуль `Draft`.

Пример:

```
import FreeCAD, Draft

myrect = Draft.makeRectangle(4, 3)
mydistance = FreeCAD.Vector(2, 2, 0)
Draft.move(myrect, mydistance)

```

![](/images/Method.png) **cut(***FreeCAD.Object, FreeCAD.Object***)**

**Description**: Возвращает "Вырезанный" объект состоящий из различий двух данных объектов. Оригинальные объекты скрываются.

**Returns**: Вновь созданный объект

![](/images/Method.png) **extrude(***FreeCAD.Object, Vector***)**

**Description**: Вытягивает данный объект в направлении определяемым вектором. Оригинальные объекты скрываются.

**Returns**: Вновь созданный объект

![](/images/Method.png) **formatObject(***FreeCAD.Object, [FreeCAD.Object]***)**

**Description**: Это функция применяет на данном объекте текушме настройки Чертежной панели(набора инструментов) (цвет и ширину линий), или копирует свойства второго объекта , если он указан. Она также помещает объект в группу построений если нажата кнопка построений(кнопка совок - чертежной панели).

**Returns**: Ничего

![](/images/Method.png) **fuse(***FreeCAD.Object, FreeCAD.Object***)**

**Description**: Возвращает объект получившийся объединением двух указанных объектов. Если объекты лежат в одной плоскости, используется специальный объект Ломаная Прямая(Draft Wire), в противном случае конечный объект является стандартным слиянием деталей.

**Returns**: Вновь созданный объект

![](/images/Method.png) **getDraftPath(***[string]Возвращает системный или пользовательский путь откуда запущен Draft(Эскизный) модуль. Если указано подпуть(!) или имя файла вернется строка содержащая полный путь вместе с подпутем(!) внутри папки Draft модуля.***)**

**Description**: Путь к файлу

**Returns**: {{{4}}}

![](/images/Method.png) **getGroupContents(***list***)**

**Description**: Рекурсивно сканирует указанный список групп. Если встречаются группы их содержание добавляется в список.

**Returns**: Список объектов FreeCAD

![](/images/Method.png) **getRealName(***string***)**

**Description**: Убирает номер на который оканчивается объект.

**Returns**: Обрезаное имя объекта

![](/images/Method.png) **getSelection(****)**

**Description**: Возвращает текущее выделение FreeCAD.

**Returns**: Текущее выделение FreeCAD.

![](/images/Method.png) **makeCircle(***radius, [placement], [facemode], [startangle], [endangle]***)**

**Description**: Создает объект - кружок с указанным радиусом. Если положение указано, оно используется. Если facemode установлен как False, окружность отображается как каркас(окружность), в противно случае как грань. Если начальный И конечный угол указаны (в градусах), они используются, и объект выглядит как дуга.

**Returns**: Вновь созданный объект.

![](/images/Method.png) **makeDimension(***Vector, Vector, [Vector] or FreeCAD.Object, int, int, [Vector]***)**

**Description**: Создает Размерную выноску объект измереяет расстояние между первым и вторым векторами, с размерной линеей проходящей через третий вектор, если он указан. Будут использованы текущая длина и цвет линии из Эскизной панели инструментов. Вместо двух векторов, вы также можете указать объект FreeCAD, и два числа (и опционально вектор через который будет проходить размерная линия). В этом случае, размерная линия будет связана с объектом, и измерит расстояние между двумя вершинами заданными числами.

**Returns**: Вновь созданный объект.

![](/images/Method.png) **makeLine(***Vector, Vector***)**

**Description**: Создает линию между двумя заданными векторами. Будут использованы текущая длина и цвет линии из Эскизной панели инструментов.

**Returns**: Вновь созданный объект.

![](/images/Method.png) **makeRectangle(***length, width, [placement], [facemode]***)**

**Description**: Создает объект прямоугольник с длинной вдоль направления оси Х и высотой в направлении оси Y. Если положение указано, оно используется. Если facemode установлен как False, прямоугольник отображается как каркас(прямоугольник), в противно случае как грань. Будут использованы текущая длина и цвет линии из Эскизной панели инструментов.

**Returns**: Вновь созданный объект.

![](/images/Method.png) **makeText(***string or list, [Vector], [screenmode]***)**

**Description**: Создает тестовый объект в данной точке если задан вектор, содержит строку или строки приведенные в списке, одна строка на линии. Используются текущий цвет из Эскизной панели инструментов , высота текста и шрифт указываются в Настройка. Если screenmode установлен в True, текст всегда расположен в направлении вида(плоскость в которой находится текст), в противном случае он расположен в плоскости XY.

**Returns**: Вновь созданный объект.

![](/images/Method.png) **makeWire(***list or Part.Wire, [closed], [placement], [facemode]***)**

**Description**: Создает Ломанную прямую по заданному списку векторов или из заданной Ломанной прямой. Если closed установлен в True или если первая и последняя точки совпадают , ломанная прямая является замкнутой. Если facemode установлен True (и ломанная прямая закнута), замкнута кривая будет заполнена. Будут использованы текущая длина и цвет линии из Эскизной панели инструментов.

**Returns**: Вновь созданный объект.

![](/images/Method.png) **move(***FreeCAD.Object or list, Vector, [copymode]***)**

**Description**: Перемещает заданный объект или объекты содержащиеся в заданном списке в направлении и на растояние определяемые вектором. Если copymode установлен как True, подлинные объекты не перемещаются, вместо этого создаются копии.

**Returns**: Объект(ы) (или их копии, если copymode установлен True).

![](/images/Method.png) **precision(****)**

**Description**: Возвращает точное значение Эскизных настроек пользователя.

**Returns**: Число.

![](/images/Method.png) **rotate(***FreeCAD.Object or list, angle, [center], [axis] ,[copymode]***)**

**Description**: Попорачивает заданный объект или объекты содержащиеся в заданном списке на заданный угол вокруг заданного центра если он указан, использует ось как ось поворота. Если ось не указана, вращение будет происходить вокруг вертикальной оси Z. Если copymode установлен как True, подлинные объекты не перемещаются, вместо этого создаются копии.

**Returns**: Объекты (или их копии).

![](/images/Method.png) **scale(***FreeCAD.Object or list, vector, [center], [copymode]***)**

**Description**: Масштабирует указанный объект или объекты содержащиеся в заданном списке, с масштабным фактором определяемым по заданому вектору (в X, Y и Z направлениях) вокруг указанного центра если есть. Если copymode установлен как True, подлинные объекты не перемещаются, вместо этого создаются копии.

**Returns**: Объекты (или их копии).

![](/images/Method.png) **select(***FreeCAD.Object***)**

**Description**: Снимает выбор со всего остального и выбирает только переданый объект

**Returns**: Ничего.

![](/images/Method.png) **shapify(***FreeCAD.Object***)**

**Description**: Превращает параметрическую объект-форму в непараметрическую.

**Returns**: Новый объект.

![](/images/Method.png) **draftify(***FreeCAD.Object or list***)**

**Description**: Включает заданный объект, или каждый объект из списка в Эскизную параметрическую кривую.

**Returns**: Ничего.

![](/images/Method.png) **getSVG(***FreeCAD.Object, [linemodifier], [textmodifier], [(u,v)]***)**

**Description**: Создает SVG предствление указанного объекта. Параметр linemodifier это масштабный фактор(в прцентах)для ширины линииfor line width, и textmodifier для рахзмера текста. Вы также можете дополнительно задать набор векторов определяющих плоскость проекции, в противном случае геометрия будет спроецирована на плоскость XY.

**Returns**: строка содержащая SVG изображение заданного объекта.

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_API/ru&oldid=680841>"