---
title: Draft Ellipse
---
|  |
| --- |
| Draft Ellipse |
| Расположение в меню |
| Черчение -> Эллипс |
| Верстаки |
| [Draft](/Draft_Workbench/ru "Draft Workbench/ru"), [Arch](/Arch_Workbench/ru "Arch Workbench/ru") |
| Быстрые клавиши |
| E L |
| Представлено в версии |
| - |
| См. также |
| [Окружность](/Draft_Circle/ru "Draft Circle/ru") |
|  |

## Описание

Инструмент Ellipse создает эллипс в текущей [work plane](/Draft_SelectPlane "Draft SelectPlane"), введя две точки, определяя угол прямоугольного прямоугольника, в котором будет располагаться эллипс. Он берет [linewidth and color](/Draft_Linestyle "Draft Linestyle"), предварительно установленный на вкладке «Задачи».

A Draft Ellipse can be turned into an elliptical arc by setting its Данные**First Angle** and Данные**Last Angle** properties to different values.

![](/images/Draft_ellipse_example.jpg)

![](/images/Draft_ellipse_example.jpg)

## Usage

See also: [Draft Tray](/Draft_Tray "Draft Tray"), [Draft Snap](/Draft_Snap "Draft Snap") and [Draft Constrain](/Draft_Constrain "Draft Constrain").

## Использование

1. Нажмите кнопку ![](/images/Draft_Ellipse.png) [Draft Ellipse](/Draft_Ellipse "Draft Ellipse") или нажмите клавиши  C, затем  I
2. Щелкните первую точку на трехмерном изображении или введите coordinate
3. Нажмите вторую точку на трехмерном представлении или введите coordinate.

## Опции

The single character keyboard shortcuts available in the task panel can be changed. See [Draft Preferences](/Draft_Preferences "Draft Preferences"). The shortcuts mentioned here are the default shortcuts (for version 1.0).

* To manually enter coordinates enter the X, Y and Z component, and press Enter after each. Or you can press the ![](/images/Draft_AddPoint.svg) Enter point button when you have the desired values. It is advisable to move the pointer out of the [3D view](/3D_view "3D view") before entering coordinates.
* Press R or click the **Relative** checkbox to toggle relative mode. If relative mode is on, the coordinates of the second point are relative to the first point, else they are relative to the coordinate system origin.
* Press G or click the **Global** checkbox to toggle global mode. If global mode is on, coordinates are relative to the global coordinate system, else they are relative to the [working plane](/Draft_SelectPlane "Draft SelectPlane") coordinate system.
* Press F or click the **Filled**1.0 and below or **Make face**[introduced in 1.1](/Release_notes_1.1 "Release notes 1.1") checkbox to toggle make face mode. If make face mode is on, the created ellipse will have Данные**Make Face** set to `true` and have a filled face.
* Press N or click the **Continue** checkbox to toggle continue mode. If continue mode is on, the command will restart after finishing, allowing you to continue creating ellipses.
* Press S to switch [Draft snapping](/Draft_Snap "Draft Snap") on or off.
* Press Esc or the Close button to abort the command.

## Notes

* A Draft Ellipse can be edited with the [Draft Edit](/Draft_Edit "Draft Edit") command.

## Preferences

See also: [Preferences Editor](/Preferences_Editor "Preferences Editor") and [Draft Preferences](/Draft_Preferences "Draft Preferences").

* If the **Edit → Preferences... → Draft → General → Create Part primitives if possible** option is checked, the command will create a [Part Ellipse](/Part_Ellipse "Part Ellipse") instead of a Draft Ellipse.

## Свойства

See also: [Property editor](/Property_editor "Property editor").

A Draft Ellipse object is derived from a [Part Part2DObject](/Part_Part2DObject "Part Part2DObject") and inherits all its properties. It also has the following additional properties:

### Data

Draft

* Данные**Area** (`Area`): (read-only) specifies the area of the face of the ellipse. The value will be `0.0` if Данные**Make Face** if `false` or the face cannot be created.
* Данные**First Angle** (`Angle`): specifies the angle of the first point of the ellipse, normally `0°`.
* Данные**Last Angle** (`Angle`): specifies the angle of the last point of the ellipse, normally `0°`.
* Данные**Major Radius** (`Length`): specifies the major radius of the ellipse.
* Данные**Make Face** (`Bool`): specifies if the ellipse makes a face or not. If it is `true` a face is created, otherwise only the perimeter is considered part of the object. This property only works if the shape is a full ellipse.
* Данные**Minor Radius** (`Length`): specifies the minor radius of the ellipse.

### View

Draft

* Вид**Pattern** (`Enumeration`): specifies the [Draft Pattern](/Draft_Pattern "Draft Pattern") with which to fill the face of the ellipse. This property only works if Данные**Make Face** is `true` and if Вид**Display Mode** is `Flat Lines`.
* Вид**Pattern Size** (`Float`): specifies the size of the [Draft Pattern](/Draft_Pattern "Draft Pattern").

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To create a Draft Ellipse use the `make_ellipse` method ([introduced in 0.19](/Release_notes_0.19 "Release notes 0.19")) of the Draft module. This method replaces the deprecated `makeEllipse` method.

```
ellipse = make_ellipse(majradius, minradius, placement=None, face=True, support=None)

```

* Creates an `ellipse` object with given major (`majradius`) and minor (`minradius`) radius in millimeters.
  + The bigger value will be used for the major radius (X axis) if no other placement is given.
* If `placement` is `None` the ellipse is created at the origin.
* If `face` is `True`, the ellipse will make a face, that is, it will appear filled.

Example:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

ellipse1 = Draft.make_ellipse(3000, 200)
ellipse2 = Draft.make_ellipse(700, 1000)

zaxis = App.Vector(0, 0, 1)
p3 = App.Vector(1000, 1000, 0)
place3 = App.Placement(p3, App.Rotation(zaxis, 90))

ellipse3 = Draft.make_ellipse(700, 1000, placement=place3)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Ellipse/ru&oldid=1556234>"