---
title: Draft WireToBSpline/ru
---
|  |
| --- |
| Draft WireToBSpline |
| Расположение в меню |
| Черчение → Направляющая в BSpline |
| Верстаки |
| [Draft](/Draft_Workbench/ru "Draft Workbench/ru"), [Arch](/Arch_Workbench/ru "Arch Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| - |
| См. также |
| *Нет* |
|  |

## Description

The ![](/images/Draft_WireToBSpline.svg) **Draft WireToBSpline** command converts [Draft Wires](/Draft_Wire "Draft Wire") to [Draft BSplines](/Draft_BSpline "Draft BSpline") and vice versa.

![](/images/Draft_Wire2BSpline_example.jpg)

Converting a wire to a B-spline, and a closed B-spline to a closed wire

## Usage

1. Select a [Draft Wire](/Draft_Wire "Draft Wire") or a [Draft BSpline](/Draft_BSpline "Draft BSpline").
2. There are several ways to invoke the command:
   * Press the ![](/images/Draft_WireToBSpline.svg) [Wire to B-spline](/Draft_WireToBSpline "Draft WireToBSpline") button.
   * Select the **Modification → ![](/images/Draft_WireToBSpline.svg) Wire to B-spline** option from the menu.
3. A new object is created.

## Notes

* The command may result in a closed, self-intersecting [Draft Wire](/Draft_Wire "Draft Wire") or [Draft BSpline](/Draft_BSpline "Draft BSpline") with a face. Such an object will not display properly in the [3D view](/3D_view "3D view"). Its Данные**Make Face** property, or its Данные**Closed** property, must be set to `false`.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To convert a wire to a B-spline, or vice versa, pass the `Points` property of the source object to the `make_bspline` method, or respectively the `make_wire` method, of the Draft module.

Example:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(1000, 1000, 0)
p2 = App.Vector(2000, 1000, 0)
p3 = App.Vector(2500, -1000, 0)
p4 = App.Vector(3500, -500, 0)

base_wire = Draft.make_wire([p1, p2, p3, p4])
base_spline = Draft.make_bspline([-p1, -1.3*p2, -1.2*p3, -2.1*p4])

points1 = base_wire.Points
spline_from_wire = Draft.make_bspline(points1)

points2 = base_spline.Points
wire_from_spline = Draft.make_wire(points2)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_WireToBSpline/ru&oldid=1395871>"