---
title: Draft FlipDimension
---
|  |
| --- |
| Draft FlipDimension |
| Расположение в меню |
| Черчение → Утилиты → Перевернуть размер |
| Верстаки |
| [Draft](/Draft_Workbench/ru "Draft Workbench/ru"), [Arch](/Arch_Workbench/ru "Arch Workbench/ru") |
| Быстрые клавиши |
| *Нет* |
| Представлено в версии |
| - |
| См. также |
| [Размер](/Draft_Dimension/ru "Draft Dimension/ru") |
|  |

## Description

## Описание

Когда в 2D-режиме текст [Draft dimensions](/Draft_Dimension "Draft Dimension") отображается в соответствии с размерной строкой. Инструмент измерения всегда пытается показать вам размерный текст на правильной стороне размерной линии, в зависимости от того, где вы его просматриваете. В некоторых случаях, однако, направление просмотра может не отражать намерения зрителя, и ориентация текста измерения может быть инвертирована. Этот инструмент инвертирует эту ориентацию на выбранных объектах  [dimension](/Draft_Dimension "Draft Dimension").

## Usage

## Использование

1. Выберите один или несколько объектов [dimension](/Draft_Dimension "Draft Dimension")
2. Нажмите кнопку ![](/images/Draft_FlipDimension.png) [Flip Dimension](/Draft_FlipDimension "Draft FlipDimension")

## Notes

* [Draft Dimensions](/Draft_Dimension "Draft Dimension") also have a Данные**Flip Text** property. When set to `true` the text is rotated 180° around the normal direction. This can be combined with the effect of this command.

## Программирование

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To flip a [Draft Dimension](/Draft_Dimension "Draft Dimension") invert its `Normal` property.

Пример:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(1000, 0, 0)
p3 = App.Vector(500, 300, 0)
dimension = Draft.make_dimension(p1, p2, p3)
dimension.ViewObject.FontSize = 200

dimension.Normal = dimension.Normal.negative()
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_FlipDimension/ru&oldid=1338144>"