---
title: Draft Circle
---
|  |
| --- |
| Draft Circle |
| Расположение в меню |
| Черчение → Окружность |
| Верстаки |
| [Draft](/Draft_Workbench/ru "Draft Workbench/ru"), [Arch](/Arch_Workbench/ru "Arch Workbench/ru") |
| Быстрые клавиши |
| C I |
| Представлено в версии |
| - |
| См. также |
| [Дуга](/Draft_Arc/ru "Draft Arc/ru") |
|  |

## Description

## Описание

Инструмент «Круг» создает круг в текущей [work plane](/Draft_SelectPlane "Draft SelectPlane") путем ввода двух точек, центра и радиуса, или путем выбора тангенсов или любой их комбинации. Он берет [linewidth and color](/Draft_Linestyle "Draft Linestyle"), предварительно установленный на вкладке «Задачи». Этот инструмент работает так же, как инструмент [Draft Arc](/Draft_Arc "Draft Arc"), за исключением того, что он останавливается после ввода радиуса.

A Draft Circle can be turned into an arc by setting its Данные**First Angle** and Данные**Last Angle** properties to different values.

![](/images/Draft_Circle_example.jpg)

![](/images/Draft_Circle_example.jpg)

## Usage

See also: [Draft Tray](/Draft_Tray "Draft Tray"), [Draft Snap](/Draft_Snap "Draft Snap") and [Draft Constrain](/Draft_Constrain "Draft Constrain").

## Как использовать

1. Нажмите кнопку ![](/images/Draft_Circle.png) [Draft Circle](/Draft_Circle "Draft Circle") или нажмите  C, затем клавиши  I
2. Щелкните первую точку на трехмерном изображении или введите coordinate
3. Нажмите вторую точку на трехмерном представлении или введите значение радиуса.

## Options

The single character keyboard shortcuts available in the task panel can be changed. See [Draft Preferences](/Draft_Preferences "Draft Preferences"). The shortcuts mentioned here are the default shortcuts (for version 1.0).

* To manually enter the coordinates for the center enter the X, Y and Z component, and press Enter after each. Or you can press the ![](/images/Draft_AddPoint.svg) Enter point button when you have the desired values. It is advisable to move the pointer out of the [3D view](/3D_view "3D view") before entering coordinates.
* Press G or click the **Global** checkbox to toggle global mode. If global mode is on, coordinates are relative to the global coordinate system, else they are relative to the [working plane](/Draft_SelectPlane "Draft SelectPlane") coordinate system.
* Press F or click the **Filled**1.0 and below or **Make face**[introduced in 1.1](/Release_notes_1.1 "Release notes 1.1") checkbox to toggle make face mode. If make face mode is on, the created circle will have Данные**Make Face** set to `true` and have a filled face.
* Press N or click the **Continue** checkbox to toggle continue mode. If continue mode is on, the command will restart after finishing, allowing you to continue creating circles.
* Press S to switch [Draft snapping](/Draft_Snap "Draft Snap") on or off.
* Press Esc or the Close button to abort the command.

## Notes

* A Draft Circle can be edited with the [Draft Edit](/Draft_Edit "Draft Edit") command.

## Preferences

See also: [Preferences Editor](/Preferences_Editor "Preferences Editor") and [Draft Preferences](/Draft_Preferences "Draft Preferences").

* If the **Edit → Preferences... → Draft → General → Create Part primitives if possible** option is checked, the command will create a [Part Circle](/Part_Circle "Part Circle") instead of a Draft Circle.

## Properties

See also: [Property editor](/Property_editor "Property editor").

A Draft Circle object is derived from a [Part Part2DObject](/Part_Part2DObject "Part Part2DObject") and inherits all its properties. It also has the following additional properties:

### Data

Draft

* Данные**Area** (`Area`): (read-only) specifies the area of the face of the circle. The value will be `0.0` if Данные**Make Face** if `false` or the face cannot be created.
* Данные**First Angle** (`Angle`): specifies the start angle of the circle, normally `0°`.
* Данные**Last Angle** (`Angle`): specifies the end angle of the circle, normally `0°`.
* Данные**Make Face** (`Bool`): specifies if the circle makes a face or not. If it is `true` a face is created, otherwise only the perimeter is considered part of the object. This property only works if the Данные**First Angle** and Данные**Last Angle** have the same value. Note that `0°` and `360°` are not considered the same.
* Данные**Radius** (`Length`): specifies the radius of the circle.

### View

Draft

* Вид**Pattern** (`Enumeration`): specifies the [Draft Pattern](/Draft_Pattern "Draft Pattern") with which to fill the face of the circle. This property only works if Данные**Make Face** is `true` and if Вид**Display Mode** is `Flat Lines`.
* Вид**Pattern Size** (`Float`): specifies the size of the [Draft Pattern](/Draft_Pattern "Draft Pattern").

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To create a Draft Circle use the `make_circle` method ([introduced in 0.19](/Release_notes_0.19 "Release notes 0.19")) of the Draft module. This method replaces the deprecated `makeCircle` method.

```
circle = make_circle(radius, placement=None, face=None, startangle=None, endangle=None, support=None)
circle = make_circle(Part.Edge, placement=None, face=None, startangle=None, endangle=None, support=None)

```

* Creates a `circle` object with given `radius` in millimeters.
  + `radius` can also be a `Part.Edge`, whose `Curve` attribute must be a `Part.Circle`.
* If `placement` is `None` the circle is created at the origin.
* If `face` is `True`, the circle will make a face, that is, it will appear filled.
* If `startangle` and `endangle` are given in degrees, and have different values, they are used and the object appears as a [Draft Arc](/Draft_Arc "Draft Arc").

Example:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

circle1 = Draft.make_circle(200)

zaxis = App.Vector(0, 0, 1)
p2 = App.Vector(1000, 1000, 0)
place2 = App.Placement(p2, App.Rotation(zaxis, 0))
circle2 = Draft.make_circle(500, placement=place2)

p3 = App.Vector(-1000, -1000, 0)
place3 = App.Placement(p3, App.Rotation(zaxis, 0))
circle3 = Draft.make_circle(750, placement=place3)

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Circle/ru&oldid=1556222>"