---
title: Arch API
---
:::caution
(November 2018) The Arch API is listed in theautogenerated API documentation.
:::

The functions of the API are part of the [Arch Workbench](/Arch_Workbench "Arch Workbench") and can be used in [macros](/Macros "Macros") and from the [Python](/Python "Python") console once the `Arch` module has been imported. The [Reinforcement Workbench](/Reinforcement_Workbench "Reinforcement Workbench") has its own [Reinforcement API](/Reinforcement_API "Reinforcement API").

Example:

```
import FreeCAD, Draft, Arch

p1 = FreeCAD.Vector(0, 0, 0)
p2 = FreeCAD.Vector(2000, 0, 0)
baseline = Draft.makeLine(p1, p2)

Arch.makeWall(baseline, length=None, width=200, height=2000)

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Arch_API/en&oldid=1432704>"