---
title: Структура документа
---
![](/images/Screenshot_treeview.jpg)

Документ FreeCAD содержит все объекты проекта. Он может содержать группы, и предметы, сделанные с любого инструментария(workbench). Поэтому вы можете переключаться между инструментариями, и до сих пор работать на том же документе. Получившийся документ будет сохранён на диске при сохранении работы. В FreeCAD, вы также можете открывать несколько документов одновременно и открыть несколько видов одного и того же документа.

В документе объекты могут быть помещены в группы и им можно присвоить уникальные имена. Управлять группами, объектами и именами объектов осуществляется главным образом с помощью [древовидного списка](/Tree_view/ru "Tree view/ru"). **примечание:** Также это можно сделать, как и всё в FreeCAD, с помощью интерпретатора [Python](/Python/ru "Python/ru"). В [древовидном списке](/Tree_view/ru "Tree view/ru") вы можете создавать ![](/images/Std_Group.svg) [группы](/Std_Group "Std Group"), перемещать объекты в группы, удалять объекты или группы, кликнув правой клавишей на объект в [древовидном списке](/Tree_view/ru "Tree view/ru"), переименуйте объекты. Также можно переименовать объект выделив его в древовидном списке и нажав F2, также возможны другие комбинации в зависимости от текущего инструментария.

Объекты входящие в FreeCAD документ могут быть различных типов. Каждый инструментарий может создать свои собственные типы объектов, для примера ![](/images/Workbench_Mesh.svg) [Верстак полигонального моделирования](/Mesh_Workbench/ru "Mesh Workbench/ru") создаёт объекты состоящие из полигонов, ![](/images/Workbench_Part.svg) [Верстак Деталей](/Part_Workbench/ru "Part Workbench/ru") создает детали, ![](/images/Workbench_Draft.svg) [Чертежный Верстак](/Draft_Workbench/ru "Draft Workbench/ru") также создаёт детали, и т.д.

Если есть по крайней мере один документ открытый в FreeCAD, всегда есть один и только один активный документ. Этот документ отображается в текущем окне 3D просмотра, это документ над которым вы сейчас работаете.

## Приложения и интерфейс пользователя

Как почти все в FreeCAD, графический пользовательский интерфейс(GUI) отделен от основной части приложения(App). Также и с документами. Документы также состоят из двух частей: документ Приложение, содержащий ваши объекты, и документ как Вид, который содержит представление на экране наших объектов.

Думайте об этом как о двух местах, где определены ваши объекты. Их конструктивные параметры (это куб? конус? его размер?) хранятся в документе Приложении, а их графическое представление (отображать его в черных линиях? с синими гранями?) хранятся в части документ Вид. Зачем это сделано? Потому что FreeCAD может быть использован *без* графического интерфейса, например в других программах, и мы должны быть в состоянии управлять нашими объектами, даже если ничего не будет отображаться на экране.

Еще в части документа Вид содержатся объёмные виды. Один документ может иметь несколько открытых видов, так что вы можете просматривать ваш документ одновременно с нескольких точек зрения. Может быть вы хотели бы одновременно смотреть на ваш объект спереди и сверху? Тогда в вашем документе будет две части Вид документа. Создать новые виды или закрыть старые виды можно с помощью меню Вид или кликнув правой кнопкой мыши по закладке вида.

## Программирование

Документы легко могут быть созданы и изменены с помощью интерпретатора [Python](/Python/ru "Python/ru").
Например:

```
FreeCAD.ActiveDocument

```

Вернет текущий (активный) документ

```
FreeCAD.ActiveDocument.Blob

```

Даст доступ к объекту с именем "Blob" внутри вашего документа

```
FreeCADGui.ActiveDocument

```

Вернет вид-документ связаный с текущим документом

```
FreeCADGui.ActiveDocument.Blob

```

Получить доступ к графическому представлению (виду) объекта с именем Blob

```
FreeCADGui.ActiveDocument.ActiveView

```

Вернет текущий активный вид.

Retrieved from "<http://wiki.freecad.org/index.php?title=Document_structure/ru&oldid=1536754>"