---
title: Parça Elips
---
|  |
| --- |
| Parça Elips |
| Menü konumu |
| Parça → [Temel geometrik şekil oluştur](/Part_CreatePrimitives "Part CreatePrimitives") → Elips |
| Tezgahlar |
| [Parça](/Part_Workbench/tr "Part Workbench/tr"), [OpenSCAD](/OpenSCAD_Workbench/tr "OpenSCAD Workbench/tr") |
| Varsayılan kısayol |
| *Hiçbiri* |
| Versiyonda tanıtıldı |
| - |
| Ayrıca bkz |
| .. |
|  |

== Açıklama == Bir elips geometrik şekli, Parça tezgahındaki Temel geometrik şekil oluştur iletişim kutusundan edinilebilir.

Bu komut eliptik bir kavisli kenar oluşturacaktır. Varsayılan değerlerle, eliptik kavisli kenar kapatılacak ve bu nedenle bir elips olacaktır. Açı 1 veya Açı 2 özellikleri varsayılan değerlerinden (0 ve 360) değiştirilirse, kenar açık bir eğri olur.

A Part Ellipse is in fact a closed counterclockwise elliptical arc, it can be turned into an arc by changing its Veri**Angle1** and/or Veri**Angle2** properties.

![](/images/Part_Ellipse_Example.png)

## Usage

See [Part Primitives](/Part_Primitives#Usage "Part Primitives").

## Example

![](/images/Part_Ellipse_Scripting_Example.png)

Part Ellipse from the scripting example

A Part Ellipse object created with the [scripting example](#Scripting) below is shown here.

## Properties

See also: [Property editor](/Property_editor "Property editor").

A Part Ellipse object is derived from a [Part Feature](/Part_Feature "Part Feature") object and inherits all its properties. It also has the following additional properties:

### Data

Attachment

The object has the same attachment properties as a [Part Part2DObject](/Part_Part2DObject#Data "Part Part2DObject").

Base

* Veri**MajorRadius** (`Length`): The major radius of the ellipse or elliptical arc. The default is `4mm`.
* Veri**MinorRadius** (`Length`): The minor radius of the ellipse or elliptical arc. The default is `2mm`.
* Veri**Angle1** (`Angle`): The start angle of the elliptical arc. Valid range: `0° < value <= 360°`. The default is `0°`.
* Veri**Angle2** (`Angle`): The end angle of the elliptical arc. Valid range: `0° < value <= 360°`. The default is `360°`. If Veri**Angle1** and Veri**Angle2** are equal, or if one angle is `0°` and the other `360°`, a full ellipse is created.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/), [Part scripting](/Part_scripting "Part scripting") and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

A Part Ellipse can be created with the `addObject()` method of the document:

```
ellipse = FreeCAD.ActiveDocument.addObject("Part::Ellipse", "myEllipse")

```

* Where `"myEllipse"` is the name for the object.
* The function returns the newly created object.

Example:

```
import FreeCAD as App

doc = App.activeDocument()

ellipse = doc.addObject("Part::Ellipse", "myEllipse")
ellipse.MajorRadius = 20
ellipse.MinorRadius = 10
ellipse.Angle1 = 45
ellipse.Angle2 = 135
ellipse.Placement = App.Placement(App.Vector(1, 2, 3), App.Rotation(30, 45, 10))

doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Part_Ellipse/tr&oldid=1106670>"