---
title: Separar
---
|  |
| --- |
| Draft Split |
| Menu location |
| Modification → Split Modify → Split |
| Workbenches |
| [Draft](/Draft_Workbench "Draft Workbench"), [BIM](/BIM_Workbench "BIM Workbench") |
| Default shortcut |
| S P |
| Introduced in version |
| 0.18 |
| See also |
| [Draft Join](/Draft_Join "Draft Join") |
|  |

## Descrição

The ![](/images/Draft_Split.svg) **Draft Split** command splits a [Draft Line](/Draft_Line "Draft Line") or [Draft Wire](/Draft_Wire "Draft Wire") at a specified point or edge. This command is the counterpart of the [Draft Join](/Draft_Join "Draft Join") command.

## Utilização

1. There are several ways to invoke the command:
   * Press the ![](/images/Draft_Split.svg) [Split](/Draft_Split "Draft Split") button.
   * [Draft](/Draft_Workbench "Draft Workbench"): Select the **Modification → ![](/images/Draft_Split.svg) Split** option from the menu.
   * [BIM](/BIM_Workbench "BIM Workbench"): Select the **Modify → ![](/images/Draft_Split.svg) Split** option from the menu.
   * Use the keyboard shortcut: S then P.
2. Move the pointer over the correct edge of a [Draft Line](/Draft_Line "Draft Line") or [Draft Wire](/Draft_Wire "Draft Wire").
3. The edge is highlighted.
4. Do one of the following:
   * If the wire is closed:
     + Pick any point on the edge.
     + The edge is detached from the wire and becomes a separate wire.
   * If the wire is open:
     + Pick the correct point on the edge. See [Notes](#Notes).
     + The wire is split at the picked point.

## Notas

* If an open wire is split and the clicked point does not lie exactly on the selected edge, the new point will not be collinear with that former edge. Use an appropriate [Draft Snap](/Draft_Snap "Draft Snap") option to prevent this.
* To split objects that are not [Draft Lines](/Draft_Line "Draft Line") or [Draft Wires](/Draft_Wire "Draft Wire") you can try using [Draft Upgrade](/Draft_Upgrade "Draft Upgrade") and/or [Draft Downgrade](/Draft_Downgrade "Draft Downgrade") on them one or more times first.

## Scripting

See also: [Autogenerated API documentation](https://freecad.github.io/SourceDoc/) and [FreeCAD Scripting Basics](/FreeCAD_Scripting_Basics "FreeCAD Scripting Basics").

To split a wire use the `split` method of the Draft module. This method returns `None`.

```
split(wire, newPoint, edgeIndex)

```

* `wire` the wire object to be split.
* `newPoint` the point where the split should occur.
* `edgeIndex` index of the edge where the split should occur (1-based).

Example:

```
import FreeCAD as App
import Draft

doc = App.newDocument()

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(500, 0, 0)
p3 = App.Vector(250, 0, 0)

wire = Draft.make_wire([p1, p2])

Draft.split(wire, p3, 1)
doc.recompute()

```

Retrieved from "<http://wiki.freecad.org/index.php?title=Draft_Split/pt-br&oldid=1473236>"